### PR TITLE
Throw transient instead of permanent error for missing ExchangeWorkflow

### PR DESCRIPTION
**Pull request by efoxepstein**
This fixes a pain point: when adding a new RecurringExchange that starts in the past, there's a circular dependency. In order to set up some required inputs, like the private list of valid ExchangeWorkflows, the RecurringExchange id is needed. But as soon as the RecurringExchange is created, any running client will start picking up tasks for it and permanently failing them.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/298)

### CODE REVIEW

**Review by robinsons — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/298)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepValidatorImpl.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/298#-Mzzh1egBWR6PLMuLoot:-Mzzh1egBWR6PLMuLoou:b-5vgp9o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5bba3d2238fea5630955f4ab48ab30765ebeb1ff/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepValidatorImpl.kt#L45)):*
> ```Kotlin
>           "No ExchangeWorkflow known for RecurringExchange $recurringExchangeId"
>         )
>     if (existingExchangeWorkflow != serializedExchangeWorkflow) {
> ```

Unrelated to this PR's change, but we should avoid comparing serialized protos because serializations are not canonical.

**Review by yunyeng — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/298)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/298)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepValidatorImpl.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/298#-N-3thZT6Eue9-bh5HKz:-N-3thZT6Eue9-bh5HL-:b-mj6s2v) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5bba3d2238fea5630955f4ab48ab30765ebeb1ff/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepValidatorImpl.kt#L42)):*
> ```Kotlin
>       validExchangeWorkflows.get(recurringExchangeId)
>         ?: throw InvalidExchangeStepException(
>           TRANSIENT,
> ```

needs a test

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/298)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @robinsons, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepValidatorImpl.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/298#-N-3thZT6Eue9-bh5HKz:-N-3xRsfEYtCMkCfWDrY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5bba3d2238fea5630955f4ab48ab30765ebeb1ff/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepValidatorImpl.kt#L42)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

needs a test
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepValidatorImpl.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/298#-Mzzh1egBWR6PLMuLoot:-N-3w8TY55VBYW3b_Wl_:b-iypmbn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5bba3d2238fea5630955f4ab48ab30765ebeb1ff/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepValidatorImpl.kt#L45)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Unrelated to this PR's change, but we should avoid comparing serialized protos because serializations are not canonical.
</blockquote></details>

Discussed offline

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/298)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @robinsons, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepValidatorImplTest.kt, line 125 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/298#-N-8z9gZ7NfRkYumvBXM:-N-8z9g_CtjyxsWKcIbg:bwcusbw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fc53c6d40dda9cd485e2348edf4d0df80d603bb4/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepValidatorImplTest.kt#L125)):*
> ```Kotlin
>           ExchangeStepKey(MISSING_RECURRING_EXCHANGE_ID, EXCHANGE_ID, EXCHANGE_STEP_ID).toName()
>       }
>     assertValidationFailsTransiently(wrongExchangeStep)
> ```

can you validate the failure type?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/298)* status: all files reviewed, 1 unresolved discussion (waiting on @robinsons, @stevenwarejones, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepValidatorImplTest.kt, line 125 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/298#-N-8z9gZ7NfRkYumvBXM:-N-8zUrOD1jy3OjQjGbg:b-i3o0t2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0e3448e083b00e2d8ead6739a862658b75a6e548/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepValidatorImplTest.kt#L125)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you validate the failure type?
</blockquote></details>

What do you mean? Isn't that exactly what assertValidationFailsTransiently does?

**Review by yunyeng — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/298)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @robinsons)

**Review by robinsons — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/298)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Pull request merged**
