### PR TITLE
Implement copy to/from shared storage in Beam for manifest blobs.

### PR DESCRIPTION
**Pull request by robinsons**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325)

### CODE REVIEW

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325)* status: 0 of 22 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325#-N0h8qR717x7a0rPAAmd:-N0h8qR717x7a0rPAAme:buwhl64) (no related file):*
Overview:
* Splits `VerifiedStorageClient` into `VerifyingStorageClient` and `SigningStorageClient`. These new clients divide the responsibility for verifying blobs (copy-from) and signing blobs (copy-to). Critically, these clients are also serializable, which allows them to be used in Beam.
* Updates `SharedStorageSelector` to build these new storage client types.
* Makes `CopyFromSharedStorageTask` and `CopyToSharedStorageTask` only apply to ordinary blobs, not manifests.
* Introduces `CopyFromSharedStorageBeamTask` and `CopyToSharedStorageBeamTask` to handle copying for manifest blobs. As the names imply, these run on Beam.
* Updates `ProductionExchangeTaskMapper` to use choose the correct task type based on the step's `CopyOptions`.
* Miscellaneous changes to make things build.

---

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 18 of 22 files at r1, 2 of 2 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @robinsons)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyFromSharedStorageBeamTask.kt` line 57 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325#-N0hMfYZ7lWnCfqG26Mu:-N0hMfYZ7lWnCfqG26Mv:b-rfmcws) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c8568c7508d969f8edef91a671bd717ce778c94e/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyFromSharedStorageBeamTask.kt#L57)):*
> ```Kotlin
>     pipeline.apply("Generate Shard Names", Create.of(shardedFileName.fileNames.asIterable()))
> 
>   shardNames.breakFusion("Break Fusion Before Copy").parDo<String, String>(
> ```

Any reason this is a parDo instead of map?
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyFromSharedStorageBeamTask.kt` line 62 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325#-N0hMrx6773PL2Xq2-6m:-N0hMrx6773PL2Xq2-6n:bpzvhgx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c8568c7508d969f8edef91a671bd717ce778c94e/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyFromSharedStorageBeamTask.kt#L62)):*
> ```Kotlin
>     runBlocking(Dispatchers.IO) {
>       val shard: VerifiedBlob = source.getBlob(shardName)
>       val destination: StorageClient = destinationFactory.build()
> ```

Is it worth caching destination? Not sure what the overhead is
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/storage/VerifyingStorageClient.kt` line 55 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325#-N0hO3AFDg1TKAtZtTpE:-N0hO3AFDg1TKAtZtTpF:bpea19i) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c8568c7508d969f8edef91a671bd717ce778c94e/src/main/kotlin/org/wfanet/panelmatch/client/storage/VerifyingStorageClient.kt#L55)):*
> ```Kotlin
> 
>   /** [Blob] wrapper that ensures the blob's signature is verified when read. */
>   inner class VerifiedBlob(private val sourceBlob: SignedBlob) {
> ```

Why inner?

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyFromSharedStorageBeamTask.kt` line 57 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325#-N0hMfYZ7lWnCfqG26Mu:-N0hPPHKDq1tYTAU6ghD:b-56b6fy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c8568c7508d969f8edef91a671bd717ce778c94e/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyFromSharedStorageBeamTask.kt#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Any reason this is a parDo instead of map?
</blockquote></details>

Nope, updated.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyFromSharedStorageBeamTask.kt` line 62 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325#-N0hMrx6773PL2Xq2-6m:-N0hR6ZTAGSqitueMTQh:b1c1byj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c8568c7508d969f8edef91a671bd717ce778c94e/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyFromSharedStorageBeamTask.kt#L62)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is it worth caching destination? Not sure what the overhead is
</blockquote></details>

It could be, though the overhead of creating a storage client pales in comparison to the blob transfer itself. I'll see how it performs in practical testing. Also sent you a message offline about this.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/storage/VerifyingStorageClient.kt` line 55 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325#-N0hO3AFDg1TKAtZtTpE:-N0hQuN-CQDnML7s0EcL:b-toog0t) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c8568c7508d969f8edef91a671bd717ce778c94e/src/main/kotlin/org/wfanet/panelmatch/client/storage/VerifyingStorageClient.kt#L55)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why inner?
</blockquote></details>

It was using `x509` from the enclosing class. Changed this to just pass the cert as a parameter.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @robinsons)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt` line 39 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325#-N0hvpXt383zaR8Kr9On:-N0hvpXt383zaR8Kr9Oo:b-wgu0xy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/60fce3be4d409ac0095c07749a9d117b1fa6b4ba/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt#L39)):*
> ```Kotlin
>    * Defaults to false.
>    */
>   fun skipReadInput(): Boolean = false
> ```

Seems like we might need to rethink how ExchangeTaskExecutor works in general as this is a little awkward, but this seems fine for now. Maybe put a Todo to rethink this?

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325)* status: all files reviewed, 2 unresolved discussions (waiting on @robinsons)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325)* status: all files reviewed, 2 unresolved discussions (waiting on @robinsons)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt` line 39 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325#-N0hvpXt383zaR8Kr9On:-N0kUmb65uvfI5DSg95Y:b-hkmhib) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/60fce3be4d409ac0095c07749a9d117b1fa6b4ba/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Seems like we might need to rethink how ExchangeTaskExecutor works in general as this is a little awkward, but this seems fine for now. Maybe put a Todo to rethink this?
</blockquote></details>

Idea, wdyt?

```
interface ExchangeTask {
  suspend fun ExchangeTaskContext.execute()
}

interface ExchangeTaskContext {
  suspend fun readInputs(): Map<String, Blob>
  suspend fun writeOutput(key: String, value: Flow<ByteString>)
}

abstract class ReadWriteExchangeTask : ExchangeTask {
  suspend fun execute(inputs: Map<String, Blob>): Map<String, Flow<ByteString>>

  override suspend fun ExchangeTaskContext.execute() {
    val outputs = execute(readInputs())
    for ((k, v) in outputs) writeOutput(k, v)
  }
}
```

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325)* status: all files reviewed, 1 unresolved discussion (waiting on @robinsons)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt` line 39 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325#-N0hvpXt383zaR8Kr9On:-N0kzkBKEVhfU0pfQ-PX:bhjgld5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/60fce3be4d409ac0095c07749a9d117b1fa6b4ba/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Idea, wdyt?

```
interface ExchangeTask {
  suspend fun ExchangeTaskContext.execute()
}

interface ExchangeTaskContext {
  suspend fun readInputs(): Map<String, Blob>
  suspend fun writeOutput(key: String, value: Flow<ByteString>)
}

abstract class ReadWriteExchangeTask : ExchangeTask {
  suspend fun execute(inputs: Map<String, Blob>): Map<String, Flow<ByteString>>

  override suspend fun ExchangeTaskContext.execute() {
    val outputs = execute(readInputs())
    for ((k, v) in outputs) writeOutput(k, v)
  }
}
```
</blockquote></details>

Discussed offline. This looks good in the long-term, but for this PR we will keep as-is to prevent scope creep.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 11 of 22 files at r1, 2 of 2 files at r2, 1 of 3 files at r4, 3 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325)* status: all files reviewed, 3 unresolved discussions (waiting on @robinsons)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyFromSharedStorageTask.kt` line 51 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325#-N0l7dKo5ivI0ZQoJ96z:-N0l7dKo5ivI0ZQoJ97-:bqhhvcr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f225b977e49868eec2a557bf71651893da5123b7/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyFromSharedStorageTask.kt#L51)):*
> ```Kotlin
>   }
> 
>   private suspend fun writeManifestOutputs(blob: VerifiedBlob) {
> ```

i'm thinking we should keep this functionality in case someone wants to write a manifest blob without using a pipeline
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/storage/SigningStorageClient.kt` line 50 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325#-N0l8NtW7XDI9YsST3-z:-N0l8NtW7XDI9YsST30-:b-7xhues) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fb70ae65ed9f80d239583c981ff1be7ecf5fc25b/src/main/kotlin/org/wfanet/panelmatch/client/storage/SigningStorageClient.kt#L50)):*
> ```Kotlin
>     // This is to ensure that transient failures after some blobs are written do not cause problems
>     // when re-attempting to write.
>     sharedStorage.getBlob(blobKey)?.delete()
> ```

can this be a parameter to the constructor? `deletePreviousBlobOnWrite: Boolean`

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325)* status: all files reviewed, 3 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyFromSharedStorageTask.kt` line 51 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325#-N0l7dKo5ivI0ZQoJ96z:-N0mLqRM4W4l0XTYGHmt:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f225b977e49868eec2a557bf71651893da5123b7/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyFromSharedStorageTask.kt#L51)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i'm thinking we should keep this functionality in case someone wants to write a manifest blob without using a pipeline
</blockquote></details>

+1
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/storage/SigningStorageClient.kt` line 50 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325#-N0l8NtW7XDI9YsST3-z:-N0mLhy46kzxHgPctS63:b-v66up6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fb70ae65ed9f80d239583c981ff1be7ecf5fc25b/src/main/kotlin/org/wfanet/panelmatch/client/storage/SigningStorageClient.kt#L50)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can this be a parameter to the constructor? `deletePreviousBlobOnWrite: Boolean`
</blockquote></details>

This seems out of scope of this PR -- this code preserves the current behavior. Can we discuss in a separate PR?

**Review by jonmolle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325)* status: 20 of 28 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @robinsons, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyFromSharedStorageTask.kt` line 51 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325#-N0l7dKo5ivI0ZQoJ96z:-N0nuyNRCI9joYYCPZh8:b-4m262x) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f225b977e49868eec2a557bf71651893da5123b7/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CopyFromSharedStorageTask.kt#L51)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done. I've rolled back this change, so if someone wants to use a non-beam job to write a manifest they're still able to.

**Comment by jonmolle** [comment]
@stevenwarejones I've taken over this PR and (I believe) addressed your comments. Is there anything else in the PR you're concerned about?

**Review by efoxepstein — APPROVED** [review]
> Reviewed 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325)* status: all files reviewed, 3 unresolved discussions (waiting on @robinsons and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 22 files at r1, 2 of 5 files at r5, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325)* status: all files reviewed, 2 unresolved discussions (waiting on @robinsons and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/325)* status: all files reviewed, 1 unresolved discussion (waiting on @robinsons)

**Pull request merged**
