### PR TITLE
Sync repositories.bzl with xmm repo

### PR DESCRIPTION
**Pull request by Marco-Premier**

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/364)

**Review by stevenwarejones — APPROVED** [review]
Looks like you have some minor linter errors, too.

:lgtm:

> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/364#-:-NUN5ykd42Z3tCY85jeY:b-kkspyf)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @SanjayVas)

___
*[`WORKSPACE` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/364#-NUN5BAaCg5g7_NeGaBD:-NUN5BAaCg5g7_NeGaBE:bvox7o4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e26663bcdfa399dd206e50b6da768fb64e4cc89/WORKSPACE#L31)):*
> ```Starlark
> load("//build:repo.bzl", "grpc_health_probe")
> 
> grpc_health_probe()
> ```

did you end up needing this?

**Review by Marco-Premier — COMMENTED** [review]
+1 Forgot to run the linter... will do it before merging the branch

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/364#-:-NUQHZaI6pim1UIbRYGV:b-5rscby)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`WORKSPACE` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/364#-NUN5BAaCg5g7_NeGaBD:-NUQHOtT656bIs-akElJ:b-2ks99o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e26663bcdfa399dd206e50b6da768fb64e4cc89/WORKSPACE#L31)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

did you end up needing this?
</blockquote></details>

Yes indeed.  Will use health server created in XMM repo once the merged is done.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/364)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @SanjayVas)

___
*[`WORKSPACE` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/364#-NUN5BAaCg5g7_NeGaBD:-NUSBPoYDVULiJmztaOV:b-1v4nkl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e26663bcdfa399dd206e50b6da768fb64e4cc89/WORKSPACE#L31)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Yes indeed.  Will use health server created in XMM repo once the merged is done.
</blockquote></details>

okay - maybe add that as a TODO

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/364)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier)

___
*[`WORKSPACE` line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/364#-NUSh-cS9ifCpnF0zd88:-NUSh-cS9ifCpnF0zd89:b-213qdd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e26663bcdfa399dd206e50b6da768fb64e4cc89/WORKSPACE#L55)):*
> ```Starlark
>     name = "maven_export",
>     artifacts = [
>         "io.grpc:grpc-kotlin-stub:1.2.0",
> ```

This should be GRPC_KOTLIN.version



_Code quote:_
```Starlark
1.2.0
```
___
*[`src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt` line 268 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/364#-NUShd8XCXbmp9oawPQR:-NUShd8XCXbmp9oawPQS:b-zbtw8k) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e26663bcdfa399dd206e50b6da768fb64e4cc89/src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt#L268)):*
> ```Kotlin
>         EntityContent(
>           displayName = "edp1",
>           encryptionPublicKey = EncryptionPublicKey.newBuilder().apply { data = ByteString.copyFromUtf8("testMCPublicKey") }.build(),
> ```

nit: Use Kotlin DSL builder



_Code quote:_
```Kotlin
EncryptionPublicKey.newBuilder().apply
```
___
*[`src/test/kotlin/org/wfanet/panelmatch/common/certificates/V2AlphaCertificateManagerTest.kt` line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/364#-NUSi3lsCSyg8mp4sxmX:-NUSi3lsCSyg8mp4sxmY:bw223tl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e26663bcdfa399dd206e50b6da768fb64e4cc89/src/test/kotlin/org/wfanet/panelmatch/common/certificates/V2AlphaCertificateManagerTest.kt#L57)):*
> ```Kotlin
> private val ROOT_CERTIFICATE by lazy { readCertificate(TestData.FIXED_CA_CERT_PEM_FILE) }
> private val CERTIFICATE by lazy { readCertificate(TestData.FIXED_SERVER_CERT_PEM_FILE) }
> private val PRIVATE_KEY by lazy { readPrivateKey(TestData.FIXED_SERVER_KEY_FILE, KEY_ALGORITHM) }
> ```

You shouldn't need a constant. This comes from the matching certificate's public key.



_Suggestion:_
```Kotlin
CERTIFICATE.publicKey.algorithm
```

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/364)* status: 20 of 36 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`WORKSPACE` line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/364#-NUSh-cS9ifCpnF0zd88:-NUVi4tC1c7kU8TfjyK4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e26663bcdfa399dd206e50b6da768fb64e4cc89/WORKSPACE#L55)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be GRPC_KOTLIN.version
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/panelmatch/common/certificates/V2AlphaCertificateManagerTest.kt` line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/364#-NUSi3lsCSyg8mp4sxmX:-NUViYGo8DGmEOKAXFJl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e26663bcdfa399dd206e50b6da768fb64e4cc89/src/test/kotlin/org/wfanet/panelmatch/common/certificates/V2AlphaCertificateManagerTest.kt#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You shouldn't need a constant. This comes from the matching certificate's public key.
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 16 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/364)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

**Pull request merged**
