### PR TITLE
Add Kotlin convenience function to generate KeyPairs

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/207)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/207)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @kungfucraig)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/certificates/GenerateKeyPair.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/207#-MoOInTN6fa7uPGHBg4A:-MoOInTOBnjMFsJ4EZ3s:b-w6gbw8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d6e4dd429fa0ac21896da0cd5837238048876438/src/main/kotlin/org/wfanet/panelmatch/common/certificates/GenerateKeyPair.kt#L23)):*
> ```Kotlin
> /** Generates a new [KeyPair]. */
> fun generateKeyPair(keyAlgorithm: String): KeyPair {
>   return KeyPairGenerator.getInstance(keyAlgorithm, jceProvider).genKeyPair()
> ```

shouldn't this live in common?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/207)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/certificates/GenerateKeyPair.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/207#-MoOInTN6fa7uPGHBg4A:-MoP9G8c0BIB9nGb7U06:b-he7pj4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d6e4dd429fa0ac21896da0cd5837238048876438/src/main/kotlin/org/wfanet/panelmatch/common/certificates/GenerateKeyPair.kt#L23)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't this live in common?
</blockquote></details>

Isn't it?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/207)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @kungfucraig)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/certificates/GenerateKeyPair.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/207#-MoOInTN6fa7uPGHBg4A:-MoZK_uI9rBSCAvyySuF:b-hs552c) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d6e4dd429fa0ac21896da0cd5837238048876438/src/main/kotlin/org/wfanet/panelmatch/common/certificates/GenerateKeyPair.kt#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Isn't it?
</blockquote></details>

common-jvm I meant

**Comment by efoxepstein** [comment]
Replacing this with https://github.com/world-federation-of-advertisers/common-jvm/pull/62

**Pull request closed without merging**
