### PR TITLE
Change Type of encrypted_id to Long

### PR DESCRIPTION
**Pull request by jmorrrr**
Changes id type from ByteString to Long to avoid interface issues and comply with int64 C++ type

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/proto/wfa/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61#-MfJn8dRBtDhTNAwfxtU:-MfJn8dRBtDhTNAwfxtV:bx5b3a7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b971cffe0ab2ad50ffb59745d41b315221d0fef4/src/main/proto/wfa/panelmatch/client/eventpreprocessing/preprocess_events.proto#L26)):*
> ```protobuf
>   repeated UnprocessedEvent unprocessed_events = 1;
>   message UnprocessedEvent {
>     bytes id = 1;
> ```

This one should stay bytes. It's only the output that's a Long.
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61#-MfJn_6w-XJBgWKHVjZ0:-MfJn_6xDUuVm-x91CBO:bapqpmd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/43367eb8eca7fd38e2a91589f9468e6485ac9a69/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L43)):*
> ```cpp
> 
> TEST(PreprocessEventsTest, ReturnsUnimplemented) {
>   uint64_t test_id = 1111;
> ```

This change should be undone (as mentioned in another file, the input type was correct before, it's only the output identifier that changes)
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EncryptEventsTest.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61#-MfJnghOE1LqAQfV1KOD:-MfJnghOE1LqAQfV1KOE:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/43367eb8eca7fd38e2a91589f9468e6485ac9a69/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EncryptEventsTest.kt#L37)):*
> ```Kotlin
>           pepper = ByteString.copyFromUtf8("pepper")
>           addUnprocessedEventsBuilder().apply {
>             id = 10000
> ```

Ditto
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/KvPairSize.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61#-MfJlpQy3p7ezlreYRA4:-MfJlpQy3p7ezlreYRA5:b-1xqj19) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/43367eb8eca7fd38e2a91589f9468e6485ac9a69/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/KvPairSize.kt#L22)):*
> ```Kotlin
> 
> /** Takes in a KV<Long,ByteString> and returns its size in bytes */
> object KvPairSize : SerializableFunction<KV<Long, ByteString>, Int> {
> ```

Can you rename it `EventSize`?

**Review by matthewclegg — APPROVED** [review]

**Review by jmorrrr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @enfreck)

___
*[src/main/proto/wfa/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61#-MfJn8dRBtDhTNAwfxtU:-MfJp9Bk0SI6ArFKBZ2Q:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b971cffe0ab2ad50ffb59745d41b315221d0fef4/src/main/proto/wfa/panelmatch/client/eventpreprocessing/preprocess_events.proto#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This one should stay bytes. It's only the output that's a Long.
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61#-MfJn_6w-XJBgWKHVjZ0:-MfJpJp3CVeVfHlCjrs9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/43367eb8eca7fd38e2a91589f9468e6485ac9a69/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This change should be undone (as mentioned in another file, the input type was correct before, it's only the output identifier that changes)
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EncryptEventsTest.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61#-MfJnghOE1LqAQfV1KOD:-MfJwQiQDdruj1fl5am8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/43367eb8eca7fd38e2a91589f9468e6485ac9a69/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EncryptEventsTest.kt#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/KvPairSize.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61#-MfJlpQy3p7ezlreYRA4:-MfJwOia5ZfwdoOAl-2x:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/43367eb8eca7fd38e2a91589f9468e6485ac9a69/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/KvPairSize.kt#L22)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you rename it `EventSize`?
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61)* status: all files reviewed, 2 unresolved discussions (waiting on @enfreck and @jmorrrr)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EncryptionEventsDoFnTest.kt, line 68 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61#-MfK2EoDDoCll8vBf8P8:-MfK2EoDDoCll8vBf8P9:b-gliqta) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/04966ad48236a9b83450a5160ee3e5ca78c31771/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EncryptionEventsDoFnTest.kt#L68)):*
> ```Kotlin
> }
> 
> fun byteStringKvOf(key: String, value: String): KV<ByteString, ByteString> {
> ```

Maybe rename these to something like `inputOf` and `outputOf` to make their usage more clear
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EncryptionEventsDoFnTest.kt, line 84 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61#-MfK2Rz8BQQQQbbwd63a:-MfK2Rz8BQQQQbbwd63b:b-hc1tly) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/04966ad48236a9b83450a5160ee3e5ca78c31771/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EncryptionEventsDoFnTest.kt#L84)):*
> ```Kotlin
>           for (events in request.unprocessedEventsList) {
>             addProcessedEventsBuilder().apply {
>               this.encryptedId = events.id.toStringUtf8().toLong().plus(1)
> ```

` + 1` should work instead of `.plus(1)`

**Review by jmorrrr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @enfreck)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EncryptionEventsDoFnTest.kt, line 68 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61#-MfK2EoDDoCll8vBf8P8:-MfK3iaK7UCcX5OSA9In:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/04966ad48236a9b83450a5160ee3e5ca78c31771/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EncryptionEventsDoFnTest.kt#L68)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe rename these to something like `inputOf` and `outputOf` to make their usage more clear
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EncryptionEventsDoFnTest.kt, line 84 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61#-MfK2Rz8BQQQQbbwd63a:-MfK3q-l2W16wf-_qg_H:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/04966ad48236a9b83450a5160ee3e5ca78c31771/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EncryptionEventsDoFnTest.kt#L84)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

` + 1` should work instead of `.plus(1)`
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck, @jmorrrr, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61#-MfK8IfR38mGXueDczoO:-MfK8IfSD5Sxzr3gbMkI:b5oz3qo) (no related file):*
Can you update the PR title to `Change` instead of `Changes`? We want to use the imperative mood

---

**Review by jmorrrr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @enfreck, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61#-MfK8IfR38mGXueDczoO:-MfK8sMK6pVMeP-MHsbd:b-896fix) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you update the PR title to `Change` instead of `Changes`? We want to use the imperative mood
</blockquote></details>

Done.

---

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Review by enfreck — APPROVED** [review]
> Reviewed 6 of 10 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/61)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmorrrr)

**Pull request merged**
