### PR TITLE
Add tool to generate GraphViz for an ExchangeWorkflow

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/136)

### CODE REVIEW

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/136)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @robinsons and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/136#-MkbWKh24FSpYWoi-9Cq:-MkbWKh24FSpYWoi-9Cr:b-sjtm2n) (no related file):*
Question for reviewers: should we move this over to cross-media-measurement and embed it into the `Exchange` resource so `/Exchanges.GetExchange` would include a string field containing the graphviz with the current status of the exchange indicated? (We can highlight which steps are completed/active/failed/not yet done.)

---

**Review by robinsons — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/136)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/136#-MkbWKh24FSpYWoi-9Cq:-MkcRd5s170ivDbbGSxr:b-d2p1ep) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Question for reviewers: should we move this over to cross-media-measurement and embed it into the `Exchange` resource so `/Exchanges.GetExchange` would include a string field containing the graphviz with the current status of the exchange indicated? (We can highlight which steps are completed/active/failed/not yet done.)
</blockquote></details>

That sounds neat to me.

---
___
*[src/main/kotlin/org/wfanet/panelmatch/tools/ExchangeWorkflowToGraphvizMain.kt, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/136#-MkcTGjEEzlgHLxX1dsW:-MkcTGjEEzlgHLxX1dsX:bwynrn1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c55c1e58da7fe8d1ed0cf4f788332daf8eb03ed3/src/main/kotlin/org/wfanet/panelmatch/tools/ExchangeWorkflowToGraphvizMain.kt#L43)):*
> ```
> egg
> ```
Has `egg` grown on you?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/136)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/tools/ExchangeWorkflowToGraphvizMain.kt, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/136#-MkcTGjEEzlgHLxX1dsW:-MkcUaBm9ANgt9hu7CB8:bf95gjc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c55c1e58da7fe8d1ed0cf4f788332daf8eb03ed3/src/main/kotlin/org/wfanet/panelmatch/tools/ExchangeWorkflowToGraphvizMain.kt#L43)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

> ```
> egg
> ```
Has `egg` grown on you?
</blockquote></details>

It's so nice and blob-shaped! How can I resist?

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/136)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @robinsons)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/136)* status: all files reviewed, 2 unresolved discussions (waiting on @robinsons and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/136#-MkbWKh24FSpYWoi-9Cq:-Mkh9xp57mp3TtxkkVaS:b8pc323) (no related file):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

That sounds neat to me.
</blockquote></details>

@stevenwarejones WDYT?

---

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
Should we be using the PipelineDotRenderer?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/136#-:-MkljOAJ37deXUNFD8U1:b-dudwml)* status: all files reviewed, 2 unresolved discussions (waiting on @robinsons and @stevenwarejones)

**Review by efoxepstein — COMMENTED** [review]
> Should we be using the PipelineDotRenderer?

Why? That's specific to Apache Beam

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/136#-:-MkxWicQ41Vd8kiSr9bN:b-kh2uq3)* status: all files reviewed, 2 unresolved discussions (waiting on @robinsons and @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/136)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @robinsons)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/136#-MkbWKh24FSpYWoi-9Cq:-MlAH1mN8jB1aBxINpSZ:b-wqugq6) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@stevenwarejones WDYT?
</blockquote></details>

yes - I like the centralized view. Please move to cross-media-measurement.

---

**Pull request closed without merging**
