### PR TITLE
Creates EncryptEvents

### PR DESCRIPTION
**Pull request by jmorrrr**
Creates implementation for encryption serializable function and tests
that it returns kUnimplemented for now

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55)* status: all files reviewed, 6 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEvents.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55#-Mf9y3DV2k8m41gXDfnM:-Mf9y3DV2k8m41gXDfnN:b-4w62wf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfe75c9f3cd376f498029f6d10084f17b22660ab/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEvents.kt#L27)):*
> ```Kotlin
>  * PreprocessEventsResponse
>  */
> class EncryptEvents : SerializableFunction<PreprocessEventsRequest, PreprocessEventsResponse> {
> ```

What about the pepper and crypto key?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEvents.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55#-Mf9xjTG8tsWbP2aFB5e:-Mf9xjTTAxIu7FVXjR26:by3rcmw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfe75c9f3cd376f498029f6d10084f17b22660ab/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEvents.kt#L29)):*
> ```Kotlin
> class EncryptEvents : SerializableFunction<PreprocessEventsRequest, PreprocessEventsResponse> {
>   override fun apply(request: PreprocessEventsRequest): PreprocessEventsResponse {
>     val preprocessEvents: PreprocessEvents = JniPreprocessEvents()
> ```

This will make a new `JniPreprocessEvents` with each call to `apply`. Can you instead pull it out into a property?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55#-Mf9y9fu-KS5785dQ8Ia:-Mf9y9fv87iORTcvd6py:bxb63sg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfe75c9f3cd376f498029f6d10084f17b22660ab/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt#L39)):*
> ```Kotlin
>               addUnprocessedEventsBuilder().apply {
>                 this.id = ByteString.copyFromUtf8("11111")
>                 this.data = ByteString.copyFromUtf8("11111")
> ```

Please use different strings (so you can detect if e.g. the wires get crossed somewhere)
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55#-Mf9yGLxCOomZc_X77Eu:-Mf9yGLxCOomZc_X77Ev:bm7v8q3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfe75c9f3cd376f498029f6d10084f17b22660ab/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt#L43)):*
> ```Kotlin
>             }
>             .build()
>         val E: EncryptEvents = EncryptEvents()
> ```

camelCasePlease
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55#-Mf9yKxT9xvxkKy7VUGB:-Mf9yKxT9xvxkKy7VUGC:b-p4mulb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfe75c9f3cd376f498029f6d10084f17b22660ab/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt#L44)):*
> ```Kotlin
>             .build()
>         val E: EncryptEvents = EncryptEvents()
>         val response: PreprocessEventsResponse = E.apply(request)
> ```

Can you move everything except for this statement outside of the `assertFailsWith` so we can be sure that it's this line in particular that's problematic?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55#-Mf9yRQI-5D4PJQCtdVj:-Mf9yRQI-5D4PJQCtdVk:b8cknwt) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfe75c9f3cd376f498029f6d10084f17b22660ab/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt#L44)):*
> ```Kotlin
>             .build()
>         val E: EncryptEvents = EncryptEvents()
>         val response: PreprocessEventsResponse = E.apply(request)
> ```

It looks like the variable `response` is unused -- can you just use the RHS without assigning it to anything?

**Review by jmorrrr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEvents.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55#-Mf9y3DV2k8m41gXDfnM:-MfA09itBeP2OElF5Wfu:b-4xdwvu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfe75c9f3cd376f498029f6d10084f17b22660ab/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEvents.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What about the pepper and crypto key?
</blockquote></details>


The pepper and crypto key are included in the PreprocessEventsRequest so it shouldn't change what the SerializableFunction takes in but I will assign them in the test.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEvents.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55#-Mf9xjTG8tsWbP2aFB5e:-MfA0wUJ7qSZApdPlwL0:bvm7z8d) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfe75c9f3cd376f498029f6d10084f17b22660ab/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEvents.kt#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This will make a new `JniPreprocessEvents` with each call to `apply`. Can you instead pull it out into a property?
</blockquote></details>

Resolved
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55#-Mf9y9fu-KS5785dQ8Ia:-MfA0LilACUS_ZjSFC8t:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfe75c9f3cd376f498029f6d10084f17b22660ab/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use different strings (so you can detect if e.g. the wires get crossed somewhere)
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55#-Mf9yGLxCOomZc_X77Eu:-MfA-wQs-3_DQ7rbMgqx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfe75c9f3cd376f498029f6d10084f17b22660ab/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

camelCasePlease
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55#-Mf9yRQI-5D4PJQCtdVj:-MfA-Nfs8UU-k3aog4jG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfe75c9f3cd376f498029f6d10084f17b22660ab/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt#L44)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It looks like the variable `response` is unused -- can you just use the RHS without assigning it to anything?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55#-Mf9yKxT9xvxkKy7VUGB:-MfA-uaUCJLjctzcHnk9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfe75c9f3cd376f498029f6d10084f17b22660ab/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt#L44)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you move everything except for this statement outside of the `assertFailsWith` so we can be sure that it's this line in particular that's problematic?
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55)* status: all files reviewed, 3 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEvents.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55#-Mf9y3DV2k8m41gXDfnM:-MfA9KD20myQk793V1-U:btne2rn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfe75c9f3cd376f498029f6d10084f17b22660ab/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEvents.kt#L27)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

The pepper and crypto key are included in the PreprocessEventsRequest so it shouldn't change what the SerializableFunction takes in but I will assign them in the test.
</blockquote></details>

Where are the pepper and crypto key set? https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt#L36 -- I don't see it
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55#-Mf9yKxT9xvxkKy7VUGB:-MfA9iCjD4wHRCWavPlG:bijhv4a) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfe75c9f3cd376f498029f6d10084f17b22660ab/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt#L44)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's still unclear if `EncryptEvents()` is throwing or if `apply` is throwing. Can you pull out `val encryptEvents = EncryptEvents()` from the `assertFailsWith`?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt, line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55#-MfA9RBEBzpys_dqruyr:-MfA9RBEBzpys_dqruys:b59tth2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/73d47d0d7e4dfcb24dc9f0f423408049150afbc2/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt#L34)):*
> ```Kotlin
>       PreprocessEventsRequest.newBuilder()
>         .apply {
>           this.cryptoKey = ByteString.copyFromUtf8("cryptokey")
> ```

You shouldn't need `this.` -- you should be able to just write `cryptoKey = ...`

**Review by jmorrrr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEvents.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55#-Mf9y3DV2k8m41gXDfnM:-MfAFrNl85EtQ5NDNJip:bmkzhxm) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfe75c9f3cd376f498029f6d10084f17b22660ab/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEvents.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Where are the pepper and crypto key set? https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptionEventsDoFn.kt#L36 -- I don't see it
</blockquote></details>

Next PR
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55#-Mf9yKxT9xvxkKy7VUGB:-MfAC5Kz4JtDu0R5rcrf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfe75c9f3cd376f498029f6d10084f17b22660ab/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt#L44)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's still unclear if `EncryptEvents()` is throwing or if `apply` is throwing. Can you pull out `val encryptEvents = EncryptEvents()` from the `assertFailsWith`?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt, line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55#-MfA9RBEBzpys_dqruyr:-MfAC4fj6a-5subMYZ5J:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/73d47d0d7e4dfcb24dc9f0f423408049150afbc2/src/test/kotlin/org/wfanet/panelmatch/client/eventencryption/EncryptEventsTest.kt#L34)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

You shouldn't need `this.` -- you should be able to just write `cryptoKey = ...`
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck and @matthewclegg)

**Review by matthewclegg — APPROVED** [review]

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 7 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/55)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmorrrr)

**Pull request merged**
