### PR TITLE
Update and Create Bazel files to support gcloud

### PR DESCRIPTION
**Pull request by mpatel24**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/230)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/230)* status: 1 of 10 files reviewed, 1 unresolved discussion (waiting on @mpatel24)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/230#-MpxUqx2D4Tl_QCZGl9J:-MpxUqx34xgD-O3kIaxm:b-lp0yoc) (no related file):*
Please fix build and lint.

---

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/230)* status: 1 of 10 files reviewed, 7 unresolved discussions (waiting on @mpatel24)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/certificates/CertificateAuthority.kt, line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/230#-MpxUwirDNBEZEOLBgEt:-MpxUwirDNBEZEOLBgEu:b90sz5c) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/36e82523362955895c02715c9f5f12d93877ae26/src/main/kotlin/org/wfanet/panelmatch/common/certificates/CertificateAuthority.kt#L31)):*
> ```Kotlin
>   suspend fun generateX509CertificateAndPrivateKey(
>     rootPublicKey: PublicKey, projectId : String, caLocation: String,
>     poolId : String, certificateAuthorityName : String, certificateName : String,
> ```

Please revert this. These things, if needed, can be passed into the ctor of specific instances.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/certificates/V2AlphaCertificateManager.kt, line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/230#-MpxV47sCOpnKGuD87b9:-MpxV47sCOpnKGuD87bA:bpxjd3d) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/36e82523362955895c02715c9f5f12d93877ae26/src/main/kotlin/org/wfanet/panelmatch/common/certificates/V2AlphaCertificateManager.kt#L93)):*
> ```Kotlin
> 
>     val rootKey = getRootCertificate(localName).publicKey
>     val (x509, privateKey) = certificateAuthority.generateX509CertificateAndPrivateKey(rootKey,"test","test", "test","test", "test", "test", "test", "test")
> ```

Please revert this
___
*[src/main/kotlin/org/wfanet/panelmatch/common/certificates/gcloud/CertificateAuthority.kt, line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/230#-MpxVDpiCgrtqeOgruLM:-MpxVDpiCgrtqeOgruLN:b2s2ria) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/36e82523362955895c02715c9f5f12d93877ae26/src/main/kotlin/org/wfanet/panelmatch/common/certificates/gcloud/CertificateAuthority.kt#L52)):*
> ```Kotlin
>     rootPublicKey: PublicKey,
>   ): Pair<X509Certificate, PrivateKey> {
>     val certificateLifetime = 1000L
> ```

What is this?
___
*[src/main/kotlin/org/wfanet/panelmatch/common/certificates/gcloud/CertificateAuthority.kt, line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/230#-MpxVB2J8Soc2B5ds949:-MpxVB2J8Soc2B5ds94A:bbnzn2r) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/36e82523362955895c02715c9f5f12d93877ae26/src/main/kotlin/org/wfanet/panelmatch/common/certificates/gcloud/CertificateAuthority.kt#L70)):*
> ```Kotlin
> 
>     // Set the X.509 fields required for the certificate.
>     val x509Parameters: X509Parameters =
> ```

This can be a constant
___
*[src/main/kotlin/org/wfanet/panelmatch/common/certificates/testing/TestCertificateAuthority.kt, line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/230#-MpxVHW_9fIUpFd7mnU1:-MpxVHW_9fIUpFd7mnU2:b-n67mzv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/36e82523362955895c02715c9f5f12d93877ae26/src/main/kotlin/org/wfanet/panelmatch/common/certificates/testing/TestCertificateAuthority.kt#L25)):*
> ```Kotlin
>   override suspend fun generateX509CertificateAndPrivateKey(
>     rootPublicKey: PublicKey, projectId : String, caLocation: String,
>     poolId : String, certificateAuthorityName : String, certificateName : String
> ```

Please revert
___
*[src/test/kotlin/org/wfanet/panelmatch/common/certificates/V2AlphaCertificateManagerTest.kt, line 206 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/230#-MpxVIJbBiXeulC8ZFw_:-MpxVIJbBiXeulC8ZFwa:b-n67mzv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/36e82523362955895c02715c9f5f12d93877ae26/src/test/kotlin/org/wfanet/panelmatch/common/certificates/V2AlphaCertificateManagerTest.kt#L206)):*
> ```Kotlin
>   override suspend fun generateX509CertificateAndPrivateKey(
>     rootPublicKey: PublicKey, projectId : String, caLocation: String,
>     poolId : String, certificateAuthorityName : String, certificateName : String
> ```

Please revert

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 7 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/230)* status: 8 of 10 files reviewed, 9 unresolved discussions (waiting on @mpatel24)

___
*[imports/java/com/google/api/BUILD.bazel, line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/230#-MqVwApPBw67KohfCaX9:-MqVwApPBw67KohfCaXA:b-9fw1n9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/36e82523362955895c02715c9f5f12d93877ae26/imports/java/com/google/api/BUILD.bazel#L4)):*
> ```Starlark
> 
> alias(
>     name = "core",
> ```

should these come via common?
___
*[src/main/kotlin/org/wfanet/panelmatch/common/certificates/gcloud/CertificateAuthority.kt, line 71 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/230#-MqVwMbqEv65kMu-sNuW:-MqVwMbqEv65kMu-sNuX:bkiv394) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/36e82523362955895c02715c9f5f12d93877ae26/src/main/kotlin/org/wfanet/panelmatch/common/certificates/gcloud/CertificateAuthority.kt#L71)):*
> ```Kotlin
>     // Set the X.509 fields required for the certificate.
>     val x509Parameters: X509Parameters =
>       X509Parameters.newBuilder()
> ```

use the proto kotlin builders please

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/230)* status: 9 of 10 files reviewed, 10 unresolved discussions (waiting on @mpatel24)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/230#-MquMAz0EhWh5OnVJrCu:-MquMAz0EhWh5OnVJrCv:b-z9hhx5) (no related file):*
Can this PR be closed?

---

**Pull request closed without merging**
