### PR TITLE
Improve AbstractStorageTest

### PR DESCRIPTION
**Pull request by efoxepstein**
- Eliminates unused variables.
 - Pulls out constants.
 - Uses runBlockingTest.
 - Expands test coverage.

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/29)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
Needs a rebase

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/29#-:-Mctzfi4C6RWvD3urDm8:b-7blfmd)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @enfreck and @jmorrrr)

**Review by enfreck — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmorrrr and @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/29)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @jmorrrr)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt, line 44 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/29#-MczBg5i8z59r2dqtX_H:-MczBg5i8z59r2dqtX_I:b-pejvpa) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/972bbee34f634865bc28e8dba2244ea9b4c63081/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt#L44)):*
> ```Kotlin
>   companion object {
>     /** Deletes all existing stored items. */
>     fun clear() {
> ```

internal

**Review by jmorrrr — APPROVED** [review]
> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/29)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/29)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt, line 44 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/29#-MczBg5i8z59r2dqtX_H:-Mczfyeb9ya1e4a0Dvby:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/972bbee34f634865bc28e8dba2244ea9b4c63081/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorage.kt#L44)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

internal
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/29)* status: 7 of 9 files reviewed, all discussions resolved (waiting on @enfreck and @jmorrrr)

**Pull request merged**
