### PR TITLE
Add salt to Hkdf

### PR DESCRIPTION
**Pull request by enfreck**
Add salt to Hkdf

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85)

### CODE REVIEW

**Review by jmorrrr — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein, @matthewclegg, and @stevenwarejones)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85)* status: all files reviewed, 3 unresolved discussions (waiting on @enfreck, @matthewclegg, and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85#-MgvmMJ1DeFtVxUIwVG0:-MgvmMJ2E2INJY720nLW:b7hh520) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/198e00ffd708029e1926ff2aa1d41f5447cc9a00/src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc#L65)):*
> ```cpp
>   EventDataPreprocessor preprocessor = EventDataPreprocessor(
>       std::move(cryptor), SecretDataFromStringView(request.pepper()),
>       SecretDataFromStringView(""), &fingerprinter, &aes_hkdf);
> ```

Can you add: `// TODO: load the salt from the request`
___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85#-Mgvmb5w2PqAbnK2FWN4:-Mgvmb5w2PqAbnK2FWN5:b-jmsk9v) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/198e00ffd708029e1926ff2aa1d41f5447cc9a00/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L46)):*
> ```objc
>   EventDataPreprocessor(std::unique_ptr<common::crypto::Cryptor> cryptor,
>                         const ::crypto::tink::util::SecretData& pepper,
>                         const ::crypto::tink::util::SecretData& salt,
> ```

Rename `salt` and `pepper` to `hkdf_pepper` and `identifier_hash_pepper` please
___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85#-Mgvmona3OA13HtFdFsb:-Mgvmona3OA13HtFdFsc:b-7cixuu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/198e00ffd708029e1926ff2aa1d41f5447cc9a00/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L57)):*
> ```objc
>  private:
>   std::unique_ptr<common::crypto::Cryptor> cryptor_;
>   const ::crypto::tink::util::SecretData& salt_;
> ```

Store this by value please (remove the `const` and `&` please) so that we don't run into lifetime bugs (and rename per above)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85#-MgvmMJ1DeFtVxUIwVG0:-MgvpmqA16UZuNQaRmsW:b-jthpc6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/198e00ffd708029e1926ff2aa1d41f5447cc9a00/src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc#L65)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you add: `// TODO: load the salt from the request`
</blockquote></details>

Do we have documentation about a shared secret salt for the AES key derivation? Do we need a salt if the AES keys are rotating frequently? This applies to the fingerprinter too. Not sure if I see that in the docs.
___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85#-Mgvmb5w2PqAbnK2FWN4:-MgvvSMo9_zCXLwT5yRt:b-1b83p5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/198e00ffd708029e1926ff2aa1d41f5447cc9a00/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L46)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Rename `salt` and `pepper` to `hkdf_pepper` and `identifier_hash_pepper` please
</blockquote></details>

but about prepending this with `shared_` 
___
*[src/test/cc/wfa/panelmatch/common/crypto/aes_with_hkdf_test.cc, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85#-MgvvfR3DCa8Fd6lDTre:-MgvvfR3DCa8Fd6lDTrf:b-o8oreg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/198e00ffd708029e1926ff2aa1d41f5447cc9a00/src/test/cc/wfa/panelmatch/common/crypto/aes_with_hkdf_test.cc#L37)):*
> ```cpp
>   ASSERT_OK_AND_ASSIGN(
>       std::string ciphertext,
>       aes_hkdf.Encrypt(plaintext, key, SecretDataFromStringView("test-salt")));
> ```

I know you have a test showing the hkdf class yields different results for different salts but probably good to replicate here as well to show the encrypt returns different results for different salts

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85)* status: all files reviewed, 4 unresolved discussions (waiting on @enfreck, @matthewclegg, and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85#-MgvmMJ1DeFtVxUIwVG0:-MgvzuJjD2lYIje4UGoa:btj0kyg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/198e00ffd708029e1926ff2aa1d41f5447cc9a00/src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc#L65)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Do we have documentation about a shared secret salt for the AES key derivation? Do we need a salt if the AES keys are rotating frequently? This applies to the fingerprinter too. Not sure if I see that in the docs.
</blockquote></details>

No documentation yet -- but it'll be required if we want to experiment with optimizations to reuse the same queries for several days (since it's potentially unsafe to reuse the same AES keys).

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @matthewclegg, and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85#-MgvmMJ1DeFtVxUIwVG0:-MgwFv3q8WApza6SFCbN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/198e00ffd708029e1926ff2aa1d41f5447cc9a00/src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc#L65)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

No documentation yet -- but it'll be required if we want to experiment with optimizations to reuse the same queries for several days (since it's potentially unsafe to reuse the same AES keys).
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85#-Mgvmb5w2PqAbnK2FWN4:-MgwFwTD1-hApPZIuwHZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/198e00ffd708029e1926ff2aa1d41f5447cc9a00/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L46)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

but about prepending this with `shared_` 
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85#-Mgvmona3OA13HtFdFsb:-MgwG4Id4Ub7eHgoXLb6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/198e00ffd708029e1926ff2aa1d41f5447cc9a00/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Store this by value please (remove the `const` and `&` please) so that we don't run into lifetime bugs (and rename per above)
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/common/crypto/aes_with_hkdf_test.cc, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85#-MgvvfR3DCa8Fd6lDTre:-MgwGLYqDNr7vmQt1Vqr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/198e00ffd708029e1926ff2aa1d41f5447cc9a00/src/test/cc/wfa/panelmatch/common/crypto/aes_with_hkdf_test.cc#L37)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I know you have a test showing the hkdf class yields different results for different salts but probably good to replicate here as well to show the encrypt returns different results for different salts
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85)* status: all files reviewed, 3 unresolved discussions (waiting on @enfreck, @matthewclegg, and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 64 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85#-MgwZRTn41eqnWpvmJBM:-MgwZRTo-a7qhtcK4DM3:b-u984u7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac4cf7713288eafd11a306a065055f83021c3fc2/src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc#L64)):*
> ```cpp
>   }
>   // TODO(juliamorrissey): load the salt from the request
>   EventDataPreprocessor preprocessor = EventDataPreprocessor(
> ```

`Foo foo = Foo(...)` -> `Foo foo(...)` please
___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85#-Mgvmb5w2PqAbnK2FWN4:-MgwZZVV27FYo86WALmy:bqtrb2j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/198e00ffd708029e1926ff2aa1d41f5447cc9a00/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L46)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Doesn't look done in the constructor. Also @stevenwarejones what do you mean by `shared_`?

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @matthewclegg, and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 64 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85#-MgwZRTn41eqnWpvmJBM:-MgwcCqL400GvGrA75rI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac4cf7713288eafd11a306a065055f83021c3fc2/src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc#L64)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`Foo foo = Foo(...)` -> `Foo foo(...)` please
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85#-Mgvmb5w2PqAbnK2FWN4:-MgwcCCi2cc587ENzpTA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/198e00ffd708029e1926ff2aa1d41f5447cc9a00/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L46)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Doesn't look done in the constructor. Also @stevenwarejones what do you mean by `shared_`?
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85)* status: all files reviewed, 2 unresolved discussions (waiting on @matthewclegg and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85#-Mgvmb5w2PqAbnK2FWN4:-MgwdRTkBT1RWSO4qyhU:b-gr7620) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/198e00ffd708029e1926ff2aa1d41f5447cc9a00/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L46)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Waiting on @stevenwarejones

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @matthewclegg)

___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85#-Mgvmb5w2PqAbnK2FWN4:-MgzzPYb8OZmyEiRI5SL:b-a0fzh0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/198e00ffd708029e1926ff2aa1d41f5447cc9a00/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L46)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Waiting on @stevenwarejones 
</blockquote></details>

ultimately, these peppers need to be shared with the model provider so they can hash the data and generate AES keys the same way. Maybe at least a comment if you dont want to delineate that in the variable name.

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @matthewclegg)

___
*[src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85#-Mgvmb5w2PqAbnK2FWN4:-Mh-3Mfq2_RRsLr0OeqT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/198e00ffd708029e1926ff2aa1d41f5447cc9a00/src/main/cc/wfa/panelmatch/protocol/crypto/event_data_preprocessor.h#L46)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ultimately, these peppers need to be shared with the model provider so they can hash the data and generate AES keys the same way. Maybe at least a comment if you dont want to delineate that in the variable name.
</blockquote></details>

Done.

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 5 of 10 files at r1, 2 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @matthewclegg, and @oliver-amzn)

**Review by matthewclegg — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

**Review by matthewclegg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/85)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Pull request merged**
