### PR TITLE
Decrypt Query Result and resulting Encrypted Event in a single JNI call

### PR DESCRIPTION
**Pull request by stevenwarejones**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 20 files at r2, 13 of 54 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104)* status: 17 of 60 files reviewed, 8 unresolved discussions (waiting on @stevenwarejones)

___
*[build/repositories.bzl, line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibItBGA2VBRVwVWVKl:-MibItBGA2VBRVwVWVKm:bfzjnag) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/build/repositories.bzl#L27)):*
> ```Starlark
>         sha256 = "dafd0e129c06fc67c48a714ba34e7503d6e767ae1f287b47f9ce4072401f5f8b",
>         strip_prefix = "common-cpp-f9c572d081e0c33ec1b094379e550e750d5baf15",
>         url = "https://github.com/world-federation-of-advertisers/common-cpp/archive/f9c572d081e0c33ec1b094379e550e750d5baf15.tar.gz",
> ```

Can you please use a tagged release? (We can create a new one if needed)
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.h, line 18 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibJPr203L8RmxqObGw:-MibJPr203L8RmxqObGx:bgil992) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.h#L18)):*
> ```objc
> 
> #ifndef SRC_MAIN_CC_WFA_PANELMATCH_CLIENT_PRIVATEMEMBERSHIP_SYMMETRIC_PRIVATE_MEMBERSHIP_H_
> #define SRC_MAIN_CC_WFA_PANELMATCH_CLIENT_PRIVATEMEMBERSHIP_SYMMETRIC_PRIVATE_MEMBERSHIP_H_
> ```

Private memership, by definition, is symmetric -- this is redundant.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.h, line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibJURJ2TefmNfIeTop:-MibJURJ2TefmNfIeToq:bii5n5n) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.h#L27)):*
> ```objc
> namespace wfa::panelmatch::client::privatemembership {
> absl::StatusOr<SymmetricDecryptQueryResultsResponse>
> SymmetricDecryptQueryResults(
> ```

Will other functions eventually live in here? If not, we should name the file after this function probably.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.cc, line 43 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibJq3T-Nmy9aYYqK58:-MibJq3T-Nmy9aYYqK59:bt8k3b6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.cc#L43)):*
> ```cpp
> 
> absl::StatusOr<SymmetricDecryptQueryResultsResponse>
> SymmetricDecryptQueryResults(
> ```

The style guide prefers short functions in C++. Can you extract a few helper functions?

One could be building the ClientDecryptQueriesRequest, once could be building the final result, for example.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.cc, line 68 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibK8Kx4jPYzk1JXAs9:-MibK8Kx4jPYzk1JXAsA:b-amc9uz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.cc#L68)):*
> ```cpp
>   }
>   ASSIGN_OR_RETURN(ClientDecryptQueriesResponse client_decrypt_queries_response,
>                    ::private_membership::batch::DecryptQueries(
> ```

https://abseil.io/tips/130 -- only fully qualify if necessary (except for in using-declarations)
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/testing/private_membership_helper.h, line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibKZh76qmTsqrtWLZs:-MibKZh76qmTsqrtWLZt:bb6upda) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/client/privatemembership/testing/private_membership_helper.h#L27)):*
> ```objc
> namespace wfa::panelmatch::client::privatemembership::testing {
> 
> absl::StatusOr<::private_membership::batch::DecryptQueriesRequest>
> ```

https://abseil.io/tips/130 -- only fully qualify if necessary (except for using-decls, which should always be fully qualified)
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/testing/private_membership_helper.cc, line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibKih77KwGKXuilK0o:-MibKih77KwGKXuilK0p:bl1gfif) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/client/privatemembership/testing/private_membership_helper.cc#L25)):*
> ```cpp
> #include <vector>
> 
> #include "./galois_key.h"
> ```

This is weird, what's happening here?
___
*[src/main/cc/wfa/panelmatch/common/crypto/peppered_fingerprinter.cc, line 21 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibKuNUEInJJ2j0QqV3:-MibKuNUEInJJ2j0QqV4:bg6lgd8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/common/crypto/peppered_fingerprinter.cc#L21)):*
> ```cpp
> #include "absl/status/status.h"
> #include "common_cpp/fingerprinters/fingerprinters.h"
> #include "common_cpp/macros/macros.h"
> ```

I'm not sure I like this change -- CHECK_NOTNULL is a pretty canonical way to do it.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104)* status: 9 of 63 files reviewed, 8 unresolved discussions (waiting on @efoxepstein)

___
*[build/repositories.bzl, line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibItBGA2VBRVwVWVKl:-Mj0iCigAp7t6AeqdqTd:b-kcx7f7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/build/repositories.bzl#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you please use a tagged release? (We can create a new one if needed)
</blockquote></details>

Used your latest from common-cpp
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/testing/private_membership_helper.h, line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibKZh76qmTsqrtWLZs:-Mj09xgS9-TZ3LkAt142:bpa364b) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/client/privatemembership/testing/private_membership_helper.h#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

https://abseil.io/tips/130 -- only fully qualify if necessary (except for using-decls, which should always be fully qualified)
</blockquote></details>

I thought in .h files, I should use `using` since it would export it.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/testing/private_membership_helper.cc, line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibKih77KwGKXuilK0o:-Mj0A9LR0PvXYCPhagAX:bjzqp3a) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/client/privatemembership/testing/private_membership_helper.cc#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is weird, what's happening here?
</blockquote></details>

These files are from `shell-encryption` in the base directory. If I don't preface with `./...` the linter is complaining. Whats the best practice here?
___
*[src/main/cc/wfa/panelmatch/common/crypto/peppered_fingerprinter.cc, line 21 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibKuNUEInJJ2j0QqV3:-Mj0i73l7OQoj6g5sNkR:boo7g7v) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/common/crypto/peppered_fingerprinter.cc#L21)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'm not sure I like this change -- CHECK_NOTNULL is a pretty canonical way to do it.
</blockquote></details>

Reverted - based on your fixes in common-cpp
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.h, line 18 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibJPr203L8RmxqObGw:-Mj08tE63nCfATRdegJ8:b-hps4v3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.h#L18)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Private memership, by definition, is symmetric -- this is redundant.
</blockquote></details>

For now, I'm just using the naming convention already in the repo. I agree that we need to decide on a new name. I think the key nuance is what is the difference in functionality between this file and `private_membership.h`
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.h, line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibJURJ2TefmNfIeTop:-Mj09Bm4C2OJ04EK8JVA:bq7ifq5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.h#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Will other functions eventually live in here? If not, we should name the file after this function probably.
</blockquote></details>

are you okay with the name `symmetric_decrypt_query_results.h` for now? Did some renaming for now across the repo with this in mind.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.cc, line 43 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibJq3T-Nmy9aYYqK58:-Mj0gSZp4Cj_lEx0T3BJ:bnmw77q) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.cc#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The style guide prefers short functions in C++. Can you extract a few helper functions?

One could be building the ClientDecryptQueriesRequest, once could be building the final result, for example.
</blockquote></details>

I divided it into `RemoveRLWE` and `RemoveAes` ... does that work?
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.cc, line 68 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibK8Kx4jPYzk1JXAs9:-Mj09u13BEztRelg0dfL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.cc#L68)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

https://abseil.io/tips/130 -- only fully qualify if necessary (except for in using-declarations)
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 17 of 54 files at r3, 37 of 37 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104)* status: all files reviewed, 5 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/testing/private_membership_helper.h, line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibKZh76qmTsqrtWLZs:-Mj0yyKg0M-Vlg54Xgy_:b-nz6iaw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/client/privatemembership/testing/private_membership_helper.h#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I thought in .h files, I should use `using` since it would export it.
</blockquote></details>

All I'm saying is write `private_membership::Foo` instead of `::private_membership::Foo`
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/testing/private_membership_helper.cc, line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibKih77KwGKXuilK0o:-Mj0z7jODeUdPlzRKg87:b-8ei47l) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/client/privatemembership/testing/private_membership_helper.cc#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

These files are from `shell-encryption` in the base directory. If I don't preface with `./...` the linter is complaining. Whats the best practice here?
</blockquote></details>

Maybe just add a big TODO above all of this saying that we shouldn't need to do any of this but we're lacking the server-side libraries necessary to test this yet?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptorTest.kt, line 32 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-Mj0ykCGAwsuwdvrR3sV:-Mj0ykCGAwsuwdvrR3sW:betquxn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bfc194be1d785c4c35288905bfae752b593937e9/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptorTest.kt#L32)):*
> ```Kotlin
>   val privateMembershipCryptor = JniPrivateMembershipCryptor()
>   val parameters = clientParameters {
>     this.shardParameters =
> ```

`this` should be unnecessary here and in a number of other spots
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 73 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-Mj0vR0z366sRu4hTrOE:-Mj0vR0z366sRu4hTrOF:bfddgcz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bfc194be1d785c4c35288905bfae752b593937e9/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L73)):*
> ```cpp
> absl::StatusOr<DecryptQueryResultsResponse> RemoveAes(
>     const DecryptQueryResultsRequest& request,
>     ClientDecryptQueriesResponse client_decrypt_queries_response) {
> ```

pass by const ref please
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.h, line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibJURJ2TefmNfIeTop:-Mj0v8ym0NLQqus16W3D:b-l5i41r) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.h#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

are you okay with the name `symmetric_decrypt_query_results.h` for now? Did some renaming for now across the repo with this in mind.
</blockquote></details>

Sure, for now anything is fine
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.cc, line 43 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibJq3T-Nmy9aYYqK58:-Mj0vHFs9XFS4EqZxxZc:bb77uci) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/client/privatemembership/symmetric_private_membership.cc#L43)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I divided it into `RemoveRLWE` and `RemoveAes` ... does that work?
</blockquote></details>

Yep!
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniQueryResultsDecryptor.kt, line 40 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-Mj0w1RZCgQCHAPStd6K:-Mj0w1RZCgQCHAPStd6L:bj85o5j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bfc194be1d785c4c35288905bfae752b593937e9/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniQueryResultsDecryptor.kt#L40)):*
> ```Kotlin
>     private val SWIG_PATH =
>       Paths.get(
>         "panel_exchange_client/src/main/",
> ```

I think in some other PR we decided to do "`Paths.get("a", "b", "c")`" instead of using slashes?

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104)* status: 56 of 63 files reviewed, 5 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/testing/private_membership_helper.h, line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibKZh76qmTsqrtWLZs:-Mj1CR8R3bIKAETvNn3e:baxt6l9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/client/privatemembership/testing/private_membership_helper.h#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

All I'm saying is write `private_membership::Foo` instead of `::private_membership::Foo`
</blockquote></details>

thx for the clarification. done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/testing/private_membership_helper.cc, line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-MibKih77KwGKXuilK0o:-Mj1C_Fw-Vj4DAq7ducC:bjbu0ji) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbafc28759f9e5dd4965dbde55074eeb9745f740/src/main/cc/wfa/panelmatch/client/privatemembership/testing/private_membership_helper.cc#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe just add a big TODO above all of this saying that we shouldn't need to do any of this but we're lacking the server-side libraries necessary to test this yet?
</blockquote></details>

100% agree. There was already a TODO above all this. I added more content to it.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptorTest.kt, line 32 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-Mj0ykCGAwsuwdvrR3sV:-Mj1DvyY53mjjixX6U7P:biam9ss) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bfc194be1d785c4c35288905bfae752b593937e9/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/JniPrivateMembershipCryptorTest.kt#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`this` should be unnecessary here and in a number of other spots
</blockquote></details>

got rid of the ones in this file and a few in other files.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 73 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-Mj0vR0z366sRu4hTrOE:-Mj1CI1Z-eKzH_dEHt6l:b-jw2v8p) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bfc194be1d785c4c35288905bfae752b593937e9/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L73)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

pass by const ref please
</blockquote></details>

+1 done
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniQueryResultsDecryptor.kt, line 40 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-Mj0w1RZCgQCHAPStd6K:-Mj1D66Z4xsQWBHWgn0J:b-zaspvo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bfc194be1d785c4c35288905bfae752b593937e9/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/JniQueryResultsDecryptor.kt#L40)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think in some other PR we decided to do "`Paths.get("a", "b", "c")`" instead of using slashes?
</blockquote></details>

it's been done both ways in recent PRs. Got rid of the slashes. Done

**Review by efoxepstein — APPROVED** [review]
> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — COMMENTED** [review]
@efoxepstein - I think reviewable still wants you to review a few files. Maybe from the rebase I had to do.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/104#-:-Mj1Mr_lCWsMyVUomYf1:b-8zqpv1)* status: 51 of 63 files reviewed, all discussions resolved (waiting on @efoxepstein)

**Pull request merged**
