### PR TITLE
Added folder/Bazel file for Kotlin encryption code

### PR DESCRIPTION
**Pull request by jmorrrr**
Added folder and Bazel Build file for kotlin client encryption code

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23#-:-Mc_XNfH6NgENtHBnbsg:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmorrrr)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23)* status: all files reviewed, 1 unresolved discussion (waiting on @jmorrrr)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/BUILD.bazel, line 0 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23#-Mck9AvADvapKwVzaijP:-Mck9AvB81IOjK1-idrp:b-bbabtq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b5e60f17d2cd48ef0fdae089a458fac7e599afd3/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/BUILD.bazel#L0)):*
can we rename the folder from `eventencryption` to `datapreparation` ?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/BUILD.bazel, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23#-Mck9AvADvapKwVzaijP:-MclHEp6DVJSIQE9VyvA:b-q0hi3e) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b5e60f17d2cd48ef0fdae089a458fac7e599afd3/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/BUILD.bazel#L)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can we rename the folder from `eventencryption` to `datapreparation` ?
</blockquote></details>

`data` is a little generic -- the entities running this are called "Event Data Providers" after all. How about `eventdatapreparation`? Or `eventprep` or `eventpreprocessing` or `preprocessing`?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/BUILD.bazel, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23#-Mck9AvADvapKwVzaijP:-Md2iPsT0HO3ndyKkj3_:b-fasexd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b5e60f17d2cd48ef0fdae089a458fac7e599afd3/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/BUILD.bazel#L)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`data` is a little generic -- the entities running this are called "Event Data Providers" after all. How about `eventdatapreparation`? Or `eventprep` or `eventpreprocessing` or `preprocessing`?
</blockquote></details>

how about just `preprocessing` so it could include profile or event pre-processing.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/BUILD.bazel, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23#-Mck9AvADvapKwVzaijP:-MdHhTcj9szZvF_F8nO5:b-woyx4y) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b5e60f17d2cd48ef0fdae089a458fac7e599afd3/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/BUILD.bazel#L)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

how about just `preprocessing` so it could include profile or event pre-processing.
</blockquote></details>

I'm a little worried we'll run into other `preprocessing` tasks that are unrelated. I think regardless, we'll want to rename a bunch of things in a month or two when we're closer to completing the project and have a better, more holistic sense of all components.

As discussed in https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28# -- can we get these PRs in and then plan on doing a renaming once we understand everything a little better?

How about we file a GH issue to reevaluate all these names?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/BUILD.bazel, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23#-Mck9AvADvapKwVzaijP:-MdIJr6WBg8DGG8cgO-k:bgkx1pj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b5e60f17d2cd48ef0fdae089a458fac7e599afd3/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/BUILD.bazel#L)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'm a little worried we'll run into other `preprocessing` tasks that are unrelated. I think regardless, we'll want to rename a bunch of things in a month or two when we're closer to completing the project and have a better, more holistic sense of all components.

As discussed in https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/28# -- can we get these PRs in and then plan on doing a renaming once we understand everything a little better?

How about we file a GH issue to reevaluate all these names? 
</blockquote></details>

are you not comfortable with `eventpreprocessing` then?

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/BUILD.bazel, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23#-Mck9AvADvapKwVzaijP:-MdIK7Eq2J1yE4LHBiJd:b-5rcuir) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b5e60f17d2cd48ef0fdae089a458fac7e599afd3/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/BUILD.bazel#L)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

are you not comfortable with `eventpreprocessing` then?
</blockquote></details>

I'm fine with `preprocessing` if that's the fastest way to get Julia unblocked

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/BUILD.bazel, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23#-Mck9AvADvapKwVzaijP:-MdIKDKG7exCIFViM2vY:b-f6sxyp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b5e60f17d2cd48ef0fdae089a458fac7e599afd3/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/BUILD.bazel#L)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'm fine with `preprocessing` if that's the fastest way to get Julia unblocked
</blockquote></details>

Oh, I misread, I'm more fine with `eventpreprocessing` than just `preprocessing`

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/BUILD.bazel, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23#-Mck9AvADvapKwVzaijP:-MdIZ21B4-1iRlTtg3Zs:bx5lt0f) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b5e60f17d2cd48ef0fdae089a458fac7e599afd3/src/main/kotlin/org/wfanet/panelmatch/client/eventencryption/BUILD.bazel#L)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Oh, I misread, I'm more fine with `eventpreprocessing` than just `preprocessing`
</blockquote></details>

i approve once renamed to `eventpreprocessing`

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/23)* status: all files reviewed, 1 unresolved discussion (waiting on @jmorrrr)

**Pull request closed without merging**
