### PR TITLE
Add DatabaseShard size Distribution metric

### PR DESCRIPTION
**Pull request by efoxepstein**
This tracks summary statistics of the sizes of DatabaseShards. See issue #66.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/68)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
can you rebase? It'll make reviewing this much easier.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/68#-:-Mg7-vn3D92BteLw84Wl:bazaprp)* status: 0 of 29 files reviewed, all discussions resolved

**Review by efoxepstein — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/68#-:-Mg70dstAudFhaEijuHT:bb6un1j)* status: 0 of 29 files reviewed, all discussions resolved

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 26 of 26 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/68)* status: 26 of 29 files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/68#-Mg7cMXP6eRfIgEEQln5:-Mg7cMXP6eRfIgEEQln6:b8eau4p) (no related file):*
I like it!

---
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchLookupWorkflow.kt, line 164 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/68#-Mg7cGez42tgTQFDSCTo:-Mg7cGez42tgTQFDSCTp:bdj5uz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/512e0a9a12da3bed9c0c1dd9a458e169b0a99498/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchLookupWorkflow.kt#L164)):*
> ```Kotlin
>  * This makes a Distribution metric of the number of bytes in each subshard's buckets' payloads.
>  *
>  * Note that this is a different value than the size of the DatabaseShard as a serialized proto.
> ```

when would the whole shard get serialized?

**Review by efoxepstein — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/68)* status: 26 of 29 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/68#-Mg7cMXP6eRfIgEEQln5:-Mg7oyio5KsGoO8iEiZk:b-896fix) (no related file):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I like it!
</blockquote></details>

Done.

---
___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchLookupWorkflow.kt, line 164 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/68#-Mg7cGez42tgTQFDSCTo:-Mg7p-hCDZKUlK8EL2oy:b-labrhr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/512e0a9a12da3bed9c0c1dd9a458e169b0a99498/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/BatchLookupWorkflow.kt#L164)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

when would the whole shard get serialized?
</blockquote></details>

The input to this function is a `KV<ShardId, DatabaseShard>` -- a `DatabaseShard` is a full shard or a subshard.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/68)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Pull request merged**
