### PR TITLE
Move compression into C++ only

### PR DESCRIPTION
**Pull request by efoxepstein**
This is a very large PR that completely refactors how compression is done in `panel-exchange-client`:

- `CompressionParameters` is a new proto that specifies how to do compression: which algorithm and what dictionary.
- Instances of this proto are inputs to the Event Preprocessing pipeline as well as DecryptQueryResults.
- All compression logic is moved into C++.
- The SWIG wrappers for compression are removed.
- Compression now happens within the C++ `PreprocessEvents` function.

Along the way, a fair amount of code was dropped or refactored. Many classes were renamed. For example, `PreprocessEvents` was renamed to `EventPreprocessor`, as that's the right tense for an interface. And `PreprocessEventsInPipeline` was then shortened to `PreprocessEvents` (which is a more appropriate PTransform name).

This PR also realizes some important efficiency gains:

1. Event Preprocessing is going to be very expensive for EDPs. By combining compression and encryption, we reduce the number of times the JNI barrier is crossed. Since each JNI call requires serializing and deserializing protocol buffers, this should significantly reduce the memory overhead of the pipeline. A similar benefit is seen in DecryptQueryResults.
2. This PR eliminates a join in DecryptQueryResults. Joins are the most expensive Apache Beam operation.
3. This PR eliminates ~1500 lines of code and a SWIG wrapper, which should improve engineering velocity through simplification.

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 33 of 85 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192)* status: 33 of 85 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-MnRAh716HF9j908EaYd:-MnRAh716HF9j908EaYe:b-7fgf8c) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4c069ef13040adce9338c32625355d8f9488f70/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt#L41)):*
> ```Kotlin
>     return events
>       .apply(
>         "Rough Sample",
> ```

shouldn't we still offer an implementation for computing a dictionary? Also, don't we need this for a reference dictionary?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192)* status: 33 of 85 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-MnRAh716HF9j908EaYd:-MnRAz1h7YhfkCjgwPO1:bfa76af) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4c069ef13040adce9338c32625355d8f9488f70/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt#L41)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't we still offer an implementation for computing a dictionary? Also, don't we need this for a reference dictionary?
</blockquote></details>

This implementation is too dangerous, I think.

And to build a reference dictionary, we can just use some command-line tools. The easiest way will be to modify [event_generator_main](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/main/src/main/cc/wfa/virtual_people/events_generator/events_generator_main.cc) to output binary-serialized protos instead of textprotos.

Literally all the dictionary is is a bunch of concatenated example protos. If we want to be smarter, we can run this through `zstd`'s command-line tool to build a more compact dictionary from a set of examples.

My proposal would be to just provide a Markdown file documenting how to build a dictionary. EDPs can follow those instructions. Google will probably just use a reference dictionary, though, so maybe no EDPs will actually want to build their own.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192)* status: 33 of 85 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-MnRAh716HF9j908EaYd:-MnRDFibE0mYwuBFGkl7:b-qkwtg9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4c069ef13040adce9338c32625355d8f9488f70/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This implementation is too dangerous, I think.

And to build a reference dictionary, we can just use some command-line tools. The easiest way will be to modify [event_generator_main](https://github.com/world-federation-of-advertisers/virtual_people_examples/blob/main/src/main/cc/wfa/virtual_people/events_generator/events_generator_main.cc) to output binary-serialized protos instead of textprotos.

Literally all the dictionary is is a bunch of concatenated example protos. If we want to be smarter, we can run this through `zstd`'s command-line tool to build a more compact dictionary from a set of examples.

My proposal would be to just provide a Markdown file documenting how to build a dictionary. EDPs can follow those instructions. Google will probably just use a reference dictionary, though, so maybe no EDPs will actually want to build their own.
</blockquote></details>

(And I'll do this part for TA231)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 52 of 85 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192)* status: all files reviewed, 11 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mna4_R48AEZKb8QqjCP:-Mna4_R48AEZKb8QqjCQ:b7pp5vc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42f1f84f8909bfad6e62331f11e38ee8244b1e6f/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L103)):*
> ```cpp
> }
> 
> absl::StatusOr<std::unique_ptr<Compressor>> MakeCompressor(
> ```

can you combine this with the other identical function called MakeCompressor?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-MnRAh716HF9j908EaYd:-MnWA5oT5Dzk-yVBZhMP:bvledak) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4c069ef13040adce9338c32625355d8f9488f70/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

(And I'll do this part for TA231)
</blockquote></details>

okay. I'm okay with either a comment to this extent in a Readme now or as part of TA231
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mna1vFc8r7h-NrpfeU_:-Mna1vFc8r7h-NrpfeUa:bx0agl0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42f1f84f8909bfad6e62331f11e38ee8244b1e6f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt#L35)):*
> ```Kotlin
>  * 1. Group events by key -- and combine into a CombinedEvents proto.
>  * 2. Group into batches to minimize JNI overhead.
>  * 3. Compress and encrypt each key-value pair.
> ```

Can you add a comment that we use a PTransform here so others can imports this?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/EventPreprocessorTest.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mn_z57Z98ZMrDAxp-HK:-Mn_z57Z98ZMrDAxp-HL:b-fh2mku) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42f1f84f8909bfad6e62331f11e38ee8244b1e6f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/EventPreprocessorTest.kt#L33)):*
> ```Kotlin
>   fun testPreprocessEvents() {
>     val request = preprocessEventsRequest {
>       cryptoKey = "some-crypto-key".toByteString()
> ```

what do you think about specifying a few events so we can check in this abstract test that they were at least properly grouped?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mn_zM4h-WOa-J9jNZqW:-Mn_zM4h-WOa-J9jNZqX:b-q4wq7g) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4c069ef13040adce9338c32625355d8f9488f70/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L43)):*
> ```Kotlin
>  * [encryptedQueryResults].
>  *
>  * @param encryptedQueryResults data to be decrypted and decompressed
> ```

why was this deleted?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mn_zuIB8Qvxkj_5GFLN:-Mn_zuIB8Qvxkj_5GFLO:b-qtq88t) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42f1f84f8909bfad6e62331f11e38ee8244b1e6f/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L103)):*
> ```Kotlin
> }
> 
> private class BuildDecryptQueryResultsRequestsFn(
> ```

what was the thinking behind splitting this out into its own DoFn?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsTest.kt, line 0 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mna3EDX30r66B1aS_RZ:-Mna3EDY-_yBag_C4aMw:b-qr4m60) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42f1f84f8909bfad6e62331f11e38ee8244b1e6f/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsTest.kt#L0)):*
a little concerned about the removal of these tests. They seem tangential to the main purpose of the PR. What do you think about removing the decrypt test changes? (I'm okay with the other minor changes to the files). Or split it out in a different PR?
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mna3YBv5whg3DA12H76:-Mna3YBv5whg3DA12H77:b-hf99p8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42f1f84f8909bfad6e62331f11e38ee8244b1e6f/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L48)):*
> ```cpp
>   request.set_identifier_hash_pepper("some-identifier-hash-pepper");
>   request.set_hkdf_pepper("some-hkdf-pepper");
>   request.mutable_compression_parameters()->mutable_uncompressed();
> ```

can we add a brotli test, too?
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 134 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mna1LzYCFu3bb2YCP-K:-Mna1LzYCFu3bb2YCP-L:b-e6ppoq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42f1f84f8909bfad6e62331f11e38ee8244b1e6f/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L134)):*
> ```cpp
>   EXPECT_NE(processed.processed_events(0).encrypted_data(), "some-data-1");
>   EXPECT_NE(processed.processed_events(1).encrypted_data(), "some-data-2");
>   EXPECT_NE(processed.processed_events(2).encrypted_data(), "some-data-3");
> ```

might be good to actually check the output values in one of these tests
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniEventPreprocessorTest.kt, line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mna3ewM95P8CGcywRYk:-Mna3ewM95P8CGcywRYl:b-3k3qg8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42f1f84f8909bfad6e62331f11e38ee8244b1e6f/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniEventPreprocessorTest.kt#L67)):*
> ```Kotlin
>   }
> 
>   @Test
> ```

want to add one test that just succeeds?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/BUILD.bazel, line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mna2ImS9y7M_GtfaSM5:-Mna2ImS9y7M_GtfaSM6:bpxj5x6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4c069ef13040adce9338c32625355d8f9488f70/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/BUILD.bazel#L96)):*
> ```Starlark
> 
> kt_jvm_test(
>     name = "PlaintextDecryptQueryResultsTest",
> ```

don't we still want a mocked or fake version to test against?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192)* status: all files reviewed, 10 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mna4_R48AEZKb8QqjCP:-MnaBZzS1o8yVDtu3Dcx:b-gpq43a) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42f1f84f8909bfad6e62331f11e38ee8244b1e6f/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L103)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you combine this with the other identical function called MakeCompressor?
</blockquote></details>

Added a TODO to do this.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-MnRAh716HF9j908EaYd:-MnaBbe-C9Nb4MVMed4j:b-h53o1f) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4c069ef13040adce9338c32625355d8f9488f70/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt#L41)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

okay. I'm okay with either a comment to this extent in a Readme now or as part of TA231
</blockquote></details>

See https://github.com/world-federation-of-advertisers/panel-exchange-client/pull/196
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mna1vFc8r7h-NrpfeU_:-MnaC1vC85y9PyWgaqjX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42f1f84f8909bfad6e62331f11e38ee8244b1e6f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEvents.kt#L35)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Can you add a comment that we use a PTransform here so others can imports this?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/EventPreprocessorTest.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mn_z57Z98ZMrDAxp-HK:-MnaC9Fx9Dd2ova4M-P0:b-8iuhe5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42f1f84f8909bfad6e62331f11e38ee8244b1e6f/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/EventPreprocessorTest.kt#L33)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what do you think about specifying a few events so we can check in this abstract test that they were at least properly grouped?
</blockquote></details>

Recall that things got renamed. `EventPreprocessor` is now just the interface for the thing that calls the JNI (it's not Beam). So the grouping happens outside of this. This does specify two events, though.

I feel like maybe I'm misinterpreting your comment, can you clarify?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mn_zM4h-WOa-J9jNZqW:-MnaCngf34mj8Rtyf6gt:b-bvwhm5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4c069ef13040adce9338c32625355d8f9488f70/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L43)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why was this deleted?
</blockquote></details>

Restored.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mn_zuIB8Qvxkj_5GFLN:-MnaCsODDq8PtjZkCXnn:bs4mpjr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42f1f84f8909bfad6e62331f11e38ee8244b1e6f/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L103)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what was the thinking behind splitting this out into its own DoFn?
</blockquote></details>

It requires two side inputs and we don't have a convenience helper for that.

I also find it easier to reason about in isolation.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsTest.kt, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mna3EDX30r66B1aS_RZ:-MnaDBza2gfWW9kIbtH2:b-nawhjd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42f1f84f8909bfad6e62331f11e38ee8244b1e6f/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsTest.kt#L)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

a little concerned about the removal of these tests. They seem tangential to the main purpose of the PR. What do you think about removing the decrypt test changes? (I'm okay with the other minor changes to the files). Or split it out in a different PR?
</blockquote></details>

This code is still thoroughly tested. It doesn't need to be an abstract test because that doesn't help reason about the correctness of the subject under test. As long as any implementation of the QueryResultDecryptor is also unit tested, there are not likely to be integration issues.
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mna3YBv5whg3DA12H76:-MnaDa9s8Hm35eNRTl_8:bkd5ega) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42f1f84f8909bfad6e62331f11e38ee8244b1e6f/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L48)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can we add a brotli test, too?
</blockquote></details>

Added a TODO
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 134 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mna1LzYCFu3bb2YCP-K:-MnaDmEb7RkYnFlep5b6:bkd5ega) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42f1f84f8909bfad6e62331f11e38ee8244b1e6f/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L134)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

might be good to actually check the output values in one of these tests
</blockquote></details>

Added a TODO
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniEventPreprocessorTest.kt, line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mna3ewM95P8CGcywRYk:-MnaE7wiDz-JBx55wRUz:bpkvxss) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42f1f84f8909bfad6e62331f11e38ee8244b1e6f/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniEventPreprocessorTest.kt#L67)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

want to add one test that just succeeds?
</blockquote></details>

The parent class contains a test that succeeds.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/BUILD.bazel, line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mna2ImS9y7M_GtfaSM5:-MnaEEHs5CfP-IMcCuuD:b-41q58z) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4c069ef13040adce9338c32625355d8f9488f70/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/BUILD.bazel#L96)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

don't we still want a mocked or fake version to test against?
</blockquote></details>

I don't understand the question, can you clarify?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192)* status: 70 of 86 files reviewed, 10 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mna4_R48AEZKb8QqjCP:-Mnahke56ffYAtKFUJ4f:b-896fja) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42f1f84f8909bfad6e62331f11e38ee8244b1e6f/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L103)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Added a TODO to do this.
</blockquote></details>

Done!
___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mna3YBv5whg3DA12H76:-MnajeEqCVMhUtEIBcvs:b-896fja) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42f1f84f8909bfad6e62331f11e38ee8244b1e6f/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L48)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Added a TODO
</blockquote></details>

Done!

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192)* status: 67 of 88 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/BUILD.bazel, line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/192#-Mna2ImS9y7M_GtfaSM5:-MnamAhZ71zvr1lfLy-J:b-y9n158) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4c069ef13040adce9338c32625355d8f9488f70/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/BUILD.bazel#L96)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I don't understand the question, can you clarify?
</blockquote></details>

you dealt with this by leaving in the plaintext version

**Pull request merged**
