### PR TITLE
Add Google Cloud Dataflow binary

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/71)

### CODE REVIEW

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/71)* status: 0 of 9 files reviewed, 4 unresolved discussions (waiting on @efoxepstein)

___
*[.bazelrc, line 8 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/71#-MgEb4beDtYMPuYIyPZO:-MgEb4beDtYMPuYIyPZP:benhna7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b5f28a7a0f62b103e1373fac6cc05c8127e10e69/.bazelrc#L8)):*
> ```
> 
> build --action_env=BAZEL_LINKLIBS=-l%:libstdc++.a:-lm
> build --action_env=BAZEL_LINKOPTS=-static-libgcc
> ```

Without this:

```
Error message from worker: java.lang.UnsatisfiedLinkError: /tmp/panel-exchange-client-runfiles/panel_exchange_client/src/main/swig/wfanet/panelmatch/client/eventpreprocessing/libpreprocess_events.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/panel-exchange-client-runfiles/panel_exchange_client/src/main/swig/wfanet/panelmatch/client/eventpreprocessing/libpreprocess_events.so
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/71#-MgEbaal58GRr5FlYyjO:-MgEbaal58GRr5FlYyjP:b-820a23) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b5f28a7a0f62b103e1373fac6cc05c8127e10e69/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniPreprocessEvents.kt#L46)):*
> ```Kotlin
>       try {
>         loadLibrary(name = "preprocess_events", directoryPath = Paths.get(directoryPath))
>       } catch (e: Exception) {
> ```

Big hack here:

1. See if `/var/opt/google/dataflow` exists and if so, find some file named `libprepreocess_events-something.so` -- where `something` happens to be the base64-encoded SHA256 hash of the library in this case. 
2. There's always just one thing matching that pattern.
3. Copy it to wherever the `getRuntimePath` puts it (which is hacked up too).
4. Try again.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/71#-MgEc5DqBRmss92dDtbg:-MgEc5DqBRmss92dDtbh:bvyov2g) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b5f28a7a0f62b103e1373fac6cc05c8127e10e69/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsMain.kt#L72)):*
> ```Kotlin
>   val classPathFiles =
>     PipelineResources.detectClassPathResourcesToStage(Dummy::class.java.classLoader, options)
>   options.filesToStage = filesToStage + classPathFiles
> ```

This hack ensures that the `.so` file is copied over to the workers
___
*[src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/71#-MgEcBdd8AwTHphGxCuG:-MgEcBdd8AwTHphGxCuH:bhhvsxi) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b5f28a7a0f62b103e1373fac6cc05c8127e10e69/src/main/kotlin/org/wfanet/panelmatch/common/Runfiles.kt#L26)):*
> ```Kotlin
>     Runfiles.create()
>   } catch (e: Exception) {
>     // Last-ditch effort to create working runfiles.
> ```

And this hack puts the runfiles location in `/tmp/panel-exchange-client-runfiles` if it doesn't exist. This in theory should allow files to be copied into here.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/71)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @efoxepstein)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/71#-MgEcZW77IAMeAgOw4_e:-MgEcZW77IAMeAgOw4_f:b-618osg) (no related file):*
Current error:

```
[main] ERROR org.apache.beam.runners.dataflow.util.MonitoringUtil$LoggingHandler - 2021-08-04T05:00:49.281Z: java.lang.UnsatisfiedLinkError: Can't load library: /tmp/panel-exchange-client-runfiles/panel_exchange_client/src/main/swig/wfanet/panelmatch/client/eventpreprocessing/libpreprocess_events.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at org.wfanet.panelmatch.common.RunfilesKt.loadLibrary(Runfiles.kt:58)
	at org.wfanet.panelmatch.client.eventpreprocessing.JniPreprocessEvents.<clinit>(JniPreprocessEvents.kt:45)
	at org.wfanet.panelmatch.client.eventpreprocessing.EncryptEvents.apply(EncryptEvents.kt:27)
	at org.wfanet.panelmatch.client.eventpreprocessing.EncryptEvents.apply(EncryptEvents.kt:25)
	at org.wfanet.panelmatch.client.eventpreprocessing.EncryptionEventsDoFn.process(EncryptionEventsDoFn.kt:51)

[main] ERROR org.apache.beam.runners.dataflow.util.MonitoringUtil$LoggingHandler - 2021-08-04T05:00:55.886Z: java.lang.NoClassDefFoundError: Could not initialize class org.wfanet.panelmatch.client.eventpreprocessing.JniPreprocessEvents
	at org.wfanet.panelmatch.client.eventpreprocessing.EncryptEvents.apply(EncryptEvents.kt:27)
	at org.wfanet.panelmatch.client.eventpreprocessing.EncryptEvents.apply(EncryptEvents.kt:25)
	at org.wfanet.panelmatch.client.eventpreprocessing.EncryptionEventsDoFn.process(EncryptionEventsDoFn.kt:51)
```

---

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/71)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @efoxepstein)

___
*[.bazelrc, line 8 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/71#-MgEb4beDtYMPuYIyPZO:-MgGzUSEAWjqjHY-4442:bcx8g5b) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b5f28a7a0f62b103e1373fac6cc05c8127e10e69/.bazelrc#L8)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Without this:

```
Error message from worker: java.lang.UnsatisfiedLinkError: /tmp/panel-exchange-client-runfiles/panel_exchange_client/src/main/swig/wfanet/panelmatch/client/eventpreprocessing/libpreprocess_events.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/panel-exchange-client-runfiles/panel_exchange_client/src/main/swig/wfanet/panelmatch/client/eventpreprocessing/libpreprocess_events.so
```
</blockquote></details>

This is definitely not something we want to do in general. The implication is that the Beam container has an older version of glibc. This is the same issue we encounter with Duchy binaries that use JNI using the default Distroless Java images.

The solution we use there is to add a restriction to the binaries that use JNI to mark them as only compatible with certain versions of glibc. Then we have to make sure we build the targets in an environment that has a compatible version, e.g. using a container.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/71)* status: 0 of 9 files reviewed, 5 unresolved discussions (waiting on @efoxepstein)

___
*[.bazelrc, line 8 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/71#-MgEb4beDtYMPuYIyPZO:-MgHPt7G5SiD3MuHZP9w:b3l62go) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b5f28a7a0f62b103e1373fac6cc05c8127e10e69/.bazelrc#L8)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is definitely not something we want to do in general. The implication is that the Beam container has an older version of glibc. This is the same issue we encounter with Duchy binaries that use JNI using the default Distroless Java images.

The solution we use there is to add a restriction to the binaries that use JNI to mark them as only compatible with certain versions of glibc. Then we have to make sure we build the targets in an environment that has a compatible version, e.g. using a container.
</blockquote></details>

Sorry, this error is about libstdc++ rather than libc.

It seems like the Beam SDK image is just missing this library. Are we sure we're using a Debian-based SDK image rather than an Alpine-based one?

**Review by jmorrrr — APPROVED** [review]
> Reviewed 10 of 17 files at r2, 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/71)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Pull request merged**
