### PR TITLE
Update to Bazel 5.1.1

### PR DESCRIPTION
**Pull request by iverson52000**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/346)

### CODE REVIEW

**Review by robinsons — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/346)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/346)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/346)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/346)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

**Pull request merged**
