### PR TITLE
Add custom storage option

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/206)

### CODE REVIEW

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/206)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @jonmolle)

___
*[src/main/proto/wfa/panelmatch/client/storage/storage_details.proto, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/206#-MoKyHFE1_uR-_BISOcE:-MoKyHFE1_uR-_BISOcF:b-3qnu43) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c6d97ee068da685e2446daedb8f2ab8b497f85c6/src/main/proto/wfa/panelmatch/client/storage/storage_details.proto#L69)):*
> ```protobuf
>   // For those who implement custom solutions, this should be used. Arbitrary
>   // configuration data can be serialized here.
>   message CustomStorage {
> ```

i was thinking that we should just change PrivateStorageSelector to an interface to deal with issues like this.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/206)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jonmolle and @stevenwarejones)

___
*[src/main/proto/wfa/panelmatch/client/storage/storage_details.proto, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/206#-MoKyHFE1_uR-_BISOcE:-MoKz8og93_GqZ9f4KkT:b787blk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c6d97ee068da685e2446daedb8f2ab8b497f85c6/src/main/proto/wfa/panelmatch/client/storage/storage_details.proto#L69)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i was thinking that we should just change PrivateStorageSelector to an interface to deal with issues like this.
</blockquote></details>

If we do that, the implementer needs to:

1. Invent a serialization format for their custom storage config
2. Add a way to read in the config for their custom custom (via flags or StorageClient)
3. Parse the config
4. Make a custom PrivateStorageSelector
5. Make a custom StorageClient and StorageFactory

This way:

1. Add a protocol buffer for their storage config
2. Make a custom StorageClient and StorageFactory
3. Change ~1 line of code to map that storage client to the `PlatformCase.CUSTOM` enum

I think this will end up simpler. It also makes it a lot harder for clients to accidentally mess something up because they're able to follow a more restricted set of steps. WDYT?

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/206)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jonmolle)

___
*[src/main/proto/wfa/panelmatch/client/storage/storage_details.proto, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/206#-MoKyHFE1_uR-_BISOcE:-MoLFDNJ5hSqieYpZSVV:b68a112) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c6d97ee068da685e2446daedb8f2ab8b497f85c6/src/main/proto/wfa/panelmatch/client/storage/storage_details.proto#L69)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

If we do that, the implementer needs to:

1. Invent a serialization format for their custom storage config
2. Add a way to read in the config for their custom custom (via flags or StorageClient)
3. Parse the config
4. Make a custom PrivateStorageSelector
5. Make a custom StorageClient and StorageFactory

This way:

1. Add a protocol buffer for their storage config
2. Make a custom StorageClient and StorageFactory
3. Change ~1 line of code to map that storage client to the `PlatformCase.CUSTOM` enum

I think this will end up simpler. It also makes it a lot harder for clients to accidentally mess something up because they're able to follow a more restricted set of steps. WDYT?
</blockquote></details>

Lets go with this for now for all the great reasons you listed. During implementation, we'll see how it goes :)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/206)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @jonmolle)

___
*[src/main/proto/wfa/panelmatch/client/storage/storage_details.proto, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/206#-MoKyHFE1_uR-_BISOcE:-MoLFQv0BvaXi3EZs7iL:bmjg85u) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c6d97ee068da685e2446daedb8f2ab8b497f85c6/src/main/proto/wfa/panelmatch/client/storage/storage_details.proto#L69)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Lets go with this for now for all the great reasons you listed. During implementation, we'll see how it goes :)
</blockquote></details>

Works for me

**Pull request merged**
