### PR TITLE
Add default/recommended CompressionParameters.

### PR DESCRIPTION
**Pull request by efoxepstein**
https://rally1.rallydev.com/#/?detail=/userstory/613843588001&fdp=true

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/200)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/200)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/common/compression/DefaultCompressionParameters.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/200#-MnhnNK4-yC5CNNj6tZg:-MnhnNK52hFddc-UOKqN:b-d8ulsp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0694c8f671192b72acf490a0e1d7f50a04d84ea0/src/main/kotlin/org/wfanet/panelmatch/client/common/compression/DefaultCompressionParameters.kt#L28)):*
> ```Kotlin
> 
> private val DEFAULT_DICTIONARY: ByteString by lazy {
>   val stream = {}::class.java.getResourceAsStream("/data/brotli-dictionary")
> ```

don't we want the default dictionary to come from an input task?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/200)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/common/compression/DefaultCompressionParameters.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/200#-MnhnNK4-yC5CNNj6tZg:-MnkLy--E3xwsefHQE6Y:b-ludqdg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0694c8f671192b72acf490a0e1d7f50a04d84ea0/src/main/kotlin/org/wfanet/panelmatch/client/common/compression/DefaultCompressionParameters.kt#L28)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

don't we want the default dictionary to come from an input task?
</blockquote></details>

I guess my thinking is that it makes EDP deployments simpler if they don't need to think about dictionaries at all. I'm happy to revert this though if you're not sold.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/200)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/common/compression/DefaultCompressionParameters.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/200#-MnhnNK4-yC5CNNj6tZg:-MnkTzDf68N-cQEvOiKC:b-92deml) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0694c8f671192b72acf490a0e1d7f50a04d84ea0/src/main/kotlin/org/wfanet/panelmatch/client/common/compression/DefaultCompressionParameters.kt#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I guess my thinking is that it makes EDP deployments simpler if they don't need to think about dictionaries at all. I'm happy to revert this though if you're not sold.
</blockquote></details>

no - its fine. what do you think about adding a TODO to generate it with a bazel rule?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/200)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/common/compression/DefaultCompressionParameters.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/200#-MnhnNK4-yC5CNNj6tZg:-MnlDWWcC3Wimk9wVARG:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0694c8f671192b72acf490a0e1d7f50a04d84ea0/src/main/kotlin/org/wfanet/panelmatch/client/common/compression/DefaultCompressionParameters.kt#L28)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

no - its fine. what do you think about adding a TODO to generate it with a bazel rule?
</blockquote></details>

Done

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/200)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Pull request merged**
