### PR TITLE
Add interfaces for ExchangeTask and Storage.

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9)

### CODE REVIEW

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9#-M_RMt6N7_ZM96jCfxeo:-M_Rf_Kv66fZYOribYHT:b-dgtkql) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b64c7af2914778eef6ba980b973b7641c26d35f6/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What is the difference between the two versions of `execute`? I feel like you need some combination of them.
</blockquote></details>

Below one should be internal. Deleted for now.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/DataReader.kt, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9#-M_ROcmS9nI18w2mFPSa:-M_Rfhxd7YahYSnXh_Dm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b64c7af2914778eef6ba980b973b7641c26d35f6/src/main/kotlin/org/wfanet/panelmatch/client/storage/DataReader.kt#L19)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think we agreed to call this InputReader?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/DataReader.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9#-M_RO_RM2Jq09D6TG5l_:-M_Rfja56D0mhgdx-Ydz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b64c7af2914778eef6ba980b973b7641c26d35f6/src/main/kotlin/org/wfanet/panelmatch/client/storage/DataReader.kt#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why is this returning a Map?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/DataWriter.kt, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9#-M_ROh0xAgt7COQkfAxT:-M_RfkDC1fJ0crdV_4pS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b64c7af2914778eef6ba980b973b7641c26d35f6/src/main/kotlin/org/wfanet/panelmatch/client/storage/DataWriter.kt#L20)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

OutputWriter
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9#-M_RMt6N7_ZM96jCfxeo:-M_RrZkg4AJhF6Qe9IXy:b-ry4ckl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b64c7af2914778eef6ba980b973b7641c26d35f6/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt#L37)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Below one should be internal. Deleted for now.
</blockquote></details>

How does this fit into the diagram we built with the wrapper? This looks like it returns outputs that the wrapper can be responsible for writing to the appropriate storage. But how do inputs work?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9#-M_RMt6N7_ZM96jCfxeo:-M_Wiy8RCJ0_Jn6tjJQr:btdrps8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b64c7af2914778eef6ba980b973b7641c26d35f6/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

How does this fit into the diagram we built with the wrapper? This looks like it returns outputs that the wrapper can be responsible for writing to the appropriate storage. But how do inputs work?
</blockquote></details>

Updated the method to be gRPC agnostic.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9)* status: all files reviewed, 4 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt, line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9#-M_WolzrEiew1dD9Akjf:-M_WolzrEiew1dD9Akjg:btdrplc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/eebc37afd31f09e1eb81d1a6617a98dc1677086a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt#L26)):*
> ```Kotlin
>    * Executes given [ExchangeWorkflow.Step] and returns the output.
>    *
>    * @param input Input data to be executed.
> ```

Nit: the input data isn't really executed -- it's just the inputs specified by [step]
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt, line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9#-M_WotVF556S-52gARN6:-M_WotVF556S-52gARN7:b4mtfl7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/eebc37afd31f09e1eb81d1a6617a98dc1677086a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt#L27)):*
> ```Kotlin
>    *
>    * @param input Input data to be executed.
>    * @param step a [ExchangeWorkflow.Step] contains task details.
> ```

This one, on the other hand, is the thing that's executed
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt, line 28 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9#-M_WowCj2V1EVjJP_F2w:-M_WowCj2V1EVjJP_F2x:b77dfcf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/eebc37afd31f09e1eb81d1a6617a98dc1677086a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt#L28)):*
> ```Kotlin
>    * @param input Input data to be executed.
>    * @param step a [ExchangeWorkflow.Step] contains task details.
>    * @return executed output.
> ```

Maybe describe the format of the map. It's a map from the labels (which are values in `step.output_labels`) to the payload associated with the label.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9#-M_WoWcpC60QWs7dixxk:-M_WoWcq5EJwBjUnAxG_:bvbge9w) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/eebc37afd31f09e1eb81d1a6617a98dc1677086a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt#L32)):*
> ```Kotlin
>    */
>   suspend fun execute(
>     input: Map<String, String>,
> ```

`Map<String, ByteString>`?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt, line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9#-M_WotVF556S-52gARN6:-M_X1Atz9kF7QzyatGKb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/eebc37afd31f09e1eb81d1a6617a98dc1677086a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This one, on the other hand, is the thing that's executed
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt, line 28 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9#-M_WowCj2V1EVjJP_F2w:-M_X1BLc0G3THCTZDny6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/eebc37afd31f09e1eb81d1a6617a98dc1677086a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe describe the format of the map. It's a map from the labels (which are values in `step.output_labels`) to the payload associated with the label.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9#-M_WoWcpC60QWs7dixxk:-M_X1CIE-lWJZlJlkVUj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/eebc37afd31f09e1eb81d1a6617a98dc1677086a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`Map<String, ByteString>`?
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt, line 33 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9#-M_X3sHd2zE2a88Hydbj:-M_X3sHd2zE2a88Hydbk:bohs6ed) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d21e0c94d581c20070513b130453563d7d26f62b/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt#L33)):*
> ```Kotlin
>   suspend fun execute(
>     step: ExchangeWorkflow.Step,
>     input: Map<String, ByteString>
> ```

Last but not least this should probably take in some log sink. In other words, a wrapper around AppendLogEntry. For example:

```
sendDebugLog: suspend (String) -> Unit
```

That way in the implementations of execute, it can just do things like:

```
  sendDebugLog("Part X done, now starting part Y")
```

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt, line 33 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9#-M_X3sHd2zE2a88Hydbj:-M_XD9sC4OmVR3cMlv2f:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d21e0c94d581c20070513b130453563d7d26f62b/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Last but not least this should probably take in some log sink. In other words, a wrapper around AppendLogEntry. For example:

```
sendDebugLog: suspend (String) -> Unit
```

That way in the implementations of execute, it can just do things like:

```
  sendDebugLog("Part X done, now starting part Y")
```
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Review by stevenwarejones — APPROVED** [review]

**Pull request merged**
