### PR TITLE
Stub C++ and Swig for batchlookup query evaluation

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/62)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 11 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/62)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/proto/wfa/panelmatch/client/batchlookup/query_evaluator.proto, line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/62#-MfZ7W_n9kT3SfaI-mHO:-MfZ7W_n9kT3SfaI-mHP:bdwvun5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed944365ae17727f7fbedf28c4c07ac00da2b401/src/main/proto/wfa/panelmatch/client/batchlookup/query_evaluator.proto#L75)):*
> ```protobuf
> 
> // Identifier and metadata for an oblivious query.
> message QueryMetadata {
> ```

is this documented somewhere?
___
*[src/main/swig/wfanet/panelmatch/client/batchlookup/query_evaluator.swig, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/62#-MfZ5UsU8wKCAff5ApWS:-MfZ5UsU8wKCAff5ApWT:b-h5w8qz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed944365ae17727f7fbedf28c4c07ac00da2b401/src/main/swig/wfanet/panelmatch/client/batchlookup/query_evaluator.swig#L22)):*
> ```
> // Convert C++ ::absl::StatusOr<std::string> to a Java byte
> // array.
> %typemap(jni) ::absl::StatusOr<std::string> "jbyteArray"
> ```

can this file get combined with the exact same code in the other swig files?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/62)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/proto/wfa/panelmatch/client/batchlookup/query_evaluator.proto, line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/62#-MfZ7W_n9kT3SfaI-mHO:-MfZGaTO6VarUt0c3Gqf:b-1d7jeh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed944365ae17727f7fbedf28c4c07ac00da2b401/src/main/proto/wfa/panelmatch/client/batchlookup/query_evaluator.proto#L75)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is this documented somewhere?
</blockquote></details>

Once the lower-level RLWE wrapper library is open sourced, I'll be able to link to the equivalent proto in that. That will have a lot of documentation. For the purposes of this code, though, I think we can treat the contents the metadata as a black box. (And for performance, we definitely want to represent it as `bytes` so it's not eagerly deserialized.

In the future I'll put in a comment here like:

```
// Holds a serialized whatever.whatever.Whatever proto. Refer to that for documentation.
```
___
*[src/main/swig/wfanet/panelmatch/client/batchlookup/query_evaluator.swig, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/62#-MfZ5UsU8wKCAff5ApWS:-MfZHoGnD_O1dHUqhNB8:b-cd3r78) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed944365ae17727f7fbedf28c4c07ac00da2b401/src/main/swig/wfanet/panelmatch/client/batchlookup/query_evaluator.swig#L22)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can this file get combined with the exact same code in the other swig files?
</blockquote></details>

In theory there's a way to do includes in SWIG to factor out the common stuff but I never bothered to figure out how. It would require updating this: https://github.com/world-federation-of-advertisers/rules_swig/blob/main/java/defs.bzl

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/62)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/proto/wfa/panelmatch/client/batchlookup/query_evaluator.proto, line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/62#-MfZ7W_n9kT3SfaI-mHO:-MfcR6uZ7e31RFRluQho:b-5xoufk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed944365ae17727f7fbedf28c4c07ac00da2b401/src/main/proto/wfa/panelmatch/client/batchlookup/query_evaluator.proto#L75)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Once the lower-level RLWE wrapper library is open sourced, I'll be able to link to the equivalent proto in that. That will have a lot of documentation. For the purposes of this code, though, I think we can treat the contents the metadata as a black box. (And for performance, we definitely want to represent it as `bytes` so it's not eagerly deserialized.

In the future I'll put in a comment here like:

```
// Holds a serialized whatever.whatever.Whatever proto. Refer to that for documentation.
```
</blockquote></details>

can you add that as a TODO?
___
*[src/main/swig/wfanet/panelmatch/client/batchlookup/query_evaluator.swig, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/62#-MfZ5UsU8wKCAff5ApWS:-MfcRE3253bs5Nplutaj:b-phtkd8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed944365ae17727f7fbedf28c4c07ac00da2b401/src/main/swig/wfanet/panelmatch/client/batchlookup/query_evaluator.swig#L22)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

In theory there's a way to do includes in SWIG to factor out the common stuff but I never bothered to figure out how. It would require updating this: https://github.com/world-federation-of-advertisers/rules_swig/blob/main/java/defs.bzl
</blockquote></details>

can you add an issue?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/62)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/proto/wfa/panelmatch/client/batchlookup/query_evaluator.proto, line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/62#-MfZ7W_n9kT3SfaI-mHO:-Mfcq81NBNsmp_AkDCBC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed944365ae17727f7fbedf28c4c07ac00da2b401/src/main/proto/wfa/panelmatch/client/batchlookup/query_evaluator.proto#L75)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add that as a TODO?
</blockquote></details>

Done.
___
*[src/main/swig/wfanet/panelmatch/client/batchlookup/query_evaluator.swig, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/62#-MfZ5UsU8wKCAff5ApWS:-MfcqCw6Ab8x3J3r0jwG:bweefs2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ed944365ae17727f7fbedf28c4c07ac00da2b401/src/main/swig/wfanet/panelmatch/client/batchlookup/query_evaluator.swig#L22)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add an issue?
</blockquote></details>

One already exists for this: https://github.com/world-federation-of-advertisers/rules_swig/issues/2

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/62)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by efoxepstein — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/62)* status: 10 of 13 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
