### PR TITLE
Change the C++ namespaces to match what the common (and other WFA) repos use

### LINKED ISSUE #17: Update C++ namespaces
The C++ namespaces should match existing code. ie wfa.panelmatch.something

### PR DESCRIPTION
**Pull request by jonmolle**
Resolves #17 - Changes the cc namespaces to use wfa over wfanet (and removes a few leading org:: statements).

Largely cosmetic, but keeps cc code here lined up with other WFA repos.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/46)

### CODE REVIEW

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 38 of 40 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/46)* status: all files reviewed, 1 unresolved discussion (waiting on @jonmolle and @stevenwarejones)

___
*[src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 44 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/46#-MeflPvyDiE78PJtlcZQ:-MeflPvyDiE78PJtlcZR:beawf6v) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/68530dff529caf8de77203f1223111b2eda28af8/src/test/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L44)):*
> ```cpp
> using ::wfa::IsOk;
> using ::wfa::IsOkAndHolds;
> using ::wfa::StatusIs;
> ```

You can delete `using ::wfa::Foo;` statements -- they're redundant now

**Review by efoxepstein — APPROVED** [review]
> Reviewed 9 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/46)* status: all files reviewed, 1 unresolved discussion (waiting on @jonmolle and @stevenwarejones)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/46)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 15 of 40 files at r1, 2 of 3 files at r3, 4 of 9 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/46)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle)

**Pull request merged**
