### PR TITLE
update virtual people to 0.2.3

### PR DESCRIPTION
**Pull request by jonmolle**
- gives access to expanded traffic info proto
- removes some duplicate code

Should be a no-op otherwise

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/367)

**Review by Marco-Premier — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/367)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @robinsons and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/367)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @robinsons)

**Review by robinsons — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/367)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle)

**Pull request merged**
