### PR TITLE
Add signing and validating inputs into Storage

### PR DESCRIPTION
**Pull request by jonmolle**
Previously these were stubbed out.

Implements the verification and signing functions migrated to common-jvm for Storage

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @jonmolle, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 43 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114#-MjVLr1K8OSvVvD5b06G:-MjVLr1K8OSvVvD5b06H:b-7bvyew) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/69c5114c24152e606307d7eee867613d28a5b43e/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L43)):*
> ```Kotlin
> 
>   /** A helper function to get the implicit path for a input's signature. */
>   private fun getSigPath(blobKey: String): String = "${blobKey}_signature"
> ```

Nit: {}s not needed: `"$blobKey_signature"`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114#-MjVMIze1dvLmFi8EY7b:-MjVMIze1dvLmFi8EY7c:bg2koom) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/69c5114c24152e606307d7eee867613d28a5b43e/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L113)):*
> ```Kotlin
>     val sourceBlob = storageClient.createBlob(blobKey = blobKey, content = signedContent)
> 
>     val signature = deferredSig.await()
> ```

At this point, `deferredSig` should definitely by ready, right? Can you use `.getCompleted()` instead of `await()`?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @jonmolle, and @robinsons)

___
*[build/repositories.bzl, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114#-MjVfl_kAMuX3CNBTiRF:-MjVfl_kAMuX3CNBTiRG:b1aoaz3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/69c5114c24152e606307d7eee867613d28a5b43e/build/repositories.bzl#L37)):*
> ```Starlark
>         name = "wfa_common_jvm",
>         sha256 = "cb909f4775093dac760730e0172d30e9979167030127430e6552b6f925e5dbb6",
>         strip_prefix = "common-jvm-dd1b52907c7f1964e4eadca0446d9cb9962e7ccd",
> ```

please use a version
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageClient.kt, line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114#-MjVfx_5AKK3VgcHTbVI:-MjVfx_5AKK3VgcHTbVJ:bu90njk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/69c5114c24152e606307d7eee867613d28a5b43e/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageClient.kt#L32)):*
> ```Kotlin
> 
> /** [StorageClient] for InMemoryStorage service. */
> class InMemoryStorageClient(private val keyPrefix: String) : StorageClient {
> ```

can you add a TODO to move this to testing only?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114#-MjVMIze1dvLmFi8EY7b:-MjVgQTM-y8ziIs51Ri0:bms46tx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/69c5114c24152e606307d7eee867613d28a5b43e/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L113)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

At this point, `deferredSig` should definitely by ready, right? Can you use `.getCompleted()` instead of `await()`?
</blockquote></details>

whats the advantage here?

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @jonmolle, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114#-MjVMIze1dvLmFi8EY7b:-MjVpR6wATzx0qVvTqJD:b-il28xi) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/69c5114c24152e606307d7eee867613d28a5b43e/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L113)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

whats the advantage here?
</blockquote></details>

It'll throw if the deferred isn't ready, which is a better way to handle a bug than just sitting there indefinitely, waiting on a condition that might never happen.

**Review by jonmolle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114)* status: 4 of 13 files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @jonmolle, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 43 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114#-MjVLr1K8OSvVvD5b06G:-MjW2Rm_7RKIvl2qzB6X:b-chogls) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/69c5114c24152e606307d7eee867613d28a5b43e/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Nit: {}s not needed: `"$blobKey_signature"`
</blockquote></details>

I think it does unless there's a space? At least it throws an unresolved reference and assumes the "_signature" is part of the variable name. Unless there's another way to indicate the end of a variable name in this formatting.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114#-MjVMIze1dvLmFi8EY7b:-MjW2c9Q58CrkfZv3dib:b-vd81kv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/69c5114c24152e606307d7eee867613d28a5b43e/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L113)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It'll throw if the deferred isn't ready, which is a better way to handle a bug than just sitting there indefinitely, waiting on a condition that might never happen.
</blockquote></details>

I'm with you, and had it that way originally, but officially .getCompleted() is experimental and not recommended for prod use and I didn't like the constant warning. Are we not worried about that? It works exactly like you say.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageClient.kt, line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114#-MjVfx_5AKK3VgcHTbVI:-MjW88Qn8-vXFC5eJfqV:b-7rh1w6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/69c5114c24152e606307d7eee867613d28a5b43e/src/main/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageClient.kt#L32)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add a TODO to move this to testing only?
</blockquote></details>

I just moved it. Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @jonmolle, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114#-MjVMIze1dvLmFi8EY7b:-MjWFfH46JK0uudL5z43:blrl6lc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/69c5114c24152e606307d7eee867613d28a5b43e/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L113)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

I'm with you, and had it that way originally, but officially .getCompleted() is experimental and not recommended for prod use and I didn't like the constant warning. Are we not worried about that? It works exactly like you say.
</blockquote></details>

I'd say let's just use it, it's possible it'll be non-experimental before we use this code in production. We should add the `@Suppress` so it doesn't warn and then that'll make it easy to grep for all usages of experimental APIs before we deploy and re-evaluate them.

**Review by jonmolle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, @robinsons, and @stevenwarejones)

___
*[build/repositories.bzl, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114#-MjVfl_kAMuX3CNBTiRF:-MjWFK0rCsIb4WTKZxBY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/69c5114c24152e606307d7eee867613d28a5b43e/build/repositories.bzl#L37)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

please use a version
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114#-MjVMIze1dvLmFi8EY7b:-MjWLAmZ-wnf2Ylhh0it:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/69c5114c24152e606307d7eee867613d28a5b43e/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L113)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'd say let's just use it, it's possible it'll be non-experimental before we use this code in production. We should add the `@Suppress` so it doesn't warn and then that'll make it easy to grep for all usages of experimental APIs before we deploy and re-evaluate them.
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @robinsons, and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
Approving. Please take care of the last comment I posted or ask me if you have q's.

> Reviewed 8 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114#-:-MjZlvX0DdlelDjYHneI:b-jdpkwl)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @jonmolle, and @robinsons)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageTest.kt, line 15 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114#-MjZlVgwEY7KE9uhQk4W:-MjZlVgwEY7KE9uhQk4X:b-en4de1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/43e7e8e5bb410d8b4a4f2428f976644dcd038fdc/src/test/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageTest.kt#L15)):*
> ```Kotlin
> // limitations under the License.
> 
> package org.wfanet.panelmatch.client.storage
> ```

probably should move this test to `package org.wfanet.panelmatch.client.storage.testing`

**Review by robinsons — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 1 of 1 files at r2, 9 of 9 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @jonmolle)

**Review by jonmolle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114)* status: 11 of 15 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, @robinsons, and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageTest.kt, line 15 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114#-MjZlVgwEY7KE9uhQk4W:-MjeipFp8RysbTvJtiTJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/43e7e8e5bb410d8b4a4f2428f976644dcd038fdc/src/test/kotlin/org/wfanet/panelmatch/client/storage/InMemoryStorageTest.kt#L15)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

probably should move this test to `package org.wfanet.panelmatch.client.storage.testing`
</blockquote></details>

Done.

**Review by jonmolle — COMMENTED** [review]
Test moved.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114#-:-Mjeiqh2B9pVuriOejB9:b-ao658)* status: 11 of 15 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, @robinsons, and @stevenwarejones)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @stevenwarejones)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/114)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Pull request merged**
