### PR TITLE
invalidateAttempt() at any recoverable error at ExchangeStepLauncher

### PR DESCRIPTION
**Pull request by duliomatos1**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/112)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/112)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/112#-Mj_pd3--3O2SeSMgqyo:-Mj_pd306Z8svh4sn-fX:b5pqsg9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/695a10c58c346f9a4a409eacf331ee482cba0371/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L17)):*
> ```Kotlin
> package org.wfanet.panelmatch.client.launcher
> 
> import java.util.Collections.emptyList
> ```

I think you want Kotlin's `emptyList` instead
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/112#-Mj_pzwM39NvR-Rwrz77:-Mj_pzwM39NvR-Rwrz78:b-8d3mmp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/695a10c58c346f9a4a409eacf331ee482cba0371/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L52)):*
> ```Kotlin
>       attemptKey,
>       ExchangeStepAttempt.State.FAILED_STEP,
>       cause.message?.let { listOf(it) } ?: emptyList()
> ```

Simpler: `listOf(cause.message).filterNotNull()`?

**Review by stevenwarejones — APPROVED** [review]
take care of Eli's comments and I'm good.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/112#-:-Mja0G7J-_8JjHO-x-i5:b-gnff1x)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @yunyeng)

**Review by yunyeng — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/112)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/112#-MjaRI8F1A1NyGOLLEQS:-MjaRI8F1A1NyGOLLEQT:bjt2n1i) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/695a10c58c346f9a4a409eacf331ee482cba0371/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L46)):*
> ```
> cause
> ```
Can this variable be called exception: now?

**Review by duliomatos1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/112)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/112#-Mj_pzwM39NvR-Rwrz77:-Mjjkn3Q89OUzIJDiegD:b-v8gp5e) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/695a10c58c346f9a4a409eacf331ee482cba0371/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L52)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Simpler: `listOf(cause.message).filterNotNull()`?
</blockquote></details>

nice. Even better, found`listofNotNull()`

**Review by duliomatos1 — COMMENTED** [review]
> Dismissed @efoxepstein and @yunyeng from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/112)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/112#-Mj_pd3--3O2SeSMgqyo:-MjjmzM3-dRJtYBgNufj:b32w0x) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/695a10c58c346f9a4a409eacf331ee482cba0371/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L17)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think you want Kotlin's `emptyList` instead
</blockquote></details>

OK
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/112#-MjaRI8F1A1NyGOLLEQS:-MjjmxrE7MTh3__6KftO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/695a10c58c346f9a4a409eacf331ee482cba0371/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L46)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

> ```
> cause
> ```
Can this variable be called exception: now?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/112#-Mj_pzwM39NvR-Rwrz77:-MjjmvnlEVL0YqvAuOuJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/695a10c58c346f9a4a409eacf331ee482cba0371/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L52)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

nice. Even better, found`listofNotNull()`
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/112)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Review by duliomatos1 — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/112#-:-MjkY1RIBnefvKpYqTNL:b-896fix)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Review by yunyeng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/112)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Pull request merged**
