### PR TITLE
Add cc_binary to decrypt AesWithHkdf encryptions

### PR DESCRIPTION
**Pull request by enfreck**
Add cc_binary to decrypt BigQuery AesWithHkdf encrypted data

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)* status: all files reviewed, 2 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-Mgl-3C30PAe00WD72Dm:-Mgl-3C30PAe00WD72Dn:b-ucpnar) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c36ef90c21d9d849d4cedbce182c8ea13d76083a/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L36)):*
> ```cpp
> // Spot check AesWithHkdf enrypted values from the command line
> // Parameters: encrypted value, key
> int main(int argc, char** argv) {
> ```

`main` shouldn't be in any namespace please
___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-Mgl-9hv84r9t3vmNVvM:-Mgl-9hv84r9t3vmNVvN:b5blz2h) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c36ef90c21d9d849d4cedbce182c8ea13d76083a/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L49)):*
> ```cpp
>       aes_hkdf.Decrypt(argv[1], SecretDataFromStringView(argv[2]));
>   if (!plaintext.ok()) {
>     std::cout << "Decryption failed" << std::endl;
> ```

Can you also print out `plaintext.status()`? It supports `operator<<` so you can just write: `std::cout << "Decryption failed: " << plaintext.status() << std::endl;`

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @jmorrrr, and @matthewclegg)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-Mgl-3C30PAe00WD72Dm:-Mgl4NNh1HCEwSO_GE8K:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c36ef90c21d9d849d4cedbce182c8ea13d76083a/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L36)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`main` shouldn't be in any namespace please
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-Mgl-9hv84r9t3vmNVvM:-Mgl4NiR750xAdTdyLXH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c36ef90c21d9d849d4cedbce182c8ea13d76083a/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L49)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you also print out `plaintext.status()`? It supports `operator<<` so you can just write: `std::cout << "Decryption failed: " << plaintext.status() << std::endl;`
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 47 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-MglKmqrC8UM97xTY5Sv:-MglKmqs5Cw-tPUIK192:baxce5z) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79875181b6f2d9a8df27b8a14fc50c3a66f4b206/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L47)):*
> ```cpp
>       aes_hkdf.Decrypt(argv[1], SecretDataFromStringView(argv[2]));
>   if (!plaintext.ok()) {
>     std::cout << "Decryption failed: " << plaintext.status() << std::endl;
> ```

Maybe send this one to `std::cerr`

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-MglUkQk6spUS0TgYIEo:-MglUkQk6spUS0TgYIEp:b8dkgma) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79875181b6f2d9a8df27b8a14fc50c3a66f4b206/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L32)):*
> ```cpp
> using ::wfa::panelmatch::common::crypto::Hkdf;
> 
> // Spot check AesWithHkdf enrypted values from the command line
> ```

nit: `encrypted`
___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 47 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-MglKmqrC8UM97xTY5Sv:-MglUpO97C-2KGhmk3GZ:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79875181b6f2d9a8df27b8a14fc50c3a66f4b206/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe send this one to `std::cerr`
</blockquote></details>

+1

**Review by jmorrrr — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @enfreck, and @matthewclegg)

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @matthewclegg)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 47 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-MglKmqrC8UM97xTY5Sv:-MglddjM1_PytHJsPsRe:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/79875181b6f2d9a8df27b8a14fc50c3a66f4b206/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L47)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck and @matthewclegg)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 33 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-MgloPiZCqsXxavmQto0:-MgloPiZCqsXxavmQto1:bhq3utn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/02220ef19bf7ea0d235324f7f373d706840c0304/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L33)):*
> ```cpp
> 
> // Spot check AesWithHkdf encrypted values from the command line
> // Parameters: encrypted value, key
> ```

Have you manually tested this?

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @matthewclegg)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 33 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-MgloPiZCqsXxavmQto0:-Mgqazps5z2hRVNdJrqH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/02220ef19bf7ea0d235324f7f373d706840c0304/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Have you manually tested this?
</blockquote></details>

Done.

**Review by matthewclegg — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)* status: all files reviewed, 4 unresolved discussions (waiting on @enfreck)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 45 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-MgqhFWN4UXTg0rM6FVg:-MgqhFWN4UXTg0rM6FVh:bqitc48) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6877e7b32e2119675b18cf9fbf9e7035a3aec066/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L45)):*
> ```cpp
>   }
> 
>   std::string temp;
> ```

Can you document somewhere that we're expecting the encrypted value to be double-base64-escaped?
___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 57 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-MgqhgHW6CYD9zzu5gK6:-MgqhgHW6CYD9zzu5gK7:blefv8n) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6877e7b32e2119675b18cf9fbf9e7035a3aec066/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L57)):*
> ```cpp
>   }
> 
>   std::vector<std::string> input = {std::string(argv[2])};
> ```

`input` is a little generic of a name, as is `processed`. Can you make them more specific?
___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 59 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-Mgqhm3f6gPToIdPkixd:-Mgqhm3f6gPToIdPkixe:b30qh4m) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6877e7b32e2119675b18cf9fbf9e7035a3aec066/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L59)):*
> ```cpp
>   std::vector<std::string> input = {std::string(argv[2])};
>   absl::StatusOr<std::vector<std::string>> processed =
>       cryptor.value()->BatchProcess(input, Action::kEncrypt);
> ```

Prefer `(*cryptor)->BatchProcess` over `cryptor.value()` please
___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 70 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-Mgqhu0y5TdBKA1BgDAg:-Mgqhu0y5TdBKA1BgDAh:b-g43ls5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6877e7b32e2119675b18cf9fbf9e7035a3aec066/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L70)):*
> ```cpp
> 
>   absl::StatusOr<std::string> plaintext = aes_hkdf.Decrypt(
>       ciphertext, SecretDataFromStringView(processed.value()[0]));
> ```

Prefer `(*processed)[0]` please. But you also probably want to add a safety check like `if (processed->empty()) { std::cerr << ...; return 1; }`

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 45 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-MgqhFWN4UXTg0rM6FVg:-Mgql5S-7qkzqIA_0geZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6877e7b32e2119675b18cf9fbf9e7035a3aec066/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L45)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you document somewhere that we're expecting the encrypted value to be double-base64-escaped?
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 57 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-MgqhgHW6CYD9zzu5gK6:-Mgql5g6DGRD0bEzmmjL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6877e7b32e2119675b18cf9fbf9e7035a3aec066/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`input` is a little generic of a name, as is `processed`. Can you make them more specific?
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 59 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-Mgqhm3f6gPToIdPkixd:-Mgql6642sFIhYPW0_zN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6877e7b32e2119675b18cf9fbf9e7035a3aec066/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L59)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Prefer `(*cryptor)->BatchProcess` over `cryptor.value()` please
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 70 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-Mgqhu0y5TdBKA1BgDAg:-Mgql6mB7025sVkk9a9d:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6877e7b32e2119675b18cf9fbf9e7035a3aec066/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L70)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Prefer `(*processed)[0]` please. But you also probably want to add a safety check like `if (processed->empty()) { std::cerr << ...; return 1; }`
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Review by oliver-amzn — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)* status: all files reviewed, 2 unresolved discussions (waiting on @enfreck)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 1 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-Mh-7WqlDMz6r6iIOEV7:-Mh-7WqlDMz6r6iIOEV8:behh26b) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0ed23432d7c13d9b6032043ed8dc388f6bea3860/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L1)):*
> ```cpp
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

Is this being build as part of the CI tests?
___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 38 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-Mh-6Zs_1T45xZYwpmNz:-Mh-6ZsaAym67paaDnz5:b-n6ui2g) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0ed23432d7c13d9b6032043ed8dc388f6bea3860/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L38)):*
> ```cpp
> 
> // Spot check AesWithHkdf encrypted values from the command line
> // Parameters: double-base64-escaped encrypted value, unencrypted identifier,
> ```

Pardon my ignorance but what is this `base64 escaping` ? Same as base64 encoding / decoding? 
and why do we need this double escaped?

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 1 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-Mh-7WqlDMz6r6iIOEV7:-Mh-MaHtDHzfLYeD-0Xi:b2nhswy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0ed23432d7c13d9b6032043ed8dc388f6bea3860/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L1)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Is this being build as part of the CI tests?
</blockquote></details>

Yes
___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 38 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-Mh-6Zs_1T45xZYwpmNz:-Mh-MbG56i7d6ZWy8FfU:b4hvnr8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0ed23432d7c13d9b6032043ed8dc388f6bea3860/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L38)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Pardon my ignorance but what is this `base64 escaping` ? Same as base64 encoding / decoding? 
and why do we need this double escaped? 
</blockquote></details>

It's needed to decode the output run in BigQuery.  As for why the output is base64 encoded, I don't know.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 38 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-Mh-6Zs_1T45xZYwpmNz:-Mh-NrQO-Ftc8RId69U_:b6yursp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0ed23432d7c13d9b6032043ed8dc388f6bea3860/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L38)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

It's needed to decode the output run in BigQuery.  As for why the output is base64 encoded, I don't know.
</blockquote></details>

For a little more context -- we want to use base64 when passing bytestring command-line arguments because it's a fairly natural, compact, terminal-safe way to do it. We obviously can't put the raw bytes and using hex escapes like `\xA5` is pretty gross and less compact.

I honestly have no idea why it's double-base64-escaped -- something to look into. Erin, can you put a TODO to look into that?

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn)

**Review by oliver-amzn — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @enfreck)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 1 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-Mh-7WqlDMz6r6iIOEV7:-Mh-dYOQ2AM5jHDr5cLe:b44u5k) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0ed23432d7c13d9b6032043ed8dc388f6bea3860/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L1)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Yes
</blockquote></details>

🚀
___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 38 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80#-Mh-6Zs_1T45xZYwpmNz:-Mh-dh-y1SklDUgngwxB:bns0hvp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0ed23432d7c13d9b6032043ed8dc388f6bea3860/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

For a little more context -- we want to use base64 when passing bytestring command-line arguments because it's a fairly natural, compact, terminal-safe way to do it. We obviously can't put the raw bytes and using hex escapes like `\xA5` is pretty gross and less compact.

I honestly have no idea why it's double-base64-escaped -- something to look into. Erin, can you put a TODO to look into that?
</blockquote></details>

Yeah, single base64-encoded makes sense for the aforementioned reasons. Just haven't heard the term "base64 escaping".

I'm fine with a todo here but this also could really use a README with an example but we can save that for another day.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/80)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck)

**Pull request merged**
