### PR TITLE
Adds Cert Manager usage and StorageClient Extensions to Storage

### PR DESCRIPTION
**Pull request by jonmolle**
- VerifiedStorageClient now uses CertificateManager
- VerifiedStorageClient now reads and writes NamedSignature protos
instead of raw signature bytes
- New proto: NamedSignature - holds the signature and API resource name
of the signing certificate
- Adds BatchRead/BatchWrite and adding exchange prefix extensions to
StorageClient, for use in private storage.
- Updates tests, although InputTaskTest isn't going to need to support
VerifiedStorageClient now (although although it is always nice to have
the behaviour verified by it).

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/162)

### CODE REVIEW

**Review by efoxepstein — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/162)* status: 3 of 6 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/162#-Mluy5K741XO-TGQE2fe:-Mlv9QBVC7Ku_h6KiUe9:b-refxm0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a3ab220018fc68055c4e7038ffbf8ab0dc1eddc9/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L56)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

We can, but that sort of forces everyone to use a different bucket per-exchange. Is that something we want to do?
</blockquote></details>

You can always wrap a storage client with a `PrefixedStorageClient` upstream of this (assuming we implement `PrefixedStorageClient`)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/162)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1, 1 of 3 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/162)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @jonmolle)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt, line 43 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/162#-MlvO2wZ2GSej-oYFLuH:-MlvO2wZ2GSej-oYFLuI:bg9yx5i) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d7b229ac978697aa16d65a693cdedf1d58c3c558/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L43)):*
> ```Kotlin
>   private val ownerName: String,
>   private val partnerName: String,
>   private val ownerCertificateName: String?,
> ```

why is this optional?

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/162)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @jonmolle)

**Review by jonmolle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/162)* status: 4 of 7 files reviewed, all discussions resolved (waiting on @duliomatos1 and @efoxepstein)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTaskTest.kt, line 37 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/162#-Mlw0_ay-3WiU3LKVB51:-Mm-Lv9k9ejZBg-SZ1VN:b2nhswy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fce191bd99abc4fe784d82bbe13200f309453f07/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/InputTaskTest.kt#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ah nevermind, I see that this file is unchanged now in this PR.
</blockquote></details>

Yes

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/162)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Pull request merged**
