### PR TITLE
Add result finalization to EvaluateQueriesWorkflow

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/119)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/119)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt, line 83 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/119#-MjdWF3lAvya_Jo1DIR1:-MjdWF3m0vkRGJnZd_p6:b5d6t4y) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dcef90758db29db5c060a8eb63ccaf8cf77a8321/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt#L83)):*
> ```Kotlin
>       .values("Extract Results")
>       .map {
>         // TODO: consider batching calls to finalizeResults if JNI overhead is too large.
> ```

maybe also put a reason why this shouldn't be done too. Eg we're already dealing with large shards... queryEvaluator is cpu and memory intensive, etc. (optional)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/QueryEvaluator.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/119#-MjdWjh-CqI0CPTd2ry5:-MjdWjh-CqI0CPTd2ry6:b-yoapw0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dcef90758db29db5c060a8eb63ccaf8cf77a8321/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/QueryEvaluator.kt#L35)):*
> ```Kotlin
>    * transmitted to the client for decryption.
>    */
>   fun finalizeResults(results: Sequence<Result>): Sequence<Result>
> ```

do you want to output a Sequence of `EncryptedQueryResult`?

https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/proto/wfa/panelmatch/client/privatemembership/query.proto#L65

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/119)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/QueryEvaluator.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/119#-MjdWjh-CqI0CPTd2ry5:-Mjdlca8-ShtKB8CwiX_:b-ky7aby) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dcef90758db29db5c060a8eb63ccaf8cf77a8321/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/QueryEvaluator.kt#L35)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do you want to output a Sequence of `EncryptedQueryResult`?

https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/proto/wfa/panelmatch/client/privatemembership/query.proto#L65
</blockquote></details>

I guess that's a more general question: do we generally want to replace `Result` with `EncryptedQueryResult`?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/119)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/QueryEvaluator.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/119#-MjdWjh-CqI0CPTd2ry5:-Mjdyk9r4eo3AIufDiIc:bitoit1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dcef90758db29db5c060a8eb63ccaf8cf77a8321/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/QueryEvaluator.kt#L35)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I guess that's a more general question: do we generally want to replace `Result` with `EncryptedQueryResult`?
</blockquote></details>

Result doesn't support a repeated ciphertext like `EncryptedQueryResult` on both their repo and ours
https://github.com/google/private-membership/blob/7e88656d2fc246be844c7f75ee8d19f9ad71e98b/private_membership/rlwe/batch/proto/shared.proto#L119

I'm assuming it takes many ciphertexts to represent a single result.
This probably applies to both input and output. I suggest something more akin to 
`fun finalizeResults(results: Sequence<EncryptedQueryResult>): Sequence<EncryptedQueryResult>`

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/119)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt, line 83 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/119#-MjdWF3lAvya_Jo1DIR1:-MjeHYKrBqdinNajX750:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dcef90758db29db5c060a8eb63ccaf8cf77a8321/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/EvaluateQueriesWorkflow.kt#L83)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

maybe also put a reason why this shouldn't be done too. Eg we're already dealing with large shards... queryEvaluator is cpu and memory intensive, etc. (optional)
</blockquote></details>

Done
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/QueryEvaluator.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/119#-MjdWjh-CqI0CPTd2ry5:-MjeHZvM3e0t1fVo5i6B:b-mvupjw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dcef90758db29db5c060a8eb63ccaf8cf77a8321/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/QueryEvaluator.kt#L35)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Result doesn't support a repeated ciphertext like `EncryptedQueryResult` on both their repo and ours
https://github.com/google/private-membership/blob/7e88656d2fc246be844c7f75ee8d19f9ad71e98b/private_membership/rlwe/batch/proto/shared.proto#L119

I'm assuming it takes many ciphertexts to represent a single result.
This probably applies to both input and output. I suggest something more akin to 
`fun finalizeResults(results: Sequence<EncryptedQueryResult>): Sequence<EncryptedQueryResult>`
</blockquote></details>

`Result` = `QueryMetadata` + serialized `EncryptedQueryResult`, so they're basically the same thing. My question is: should I expunge `Result` from the codebase and only operate on `EncryptedQueryResult` or are you OK with operating on the higher level `Result` within Apache Beam?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 32 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/119)* status: 1 of 32 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/QueryEvaluator.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/119#-MjdWjh-CqI0CPTd2ry5:-MjeXRlP0iVim0bObfMF:bpbfg63) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dcef90758db29db5c060a8eb63ccaf8cf77a8321/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/QueryEvaluator.kt#L35)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`Result` = `QueryMetadata` + serialized `EncryptedQueryResult`, so they're basically the same thing. My question is: should I expunge `Result` from the codebase and only operate on `EncryptedQueryResult` or are you OK with operating on the higher level `Result` within Apache Beam?
</blockquote></details>

That's helpful information. The thing I don't like about `Result` is that it duplicates `QueryMetaData` which is present both as a field inside Result and also inside the serialized result.

Here is one short-term option I'm good with
1. adding a TODO to at least make it consistent everywhere
2. Change `payload` to `serialized_result` for now (imo it wasn't clear this was a serialized field`

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/119)* status: 1 of 32 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/QueryEvaluator.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/119#-MjdWjh-CqI0CPTd2ry5:-MjecDz04epyKfbGNUof:bx7ia3u) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dcef90758db29db5c060a8eb63ccaf8cf77a8321/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/QueryEvaluator.kt#L35)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

That's helpful information. The thing I don't like about `Result` is that it duplicates `QueryMetaData` which is present both as a field inside Result and also inside the serialized result.

Here is one short-term option I'm good with
1. adding a TODO to at least make it consistent everywhere
2. Change `payload` to `serialized_result` for now (imo it wasn't clear this was a serialized field`
</blockquote></details>

Can we defer any changes here for a little bit until I finish a sequence of refactorings? I think it'll become a bit cleaner/better after the next couple PRs I have lined up.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/119)* status: 1 of 32 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/QueryEvaluator.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/119#-MjdWjh-CqI0CPTd2ry5:-Mjf4PEH6U0JlodnagdA:b-q3gvb0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dcef90758db29db5c060a8eb63ccaf8cf77a8321/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/QueryEvaluator.kt#L35)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can we defer any changes here for a little bit until I finish a sequence of refactorings? I think it'll become a bit cleaner/better after the next couple PRs I have lined up.
</blockquote></details>

please take care of this in follow-up PRs. approving for now.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/119)* status: 1 of 32 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
