### PR TITLE
Add JniQueryEvaluator

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/69)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/69)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @oliver-amzn)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/JniQueryEvaluator.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/69#-Mg7_hDuEw3m8x1XnXwG:-Mg7_hDuEw3m8x1XnXwH:bm83n4n) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ae76911ed3944f102fb17154663af3a6a76b6af9/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/JniQueryEvaluator.kt#L26)):*
> ```Kotlin
>  * TODO: once [QueryEvaluatorParameters] are non-trivial, add a constructor argument.
>  */
> class JniQueryEvaluator : QueryEvaluator {
> ```

add a test checking for unimplemented

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/69)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/JniQueryEvaluator.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/69#-Mg7_hDuEw3m8x1XnXwG:-Mg7z7GX0C6iKa1xpoSP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ae76911ed3944f102fb17154663af3a6a76b6af9/src/main/kotlin/org/wfanet/panelmatch/client/batchlookup/JniQueryEvaluator.kt#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

add a test checking for unimplemented
</blockquote></details>

Done.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/69)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, and @stevenwarejones)

___
*[src/main/swig/wfanet/panelmatch/client/batchlookup/BUILD.bazel, line 11 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/69#-Mg8PKkF65v-X-6bFOS8:-Mg8PKkF65v-X-6bFOS9:b-j4i5ly) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/15832e23a346f3a00748f6bd985a9d84e90ca4c7/src/main/swig/wfanet/panelmatch/client/batchlookup/BUILD.bazel#L11)):*
> ```Starlark
>     name = "query_evaluator",
>     src = "query_evaluator.swig",
>     module = "SwigQueryEvaluator",
> ```

whats the preferred naming convention? I was starting to use `SwigXYZ` in my branch. I kind of like it better for clarity but it seems you're moving away from it already.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/69)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @stevenwarejones)

___
*[src/main/swig/wfanet/panelmatch/client/batchlookup/BUILD.bazel, line 11 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/69#-Mg8PKkF65v-X-6bFOS8:-MgBviOq-lWTp1vbjC-8:b-u8w1u0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/15832e23a346f3a00748f6bd985a9d84e90ca4c7/src/main/swig/wfanet/panelmatch/client/batchlookup/BUILD.bazel#L11)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

whats the preferred naming convention? I was starting to use `SwigXYZ` in my branch. I kind of like it better for clarity but it seems you're moving away from it already.
</blockquote></details>

I kind of like it too but I feel like we should migrate them all at once if we decide to use that as a convention. Right now there isn't really a convention. I can't just use `QueryEvaluator` here because I already have a `QueryEvaluator` class.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/69)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Pull request merged**
