### PR TITLE
Fix bug around DaemonFlags

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/267)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/267)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/DaemonStorageClientDefaults.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/267#-MuSBc-61vOsUH-y-HZG:-MuSBc-61vOsUH-y-HZH:b9s9kbj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/61efedea810824d345295661e3483c4966ffbbc2/src/main/kotlin/org/wfanet/panelmatch/client/deploy/DaemonStorageClientDefaults.kt#L56)):*
> ```Kotlin
>   companion object {
>     init {
>       GcpKmsClient.register(Optional.empty(), Optional.empty())
> ```

Please move this into gcloud subfolder so only the gcloud example requires this.

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/267)* status: 5 of 11 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/DaemonStorageClientDefaults.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/267#-MuSBc-61vOsUH-y-HZG:-MuSSd0V2v5P8mi7QUbp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/61efedea810824d345295661e3483c4966ffbbc2/src/main/kotlin/org/wfanet/panelmatch/client/deploy/DaemonStorageClientDefaults.kt#L56)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please move this into gcloud subfolder so only the gcloud example requires this.
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/267)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/DaemonStorageClientDefaults.kt, line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/267#-MuSSfps8_FqtMD0D31w:-MuSSfps8_FqtMD0D31x:b-j084zw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e450f101db3f8736ca64d769d40d4753e0024c4a/src/main/kotlin/org/wfanet/panelmatch/client/deploy/DaemonStorageClientDefaults.kt#L25)):*
> ```Kotlin
> import org.wfanet.panelmatch.common.storage.withPrefix
> 
> abstract class DaemonStorageClientDefaults(rootStorageClient: StorageClient, tinkKeyUri: String) {
> ```

Why is this abstract?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/ExampleDaemon.kt, line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/267#-MuSTKGm-_vcUQjujfIc:-MuSTKGm-_vcUQjujfId:b-l7mipd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e450f101db3f8736ca64d769d40d4753e0024c4a/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/ExampleDaemon.kt#L29)):*
> ```Kotlin
> 
> /** Example base class for [ExchangeWorkflowDaemonFromFlags] implementations. */
> abstract class ExampleDaemon : ExchangeWorkflowDaemonFromFlags() {
> ```

Why is it necessary to modify this file?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GcpDaemonStorageClientDefaults.kt, line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/267#-MuSTmMu811cuM8sL9qx:-MuSTmMu811cuM8sL9qy:bzfkl8j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e450f101db3f8736ca64d769d40d4753e0024c4a/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GcpDaemonStorageClientDefaults.kt#L27)):*
> ```Kotlin
>   companion object {
>     init {
>       GcpKmsClient.register(Optional.empty(), Optional.empty())
> ```

Can't you just do this in Main?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GoogleCloudExampleDaemonMain.kt, line 72 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/267#-MuSUGOGEE2hHNdJHbLu:-MuSUGOH9ASZzB_-dfk4:b305xm) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e450f101db3f8736ca64d769d40d4753e0024c4a/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GoogleCloudExampleDaemonMain.kt#L72)):*
> ```Kotlin
> private class GoogleCloudExampleDaemon : ExampleDaemon() {
>   @Option(names = ["--tink-key-uri"], description = ["KMS URI for Tink"], required = true)
>   private lateinit var tinkKeyUri: String
> ```

I think you can undo the changes in this file and just add `GcpKmsClient.register(Optional.empty(), Optional.empty())` in a companion object of this.

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/267)* status: 7 of 11 files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/ExampleDaemon.kt, line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/267#-MuSTKGm-_vcUQjujfIc:-MuSXVto51-Po7FJj1E-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e450f101db3f8736ca64d769d40d4753e0024c4a/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/ExampleDaemon.kt#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why is it necessary to modify this file?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GoogleCloudExampleDaemonMain.kt, line 72 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/267#-MuSUGOGEE2hHNdJHbLu:-MuSXWnk8r5iiTw9X9j-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e450f101db3f8736ca64d769d40d4753e0024c4a/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GoogleCloudExampleDaemonMain.kt#L72)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think you can undo the changes in this file and just add `GcpKmsClient.register(Optional.empty(), Optional.empty())` in a companion object of this.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/DaemonStorageClientDefaults.kt, line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/267#-MuSSfps8_FqtMD0D31w:-MuSXXsA1gjdyk7fYCyW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e450f101db3f8736ca64d769d40d4753e0024c4a/src/main/kotlin/org/wfanet/panelmatch/client/deploy/DaemonStorageClientDefaults.kt#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why is this abstract?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GcpDaemonStorageClientDefaults.kt, line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/267#-MuSTmMu811cuM8sL9qx:-MuSXYE49Oa9fTKkGBz6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e450f101db3f8736ca64d769d40d4753e0024c4a/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud/GcpDaemonStorageClientDefaults.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can't you just do this in Main?
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/267)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 9 files at r1, 1 of 3 files at r2, 1 of 6 files at r3, 2 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/267)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
