### PR TITLE
add decompression to decrypt workflow

### PR DESCRIPTION
**Pull request by stevenwarejones**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 5 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127)* status: 5 of 23 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127#-Mk9yqrO0m2nsGKJ0vjv:-Mk9yqrO0m2nsGKJ0vjw:byj1z5h) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c1a3c152b4535e3a075564fd070c28291d6cd1ad/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L41)):*
> ```Kotlin
>   private val queryResultsDecryptor: QueryResultsDecryptor,
>   private val hkdfPepper: ByteString,
>   private val getCompressor: (ByteString) -> Compressor,
> ```

Won't this run into the same serialization issues?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/UncompressEvents.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127#-Mk9ychd2CjSWWKNkCqu:-Mk9yche6RWHVFPso9u2:bbbr80a) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c1a3c152b4535e3a075564fd070c28291d6cd1ad/src/main/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/UncompressEvents.kt#L41)):*
> ```Kotlin
>     dictionaryData: ByteString ->
>     val compressor = getCompressor(dictionaryData)
>     CombinedEvents.parseFrom(compressor.uncompress(events.plaintext)).serializedEventsList.map {
> ```

This should be a `forEach` instead of `map`, I think -- the output isn't used.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127)* status: 2 of 28 files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127#-Mk9yqrO0m2nsGKJ0vjv:-MkCT1Hd9Ayo-AALJoqs:bsl2jw7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c1a3c152b4535e3a075564fd070c28291d6cd1ad/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Won't this run into the same serialization issues?
</blockquote></details>

Probably. This, right now, obviously isn't erroring but its also ignoring the input ByteString. It will break when someone actually tries to use it.

What do you think if I just pass in the factory instead?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/UncompressEvents.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127#-Mk9ychd2CjSWWKNkCqu:-MkCSwze6jCJW-J8jrld:b2gwdm2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c1a3c152b4535e3a075564fd070c28291d6cd1ad/src/main/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/UncompressEvents.kt#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This should be a `forEach` instead of `map`, I think -- the output isn't used.
</blockquote></details>

i agree. done.

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 1 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127)* status: 3 of 28 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127#-Mk9yqrO0m2nsGKJ0vjv:-MkCqXUxEQGP_72O54gY:bcpnlil) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c1a3c152b4535e3a075564fd070c28291d6cd1ad/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L41)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Probably. This, right now, obviously isn't erroring but its also ignoring the input ByteString. It will break when someone actually tries to use it.

What do you think if I just pass in the factory instead?
</blockquote></details>

That's fine, though now I'm kind of doubting what I said.

I need to do some more reading but I kind of think that as long as you don't need to put an object into a PCollection, it should be sufficient that it's serializable, which I believe lambdas are. If you need to put it into a PCollection then you need to appease SerializableCoder, which requires a well defined equals and hashCode.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127)* status: 3 of 28 files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127#-Mk9yqrO0m2nsGKJ0vjv:-MkDDhET2IoUFWnSJzCT:b-e7qmt1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c1a3c152b4535e3a075564fd070c28291d6cd1ad/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

That's fine, though now I'm kind of doubting what I said.

I need to do some more reading but I kind of think that as long as you don't need to put an object into a PCollection, it should be sufficient that it's serializable, which I believe lambdas are. If you need to put it into a PCollection then you need to appease SerializableCoder, which requires a well defined equals and hashCode.
</blockquote></details>

yeah - i remain a little foggy on this one. Clarity or documentation on the topic would be great.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 8 of 23 files at r1, 17 of 18 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127#-Mk9yqrO0m2nsGKJ0vjv:-MkDGqZ35-vF7WIoWrgI:b-90m1oa) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c1a3c152b4535e3a075564fd070c28291d6cd1ad/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L41)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah - i remain a little foggy on this one. Clarity or documentation on the topic would be great.
</blockquote></details>

I think my recap was correct after some more reading. I'm not going to block anything here, but the distinction is:

* `DoFn` and other transforms need to be `Serializable`, which means that all of their members (and things they close over) must be serializable as well.
* `SerializableCoder` is the default Coder for `PCollections` of Serializable things (that don't end up picking a different Coder). When used on a PCollection, it has the additional requirement of requiring `equals` and `hashCode` to be overwritten.

Let's get things working then revisit all the complexity around Compression -- I'm sure there are some simplifications to be made. In particular, the `FactoryBasedCompressor` can hopefully be removed.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 64 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127#-MkDI5fZ-l7GF41lcKUf:-MkDI5fZ-l7GF41lcKUg:b9wmybc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fab958531f2a3f495f6818834b840555242e00dd/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L64)):*
> ```Kotlin
>       encryptedQueryResults
>         .keyBy<EncryptedQueryResult, QueryId>("Key by Query Id") { requireNotNull(it.queryId) }
>         .join<QueryId, EncryptedQueryResult, JoinKey, KV<JoinKey, EncryptedQueryResult>>(
> ```

Maybe add a helper to `Beam.kt`:

```
inline fun <KeyT, LeftT, RightT> PCollection<KV<KeyT, LeftT>> strictOneToOneJoin(right: PCollection<KV<KeyT, RightT>>): PCollection<KV<LeftT, RightT>> {
  return join(right) { _, lefts, rights -> yield(kvOf(lefts.single(), rights.single())) }
}
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsWorkflowTest.kt, line 137 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127#-MkDKAgr9rztfDr-ZdIt:-MkDKAgsCp8i4rTUkjl9:b-foq8we) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fab958531f2a3f495f6818834b840555242e00dd/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsWorkflowTest.kt#L137)):*
> ```Kotlin
> 
>     val mappedCompressedEvents =
>       events.map<KV<ByteString, ByteString>, KV<QueryId, ByteString>> {
> ```

I think we have a `mapKeys` helper?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsWorkflowTest.kt, line 149 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127#-MkDKMsH-srKr5soq3i3:-MkDKMsIBeunF8qFhuX-:b12c87) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fab958531f2a3f495f6818834b840555242e00dd/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsWorkflowTest.kt#L149)):*
> ```Kotlin
>           plaintexts: Iterable<DecryptedEventData>,
>           compresseds: Iterable<ByteString> ->
>           yield(plaintextOf(compresseds.single(), queryId, plaintexts.single().shardId))
> ```

This too could use the helper I described in another comment

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 64 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127#-MkDI5fZ-l7GF41lcKUf:-MkDSHEH996w0Vj1EhFC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fab958531f2a3f495f6818834b840555242e00dd/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L64)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe add a helper to `Beam.kt`:

```
inline fun <KeyT, LeftT, RightT> PCollection<KV<KeyT, LeftT>> strictOneToOneJoin(right: PCollection<KV<KeyT, RightT>>): PCollection<KV<LeftT, RightT>> {
  return join(right) { _, lefts, rights -> yield(kvOf(lefts.single(), rights.single())) }
}
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsWorkflowTest.kt, line 137 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127#-MkDKAgr9rztfDr-ZdIt:-MkDNaWV4h9JG2fUb3dA:b-1v4v6w) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fab958531f2a3f495f6818834b840555242e00dd/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsWorkflowTest.kt#L137)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think we have a `mapKeys` helper?
</blockquote></details>

Not sure we really need a helper on this one, but happy to exercise the existing one.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsWorkflowTest.kt, line 149 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127#-MkDKMsH-srKr5soq3i3:-MkDR_Iq6fSQ0hFdS0H7:bcv6y9d) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fab958531f2a3f495f6818834b840555242e00dd/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsWorkflowTest.kt#L149)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This too could use the helper I described in another comment
</blockquote></details>

Done. This one does prefer to the the key which `strictOneToOneJoin` discards but its still available inside the lefts so its okay.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsWorkflowTest.kt, line 137 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/127#-MkDKAgr9rztfDr-ZdIt:-MkDdPDiDIsLuxhU-57z:bbl90ei) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fab958531f2a3f495f6818834b840555242e00dd/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsWorkflowTest.kt#L137)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Not sure we really need a helper on this one, but happy to exercise the existing one.
</blockquote></details>

Both map and mapKeys are helper functions I made. This one is more specific so it's better.

**Pull request merged**
