### PR TITLE
Refactor launcher interfaces to pass more context around

### PR DESCRIPTION
**Pull request by jonmolle**
- Enables using dates in storage paths
- Fixes Intersect & Validate bootstrapping
- Generally cleans up code

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/183)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 38 of 38 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/183)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepValidator.kt, line 27 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/183#-MnC20mz5gLob68F3uwK:-MnCG3KKBcCtAMkXMLxB:b7ssw4u) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/02b2bd4f51b7ff86ca79f382094f01dc86b58655/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepValidator.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

LocalDate does not have an attached TZ, it's morally equivalent to the protobuf Date embedded in the `Exchange` resource. I _think_ this is what we want. The only place that should need to care about the TZ are the things _outside_ the exchange workflow that write into it. Those should take care with timezones, but code in here that just uses LocalDate shouldn't need to care.
</blockquote></details>

Well, the validation function that gets the date needs to use GMT right?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt, line 95 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/183#-MnC27yH2p3OGeWjk9kA:-MnCGKgJAMH9QucFkYX_:b-nlj3sv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/02b2bd4f51b7ff86ca79f382094f01dc86b58655/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt#L95)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's a little tricky because we could have had a transient failure in a previous run after writing the done blob but before telling the Kingdom that it's finished.

I think the Kingdom itself can detect when it's giving out duplicate work because it'll try to transition the ExchangeStep into a terminal state when it's already in a terminal state.
</blockquote></details>

can you put the above in a comment?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/testing/AbstractVerifiedStorageTest.kt, line 46 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/183#-MnC3NTL2f5xxsi_-bdV:-MnCGXCaExs8-OkhTjKg:bm2bf2a) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2cdce500cac10e417b08a18987c9b53f8564cf96/src/main/kotlin/org/wfanet/panelmatch/client/storage/testing/AbstractVerifiedStorageTest.kt#L46)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This test case doesn't really make sense anymore because I deleted `verifiedBatchWrite`. Are you saying we should ensure that `createBlob` either can or can't overwrite blobs? I'm happy with leaving that up to the underlying storage client (and thus not testing it here), what do you think?
</blockquote></details>

if we don't rely that functionality one way or the other, then that's okay, but for an exchange that is re-run....let's say it partially wrote to storage before failing... it will then need to write out to that same storage and overwrite the previous stuff, right?

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 10 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/183)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/VerifiedStorageClient.kt, line 89 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/183#-MnCNt1_6pM4PTep9Pi6:-MnCNt1_6pM4PTep9Pi7:b-ek9ek3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/18a4933536d4f97c2a0a1657bcf6b09c4d3e112f/src/main/kotlin/org/wfanet/panelmatch/client/storage/VerifiedStorageClient.kt#L89)):*
> ```Kotlin
>   @Suppress("EXPERIMENTAL_API_USAGE") // For Deferred.getCompleted.
>   suspend fun createBlob(blobKey: String, content: Flow<ByteString>): VerifiedBlob {
>     deleteExistingBlobs(blobKey)
> ```

this seems like an interesting addition. Not sure if I like it or not. What was the thinking here?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/183)* status: 47 of 48 files reviewed, all discussions resolved (waiting on @duliomatos1, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/VerifiedStorageClient.kt, line 89 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/183#-MnCNt1_6pM4PTep9Pi6:-MnCPezcEeItP3B7MYGV:bg9tohb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/18a4933536d4f97c2a0a1657bcf6b09c4d3e112f/src/main/kotlin/org/wfanet/panelmatch/client/storage/VerifiedStorageClient.kt#L89)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this seems like an interesting addition. Not sure if I like it or not. What was the thinking here?
</blockquote></details>

Documented.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 45 of 45 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/183)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1, @stevenwarejones, and @yunyeng)

**Review by yunyeng — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/183)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @stevenwarejones)

**Pull request merged**
