### PR TITLE
add fake event preprocessor

### PR DESCRIPTION
**Pull request by stevenwarejones**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/213)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/213)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessorFn.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/213#-Mop1tl41YvQs0SoO1or:-Mop1tl41YvQs0SoO1os:blan5pz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/66f3c55414b5e0d02e17a89da5ad253517c8e734/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessorFn.kt#L25)):*
> ```Kotlin
>  * PreprocessEventsResponse
>  */
> class EventPreprocessorFn(private val eventPreprocessor: EventPreprocessor) :
> ```

We can probably just remove EventPreprocessorFn now and just use EventPreprocessor in its place, since EventPreprocessor is now serializable, right?

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/213)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessorFn.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/213#-Mop1tl41YvQs0SoO1or:-Mpls-ns8SgLrwMYYBS0:b76uca7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/66f3c55414b5e0d02e17a89da5ad253517c8e734/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventPreprocessorFn.kt#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

We can probably just remove EventPreprocessorFn now and just use EventPreprocessor in its place, since EventPreprocessor is now serializable, right?
</blockquote></details>

i agree. i started to do that in this PR but thought I would hold off for now. Done

**Review by efoxepstein — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/213)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniEncryptEventsTest.kt, line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/213#-Mpm9hHo01Fy-PZXKwV4:-Mpm9hHo01Fy-PZXKwV5:b-aliszy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c136a605b8948d0b2c59fd58608e8be22ba89ab2/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/JniEncryptEventsTest.kt#L45)):*
> ```Kotlin
> 
>     // TODO(@efoxepstein): once we have a JNIed way to decrypt, this should check roundtrips.
>     eventPreprocessor.preprocess(request) // Does not throw
> ```

Maybe just inline eventPreprocessor: `JniEventPreprocessor().preprocess(request)`

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/213)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
