### PR TITLE
Adds empty packages for client encryption code

### PR DESCRIPTION
**Pull request by enfreck**
These packages are used for the client encryption code for the panel
exchange data.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/22)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/22)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/22)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck and @yunyeng)

___
*[src/main/cc/wfanet/panelmatch/client/eventencryption/BUILD.bazel, line 0 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/22#-McWE6Sq9lnw7OQiKFG_:-McWE6Sq9lnw7OQiKFGa:byz3wfe) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b5e60f17d2cd48ef0fdae089a458fac7e599afd3/src/main/cc/wfanet/panelmatch/client/eventencryption/BUILD.bazel#L0)):*
I like to think of this primitive as more of 'symmetric_encryption_utility` than specifically just event encryption. What do you think about putting cc files to that effect in `panelmatch/protocol/crypto/symmetric_encryption_utility.h` ?

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/22)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/cc/wfanet/panelmatch/client/eventencryption/BUILD.bazel, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/22#-McWE6Sq9lnw7OQiKFG_:-Mc_XVwWEjiR8hk9vTrC:bh0xr2y) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b5e60f17d2cd48ef0fdae089a458fac7e599afd3/src/main/cc/wfanet/panelmatch/client/eventencryption/BUILD.bazel#L)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I like to think of this primitive as more of 'symmetric_encryption_utility` than specifically just event encryption. What do you think about putting cc files to that effect in `panelmatch/protocol/crypto/symmetric_encryption_utility.h` ?
</blockquote></details>

This will include a fair amount more than just symmetric encryption: it needs to use EcCommutativeCipher, SHA256, and HKDF.

It could be reasonable to put some or all of the code in `panelmatch/protocol/crypto/`, though. I was thinking we should isolate it elsewhere because it's all for a specific purpose, but I don't feel strongly. Steven, WDYT?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/22)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @yunyeng)

___
*[src/main/cc/wfanet/panelmatch/client/eventencryption/BUILD.bazel, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/22#-McWE6Sq9lnw7OQiKFG_:-Mck9MoU-XrOtyPnvJ1g:b-re60kr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b5e60f17d2cd48ef0fdae089a458fac7e599afd3/src/main/cc/wfanet/panelmatch/client/eventencryption/BUILD.bazel#L)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This will include a fair amount more than just symmetric encryption: it needs to use EcCommutativeCipher, SHA256, and HKDF.

It could be reasonable to put some or all of the code in `panelmatch/protocol/crypto/`, though. I was thinking we should isolate it elsewhere because it's all for a specific purpose, but I don't feel strongly. Steven, WDYT?
</blockquote></details>

i'd prefer it under protocol. The primitives could be reused for xyz in the future right?

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/22)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/cc/wfanet/panelmatch/client/eventencryption/BUILD.bazel, line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/22#-McWE6Sq9lnw7OQiKFG_:-MclG6c53jt0yxPlLAn5:bqcfw52) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b5e60f17d2cd48ef0fdae089a458fac7e599afd3/src/main/cc/wfanet/panelmatch/client/eventencryption/BUILD.bazel#L)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i'd prefer it under protocol. The primitives could be reused for xyz in the future right?
</blockquote></details>

OK, sounds good Steven. Erin, I think we can abandon this PR.

Some of the code can go under `protocol/crypto` and some of it can go under `src/main/cc/wfanet/panelmatch/common/crypto/`. Let's put all of the low-level interfaces (e.g. for AES, HKDF, Fingerprinting) under `common/crypto` and then the thing that ties it all together under `protocol/crypto`.

I think this means your first PR should probably be under `common/crypto` and add one or more of these interfaces. It should also have a corresponding `cc_library` rule in `common/crypto/BUILD.bazel` for each header you define.

**Pull request closed without merging**
