### PR TITLE
convert event preprocessing to use ptransforms

### PR DESCRIPTION
**Pull request by stevenwarejones**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186)* status: all files reviewed, 5 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/common/Coders.kt, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186#-MnCC_Y4DVeUb3uvV3_q:-MnCC_Y4DVeUb3uvV3_r:b-tt4c79) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/57756f72cbec3e6a4616840afa150669e345b2f0/src/main/kotlin/org/wfanet/panelmatch/client/common/Coders.kt#L24)):*
> ```Kotlin
> 
> /** Used for encoding collections of events to be compressed or encrypted. */
> val eventCoder: Coder<KV<ByteString, ByteString>> =
> ```

Optional: consider moving to `panelmatch/common/beam/Coders.kt` and give it a generic name like `ByteStringKvCoder`?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186#-MnCDhUF9VTpfQlh4L8o:-MnCDhUF9VTpfQlh4L8p:b5d1g0o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/57756f72cbec3e6a4616840afa150669e345b2f0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt#L36)):*
> ```Kotlin
> private const val OVERSAMPLING_FACTOR = 10L
> 
> class BuildDictionary(private val dictionaryBuilder: DictionaryBuilder) :
> ```

KDoc please
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186#-MnCD_uPDrgPFrXqjXlm:-MnCD_uPDrgPFrXqjXln:bgrkw8d) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/57756f72cbec3e6a4616840afa150669e345b2f0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt#L41)):*
> ```Kotlin
>   override fun expand(events: PCollection<KV<ByteString, ByteString>>): PCollection<Dictionary> {
>     return events
>       .values()
> ```

Since we ignore the keys, I feel like it's a cleaner interface to just take in a `PCollection<BytesString>` and make the caller deal with de-keying.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186#-MnCDjMOA_wH-vfrouuP:-MnCDjMOA_wH-vfrouuQ:b-ax6f35) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/57756f72cbec3e6a4616840afa150669e345b2f0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt#L47)):*
> ```Kotlin
>       )
>       .apply("Uniform Sample", Sample.fixedSizeGlobally(dictionaryBuilder.preferredSampleSize))
>       .map("Train Compressor") { dictionaryBuilder.buildDictionary(it) }
> ```

Rename from "Train Compressor" to "Build Dictionary from Samples" maybe?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CompressByKey.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186#-MnCDsJ49tFFIjH4cV1P:-MnCDsJ49tFFIjH4cV1Q:b56o3x0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/57756f72cbec3e6a4616840afa150669e345b2f0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CompressByKey.kt#L41)):*
> ```Kotlin
> 
>   val compressedEvents: PCollection<KV<ByteString, ByteString>> =
>     events
> ```

Do we want to pull this chain of transforms to a PCollection too?

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186#-MnCDhUF9VTpfQlh4L8o:-MnCI7JM47YVYuY5f_0H:b-ttsa3f) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/57756f72cbec3e6a4616840afa150669e345b2f0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt#L36)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

KDoc please
</blockquote></details>

the kdoc is above the private const. That's how it was before in the other file. Separated the comments here.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186#-MnCD_uPDrgPFrXqjXlm:-MnCHGxzCS4fvMpMT7XJ:bmje37z) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/57756f72cbec3e6a4616840afa150669e345b2f0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Since we ignore the keys, I feel like it's a cleaner interface to just take in a `PCollection<BytesString>` and make the caller deal with de-keying.
</blockquote></details>

+1. Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186#-MnCDjMOA_wH-vfrouuP:-MnCIYBZEt3GFq-buwmM:b-eyz3g4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/57756f72cbec3e6a4616840afa150669e345b2f0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Rename from "Train Compressor" to "Build Dictionary from Samples" maybe?
</blockquote></details>

Done. Does this sampling potentially sample PII from other events?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CompressByKey.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186#-MnCDsJ49tFFIjH4cV1P:-MnCLcaoC5pjBRYNSicj:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/57756f72cbec3e6a4616840afa150669e345b2f0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CompressByKey.kt#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Do we want to pull this chain of transforms to a PCollection too?
</blockquote></details>

Done

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186#-MnCDhUF9VTpfQlh4L8o:-MnCOE5u9YPUqIyKs8QK:b-n4d2bl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/57756f72cbec3e6a4616840afa150669e345b2f0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt#L36)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

the kdoc is above the private const. That's how it was before in the other file. Separated the comments here.
</blockquote></details>

Ah, the issue with this is that if you hover over a constructor call for BuildDictionary in IntelliJ or other tooling, it won't pull this KDoc up
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186#-MnCD_uPDrgPFrXqjXlm:-MnCOOcW9PyLu8MYHQTu:b-eep16w) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/57756f72cbec3e6a4616840afa150669e345b2f0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt#L41)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

+1. Done.
</blockquote></details>

Looks like you haven't pushed yet?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186#-MnCDjMOA_wH-vfrouuP:-MnCOSBf6KJofRie9BgB:b-eep16w) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/57756f72cbec3e6a4616840afa150669e345b2f0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt#L47)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Done. Does this sampling potentially sample PII from other events?
</blockquote></details>

Looks like you haven't pushed yet?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CompressByKey.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186#-MnCDsJ49tFFIjH4cV1P:-MnCOTHq7qn1204LTF4U:b-eep16w) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/57756f72cbec3e6a4616840afa150669e345b2f0/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CompressByKey.kt#L41)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Looks like you haven't pushed yet?

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186#-MnCDjMOA_wH-vfrouuP:-MnCT4Hj55Hxs3aeYRIl:b-3ewp74) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/de2271c93cc80d4e5f6b2ef018c5f2bc9a74d50a/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Looks like you haven't pushed yet?
</blockquote></details>

This still doesn't look done

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186#-MnCD_uPDrgPFrXqjXlm:-MnCTiWe3HSjam5norjx:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/de2271c93cc80d4e5f6b2ef018c5f2bc9a74d50a/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Looks like you haven't pushed yet?
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186#-MnCDjMOA_wH-vfrouuP:-MnCThieAOLcnQkrNLpT:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/de2271c93cc80d4e5f6b2ef018c5f2bc9a74d50a/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BuildDictionary.kt#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This still doesn't look done
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CompressByKey.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/186#-MnCDsJ49tFFIjH4cV1P:-MnCTgUE-Jmsv0RKwkeR:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/de2271c93cc80d4e5f6b2ef018c5f2bc9a74d50a/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CompressByKey.kt#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Looks like you haven't pushed yet?
</blockquote></details>

done

**Pull request merged**
