### PR TITLE
Update protos to conform to WFA standards

### PR DESCRIPTION
**Pull request by jmorrrr**
Change protos to live in src/main/wfa and change java_package to start with org.wfanet and not include protobuf

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40)

### CODE REVIEW

**Review by enfreck — APPROVED** [review]
> Reviewed 32 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 32 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40)* status: all files reviewed, 9 unresolved discussions (waiting on @jmorrrr and @matthewclegg)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWGPB60p-4WHdzCiGZ:-MeWGPB7-wBj-otMppSJ:b-ii3efa) (no related file):*
Overall the Java/Kotlin changes are correct but the C++ ones aren't quite right.

* The C++ namespace of C++ code should be unchanged
* The `package` (not `java_package`) in `.proto` files should start with `wfa.panelmatch`

---
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.h, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWFb1651_wtmcJ9Jl-:-MeWFb17A-JCva8qax-b:b-ba1p8u) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.h#L25)):*
> ```objc
> #include "wfa/panelmatch/client/eventpreprocessing/preprocess_events.pb.h"
> 
> namespace org::wfanet::panelmatch::client {
> ```

The `C++` namespace for C++ code shouldn't change (please undo this)
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWFkPb37UAJl21GHpp:-MeWFkPb37UAJl21GHpq:b-6tj8i9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc#L27)):*
> ```cpp
> #include "wfa/panelmatch/client/eventpreprocessing/preprocess_events.pb.h"
> 
> namespace org::wfanet::panelmatch::client {
> ```

The namespace for C++ code shouldn't change (please undo this)
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.h, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWFnru0Jrz4T4HmSzD:-MeWFnru0Jrz4T4HmSzE:b-6tj8i9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.h#L24)):*
> ```objc
> #include "absl/status/statusor.h"
> 
> namespace org::wfanet::panelmatch::client {
> ```

The namespace for C++ code shouldn't change (please undo this)
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWFoR_0iX6Sr6VSwlA:-MeWFoR_0iX6Sr6VSwlB:b-6tj8i9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc#L23)):*
> ```cpp
> #include "wfanet/panelmatch/common/jni_wrap.h"
> 
> namespace org::wfanet::panelmatch::client {
> ```

The namespace for C++ code shouldn't change (please undo this)
___
*[src/main/cc/wfanet/panelmatch/protocol/crypto/deterministic_commutative_encryption_utility.h, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWFstWD-S5Uxr1KUa4:-MeWFstWD-S5Uxr1KUa5:b7857qj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/cc/wfanet/panelmatch/protocol/crypto/deterministic_commutative_encryption_utility.h#L23)):*
> ```objc
> namespace wfanet::panelmatch::protocol::crypto {
> 
> absl::StatusOr<org::wfanet::panelmatch::protocol::CryptorEncryptResponse>
> ```

The C++ namespace of protos should be `wfa::panelmatch::something`
___
*[src/main/proto/wfa/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWGBLN9ViUxb0KShTa:-MeWGBLN9ViUxb0KShTb:b-puj2j1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/proto/wfa/panelmatch/client/eventpreprocessing/preprocess_events.proto#L17)):*
> ```protobuf
> syntax = "proto3";
> 
> package org.wfanet.panelmatch.client;
> ```

This should be `wfa.panelmatch.client` please
___
*[src/main/proto/wfa/panelmatch/protocol/crypto/cryptor.proto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWGFgvDo83z8QqxS0U:-MeWGFgw9rBDyWvLumx8:b-puj2j1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/proto/wfa/panelmatch/protocol/crypto/cryptor.proto#L17)):*
> ```protobuf
> syntax = "proto3";
> 
> package org.wfanet.panelmatch.protocol;
> ```

This should be `wfa.panelmatch.client` please
___
*[src/main/proto/wfa/panelmatch/protocol/exchangesteps/exchangesteps.proto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWGH1N5I2KkpijkY-Z:-MeWGH1N5I2KkpijkY-_:b-puj2j1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/proto/wfa/panelmatch/protocol/exchangesteps/exchangesteps.proto#L17)):*
> ```protobuf
> syntax = "proto3";
> 
> package org.wfanet.panelmatch.protocol;
> ```

This should be `wfa.panelmatch.client` please

**Review by jmorrrr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40)* status: all files reviewed, 9 unresolved discussions (waiting on @efoxepstein and @matthewclegg)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWGPB60p-4WHdzCiGZ:-MeWO8GN0RTLPXCQKun5:b-896fix) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Overall the Java/Kotlin changes are correct but the C++ ones aren't quite right.

* The C++ namespace of C++ code should be unchanged
* The `package` (not `java_package`) in `.proto` files should start with `wfa.panelmatch`
</blockquote></details>

Done.

---
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.h, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWFb1651_wtmcJ9Jl-:-MeWJKP22dhpGcvLKhki:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.h#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The `C++` namespace for C++ code shouldn't change (please undo this)
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWFkPb37UAJl21GHpp:-MeWJIeP5eK93xFFPAeJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The namespace for C++ code shouldn't change (please undo this)
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.h, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWFnru0Jrz4T4HmSzD:-MeWJD4u87qUmZaIdXn4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.h#L24)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The namespace for C++ code shouldn't change (please undo this)
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWFoR_0iX6Sr6VSwlA:-MeWJ9UJDIpaqN-CpVfW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The namespace for C++ code shouldn't change (please undo this)
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/protocol/crypto/deterministic_commutative_encryption_utility.h, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWFstWD-S5Uxr1KUa4:-MeWIn8uAri0-cs1IzHF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/cc/wfanet/panelmatch/protocol/crypto/deterministic_commutative_encryption_utility.h#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The C++ namespace of protos should be `wfa::panelmatch::something`
</blockquote></details>

Done.
___
*[src/main/proto/wfa/panelmatch/client/eventpreprocessing/preprocess_events.proto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWGBLN9ViUxb0KShTa:-MeWILhO6R-JSUHz0LnQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/proto/wfa/panelmatch/client/eventpreprocessing/preprocess_events.proto#L17)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This should be `wfa.panelmatch.client` please
</blockquote></details>

Done.
___
*[src/main/proto/wfa/panelmatch/protocol/crypto/cryptor.proto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWGFgvDo83z8QqxS0U:-MeWIEdU08z0YZIdwE7E:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/proto/wfa/panelmatch/protocol/crypto/cryptor.proto#L17)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This should be `wfa.panelmatch.client` please
</blockquote></details>

Done.
___
*[src/main/proto/wfa/panelmatch/protocol/exchangesteps/exchangesteps.proto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWGH1N5I2KkpijkY-Z:-MeWIAg6D-gpW8VbGI3T:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/proto/wfa/panelmatch/protocol/exchangesteps/exchangesteps.proto#L17)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This should be `wfa.panelmatch.client` please
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40)* status: all files reviewed, 8 unresolved discussions (waiting on @jmorrrr and @matthewclegg)

___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.h, line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWOmsk-ZYFogqPGb93:-MeWOmsk-ZYFogqPGb94:bp7kwmy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e07ae198e262a79b072c319140f95b7a5376af7d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.h#L29)):*
> ```objc
> PreprocessEvents(
>     const wfa::panelmatch::client::PreprocessEventsRequest& request);
> }  // namespace org::wfanet::panelmatch::client
> ```

Fix please
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWOpnI9igC0hBgey0u:-MeWOpnI9igC0hBgey0v:bp7kwmy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e07ae198e262a79b072c319140f95b7a5376af7d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc#L33)):*
> ```cpp
>   return absl::UnimplementedError("Not implemented");
> }
> }  // namespace org::wfanet::panelmatch::client
> ```

Fix please
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc, line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWOrPR6PotgG0mFb5k:-MeWOrPR6PotgG0mFb5l:bp7kwmy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e07ae198e262a79b072c319140f95b7a5376af7d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc#L29)):*
> ```cpp
>                                                PreprocessEvents);
> }
> }  // namespace org::wfanet::panelmatch::client
> ```

Fix please
___
*[src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWPAv-0i3cRGdppnNg:-MeWPAv-0i3cRGdppnNh:b-qfsubd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e07ae198e262a79b072c319140f95b7a5376af7d/src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L44)):*
> ```cpp
> using ::wfanet::StatusIs;
> 
> using wfa::panelmatch::client::PreprocessEventsRequest;
> ```

Please fully qualify (start with `using ::wfa`). Then remove the empty line above this too
___
*[src/test/cc/wfanet/panelmatch/protocol/crypto/deterministic_commutative_encryption_utility_test.cc, line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWPKB1A3gi4ZYuED4x:-MeWPKB1A3gi4ZYuED4y:b-qfsubd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e07ae198e262a79b072c319140f95b7a5376af7d/src/test/cc/wfanet/panelmatch/protocol/crypto/deterministic_commutative_encryption_utility_test.cc#L46)):*
> ```cpp
> using ::wfanet::panelmatch::protocol::crypto::DeterministicCommutativeReEncrypt;
> 
> using wfa::panelmatch::client::CryptorDecryptRequest;
> ```

Please fully qualify (start with `using ::wfa`). Then remove the empty line above this too
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.h, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWPLpI67ZnEAUShK1d:-MeWPLpI67ZnEAUShK1e:bp7kwmy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e07ae198e262a79b072c319140f95b7a5376af7d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.h#L27)):*
> ```objc
> absl::StatusOr<std::string> PreprocessEventsWrapper(
>     const std::string& serialized_request);
> }  // namespace org::wfanet::panelmatch::client
> ```

Fix please
___
*[src/main/proto/wfa/panelmatch/protocol/crypto/cryptor.proto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWGFgvDo83z8QqxS0U:-MeWP0J195uWPSmM3iBk:b-gzbut9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/proto/wfa/panelmatch/protocol/crypto/cryptor.proto#L17)):*
<details><summary><i>Previously, jmorrrr wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oops sorry, I lied, `wfa.panelmatch.protocol` (I meant to just fix the start of it)
___
*[src/main/proto/wfa/panelmatch/protocol/exchangesteps/exchangesteps.proto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWGH1N5I2KkpijkY-Z:-MeWP7Q93HBJRzN7uvEl:b-gzbut9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/proto/wfa/panelmatch/protocol/exchangesteps/exchangesteps.proto#L17)):*
<details><summary><i>Previously, jmorrrr wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oops sorry, I lied, `wfa.panelmatch.protocol` (I meant to just fix the start of it)

**Review by jmorrrr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40)* status: all files reviewed, 8 unresolved discussions (waiting on @efoxepstein, @jmorrrr, and @matthewclegg)

___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc, line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWOrPR6PotgG0mFb5k:-MeWR3aT4iuOy4oiNdZ4:biev0t0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e07ae198e262a79b072c319140f95b7a5376af7d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Fix please
</blockquote></details>

What do I need to fix here?

**Review by jmorrrr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40)* status: all files reviewed, 8 unresolved discussions (waiting on @efoxepstein, @jmorrrr, and @matthewclegg)

___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.h, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWPLpI67ZnEAUShK1d:-MeWRGN_AZlfIS8smGPa:b-z1x3oo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e07ae198e262a79b072c319140f95b7a5376af7d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.h#L27)):*
> What do I need to fix here?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40)* status: all files reviewed, 7 unresolved discussions (waiting on @efoxepstein, @jmorrrr, and @matthewclegg)

___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc, line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWOrPR6PotgG0mFb5k:-MeWRJumBq5m7MusjQtG:bb80ius) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e07ae198e262a79b072c319140f95b7a5376af7d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc#L29)):*
<details><summary><i>Previously, jmorrrr wrote…</i></summary><blockquote>

What do I need to fix here?
</blockquote></details>

Looks like you already fixed it (`namespace org::wfanet` -> `namespace wfanet`)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40)* status: all files reviewed, 6 unresolved discussions (waiting on @jmorrrr and @matthewclegg)

___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.h, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWPLpI67ZnEAUShK1d:-MeWRUbb2IYiMo_pwbcx:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e07ae198e262a79b072c319140f95b7a5376af7d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.h#L27)):*
<details><summary><i>Previously, jmorrrr wrote…</i></summary><blockquote>

> What do I need to fix here?
</blockquote></details>

Ditto

**Review by jmorrrr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein and @matthewclegg)

___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.h, line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWOmsk-ZYFogqPGb93:-MeWRdp17UOOGgL_TYK7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e07ae198e262a79b072c319140f95b7a5376af7d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.h#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Fix please
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWOpnI9igC0hBgey0u:-MeWRzyn0UZ5RE12Qg6Y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e07ae198e262a79b072c319140f95b7a5376af7d/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events.cc#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Fix please
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_test.cc, line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWPAv-0i3cRGdppnNg:-MeWRnL09wdoNdAWPmVa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e07ae198e262a79b072c319140f95b7a5376af7d/src/test/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_test.cc#L44)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please fully qualify (start with `using ::wfa`). Then remove the empty line above this too
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/protocol/crypto/deterministic_commutative_encryption_utility_test.cc, line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWPKB1A3gi4ZYuED4x:-MeWRkW8-uydT3Bbfdqs:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e07ae198e262a79b072c319140f95b7a5376af7d/src/test/cc/wfanet/panelmatch/protocol/crypto/deterministic_commutative_encryption_utility_test.cc#L46)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please fully qualify (start with `using ::wfa`). Then remove the empty line above this too
</blockquote></details>

Done.
___
*[src/main/proto/wfa/panelmatch/protocol/crypto/cryptor.proto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWGFgvDo83z8QqxS0U:-MeWURce1TpjEiQ0RgTS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/proto/wfa/panelmatch/protocol/crypto/cryptor.proto#L17)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Oops sorry, I lied, `wfa.panelmatch.protocol` (I meant to just fix the start of it)
</blockquote></details>

Done.
___
*[src/main/proto/wfa/panelmatch/protocol/exchangesteps/exchangesteps.proto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeWGH1N5I2KkpijkY-Z:-MeWUJpG3c2IJmK94aJR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/11b6b253cac8a04663503f0acb3fcdc4dadbbc37/src/main/proto/wfa/panelmatch/protocol/exchangesteps/exchangesteps.proto#L17)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Oops sorry, I lied, `wfa.panelmatch.protocol` (I meant to just fix the start of it)
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Review by matthewclegg — APPROVED** [review]

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 21 of 32 files at r1, 1 of 11 files at r2, 3 of 4 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Review by oliver-amzn — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40)* status: all files reviewed, 1 unresolved discussion (waiting on @jmorrrr)

___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc, line 19 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeexDPICdkLCI1v3pQ1:-MeexDPICdkLCI1v3pQ2:blc4ewf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d45edaef7eac27fcd3b79fcac70247065a137923/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc#L19)):*
> ```cpp
> 
> #include "absl/status/statusor.h"
> #include "wfa/panelmatch/client/eventpreprocessing/preprocess_events.pb.h"
> ```

This looks like a bit of a mess now, having one `wfa` and one `wfanet` directory with header includes in all the files. 

I don't think I fully understand why this is necessary. Can someone maybe try to explain in real simple terms?

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn)

___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc, line 19 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeexDPICdkLCI1v3pQ1:-MeezgXH3mk4LDFKU5nP:bub8ov9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d45edaef7eac27fcd3b79fcac70247065a137923/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc#L19)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

This looks like a bit of a mess now, having one `wfa` and one `wfanet` directory with header includes in all the files. 

I don't think I fully understand why this is necessary. Can someone maybe try to explain in real simple terms? 
</blockquote></details>

All of our C++ code is going to be migrated to be under `wfa`: https://github.com/world-federation-of-advertisers/panel-exchange-client/issues/17 (Both in this repo and in others)

We're in a transient state for now, though.

But either way, C++ needs to include what you use (for some reading: https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/WhyIWYU.md)

**Review by oliver-amzn — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmorrrr)

___
*[src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc, line 19 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40#-MeexDPICdkLCI1v3pQ1:-Mef0FrBC4Qn3IGfK-0p:b-t8mzm3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d45edaef7eac27fcd3b79fcac70247065a137923/src/main/cc/wfanet/panelmatch/client/eventpreprocessing/preprocess_events_wrapper.cc#L19)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

All of our C++ code is going to be migrated to be under `wfa`: https://github.com/world-federation-of-advertisers/panel-exchange-client/issues/17 (Both in this repo and in others)

We're in a transient state for now, though.

But either way, C++ needs to include what you use (for some reading: https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/WhyIWYU.md)
</blockquote></details>

Thanks, that makes sense. :ship: it.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmorrrr)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/40)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmorrrr)

**Pull request merged**
