### PR TITLE
Add AWS CA

### PR DESCRIPTION
**Pull request by sandip80**
Adding support to create certificates with AWS private CA.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352)* status: all files reviewed, 6 unresolved discussions (waiting on @duliomatos1 and @sandip80)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V6-i54292-ZPdjtB3:-N8V6-i54292-ZPdjtB4:b8ddyp8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt#L60)):*
> ```Kotlin
>               .digitalSignature(true)
>               .keyEncipherment(true)
>               .keyCertSign(true)
> ```

nonRepudiation should also be true, right @sanjayvas ?
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt` line 97 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V2hBS-RbklyCWxXWt:-N8V2hBS-RbklyCWxXWu:bwl6f9r) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt#L97)):*
> ```Kotlin
>           )
>         )
>         .signingAlgorithm(SigningAlgorithm.SHA256_WITHECDSA)
> ```

can you make this a constant at the top?



_Code quote:_
```Kotlin
org.wfanet.panelmatch.common.certificates.aws
```
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CreateCertificateClient.kt` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V-84a5-MN5sbcRe3A:-N8V-84a5-MN5sbcRe3B:bm3wo3p) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CreateCertificateClient.kt#L15)):*
> ```Kotlin
> // limitations under the License.
> 
> package org.wfanet.panelmatch.common.certificates.aws
> ```

i think you could move this to just package org.wfanet.panelmatch.common.certificates
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CreateCertificateClient.kt` line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V4oDcDZX2CQrX9eDS:-N8V4oDcDZX2CQrX9eDT:b6dtknp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CreateCertificateClient.kt#L22)):*
> ```Kotlin
> import software.amazon.awssdk.services.acmpca.model.IssueCertificateResponse
> 
> interface CreateCertificateClient {
> ```

what do you think about refactoring the existing CreateCertificateClient to extend this interface? https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7d0f9b6f5f1b84af42220a306571587f67e89800/src/main/kotlin/org/wfanet/panelmatch/common/certificates/gcloud/CreateCertificateClient.kt
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/GenerateCsr.kt` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V-IxgDnXXmzVc8Fmq:-N8V-IxgDnXXmzVc8Fmr:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/GenerateCsr.kt#L15)):*
> ```Kotlin
> // limitations under the License.
> 
> package org.wfanet.panelmatch.common.certificates.aws
> ```

ditto
___
*[`src/test/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthorityTest.kt` line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V1oxdDktXPQM0n3VX:-N8V1oxdDktXPQM0n3VY:b-1rpy5c) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/test/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthorityTest.kt#L61)):*
> ```Kotlin
> private val ROOT_X509 by lazy { readCertificate(FIXED_CA_CERT_PEM_FILE) }
> private val ROOT_PUBLIC_KEY by lazy { ROOT_X509.publicKey }
> private val ROOT_PRIVATE_KEY_FILE by lazy { FIXED_CA_CERT_PEM_FILE.resolveSibling("ca.key") }
> ```

instead of using resolveSibling, can you just expose it in common-jvm? https://github.com/world-federation-of-advertisers/common-jvm/blob/06cfa9c95295af4c76d879329d2d1a0823a06e7a/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/TestData.kt#L48

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352)* status: all files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @sandip80, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V6-i54292-ZPdjtB3:-N8VhTxUA9GWAgI8mXHf:buxnjho) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt#L60)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

nonRepudiation should also be true, right @sanjayvas ?
</blockquote></details>

For CA certs, we're using: Digital Signature, Certificate Sign, CRL Sign

For user certs, we're using: Digital Signature, Non Repudiation, Key Encipherment (I believe from OpenSSL defaults)

Note that when I take a look at sample TLS certs (e.g. google.com, github.com), I see the same for CA certs but only Digital Signature on user certs. IIUC, that should be all we need as well.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
it looks like you re-requested my review @sandip80 but I don't see that you resolved any of the comments below or pushed new code.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-:-N8W3ksnEWfTQBx3N23I:bo2j35c)* status: all files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @sandip80, and @stevenwarejones)

**Review by jonmolle — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352)* status: all files reviewed, 7 unresolved discussions (waiting on @duliomatos1, @sandip80, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CreateCertificateClient.kt` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V-84a5-MN5sbcRe3A:-N8VMgG-89DMV-Nis85K:b-5pe0nt) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CreateCertificateClient.kt#L15)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i think you could move this to just package org.wfanet.panelmatch.common.certificates
</blockquote></details>

I think the goal here is to isolate cloud-specific code into their own directories so people who don't want to use the SDKs can avoid the code that contains dependencies.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CreateCertificateClient.kt` line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V4oDcDZX2CQrX9eDS:-N8VO68AEzzPV-Jjsykh:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CreateCertificateClient.kt#L22)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what do you think about refactoring the existing CreateCertificateClient to extend this interface? https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7d0f9b6f5f1b84af42220a306571587f67e89800/src/main/kotlin/org/wfanet/panelmatch/common/certificates/gcloud/CreateCertificateClient.kt
</blockquote></details>

+1
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/GenerateCsr.kt` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8ePMn04pt9Pw1gMWki:-N8ePMn04pt9Pw1gMWkj:b-zezbw4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/GenerateCsr.kt#L24)):*
> ```Kotlin
>  * Generates a PEM format CSR through OpenSSL for a given private key, organization and common name.
>  */
> fun generateCsrFromPrivateKey(key: PrivateKey, organization: String, commonName: String): String {
> ```

I'm a bit confused here. How does this tie back to the AWS private CA? Are we assuming the key here is from the ACM? I'm just looking at the docs here; I'm not sure if/how that maps to their SDK
https://docs.aws.amazon.com/acm/latest/userguide/gs-acm-request-private.html

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352)* status: all files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @sandip80, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/GenerateCsr.kt` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V-IxgDnXXmzVc8Fmq:-N8eudUe7VsLVlvcJBbB:b-tapubu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/GenerateCsr.kt#L15)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

this file doesn't seem aws specific

**Review by sandip80 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352)* status: 7 of 10 files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @jonmolle, @sandip80, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt` line 97 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V2hBS-RbklyCWxXWt:-N9I0V5N1BFDR24aHvzz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt#L97)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you make this a constant at the top?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CreateCertificateClient.kt` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V-84a5-MN5sbcRe3A:-N9I0ZmX0VslupPzhCZg:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CreateCertificateClient.kt#L15)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

I think the goal here is to isolate cloud-specific code into their own directories so people who don't want to use the SDKs can avoid the code that contains dependencies.
</blockquote></details>

+1
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CreateCertificateClient.kt` line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V4oDcDZX2CQrX9eDS:-N9I-uF841aFqBXaVR_3:b-qfumsj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CreateCertificateClient.kt#L22)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

+1
</blockquote></details>

GCP and AWS create certificate client interfaces are completely different. They use different APIs, request/response objects. I don't think they can be refactored into 1 interface.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/GenerateCsr.kt` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V-IxgDnXXmzVc8Fmq:-N9I0cOvDLZf7M2kWAym:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/GenerateCsr.kt#L15)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this file doesn't seem aws specific
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/GenerateCsr.kt` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8ePMn04pt9Pw1gMWki:-N9I0hsOCQTVp9Z--FUf:be8bghf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/GenerateCsr.kt#L24)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

I'm a bit confused here. How does this tie back to the AWS private CA? Are we assuming the key here is from the ACM? I'm just looking at the docs here; I'm not sure if/how that maps to their SDK
https://docs.aws.amazon.com/acm/latest/userguide/gs-acm-request-private.html
</blockquote></details>

AWS private CA issues the certificate with the CSR (containing the SKI for a keypair generated with PEC security provider) provided by PEC here. The doc you mentioned is for SSL certificates only (and they only support RSA2048).

**Review by sandip80 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352)* status: 7 of 10 files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @jonmolle, @sandip80, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V6-i54292-ZPdjtB3:-N9I5moe4GCZKfmzHWYk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

For CA certs, we're using: Digital Signature, Certificate Sign, CRL Sign

For user certs, we're using: Digital Signature, Non Repudiation, Key Encipherment (I believe from OpenSSL defaults)

Note that when I take a look at sample TLS certs (e.g. google.com, github.com), I see the same for CA certs but only Digital Signature on user certs. IIUC, that should be all we need as well.
</blockquote></details>

Done.

**Comment by sandip80** [comment]
*[`src/test/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthorityTest.kt` line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V1oxdDktXPQM0n3VX:-N9I7U0-3l4AatOSfmh_:b-2ckk42) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/test/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthorityTest.kt#L61)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

instead of using resolveSibling, can you just expose it in common-jvm? https://github.com/world-federation-of-advertisers/common-jvm/blob/06cfa9c95295af4c76d879329d2d1a0823a06e7a/src/main/kotlin/org/wfanet/measurement/common/crypto/testing/TestData.kt#L48
</blockquote></details>

https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/152 Please take a look.

**Comment by sandip80** [comment]
Apologies as I get used to this product :)

**Review by jonmolle — APPROVED** [review]
LGTM barring the lint and merge issues, but please give me a ping when those are resolved if you don't mind. I don't want to block on that, though, given how Reviewable works.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-:-N9JUwvT47STCZyypB-B:by1avfc)* status: 7 of 10 files reviewed, 5 unresolved discussions (waiting on @duliomatos1 and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/GenerateCsr.kt` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8ePMn04pt9Pw1gMWki:-N9JUWw_7ZJaWqfw_3LZ:bk3mcpa) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/GenerateCsr.kt#L24)):*
<details><summary><i>Previously, sandip80 (Sandip Samantaray) wrote…</i></summary><blockquote>

AWS private CA issues the certificate with the CSR (containing the SKI for a keypair generated with PEC security provider) provided by PEC here. The doc you mentioned is for SSL certificates only (and they only support RSA2048).
</blockquote></details>

I reread this and see what you mean. I was concerned there was no chain of trust back to the root cert using this, but looking again it seems fine. Thanks for the clarification.

**Review by jonmolle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352)* status: 7 of 10 files reviewed, 5 unresolved discussions (waiting on @duliomatos1 and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CreateCertificateClient.kt` line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V4oDcDZX2CQrX9eDS:-N9XeewWBb2-7ph5zfrx:boslfmv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CreateCertificateClient.kt#L22)):*
<details><summary><i>Previously, sandip80 (Sandip Samantaray) wrote…</i></summary><blockquote>

GCP and AWS create certificate client interfaces are completely different. They use different APIs, request/response objects. I don't think they can be refactored into 1 interface.
</blockquote></details>

That makes sense; they're both hidden by their common CA implementation, so I don't see any problems.

**Comment by sandip80** [comment]
*[`src/test/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthorityTest.kt` line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V1oxdDktXPQM0n3VX:-N9Y-beo3iELUSBBjhc-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/test/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthorityTest.kt#L61)):*
<details><summary><i>Previously, sandip80 (Sandip Samantaray) wrote…</i></summary><blockquote>

https://reviewable.io/reviews/world-federation-of-advertisers/common-jvm/152 Please take a look.
</blockquote></details>

Done.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V6-i54292-ZPdjtB3:-N9YVDUo8lqqgIuH5UML:bjnhgx7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt#L60)):*
<details><summary><i>Previously, sandip80 (Sandip Samantaray) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Aren't these the leaf certificates you are creating here? (eg the user cert and not the root cert)? 

Looks like we might have the same issue on the existing Google CA too -- https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7d0f9b6f5f1b84af42220a306571587f67e89800/src/main/kotlin/org/wfanet/panelmatch/common/certificates/gcloud/CertificateAuthority.kt#L51

**Review by jonmolle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V6-i54292-ZPdjtB3:-N9c2JFQ7YtoOr8Zic_3:b-z1bfbg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt#L60)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Aren't these the leaf certificates you are creating here? (eg the user cert and not the root cert)? 

Looks like we might have the same issue on the existing Google CA too -- https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7d0f9b6f5f1b84af42220a306571587f67e89800/src/main/kotlin/org/wfanet/panelmatch/common/certificates/gcloud/CertificateAuthority.kt#L51
</blockquote></details>

That's correct. These are supposed to be one-exchange keys

**Comment by sandip80** [comment]
*[`src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V6-i54292-ZPdjtB3:-N9cvCbG4nuqjUlirqgJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/main/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthority.kt#L60)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

That's correct. These are supposed to be one-exchange keys
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, 1 of 1 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Comment by sandip80** [comment]
*[`src/test/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthorityTest.kt` line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V1oxdDktXPQM0n3VX:-N9hqMZcCAj767kC9eH4:brxw1cq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/test/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthorityTest.kt#L61)):*
<details><summary><i>Previously, sandip80 (Sandip Samantaray) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@stevenwarejones I am reverting this change for now. This is a breaking change which will require a lot of other changes to PEC code which might be out of context for this CR (common-jvm & cmm code has been refactored a lot, need to do some refactoring on PEC side to upgrade the dependencies). I think this should be separate CR.

**Comment by sandip80** [comment]
*[`src/test/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthorityTest.kt` line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/352#-N8V1oxdDktXPQM0n3VX:-N9hvr3I6rx8N__4zvI5:b-a42k4c) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/920f2725d4df36551904442d02af16044098e98c/src/test/kotlin/org/wfanet/panelmatch/common/certificates/aws/CertificateAuthorityTest.kt#L61)):*
<details><summary><i>Previously, sandip80 (Sandip Samantaray) wrote…</i></summary><blockquote>

@stevenwarejones I am reverting this change for now. This is a breaking change which will require a lot of other changes to PEC code which might be out of context for this CR (common-jvm & cmm code has been refactored a lot, need to do some refactoring on PEC side to upgrade the dependencies). I think this should be separate CR.
</blockquote></details>

Separate PR: https://github.com/world-federation-of-advertisers/panel-exchange-client/pull/355

**Pull request merged**
