### PR TITLE
Add support for padding queries in PSM query evaluation.

### PR DESCRIPTION
**Pull request by efoxepstein**
https://rally1.rallydev.com/#/?detail=/task/611318399997&fdp=true

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 26 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254)* status: 26 of 29 files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExecutePrivateMembershipQueries.kt, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-Msg4WTG74ZpS8ygoq3c:-Msg4WTH1uZxuE6xWt5P:b-7ff15u) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/51bdd2bd2ffa7bfad04193f466296f73e2317e29/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExecutePrivateMembershipQueries.kt#L70)):*
> ```Kotlin
> private const val PADDING_NONCE_SIZE_BYTES = 16
> 
> private fun generatePaddingNonce(): PaddingNonce {
> ```

i think we need this for salts too. Move this to common/crypto ?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/JniQueryEvaluatorContext.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-Msg3_5DEIhBtESWC-KC:-Msg3_5DEIhBtESWC-KD:b-rtt3bf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/51bdd2bd2ffa7bfad04193f466296f73e2317e29/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/JniQueryEvaluatorContext.kt#L31)):*
> ```Kotlin
>       shardParameters {
>         numberOfShards = shardCount
>         numberOfBucketsPerShard = bucketsPerShardCount + 1 // To account for padding queries
> ```

why are you incrementing it in 2 different places?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/BUILD.bazel, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-Msg4rlQ5lXOXsNkbaQ-:-Msg4rlQ5lXOXsNkbaQ0:bfp0iom) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/51bdd2bd2ffa7bfad04193f466296f73e2317e29/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/BUILD.bazel#L62)):*
> ```Starlark
>     size = "medium",
>     srcs = ["JniQueryEvaluatorTest.kt"],
>     shard_count = 2,
> ```

i'd prefer this in the test itself vs coming from here

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254)* status: 22 of 30 files reviewed, 3 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExecutePrivateMembershipQueries.kt, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-Msg4WTG74ZpS8ygoq3c:-MsgHHRVAnHqEOnfPN_j:b786rwj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/51bdd2bd2ffa7bfad04193f466296f73e2317e29/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExecutePrivateMembershipQueries.kt#L70)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i think we need this for salts too. Move this to common/crypto ?
</blockquote></details>

Salts probably won't use a `PaddingNonce` type, right? I've extracted `generateSecureByteString()` as a helper function.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/JniQueryEvaluatorContext.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-Msg3_5DEIhBtESWC-KC:-MsgAc-uA5KKh9daL6JR:bzcydy3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/51bdd2bd2ffa7bfad04193f466296f73e2317e29/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/JniQueryEvaluatorContext.kt#L31)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why are you incrementing it in 2 different places?
</blockquote></details>

This is an excellent question. Fixed, PTAL
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/BUILD.bazel, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-Msg4rlQ5lXOXsNkbaQ-:-MsgALp15MKNzzL96f9h:byp8gwf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/51bdd2bd2ffa7bfad04193f466296f73e2317e29/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/BUILD.bazel#L62)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i'd prefer this in the test itself vs coming from here
</blockquote></details>

This is a bazel parameter telling it to run the partition the test cases between two separate processes -- it's unrelated to shards within PSM.

Or am I misunderstanding? Is there a way to specify how many processes should run the test as like a JUnit annotation?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 29 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254)* status: 27 of 30 files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteSingleBlob.kt, line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-MsjfxqC7XQ7fxFmlsc3:-MsjfxqC7XQ7fxFmlsc4:b9rabuh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0567396373dc65d724b14e306bed8db7d3616612/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteSingleBlob.kt#L1)):*
> ```Kotlin
> package org.wfanet.panelmatch.client.privatemembership
> ```

2 things
1. Package should go below copyright
2. Is this the write package? common.beam feels like a better place. That also probably applies to the existing WriteShardedData as well.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteSingleBlob.kt, line 35 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-MsjegTeAKZVX9hsZ19-:-MsjegTeAKZVX9hsZ190:b-q1qwt1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0567396373dc65d724b14e306bed8db7d3616612/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteSingleBlob.kt#L35)):*
> ```Kotlin
> 
> /** Writes a single input message into a blob. */
> class WriteSingleBlob<T : Message>(
> ```

today, for the `query-to-ids-map` we are writing a manifest file. That, too, could be done with a single blob. Do you want to add a todo for that or add that in quickly?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteSingleBlob.kt, line 81 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-MsjhUW17SRLBODyU2PT:-MsjhUW17SRLBODyU2PU:bn747q2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0567396373dc65d724b14e306bed8db7d3616612/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteSingleBlob.kt#L81)):*
> ```Kotlin
>     val storageClient = storageFactory.build()
>     runBlocking(Dispatchers.IO) {
>       storageClient.createOrReplaceBlob(blobKey, context.element().toByteString())
> ```

asFlow?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/BUILD.bazel, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-Msg4rlQ5lXOXsNkbaQ-:-MsjiVT1BZhtOBM9fGEA:bnei7dd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/51bdd2bd2ffa7bfad04193f466296f73e2317e29/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/BUILD.bazel#L62)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is a bazel parameter telling it to run the partition the test cases between two separate processes -- it's unrelated to shards within PSM.

Or am I misunderstanding? Is there a way to specify how many processes should run the test as like a JUnit annotation?
</blockquote></details>

no, I was the one misunderstanding :)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254)* status: 27 of 30 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteSingleBlob.kt, line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-MsjfxqC7XQ7fxFmlsc3:-MskQgIU4WHrLgzDSV3x:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0567396373dc65d724b14e306bed8db7d3616612/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteSingleBlob.kt#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

2 things
1. Package should go below copyright
2. Is this the write package? common.beam feels like a better place. That also probably applies to the existing WriteShardedData as well.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteSingleBlob.kt, line 35 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-MsjegTeAKZVX9hsZ19-:-MskRL-2EE71bC_GUFZE:b5e4u4h) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0567396373dc65d724b14e306bed8db7d3616612/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteSingleBlob.kt#L35)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

today, for the `query-to-ids-map` we are writing a manifest file. That, too, could be done with a single blob. Do you want to add a todo for that or add that in quickly?
</blockquote></details>

Done, added TODO
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteSingleBlob.kt, line 81 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-MsjhUW17SRLBODyU2PT:-MskU0dN5FjhRHA-aoEJ:bb76mu4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0567396373dc65d724b14e306bed8db7d3616612/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteSingleBlob.kt#L81)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

asFlow?
</blockquote></details>

Why?

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 37 of 37 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254)* status: 54 of 55 files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt, line 83 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-MskgU9F38dULL68w-eu:-MskgU9G9laMv8tumNJP:b-5vq7tn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d08a0f137e40522ce310dfe79443da9111c72fb9/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt#L83)):*
> ```Kotlin
>   shardParameters =
>     shardParameters {
>       numberOfBucketsPerShard = BUCKETS_PER_SHARD_COUNT + 1
> ```

can you just use JniQueryEvaluatorContext?
___
*[src/test/kotlin/org/wfanet/panelmatch/integration/config/full_with_preprocessing.textproto, line 349 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-MskhBvV7Pvi09U3Mr0U:-MskhBvV7Pvi09U3Mr0V:b-tx5lom) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d08a0f137e40522ce310dfe79443da9111c72fb9/src/test/kotlin/org/wfanet/panelmatch/integration/config/full_with_preprocessing.textproto#L349)):*
> ```
> 
>   generate_serialized_rlwe_key_pair_step {
>     # unserialized_parameters:
> ```

is there an easy way to factor out the common parts of both these files?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteSingleBlob.kt, line 81 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-MsjhUW17SRLBODyU2PT:-MskgqOQ6KkmCF9lfeW1:be2dd1t) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0567396373dc65d724b14e306bed8db7d3616612/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteSingleBlob.kt#L81)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Doesn't writing it as a flow give more flexibility to the writer to choose how to write it?

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254)* status: 54 of 55 files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt, line 267 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-MskhsQ86PuuMByp59Xb:-MskhsQ86PuuMByp59Xc:bvsri9s) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d08a0f137e40522ce310dfe79443da9111c72fb9/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt#L267)):*
> ```Kotlin
>   }
> 
>   private suspend fun ExchangeContext.apacheBeamTaskFor(
> ```

feels like this function belongs somewhere else so other mappers could use it.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254)* status: 54 of 55 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt, line 267 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-MskhsQ86PuuMByp59Xb:-MskoZ7l4tJ_Inbr6ASe:bod7nki) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d08a0f137e40522ce310dfe79443da9111c72fb9/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt#L267)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

feels like this function belongs somewhere else so other mappers could use it.
</blockquote></details>

Why wouldn't other mappers just subclass `ProductionExchangeTaskMapper`?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt, line 83 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-MskgU9F38dULL68w-eu:-MskogtUCmNHAa9fEEYy:b-p8e60z) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d08a0f137e40522ce310dfe79443da9111c72fb9/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt#L83)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you just use JniQueryEvaluatorContext?
</blockquote></details>

They're slightly different for now. Can I leave as is for now and then maybe eventually unify?
___
*[src/test/kotlin/org/wfanet/panelmatch/integration/config/full_with_preprocessing.textproto, line 349 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-MskhBvV7Pvi09U3Mr0U:-MskiL8XErByAbxvgg26:b24w9ia) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d08a0f137e40522ce310dfe79443da9111c72fb9/src/test/kotlin/org/wfanet/panelmatch/integration/config/full_with_preprocessing.textproto#L349)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is there an easy way to factor out the common parts of both these files?
</blockquote></details>

I'd prefer not to, I think it's helpful to be explicit with these
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteSingleBlob.kt, line 81 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/254#-MsjhUW17SRLBODyU2PT:-Mski5bWDX9qyp1lOnhL:b-ctbm4o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0567396373dc65d724b14e306bed8db7d3616612/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/WriteSingleBlob.kt#L81)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Doesn't writing it as a flow give more flexibility to the writer to choose how to write it?
</blockquote></details>

Why would it? It's converted to a flow internally in `createOrReplaceBlob`

**Pull request merged**
