### PR TITLE
match up inputs and outputs from dbe, create queries, and decrypt queries

### PR DESCRIPTION
**Pull request by stevenwarejones**
- Adds a step to automatically generate ids for joinkeys (current plan is to make another PR where that ID is basically the same as the singleBlindedKey)
- Line up inputs/outputs of DBE, create queries, and decrypt queries

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166)* status: 0 of 49 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-Mlwrz838UtbyOjSaeUU:-Mlwrz84Dpl0B-VcuCPI:b-gg86sb) (no related file):*
Do you mind rebasing this before I review it? Thanks

---

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 33 of 49 files at r1, 16 of 16 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166)* status: all files reviewed, 12 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptPrivateMembershipResultsTask.kt, line 106 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-MlzqkMx0GhCTydnJKnu:-MlzqkMx0GhCTydnJKnv:b-t3h7iu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptPrivateMembershipResultsTask.kt#L106)):*
> ```Kotlin
>       )
>     require(
>       keyedDecryptedEventDataSetFileSpec.shardCount == outputs.keyedDecryptedEventDataSetFileCount
> ```

I don't think we need these `require`s -- this is part of the contract for `ShardedFileName`. Adding them actually makes it _less_ clear to me because it makes me doubt that ShardedFileName does what I think it does. WDYT?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt, line 194 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-Mlzr61k6C4qQayYE52G:-Mlzr61k6C4qQayYE52H:b-c97d5r) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L194)):*
> ```Kotlin
>       .keyBy { it.lookupKeyAndId.joinKeyIdentifier }
>       /** We can't strict join here in case one of the queries was dropped. */
>       .join(keyedHashedJoinKeyAndIds, name = "Join FullUnencryptedQuery+HashedJoinKeys") {
> ```

Feel free to just add a TODO here but we should probably move this into a `DoFn` so we can export some metrics about it
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt, line 196 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-MlzrGzh2rb-AB3pCdox:-MlzrGzh2rb-AB3pCdoy:b-doyca5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L196)):*
> ```Kotlin
>       .join(keyedHashedJoinKeyAndIds, name = "Join FullUnencryptedQuery+HashedJoinKeys") {
>         key: JoinKeyIdentifier,
>         fullUnencryptedQueriesList: Iterable<FullUnencryptedQuery>,
> ```

`List` is confusing, given that it's an iterable.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt, line 198 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-MlzrD2U5WK6xx_TX97G:-MlzrD2U5WK6xx_TX97H:bs0r81q) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L198)):*
> ```Kotlin
>         fullUnencryptedQueriesList: Iterable<FullUnencryptedQuery>,
>         hashedJoinKeyAndIdsList: Iterable<JoinKeyAndId> ->
>         if ((fullUnencryptedQueriesList.count() > 0) and (hashedJoinKeyAndIdsList.count() > 0)) {
> ```

Probably want to actually turn it into a list above this (so you don't iterate it multiple times) and then just check `.isNotEmpty()`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt, line 61 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-Mlzrsq18mOjsw3MZyCG:-Mlzrsq18mOjsw3MZyCH:b7vf87c) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt#L61)):*
> ```Kotlin
>     )
>   }
>   private val hashedJoinKeysAndIds by lazy {
> ```

What do you think about having a specific term for this besides  "Hashed Join Keys"?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsTest.kt, line 62 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-MlzsRO8C14_SCudS58b:-MlzsRO98dkMh--xBa4Z:b-5b7u9y) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsTest.kt#L62)):*
> ```Kotlin
> private val LOOKUP_KEYS: List<Triple<Int, String, String>> =
>   listOf(
>     Triple(1, "some lookup key 1", "some hashed joinkey 1"),
> ```

Maybe just make a test helper `queryIdAndJoinKeysOf` so we can use the actual proto here instead of using Triples?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt, line 83 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-Mlzsk8v0onFUyObr5b5:-Mlzsk8v0onFUyObr5b6:bn5m3t0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt#L83)):*
> ```Kotlin
>     lookupKey: String,
>     bucket: Int
>   ) : this(shardIdOf(shard), joinKeyOf(hashedJoinKey), joinKeyOf(lookupKey), bucketIdOf(bucket))
> ```

Should we have a `hashedJoinKeyOf` and a different type for it? It feels a little type-unsafe to use `JoinKey` to mean both a lookup key and an encrypted, hashed lookup key
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt, line 136 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-Mlzt7fHC4ANXjuVMJJ-:-Mlzt7fHC4ANXjuVMJJ0:b-64jkfe) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt#L136)):*
> ```Kotlin
>         val joinkeyIndex = Random.nextInt(JOINKEY_UNIVERSE_SIZE)
>         yield(
>           joinKeyAndId {
> ```

Can we use a helper `joinKeyAndIdOf`?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt, line 144 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-MlztDor629O0NwC6iyn:-MlztDor629O0NwC6iyo:b-urll93) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt#L144)):*
> ```Kotlin
>       }
>     }
>   val hashedJoinKeys: PCollection<JoinKeyAndId> =
> ```

I think I said this in another comment but it makes me a little uncomfortable to use the same type for this and the previous pcollection
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt, line 150 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-MlztCHE-fxrRcF8v-RT:-MlztCHE-fxrRcF8v-RU:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt#L150)):*
> ```Kotlin
>         val joinkeyIndex = Random.nextInt(JOINKEY_UNIVERSE_SIZE)
>         yield(
>           joinKeyAndId {
> ```

Ditto
___
*[src/main/proto/wfa/panelmatch/client/privatemembership/decrypt_event_data.proto, line 55 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-MlztckZ285oGAkMn1gR:-MlztckZ285oGAkMn1gS:b32ve7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/proto/wfa/panelmatch/client/privatemembership/decrypt_event_data.proto#L55)):*
> ```protobuf
>   bytes serialized_private_key = 3;
>   repeated EncryptedQueryResult encrypted_query_results = 4;
>   wfa.panelmatch.client.exchangetasks.JoinKey lookup_key = 6;
> ```

5?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt, line 80 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-MlztuQlDQRhdcTzegQ6:-MlztuQlDQRhdcTzegQ7:b-fq3m4y) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt#L80)):*
> ```Kotlin
>     mockStorage.createBlob(
>       "double-blinded-keys",
>       flowOf(joinKeyAndIdCollection { joinKeysAndIds += doubleBlindedKeysAndIds }.toByteString())
> ```

There's a `createBlob` helper that takes in a ByteString instead of a Flow for the second argument. Can you use that instead here and above?

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166)* status: 36 of 50 files reviewed, 12 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptPrivateMembershipResultsTask.kt, line 106 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-MlzqkMx0GhCTydnJKnu:-Mm-2IZR-7HysfM-iJPa:b-366ci4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptPrivateMembershipResultsTask.kt#L106)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I don't think we need these `require`s -- this is part of the contract for `ShardedFileName`. Adding them actually makes it _less_ clear to me because it makes me doubt that ShardedFileName does what I think it does. WDYT?
</blockquote></details>

I'm fine either way. Some of them were removed. Others remained. Deleted them all.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt, line 194 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-Mlzr61k6C4qQayYE52G:-Mm-2gcTCatrbpNZGqLx:b491tyo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L194)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Feel free to just add a TODO here but we should probably move this into a `DoFn` so we can export some metrics about it
</blockquote></details>

added TODO. I'm not sure what metrics you are referring to that we couldn't get elsewhere from the pipeline though.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt, line 196 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-MlzrGzh2rb-AB3pCdox:-Mm-3A8MDksqnXcz0nB4:b28g9tq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L196)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`List` is confusing, given that it's an iterable.
</blockquote></details>

change to `fullUnencryptedQueriesIterable`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt, line 198 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-MlzrD2U5WK6xx_TX97G:-Mm-3V0J0pvMQzhPwT7Z:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L198)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Probably want to actually turn it into a list above this (so you don't iterate it multiple times) and then just check `.isNotEmpty()`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt, line 61 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-Mlzrsq18mOjsw3MZyCG:-Mm-3efV78lyXgb15UDX:bhldhpt) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt#L61)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What do you think about having a specific term for this besides  "Hashed Join Keys"?
</blockquote></details>

what did you have in mind?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsTest.kt, line 62 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-MlzsRO8C14_SCudS58b:-Mm-4__J4KPNlKja7AJM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsTest.kt#L62)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe just make a test helper `queryIdAndJoinKeysOf` so we can use the actual proto here instead of using Triples?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt, line 83 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-Mlzsk8v0onFUyObr5b5:-Mm-4dAWEclIByXP7Gil:b-7be9u5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt#L83)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Should we have a `hashedJoinKeyOf` and a different type for it? It feels a little type-unsafe to use `JoinKey` to mean both a lookup key and an encrypted, hashed lookup key
</blockquote></details>

does it? I think they are all just derived from a raw join key that's been hashed, encrypted, decrypted, etc, etc. Added a couple TODOs for now to think about it.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt, line 136 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-Mlzt7fHC4ANXjuVMJJ-:-Mm-5PK-7HFuaCg7yiKS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt#L136)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can we use a helper `joinKeyAndIdOf`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt, line 144 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-MlztDor629O0NwC6iyn:-Mm-5R42CftJQiEFr0NN:b9035gu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt#L144)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think I said this in another comment but it makes me a little uncomfortable to use the same type for this and the previous pcollection
</blockquote></details>

i'll add a TODO for now.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt, line 150 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-MlztCHE-fxrRcF8v-RT:-Mm-5XBR5tVDumZVtCU8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/deploy/gcloud/DataflowRoundTripTestMain.kt#L150)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/proto/wfa/panelmatch/client/privatemembership/decrypt_event_data.proto, line 55 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-MlztckZ285oGAkMn1gR:-Mm-5bLY3HwSPnPtwgDP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/proto/wfa/panelmatch/client/privatemembership/decrypt_event_data.proto#L55)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

5?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt, line 80 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-MlztuQlDQRhdcTzegQ6:-Mm-6Cgq40Bwj_fJpyer:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt#L80)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

There's a `createBlob` helper that takes in a ByteString instead of a Flow for the second argument. Can you use that instead here and above?
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt, line 194 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-Mlzr61k6C4qQayYE52G:-Mm-Khb_1MNJQCQKTwqj:b-dacb0t) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L194)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

added TODO. I'm not sure what metrics you are referring to that we couldn't get elsewhere from the pipeline though.
</blockquote></details>

I'd be curious about how often each input is empty -- but I guess you're right, that metric is likely available elsewhere.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt, line 204 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-Mm-Kv7tEL5KAm4fDqkv:-Mm-Kv7tEL5KAm4fDqkw:b4j8zpl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4e950b9eb98f371fc2e246e540da72a9cf53cd11/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L204)):*
> ```Kotlin
> 
>           val fullUnencryptedQuery =
>             requireNotNull(fullUnencryptedQueriesList.toList().singleOrNull()) {
> ```

Redundant `toList` calls (4x)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt, line 204 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-Mm-L_Aw2yyl2p75RSQj:-Mm-L_Aw2yyl2p75RSQk:b-rgxb2x) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4e950b9eb98f371fc2e246e540da72a9cf53cd11/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L204)):*
> ```Kotlin
> 
>           val fullUnencryptedQuery =
>             requireNotNull(fullUnencryptedQueriesList.toList().singleOrNull()) {
> ```

It seems like we have this pattern a few times in the codebase where we want the following behavior:

* If an Iterable is empty, we want to know but not throw
* If an Iterable has a single item, we want that item
* If an Iterable has more than 1 item, we want to throw

How about this helper function:

```
inline fun <T> Iterable<T>.singleOrNullIfEmpty(): T? {
  if (!iterator().hasNext()) return null
  return single()
}
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt, line 61 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-Mlzrsq18mOjsw3MZyCG:-Mm-Mux31FaTUxqririd:bo5p05v) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractCreateQueriesTest.kt#L61)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what did you have in mind?
</blockquote></details>

No idea. Nevermind.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt, line 83 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-Mlzsk8v0onFUyObr5b5:-Mm-NLIq57CbFqsWG-nR:b-hfghm4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2684df535c41c22a545a62829b1b2cc7f271932d/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt#L83)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

does it? I think they are all just derived from a raw join key that's been hashed, encrypted, decrypted, etc, etc. Added a couple TODOs for now to think about it.
</blockquote></details>

Sounds good

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166)* status: 49 of 51 files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt, line 204 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-Mm-Kv7tEL5KAm4fDqkv:-Mm-REQB83rkxYYdOrug:b3v18r4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4e950b9eb98f371fc2e246e540da72a9cf53cd11/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L204)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Redundant `toList` calls (4x)
</blockquote></details>

yuk. done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt, line 204 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166#-Mm-L_Aw2yyl2p75RSQj:-Mm-SlBi1iGnrZWbklqF:b3tj0ik) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/4e950b9eb98f371fc2e246e540da72a9cf53cd11/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L204)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It seems like we have this pattern a few times in the codebase where we want the following behavior:

* If an Iterable is empty, we want to know but not throw
* If an Iterable has a single item, we want that item
* If an Iterable has more than 1 item, we want to throw

How about this helper function:

```
inline fun <T> Iterable<T>.singleOrNullIfEmpty(): T? {
  if (!iterator().hasNext()) return null
  return single()
}
```
</blockquote></details>

i'm not sure if that really simplifies things.. i'll think about it and one of us can add it in a follow-up

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/166)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Pull request merged**
