### PR TITLE
add cpp oblivious query stubs

### PR DESCRIPTION
**Pull request by stevenwarejones**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56)* status: all files reviewed, 12 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/batchlookup/oblivious_query.h, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9vXd13Eu0KPg9LceM:-Mf9vXd2Dy7lwvqcECcl:b-3joaxd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/main/cc/wfa/panelmatch/client/batchlookup/oblivious_query.h#L26)):*
> ```objc
> 
> namespace wfa::panelmatch::client::batchlookup {
> absl::StatusOr<wfa::panelmatch::client::batchlookup::GenerateKeysResponse>
> ```

These protos are in the same namespace as this code so you can just write `GenerateKeysResponse` and `GenerateKeysRequest` (without the `wfa::blah::blah::blah`)
___
*[src/main/cc/wfa/panelmatch/client/batchlookup/oblivious_query.cc, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9vjPT6C8ieym505o2:-Mf9vjPT6C8ieym505o3:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/main/cc/wfa/panelmatch/client/batchlookup/oblivious_query.cc#L28)):*
> ```cpp
> namespace wfa::panelmatch::client::batchlookup {
> 
> absl::StatusOr<wfa::panelmatch::client::batchlookup::GenerateKeysResponse>
> ```

Ditto
___
*[src/main/cc/wfa/panelmatch/client/batchlookup/oblivious_query_wrapper.cc, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9vmITBLCKlui58pqh:-Mf9vmIU4PWJrUwnf4w7:b1m8crl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/main/cc/wfa/panelmatch/client/batchlookup/oblivious_query_wrapper.cc#L27)):*
> ```cpp
> absl::StatusOr<std::string> GenerateKeysWrapper(
>     const std::string& serialized_request) {
>   return wfa::JniWrap(serialized_request, GenerateKeys);
> ```

Since you're in namespace `wfa`, you shouldn't need to prefix `JniWrap` with `wfa::`
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9xX6P8wKjO_o0bGnT:-Mf9xX6P8wKjO_o0bGnU:bzcloqw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L35)):*
> ```cpp
> namespace wfa::panelmatch::client::batchlookup {
> namespace {
> using ::testing::ContainerEq;
> ```

I think all of these `using ::testing::Foo` things are unused
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9vvc5AnC5GIUM4iTx:-Mf9vvc5AnC5GIUM4iTy:b-dn4oed) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L40)):*
> ```cpp
> using ::testing::Not;
> using ::testing::Pointwise;
> using ::wfa::panelmatch::client::batchlookup::DecryptQueriesRequest;
> ```

I don't think these using-decls are necessary (or do anything)
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9xUEf8FDwzP0r7Zgk:-Mf9xUEf8FDwzP0r7Zgl:b-z4tfd7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L52)):*
> ```cpp
>               StatusIs(absl::StatusCode::kUnimplemented, ""));
> 
>   std::string validSerializedRequest;
> ```

snake_case_please
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9xTn1-9y7LXpsIxSr:-Mf9xTn1-9y7LXpsIxSs:b-z4tfd7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L58)):*
> ```cpp
>               StatusIs(absl::StatusCode::kUnimplemented, ""));
> 
>   std::string invalidSerializedRequest = "some-invalid-serialized-request";
> ```

snake_case_please
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9w9Jk8cN0n1X66Y4y:-Mf9w9Jk8cN0n1X66Y4z:b-z4tfd7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L78)):*
> ```cpp
>               StatusIs(absl::StatusCode::kUnimplemented, ""));
> 
>   std::string validSerializedRequest;
> ```

snake_case_please
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9wBc46kVVsKK9e0Ra:-Mf9wBc46kVVsKK9e0Rb:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L84)):*
> ```cpp
>               StatusIs(absl::StatusCode::kUnimplemented, ""));
> 
>   std::string invalidSerializedRequest = "some-invalid-serialized-request";
> ```

Ditto
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 94 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9wkCKEwL6ZDjKTwUI:-Mf9wkCKEwL6ZDjKTwUJ:bg0jciy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L94)):*
> ```cpp
>   std::string some_public_key = "some-public-key";
>   std::string some_private_key = "some-private-key";
>   test_request.set_public_key(some_public_key);
> ```

I think this might be cleaner by just inlining all the strings: `some_proto.set_foo("some string literal")` -- the local variables are used once each and nearly double the length of the test body
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 102 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9xPj5BLPUqc4PURDK:-Mf9wDX4EIKLHBO-9tTW:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L102)):*
> ```cpp
>               StatusIs(absl::StatusCode::kUnimplemented, ""));
> 
>   std::string validSerializedRequest;
> ```

Ditto
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 108 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9wED4A-hvIOyLE2kl:-Mf9wED4A-hvIOyLE2km:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L108)):*
> ```cpp
>               StatusIs(absl::StatusCode::kUnimplemented, ""));
> 
>   std::string invalidSerializedRequest = "some-invalid-serialized-request";
> ```

Ditto

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56)* status: all files reviewed, 12 unresolved discussions (waiting on @stevenwarejones)

___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 94 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9wkCKEwL6ZDjKTwUI:-Mf9z_efBlKY9hl2DkjA:bfayuvf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L94)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think this might be cleaner by just inlining all the strings: `some_proto.set_foo("some string literal")` -- the local variables are used once each and nearly double the length of the test body
</blockquote></details>

Some good reading: https://abseil.io/tips/161

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56)* status: all files reviewed, 12 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/cc/wfa/panelmatch/client/batchlookup/oblivious_query.h, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9vXd13Eu0KPg9LceM:-MfES0x33HyeJJQRuv37:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/main/cc/wfa/panelmatch/client/batchlookup/oblivious_query.h#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

These protos are in the same namespace as this code so you can just write `GenerateKeysResponse` and `GenerateKeysRequest` (without the `wfa::blah::blah::blah`)
</blockquote></details>

done
___
*[src/main/cc/wfa/panelmatch/client/batchlookup/oblivious_query.cc, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9vjPT6C8ieym505o2:-MfES6vF4MteZks_ooMM:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/main/cc/wfa/panelmatch/client/batchlookup/oblivious_query.cc#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

done
___
*[src/main/cc/wfa/panelmatch/client/batchlookup/oblivious_query_wrapper.cc, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9vmITBLCKlui58pqh:-MfETGl3AE-JwN7NYgMK:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/main/cc/wfa/panelmatch/client/batchlookup/oblivious_query_wrapper.cc#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Since you're in namespace `wfa`, you shouldn't need to prefix `JniWrap` with `wfa::`
</blockquote></details>

done
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9xX6P8wKjO_o0bGnT:-MfET_vA5SVWsYS2v1C7:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L35)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think all of these `using ::testing::Foo` things are unused
</blockquote></details>

done
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9vvc5AnC5GIUM4iTx:-MfETUTA7EteJP5_HzCw:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L40)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I don't think these using-decls are necessary (or do anything)
</blockquote></details>

done
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9xUEf8FDwzP0r7Zgk:-MfESWZS3rcOpLgkQmim:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L52)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

snake_case_please
</blockquote></details>

done
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9xTn1-9y7LXpsIxSr:-MfESXA799cWbSvSVQDZ:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L58)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

snake_case_please
</blockquote></details>

done
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9w9Jk8cN0n1X66Y4y:-MfESY8KC50sTHJMkv3l:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L78)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

snake_case_please
</blockquote></details>

done
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9wBc46kVVsKK9e0Ra:-MfESYzU-Y6TUS7LlqJD:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L84)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

done
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 94 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9wkCKEwL6ZDjKTwUI:-MfESyW8-RoYefp7AXSF:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L94)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Some good reading: https://abseil.io/tips/161
</blockquote></details>

done
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 102 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9xPj5BLPUqc4PURDK:-MfET-EyCQv1VURC-hy1:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L102)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

done
___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 108 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-Mf9wED4A-hvIOyLE2kl:-MfET0160xZo2Carrwb0:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3604582f103a525c8224b1172aee5bb75840b3c0/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L108)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

done

**Review by efoxepstein — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-:-MfEZ6bJ4g6AzAyzLsJR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 73 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-MfEYKlg9slNVsD-HI0Z:-MfEYKlg9slNVsD-HI0_:b-45wj9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0c6d2f0a93adf4c69de313caf1706a6860bab5e3/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L73)):*
> ```cpp
>   test_request.set_public_key("some-public-key");
>   test_request.set_private_key("some-private-key");
>   std::string some_encrypted_query_result = "some-encrypted-query-result";
> ```

Inline this too?

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc, line 73 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56#-MfEYKlg9slNVsD-HI0Z:-MfIVk3-6i--I7VOOIzo:b-7x1gp6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0c6d2f0a93adf4c69de313caf1706a6860bab5e3/src/test/cc/wfa/panelmatch/client/batchlookup/oblivious_query_test.cc#L73)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Inline this too?
</blockquote></details>

oops. missed that one.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/56)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
