### PR TITLE
Adopt Abseil flags in encrypted_event_decrypter_main

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/90)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/90)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/90#-MhKfClP4lM9ZEVTs3nC:-MhKfClP4lM9ZEVTs3nD:b-1vtrcd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfb7e5534400cdbae979e63210ee8eca8faa448a/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L16)):*
> ```cpp
> 
> #include <iostream>
> #include <memory>
> ```

whats the purpose of this file? What tests is it running that we aren't getting info from elsewhere?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/90)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/90#-MhKfClP4lM9ZEVTs3nC:-MhKt4_p4g9qmfopFm5y:bpx8lal) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfb7e5534400cdbae979e63210ee8eca8faa448a/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L16)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

whats the purpose of this file? What tests is it running that we aren't getting info from elsewhere?
</blockquote></details>

This is a tool -- a utility for manually testing things. We've found it really helpful when looking at results from test runs on Google Cloud Dataflow.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/90)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by efoxepstein — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/90)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/90#-MhKfClP4lM9ZEVTs3nC:-MhLH7im-1YdtJZhcFYk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dfb7e5534400cdbae979e63210ee8eca8faa448a/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L16)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is a tool -- a utility for manually testing things. We've found it really helpful when looking at results from test runs on Google Cloud Dataflow.
</blockquote></details>

Done.

**Pull request merged**
