### PR TITLE
Adds SWIG File and Bazel Rule

### PR DESCRIPTION
**Pull request by jmorrrr**
Adds necessary SWIG File to be used with C++ library and adds corresponding Bazel rule

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/35)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/35)* status: all files reviewed, 1 unresolved discussion (waiting on @jmorrrr)

___
*[src/main/swig/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/35#-MdTXxx62mI1PGFvajx0:-MdTXxx62mI1PGFvajx1:b-bwtijx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dab39cce6a97d6ed29f39f0e02deb23de54c4714/src/main/swig/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L12)):*
> ```Starlark
>     src = "preprocess_events.swig",
>     module = "PreprocessEvents",
>     package = "wfanet.panelmatch.client.eventpreprocessing",
> ```

This should start with `org.wfanet` please

**Review by jmorrrr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/35)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @enfreck, @matthewclegg, and @oliver-amzn)

___
*[src/main/swig/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/35#-MdTXxx62mI1PGFvajx0:-MdTZ6gi3PPt3UNSgnbO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dab39cce6a97d6ed29f39f0e02deb23de54c4714/src/main/swig/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L12)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This should start with `org.wfanet` please
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/35#-:-MdTZeMjB2pFK4-xnd6s:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck, @matthewclegg, and @oliver-amzn)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/35)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck and @matthewclegg)

**Review by enfreck — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/35)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Review by matthewclegg — APPROVED** [review]

**Pull request merged**
