### PR TITLE
Extract base integration test class

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/216)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/216)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt, line 88 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/216#-Mp81Ek6EfaGmFkg53lh:-Mp81Ek6EfaGmFkg53li:bpvdf93) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dcf329d4173029544d26886e770b69df440e382e/src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt#L88)):*
> ```Kotlin
> 
>   private suspend fun isDone(): Boolean {
>     // TODO(@yunyeng): call /Exchanges.GetExchange to get Exchange status.
> ```

whats the plan here? are we going to have the kingdom running in a separate process? or pull it in as a dependency?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/216)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt, line 88 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/216#-Mp81Ek6EfaGmFkg53lh:-Mp81VJFCslycIawXgko:b-n0c8v6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dcf329d4173029544d26886e770b69df440e382e/src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt#L88)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

whats the plan here? are we going to have the kingdom running in a separate process? or pull it in as a dependency?
</blockquote></details>

The Kingdom is already running in-process for this test. Look ~15 lines above this: `private val inProcessKingdom`

**Review by yunyeng — APPROVED** [review]
> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/216)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/216)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt, line 88 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/216#-Mp81Ek6EfaGmFkg53lh:-Mp825u3-SC7iT32msIk:bvbc0bq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dcf329d4173029544d26886e770b69df440e382e/src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt#L88)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The Kingdom is already running in-process for this test. Look ~15 lines above this: `private val inProcessKingdom`
</blockquote></details>

If you're wondering how this fits into the plan to remove cmm as a dep for this repo: I think eventually we'll want an integration-testing repo that has a dependency on everything. At some point there was a plan for this but it never got implemented.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/216)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Pull request merged**
