### PR TITLE
generate symmetric key step

### PR DESCRIPTION
**Pull request by stevenwarejones**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 37 of 37 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateSymmetricKeyTask.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146#-MlFdMct9Ns48b-rRodO:-MlFdMct9Ns48b-rRodP:b-69zs5v) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ddac3c938339f4d6057193738d680b19ee63a6bb/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateSymmetricKeyTask.kt#L25)):*
> ```Kotlin
> 
> class GenerateSymmetricKeyTask(
>   private val operation: () -> ByteString,
> ```

Maybe call this generateKey
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateSymmetricKeyTask.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146#-MlFdEkG-eWDEOkyXE0U:-MlFdEkG-eWDEOkyXE0V:b-xfc9zz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ddac3c938339f4d6057193738d680b19ee63a6bb/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateSymmetricKeyTask.kt#L33)):*
> ```Kotlin
> 
>     val key = operation()
>     return mapOf(outputDataLabel to listOf(key).asFlow())
> ```

flowOf(key) is probably simpler
___
*[src/main/kotlin/org/wfanet/panelmatch/common/crypto/SymmetricCryptor.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146#-MlFeGznBVTuIFseJUA3:-MlFeGzoBuhPe_KW_XQ0:b-ocoisz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ddac3c938339f4d6057193738d680b19ee63a6bb/src/main/kotlin/org/wfanet/panelmatch/common/crypto/SymmetricCryptor.kt#L30)):*
> ```Kotlin
> 
>   /** Decrypts text */
>   fun decrypt(privateKey: ByteString, encryptedTexts: List<ByteString>): List<ByteString>
> ```

Is there a reason to use encryptedTexts instead of the common term ciphertexts?
___
*[src/main/kotlin/org/wfanet/panelmatch/common/crypto/JniDeterministicCommutativeCipher.kt, line 87 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146#-MlFe5n_CEPl70c1n7zx:-MlFe5n_CEPl70c1n7zy:b7af6mj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ddac3c938339f4d6057193738d680b19ee63a6bb/src/main/kotlin/org/wfanet/panelmatch/common/crypto/JniDeterministicCommutativeCipher.kt#L87)):*
> ```Kotlin
>       this.encryptedTexts += encryptedTexts
>     }
>     val data = wrapJniException {
> ```

Data means almost nothing, how about "response"?

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146)* status: 29 of 37 files reviewed, 5 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/crypto/testing/AbstractDeterministicCommutativeCipherTest.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146#-MlFm9Nf5vMS6mzhS2a-:-MlFok9cDwk-7tdFhsLK:bof16au) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ddac3c938339f4d6057193738d680b19ee63a6bb/src/main/kotlin/org/wfanet/panelmatch/common/crypto/testing/AbstractDeterministicCommutativeCipherTest.kt#L37)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@efoxepstein - I actually prefer to extend this test to the AbstractSymmetricCipherTest but I'm not sure how to decrypt back to plaintext. Not sure if there is some quirk to get the plaintext back out.
</blockquote></details>

Specifically, this one test fails: https://github.com/world-federation-of-advertisers/panel-exchange-client/pull/146/files#diff-8a9fa9fec5768a9ec91af2249be41f142509f9248679764917326a916d5b1558R49

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 5 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateSymmetricKeyTask.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146#-MlFdMct9Ns48b-rRodO:-MlGayzBCLozD5D4ze3U:baxt6l9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ddac3c938339f4d6057193738d680b19ee63a6bb/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateSymmetricKeyTask.kt#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This comment is on "operation"
</blockquote></details>

thx for the clarification. done.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/crypto/testing/AbstractDeterministicCommutativeCipherTest.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146#-MlFm9Nf5vMS6mzhS2a-:-MlGb38vC33k5z9rgLQt:b-o3gosw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ddac3c938339f4d6057193738d680b19ee63a6bb/src/main/kotlin/org/wfanet/panelmatch/common/crypto/testing/AbstractDeterministicCommutativeCipherTest.kt#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The result of decryption is an elliptic curve point, it doesn't support true decryption. Basically, the first step of encryption is hashing the input to a point on a curve and then this point is all you get from decryption.
</blockquote></details>

yeah. thats what I had thought from looking through the private join and compute code. could possibly compare the points on the curve, but I think I'll leave it as is if you're good with that.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 12 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt, line 54 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146#-MlH7MxMCJ0hHqpMmV0P:-MlH7MxMCJ0hHqpMmV0Q:b-z1ew4p) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5a0d7f9f6bc35fc92a62ce18d4e00692267e18e7/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt#L54)):*
> ```Kotlin
>   private val lookupKeys =
>     FakeDeterministicCommutativeCipher().decrypt(mpSecretKey, doubleBlindedKeys)
>   private val invalidKey = "invalid key".toByteString()
> ```

Maybe reference the one in FakeDeterministicCommutativeCipher?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt, line 68 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146#-MlH7rUCBz61wmRdgF36:-MlH7rUCBz61wmRdgF37:b1igwsx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5a0d7f9f6bc35fc92a62ce18d4e00692267e18e7/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt#L68)):*
> ```Kotlin
>               ),
>             "encrypted-data" to
>               storage.createBlob(
> ```

There's a version of `createBlob` that takes in a ByteString, so you can probably just delete all the `asBufferedFlow` stuff in this file
___
*[src/main/kotlin/org/wfanet/panelmatch/common/crypto/testing/AbstractDeterministicCommutativeCipherTest.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146#-MlFm9Nf5vMS6mzhS2a-:-MlH8Cu2B9_LEQWSx_8e:b-hfghm4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ddac3c938339f4d6057193738d680b19ee63a6bb/src/main/kotlin/org/wfanet/panelmatch/common/crypto/testing/AbstractDeterministicCommutativeCipherTest.kt#L37)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah. thats what I had thought from looking through the private join and compute code. could possibly compare the points on the curve, but I think I'll leave it as is if you're good with that.
</blockquote></details>

Sounds good

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt, line 54 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146#-MlH7MxMCJ0hHqpMmV0P:-MlHA47t8dm02_Ed1wWH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5a0d7f9f6bc35fc92a62ce18d4e00692267e18e7/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt#L54)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe reference the one in FakeDeterministicCommutativeCipher?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt, line 68 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146#-MlH7rUCBz61wmRdgF36:-MlHCEVfCApyB6dtWx_o:b-oysm07) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5a0d7f9f6bc35fc92a62ce18d4e00692267e18e7/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt#L68)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

There's a version of `createBlob` that takes in a ByteString, so you can probably just delete all the `asBufferedFlow` stuff in this file
</blockquote></details>

I think I'm missing something. Our impl doesn't have that.
https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3807458d65de78391304a639eab64dbbf1e11ca9/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L110

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt, line 68 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146#-MlH7rUCBz61wmRdgF36:-MlHCoas7AaKf5g927gM:b-b3buck) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5a0d7f9f6bc35fc92a62ce18d4e00692267e18e7/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt#L68)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I think I'm missing something. Our impl doesn't have that.
https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3807458d65de78391304a639eab64dbbf1e11ca9/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L110
</blockquote></details>

Oh right, this is a VerifiedStorageClient. Can you add it?

```
fun createBlob(blobKey: String, content: ByteString): VerifiedBlob =
  createBlob(blobKey, content.asBufferedFlow(defaultBufferSizeBytes)
```

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146)* status: 40 of 44 files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt, line 68 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146#-MlH7rUCBz61wmRdgF36:-MlHKNGK75WVQp2gGPQj:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5a0d7f9f6bc35fc92a62ce18d4e00692267e18e7/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt#L68)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Oh right, this is a VerifiedStorageClient. Can you add it?

```
fun createBlob(blobKey: String, content: ByteString): VerifiedBlob =
  createBlob(blobKey, content.asBufferedFlow(defaultBufferSizeBytes)
```
</blockquote></details>

done

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt, line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/146#-MlHTyPE39belSFeu_pV:-MlHTyPE39belSFeu_pW:b-cj5glq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/48ca45c841780e055f826f036297f478b6116f1f/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DeterministicCommutativeCryptorExchangeTaskTest.kt#L31)):*
> ```Kotlin
> import org.wfanet.panelmatch.client.storage.testing.makeTestVerifiedStorageClient
> import org.wfanet.panelmatch.common.crypto.testing.FakeDeterministicCommutativeCipher
> import org.wfanet.panelmatch.common.crypto.testing.INVALID_KEY
> ```

Probably should move this into a companion object in FakeDeterministicCommutativeCipher so it's clear what it belongs to (from the import and usage, it's not).

**Pull request merged**
