### PR TITLE
Build StorageSelectors in ExchangeWorkflowDaemon.

### PR DESCRIPTION
**Pull request by efoxepstein**
https://rally1.rallydev.com/#/?detail=/userstory/613693992139&fdp=true

Co-authored-by: Jon Molle <jmolle@google.com>

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/198)

### CODE REVIEW

**Review by jonmolle — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/198)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonMain.kt, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/198#-MngUelC4U27cda886KO:-MngUelD5tVgGI_QLLL6:bcgcwun) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7c21a40946a6c43df1d3867e5c2173733d87d8bc/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonMain.kt#L37)):*
> ```Kotlin
>   showDefaultValues = true
> )
> private object UnimplementedExchangeWorkflowDaemon : ExchangeWorkflowDaemonFromFlags() {
> ```

Nit: could you add an `identity` override?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonMain.kt, line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/198#-MngSytpC89rWxYJ9b-v:-MngSytpC89rWxYJ9b-w:bxmisi6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7c21a40946a6c43df1d3867e5c2173733d87d8bc/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonMain.kt#L62)):*
> ```Kotlin
>   override val privateStorageFactories:
>     Map<PlatformCase, ExchangeDateKey.(StorageDetails) -> StorageFactory> =
>     mapOf(PlatformCase.FILE to { storageDetails -> FileSystemStorageFactory(storageDetails, this) })
> ```

BTW: are we expecting this specific main to be more informative than actually used unchanged?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/198)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonMain.kt, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/198#-MngUelC4U27cda886KO:-MngXFlC2H2DAjInhT7T:bb76mu4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7c21a40946a6c43df1d3867e5c2173733d87d8bc/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonMain.kt#L37)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

Nit: could you add an `identity` override?
</blockquote></details>

Why?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonMain.kt, line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/198#-MngSytpC89rWxYJ9b-v:-MngXJ63BDiE6Yn31buk:b-phmjwq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7c21a40946a6c43df1d3867e5c2173733d87d8bc/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonMain.kt#L62)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

BTW: are we expecting this specific main to be more informative than actually used unchanged?
</blockquote></details>

Yeah, this is informative. I expect it'll need to be changed in almost all circumstances

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/198)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @jonmolle)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonMain.kt, line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/198#-MngSytpC89rWxYJ9b-v:-MnkUjO60HPPam849Tne:bb6h61l) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7c21a40946a6c43df1d3867e5c2173733d87d8bc/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonMain.kt#L62)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Yeah, this is informative. I expect it'll need to be changed in almost all circumstances
</blockquote></details>

100%
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonMain.kt, line 81 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/198#-MnkUoQbCZVM_tUPf5de:-MnkUoQbCZVM_tUPf5df:b-aykzdz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7c21a40946a6c43df1d3867e5c2173733d87d8bc/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonMain.kt#L81)):*
> ```Kotlin
>   override val clock: Clock = Clock.systemUTC()
> 
>   override val certificateAuthority: CertificateAuthority
> ```

is this the certificate authority for the 1st party? We already have the 3rd parties certs in the rootCertificates?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/198#-MnkUz2P-SBuu4RiLZxn:-MnkUz2P-SBuu4RiLZxo:b-42ldxc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7c21a40946a6c43df1d3867e5c2173733d87d8bc/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L54)):*
> ```Kotlin
>     names = ["--storage-signing-algorithm"],
>     defaultValue = "EC",
>     description = ["The algorithm used in signing data written to shaerd storage."],
> ```

`shared`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/GcsStorageFactory.kt, line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/198#-MnkVm9--CxqTDySa_Rm:-MnkVm9--CxqTDySa_Rn:b-au4ofz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7c21a40946a6c43df1d3867e5c2173733d87d8bc/src/main/kotlin/org/wfanet/panelmatch/client/storage/GcsStorageFactory.kt#L52)):*
> ```Kotlin
> }
> 
> private fun fingerprint(data: String): String {
> ```

should this be in common crypto?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/198)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonMain.kt, line 81 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/198#-MnkUoQbCZVM_tUPf5de:-MnkW8gl2BJ63AqUxwLY:bwug2x2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7c21a40946a6c43df1d3867e5c2173733d87d8bc/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonMain.kt#L81)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is this the certificate authority for the 1st party? We already have the 3rd parties certs in the rootCertificates?
</blockquote></details>

Correct. Basically, it's nontrivial to generate an X509Certificate directly in java and requires accessing the root private key. Instead, the best practice would be to appeal to some CA. Google Cloud offers this as a service and I'm sure AWS does too.

I've added documentation for this parameter in V2AlphaCertificateManager.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/198#-MnkUz2P-SBuu4RiLZxn:-MnlBgTQ8Q2QCJ4JA_pk:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7c21a40946a6c43df1d3867e5c2173733d87d8bc/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L54)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`shared`
</blockquote></details>

Done
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/GcsStorageFactory.kt, line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/198#-MnkVm9--CxqTDySa_Rm:-MnlBhxJConngcoW3W6k:b-ehfesk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7c21a40946a6c43df1d3867e5c2173733d87d8bc/src/main/kotlin/org/wfanet/panelmatch/client/storage/GcsStorageFactory.kt#L52)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should this be in common crypto?
</blockquote></details>

It's kind of niche -- it's SHA-512 and lowercase hex and operates on a string. I'd vote for leaving it here but don't care strongly.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 11 files at r1, 2 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/198)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @jonmolle)

**Pull request merged**
