### PR TITLE
add ability for clients to add resources

### PR DESCRIPTION
**Pull request by stevenwarejones**
Includes a tool to add resources need to set up exchanges as well as resources to add inputs needed for particular exchange steps
Includes integration tests

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 12 of 14 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275)* status: 13 of 14 files reviewed, 6 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/DaemonStorageClientDefaults.kt, line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-MvzxwaB3386s4-jB9Sk:-MvzxwaC04ZeU7TqrYOm:b9dz9dk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/94d8c0f18221b0f7469b012792a197847125c500/src/main/kotlin/org/wfanet/panelmatch/client/deploy/DaemonStorageClientDefaults.kt#L28)):*
> ```Kotlin
>   rootStorageClient: StorageClient,
>   tinkKeyUri: String,
>   tinkStorageProvider: () -> KeyStorageProvider<TinkPrivateKeyHandle>
> ```

Why is this wrapped in a provider function rather than being passed in initialized? It's already a provider.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mvzv1bg4m4Sd_peisgy:-Mvzv1bg4m4Sd_peisgz:bavjz0p) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/94d8c0f18221b0f7469b012792a197847125c500/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L55)):*
> ```Kotlin
>     required = true
>   )
>   private lateinit var privateStorageRoot: File
> ```

This is specific to using file system storage. Shouldn't there be different implementations of this util for GCS, S3, etc?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-MvzvoXK8vswdn19cOL-:-MvzvoXK8vswdn19cOL0:b-tlsp55) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/94d8c0f18221b0f7469b012792a197847125c500/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L70)):*
> ```Kotlin
>   }
> 
>   /** This should be customized per deployment. */
> ```

Is this implying that this util is also just a reference implementation?



_Code quote:_
```Kotlin
/** This should be customized per deployment. */
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 273 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mvzz0so6nfKLGafg-j2:-Mvzz0so6nfKLGafg-j3:b857mio) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/94d8c0f18221b0f7469b012792a197847125c500/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L273)):*
> ```Kotlin
>  * ```
>  */
> fun main(args: Array<String>) {
> ```

I'm confused as to why a file called *FromFlags has a main function. Usually the name of the file with the main function is the name of the executable. Additionally, the *FromFlags pattern is for factory classes. e.g. something named AddResourceFromFlags is expected to be a class that callers can use to get an AddResources instance.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/BUILD.bazel, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-MvzzqM3CIj5mRtxx8GZ:-MvzzqM3CIj5mRtxx8G_:b-2ksc3b) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/94d8c0f18221b0f7469b012792a197847125c500/src/main/kotlin/org/wfanet/panelmatch/client/tools/BUILD.bazel#L37)):*
> ```Starlark
> 
> java_binary(
>     name = "create_resource",
> ```

java_binary targets should have UpperCamelCase names that match the name of the main class (with the slight adjustment for Kotlin that the main class may end in `Kt` where the target name should not).

I have a [PR out](https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/442) which fixes this for Kingdom tools.



_Code quote:_
```Starlark
create_resource
```
___
*[src/main/kotlin/org/wfanet/panelmatch/common/storage/testing/FakeTinkKeyStorageProvider.kt, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mvztfsr9AE2-c4N3S_Z:-Mvztfsr9AE2-c4N3S__:bsmvj4d) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/94d8c0f18221b0f7469b012792a197847125c500/src/main/kotlin/org/wfanet/panelmatch/common/storage/testing/FakeTinkKeyStorageProvider.kt#L23)):*
> ```Kotlin
> import org.wfanet.measurement.storage.Store
> 
> class FakeTinkKeyStorageProvider : KeyStorageProvider<TinkPrivateKeyHandle> {
> ```

Why this rather than just registering a fake KMS client and using the real TinkKeyStorageProvider?

**Review by yunyeng — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275)* status: 13 of 14 files reviewed, 10 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 98 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mw0EyAz2d8RkMz1fXpZ:-Mw0EyAz2d8RkMz1fXp_:bb9trxa) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7b385ac33887ecb6bb0f2b4e1445bfc78a034c11/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L98)):*
> ```Kotlin
>   @Option(
>     names = ["--exchange-workflow-file"],
>     description = ["Public API serialized ExchangeWorkflow"],
> ```

Serializing a textproto file is nontrivial. Is there a way we can have textproto in flag and serialize within this binary?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 129 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mw0G0q54PYHa8HmjtkD:-Mw0G0q54PYHa8HmjtkE:bi0cr2x) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7b385ac33887ecb6bb0f2b4e1445bfc78a034c11/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L129)):*
> ```Kotlin
> 
>   @Option(
>     names = ["--partner-id"],
> ```

Is this equivalent to DataProviderKey / ModelProviderKey or just their id?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 225 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mw0FIoB9H4fxKDcpaw_:-Mw0FIoB9H4fxKDcpawa:b-op5gph) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7b385ac33887ecb6bb0f2b4e1445bfc78a034c11/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L225)):*
> ```Kotlin
>   @Option(
>     names = ["--exchange-date"],
>     description = ["Date in format of d/MM/YYYY"],
> ```

I think the format needs to be YYYY-MM-dd
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 237 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mw0FlZsDh-bitJniWDe:-Mw0FlZsDh-bitJniWDf:b2jw523) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7b385ac33887ecb6bb0f2b4e1445bfc78a034c11/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L237)):*
> ```Kotlin
>   private lateinit var blobKey: String
> 
>   @Option(names = ["--blob-contents"], description = ["Blob Contents"], required = true)
> ```

What is in the blob-contents actually ?

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275)* status: 13 of 14 files reviewed, 10 unresolved discussions (waiting on @SanjayVas and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/DaemonStorageClientDefaults.kt, line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-MvzxwaB3386s4-jB9Sk:-Mw216vKCKsIwswzwik-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/94d8c0f18221b0f7469b012792a197847125c500/src/main/kotlin/org/wfanet/panelmatch/client/deploy/DaemonStorageClientDefaults.kt#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why is this wrapped in a provider function rather than being passed in initialized? It's already a provider.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mvzv1bg4m4Sd_peisgy:-Mw1yBBI2UJIFLRvM8is:bidi3p2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/94d8c0f18221b0f7469b012792a197847125c500/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L55)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is specific to using file system storage. Shouldn't there be different implementations of this util for GCS, S3, etc?
</blockquote></details>

renamed the class and add a kdoc. lmk if it makes more sense now.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-MvzvoXK8vswdn19cOL-:-Mw1yHb361pIj5e3TF1q:b-6xoaza) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/94d8c0f18221b0f7469b012792a197847125c500/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this implying that this util is also just a reference implementation?
</blockquote></details>

see above comment
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 273 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mvzz0so6nfKLGafg-j2:-Mw1z3qD8a0gCopGkKXs:b1b984z) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/94d8c0f18221b0f7469b012792a197847125c500/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L273)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm confused as to why a file called *FromFlags has a main function. Usually the name of the file with the main function is the name of the executable. Additionally, the *FromFlags pattern is for factory classes. e.g. something named AddResourceFromFlags is expected to be a class that callers can use to get an AddResources instance.
</blockquote></details>

What do you think of AddResourceMain?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 98 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mw0EyAz2d8RkMz1fXpZ:-Mw1yJYY7eouC8DUh6tq:bo9dc9j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7b385ac33887ecb6bb0f2b4e1445bfc78a034c11/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L98)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Serializing a textproto file is nontrivial. Is there a way we can have textproto in flag and serialize within this binary?
</blockquote></details>

this description is wrong. It already supports input of text proto. Updated the description.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 129 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mw0G0q54PYHa8HmjtkD:-Mw1zXGJA0PN0c4GmkQB:b-a6n1x1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7b385ac33887ecb6bb0f2b4e1445bfc78a034c11/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L129)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Is this equivalent to DataProviderKey / ModelProviderKey or just their id?
</blockquote></details>

Its ResourceKey.toName() eg provider/providerId
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 225 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mw0FIoB9H4fxKDcpaw_:-Mw1ylpnAeUzZfyfMajM:by45f96) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7b385ac33887ecb6bb0f2b4e1445bfc78a034c11/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L225)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

I think the format needs to be YYYY-MM-dd
</blockquote></details>

Done. Default is YYYY-MM-DD now.



_Code quote:_
```Kotlin
d/MM/YYYY
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 237 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mw0FlZsDh-bitJniWDe:-Mw1ymij1xMgupekwObC:bktatse) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7b385ac33887ecb6bb0f2b4e1445bfc78a034c11/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L237)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

What is in the blob-contents actually ?
</blockquote></details>

its the bytes for the input that is needed for input_labels of a step or out_labels of an input_step
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/BUILD.bazel, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-MvzzqM3CIj5mRtxx8GZ:-Mw1zGqm6cQy3o4DhRJD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/94d8c0f18221b0f7469b012792a197847125c500/src/main/kotlin/org/wfanet/panelmatch/client/tools/BUILD.bazel#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

java_binary targets should have UpperCamelCase names that match the name of the main class (with the slight adjustment for Kotlin that the main class may end in `Kt` where the target name should not).

I have a [PR out](https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/442) which fixes this for Kingdom tools.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/storage/testing/FakeTinkKeyStorageProvider.kt, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mvztfsr9AE2-c4N3S_Z:-Mw20fg92iiSu76wlL3P:b-z8dcga) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/94d8c0f18221b0f7469b012792a197847125c500/src/main/kotlin/org/wfanet/panelmatch/common/storage/testing/FakeTinkKeyStorageProvider.kt#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why this rather than just registering a fake KMS client and using the real TinkKeyStorageProvider?
</blockquote></details>

Maybe I'm misunderstanding what wouldn't that require passing a fake KMSStorageClient to the constructor in DaemonStorageClientDefaults which is of type StorageClient? I don't want anyone to be able to pass in a storageClient of choice. I'd prefer they pass in a KeyStorageProvider. I want the call to makeKmsStorageClient to be enforced.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275)* status: 13 of 14 files reviewed, 11 unresolved discussions (waiting on @robinsons, @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/BUILD.bazel, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-MvzzqM3CIj5mRtxx8GZ:-Mw7pwz59PpL_qsSdhjV:b8ol6nb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/94d8c0f18221b0f7469b012792a197847125c500/src/main/kotlin/org/wfanet/panelmatch/client/tools/BUILD.bazel#L37)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

For clarification: the target name should be the class name *without* any `Kt` suffix.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/BUILD.bazel, line 23 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mw7vGdJBIVWpVyJajJW:-Mw7vGdJBIVWpVyJajJX:b-wgvbll) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f6454d00dda1be75a5b4f114a2adde4326d8cfb8/src/main/kotlin/org/wfanet/panelmatch/client/tools/BUILD.bazel#L23)):*
> ```Starlark
> 
> kt_jvm_library(
>     name = "add_resource_impl",
> ```

A library for a single source file is more commonly named after said source file, but in snake_case.



_Code quote:_
```Starlark
add_resource_impl
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mvzv1bg4m4Sd_peisgy:-Mw7qDHP1bQTZx-vgoEX:b-k932g2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/94d8c0f18221b0f7469b012792a197847125c500/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L55)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

renamed the class and add a kdoc. lmk if it makes more sense now.
</blockquote></details>

I'm still trying to figure out what exactly is meant by "customized per deployment". Is this an instruction to someone potentially writing their own client library and using this code as a base, or is it just indicating that we have more than one implementation ourselves?

I guess I assumed that private storage would be just as likely (if not moreso) to be hosted on a cloud provider. Given that panel-exchange-client supports multiple storage providers, I assumed that we'd support all of those providers in our CLI tools. Either as a single tool, or a separate version of the tool for each option. The latter has been our pattern so far, so you'd have multiple executables defined in the `deploy` package or its subpackages. e.g. AddResourceGcs, AddResourceS3, AddResourceFilesystem, etc.

Let me know if I'm misunderstanding how panel-exchange-client and/or this tool would be used.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 273 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mvzz0so6nfKLGafg-j2:-Mw7v2uDDZIZo_zlDjk4:b-wd596q) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/94d8c0f18221b0f7469b012792a197847125c500/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L273)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

What do you think of AddResourceMain?
</blockquote></details>

It's very odd for the name of a tool. I'd expect the tool/command to just be called AddResource.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 129 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mw0G0q54PYHa8HmjtkD:-Mw7p97y2MGSeXBP8iLb:b-4s05oe) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7b385ac33887ecb6bb0f2b4e1445bfc78a034c11/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L129)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Its ResourceKey.toName() eg provider/providerId
</blockquote></details>

If that's the case, it shouldn't likely be called `partnerName` or `partnerResourceName`.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceMain.kt, line 129 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mw7pQFz-0dXuBUN45O6:-Mw7pQFz-0dXuBUN45O7:blhddf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f6454d00dda1be75a5b4f114a2adde4326d8cfb8/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceMain.kt#L129)):*
> ```Kotlin
>   @Option(
>     names = ["--partner-id"],
>     description = ["API resource name of the recurring-exchange-id ResourceKey.toName()"],
> ```

nit: This part isn't necessary. Saying it's a resource name is sufficient. The confusion stems from the mismatch between the description of the option (which says it's a resource name) and the option name (which says it's an ID).



_Code quote:_
```Kotlin
 ResourceKey.toName()
```

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275)* status: 13 of 14 files reviewed, 10 unresolved discussions (waiting on @robinsons, @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mvzv1bg4m4Sd_peisgy:-Mw8ZOTt8NzSu5u_dH6W:bhi77vu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/94d8c0f18221b0f7469b012792a197847125c500/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L55)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm still trying to figure out what exactly is meant by "customized per deployment". Is this an instruction to someone potentially writing their own client library and using this code as a base, or is it just indicating that we have more than one implementation ourselves?

I guess I assumed that private storage would be just as likely (if not moreso) to be hosted on a cloud provider. Given that panel-exchange-client supports multiple storage providers, I assumed that we'd support all of those providers in our CLI tools. Either as a single tool, or a separate version of the tool for each option. The latter has been our pattern so far, so you'd have multiple executables defined in the `deploy` package or its subpackages. e.g. AddResourceGcs, AddResourceS3, AddResourceFilesystem, etc.

Let me know if I'm misunderstanding how panel-exchange-client and/or this tool would be used.
</blockquote></details>

Its true that additional flags could be added to support a large number of storage clients out of the box. Changed this to a TODO.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 273 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mvzz0so6nfKLGafg-j2:-Mw8YCC-9mYTyN5N6EYw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/94d8c0f18221b0f7469b012792a197847125c500/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L273)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's very odd for the name of a tool. I'd expect the tool/command to just be called AddResource.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt, line 129 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mw0G0q54PYHa8HmjtkD:-Mw8XUUk0ieAMHvTPyK-:bjove1w) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7b385ac33887ecb6bb0f2b4e1445bfc78a034c11/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddResourceFromFlags.kt#L129)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If that's the case, it shouldn't likely be called `partnerName` or `partnerResourceName`.
</blockquote></details>

changed it to partner resource name

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275)* status: all files reviewed, 6 unresolved discussions (waiting on @robinsons, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/storage/testing/FakeTinkKeyStorageProvider.kt, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mvztfsr9AE2-c4N3S_Z:-Mw8zrHEBcR15VQ09Oup:bcs9381) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/94d8c0f18221b0f7469b012792a197847125c500/src/main/kotlin/org/wfanet/panelmatch/common/storage/testing/FakeTinkKeyStorageProvider.kt#L23)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Maybe I'm misunderstanding what wouldn't that require passing a fake KMSStorageClient to the constructor in DaemonStorageClientDefaults which is of type StorageClient? I don't want anyone to be able to pass in a storageClient of choice. I'd prefer they pass in a KeyStorageProvider. I want the call to makeKmsStorageClient to be enforced.
</blockquote></details>

The idea would be to register your fake KMS client with its own Key URI prefix. If you register that instead of registering GcpKmsClient, then Tink will automatically use your fake KMS client to get the key with that URI. This allows you to use e.g. a specified KEK instead of calling out to a real KMS service.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275)* status: all files reviewed, 4 unresolved discussions (waiting on @robinsons and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/BUILD.bazel, line 23 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-Mw7vGdJBIVWpVyJajJW:-MwD3lmCBZki1mIbLQY4:b-8ayx6q) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f6454d00dda1be75a5b4f114a2adde4326d8cfb8/src/main/kotlin/org/wfanet/panelmatch/client/tools/BUILD.bazel#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

A library for a single source file is more commonly named after said source file, but in snake_case.
</blockquote></details>

Why did this get reverted back to having `_impl`?

**Review by yunyeng — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/275#-:-MwDH08Y9Qy4kcRdebpS:bnfp4nl)* status: 14 of 15 files reviewed, 4 unresolved discussions (waiting on @robinsons, @SanjayVas, and @yunyeng)

**Pull request merged**
