### PR TITLE
Clean up Private Membership JNI usage

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118)

### CODE REVIEW

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @stevenwarejones)

**Review by duliomatos1 — APPROVED** [review]
lgtm

> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118#-:-MjbP94S8FpDXQdAF67O:bb7k0qh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 21 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Jni.kt, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118#-MjdQLSiCIZeitEQ7H8_:-MjdQLSiCIZeitEQ7H8a:bh4b1mq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bc7e7da9e105d7094c7c3b236f2ebd5aadcb751e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Jni.kt#L17)):*
> ```Kotlin
> package org.wfanet.panelmatch.client.privatemembership
> 
> internal const val SWIG_PREFIX: String = "/main/swig/wfanet/panelmatch/client/privatemembership"
> ```

JniUtil.kt maybe?
___
*[src/main/kotlin/org/wfanet/panelmatch/common/LoadLibrary.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118#-MjdQq0v-nkcXrPpJWAS:-MjdQq0v-nkcXrPpJWAT:b-y6qkqg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bc7e7da9e105d7094c7c3b236f2ebd5aadcb751e/src/main/kotlin/org/wfanet/panelmatch/common/LoadLibrary.kt#L31)):*
> ```Kotlin
>  * @param resourcePathPrefix the resource path to the directory containing the library
>  */
> fun loadLibraryFromResource(libraryName: String, resourcePathPrefix: String) {
> ```

should this be in common-jvm?
___
*[src/main/proto/wfa/panelmatch/client/privatemembership/query_evaluator.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118#-MjdQw_SDnpcFpVHsib8:-MjdQw_SDnpcFpVHsib9:b-uigs5d) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bc7e7da9e105d7094c7c3b236f2ebd5aadcb751e/src/main/proto/wfa/panelmatch/client/privatemembership/query_evaluator.proto#L29)):*
> ```protobuf
> // system.
> message QueryEvaluatorParameters {
>   private_membership.batch.Parameters private_membership_parameters = 1;
> ```

i've been preferring to just serialize these parameters and not depend on their proto.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Jni.kt, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118#-MjdQLSiCIZeitEQ7H8_:-MjdlDfQ-Pvu_yX95Lmh:b-i610uu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bc7e7da9e105d7094c7c3b236f2ebd5aadcb751e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Jni.kt#L17)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

JniUtil.kt maybe?
</blockquote></details>

How about `SwigPrefix.kt`?
___
*[src/main/kotlin/org/wfanet/panelmatch/common/LoadLibrary.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118#-MjdQq0v-nkcXrPpJWAS:-MjdlGwm0STgJkxC5qZl:bt7ka0g) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bc7e7da9e105d7094c7c3b236f2ebd5aadcb751e/src/main/kotlin/org/wfanet/panelmatch/common/LoadLibrary.kt#L31)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should this be in common-jvm?
</blockquote></details>

There's already a TODO for this on the 5th line of the KDoc above

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 2 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Jni.kt, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118#-MjdQLSiCIZeitEQ7H8_:-MjdqhUE3gm6WV6jgXV5:b-r6ebst) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bc7e7da9e105d7094c7c3b236f2ebd5aadcb751e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Jni.kt#L17)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

How about `SwigPrefix.kt`?
</blockquote></details>

All this is optional but `SwigPrefix` does feel a little specific

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Jni.kt, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118#-MjdQLSiCIZeitEQ7H8_:-MjeE7e884MCEbTnzzfR:bhgznv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bc7e7da9e105d7094c7c3b236f2ebd5aadcb751e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Jni.kt#L17)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

All this is optional but `SwigPrefix` does feel a little specific 
</blockquote></details>

I just kind of hate the word "Util" as it usually means literally nothing.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Jni.kt, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118#-MjdQLSiCIZeitEQ7H8_:-MjeFoyh1NG9DbERoWgR:b-xaehrl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bc7e7da9e105d7094c7c3b236f2ebd5aadcb751e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/Jni.kt#L17)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I just kind of hate the word "Util" as it usually means literally nothing.
</blockquote></details>

Renamed to `SwigPrefix`-- if we think of something else that belongs in that, I'll rename it again.
___
*[src/main/proto/wfa/panelmatch/client/privatemembership/query_evaluator.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118#-MjdQw_SDnpcFpVHsib8:-MjeFaMaDtq-7yl126VX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bc7e7da9e105d7094c7c3b236f2ebd5aadcb751e/src/main/proto/wfa/panelmatch/client/privatemembership/query_evaluator.proto#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i've been preferring to just serialize these parameters and not depend on their proto.
</blockquote></details>

Done.

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 25 files at r1, 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/proto/wfa/panelmatch/client/privatemembership/query_evaluator.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118#-MjdQw_SDnpcFpVHsib8:-MjeVsYsEykooQ-tvY95:bnwgzr2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bc7e7da9e105d7094c7c3b236f2ebd5aadcb751e/src/main/proto/wfa/panelmatch/client/privatemembership/query_evaluator.proto#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`can you change to `serialized_private_membership_parameters` or just `serialized_parameters`... or you could just drop `QueryEvaluatorParameters` altogether and put `serialized_parameters` in each request proto..
https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c279fdcfc877272ba0137baed928b7a1f67e147/src/main/proto/wfa/panelmatch/client/privatemembership/private_membership.proto#L43
___
*[src/test/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results_test.cc, line 140 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118#-MjeXEv_60dGjy9csWTy:-MjeXEv_60dGjy9csWTz:b-ua55fn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/421569816204571e3692224c29519b47d198eca7/src/test/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results_test.cc#L140)):*
> ```cpp
>   DecryptedEventData expected_decrypted_event_data3;
>   expected_decrypted_event_data3.set_plaintext(plaintext3);
>   expected_decrypted_event_data3.mutable_query_id()->set_id(2);
> ```

did you mean to delete this?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118)* status: 23 of 25 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @stevenwarejones)

___
*[src/main/proto/wfa/panelmatch/client/privatemembership/query_evaluator.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118#-MjdQw_SDnpcFpVHsib8:-MjebNhi7pzOjKx18hOo:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bc7e7da9e105d7094c7c3b236f2ebd5aadcb751e/src/main/proto/wfa/panelmatch/client/privatemembership/query_evaluator.proto#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`can you change to `serialized_private_membership_parameters` or just `serialized_parameters`... or you could just drop `QueryEvaluatorParameters` altogether and put `serialized_parameters` in each request proto..
https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2c279fdcfc877272ba0137baed928b7a1f67e147/src/main/proto/wfa/panelmatch/client/privatemembership/private_membership.proto#L43
</blockquote></details>

Done
___
*[src/test/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results_test.cc, line 140 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118#-MjeXEv_60dGjy9csWTy:-MjebTOn82jHIJOTdtDD:b4p57bz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/421569816204571e3692224c29519b47d198eca7/src/test/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results_test.cc#L140)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

did you mean to delete this?
</blockquote></details>

No, probably a merge issue.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118)* status: 23 of 25 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @stevenwarejones)

___
*[src/test/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results_test.cc, line 140 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118#-MjeXEv_60dGjy9csWTy:-Mjec5rJ05nnWRZa369i:b6iodx9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/421569816204571e3692224c29519b47d198eca7/src/test/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results_test.cc#L140)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

No, probably a merge issue.
</blockquote></details>

`$ git diff origin/main -- src/test/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results_test.cc` shows no diff on this file now.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/118)* status: 23 of 25 files reviewed, all discussions resolved (waiting on @oliver-amzn)

**Pull request merged**
