### PR TITLE
Add AwsKmsClient options for tink

### PR DESCRIPTION
**Pull request by jonmolle**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/349)

### CODE REVIEW

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/349)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt` line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/349#-N7XYQ-c1FFxD4vuNF5y:-N7XYQ-c1FFxD4vuNF5z:b-s3m5eg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e86ee4535ea3ac5da94e7cd48c22fb6e6dad556/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt#L136)):*
> ```Kotlin
>       // Register AwsKmsClient before setting storage folders.
>       AwsKmsClient.register(Optional.of(tinkKeyUri), Optional.empty())
>     }
> ```

Nit: You can do a switch statement (when statement) similar as your code below.



_Code quote:_
```Kotlin
    if (storageType == StorageDetails.PlatformCase.GCS) {
      // Register GcpKmsClient before setting storage folders.
      GcpKmsClient.register(Optional.of(tinkKeyUri), Optional.empty())
    } else if (storageType == StorageDetails.PlatformCase.AWS) {
      // Register AwsKmsClient before setting storage folders.
      AwsKmsClient.register(Optional.of(tinkKeyUri), Optional.empty())
    }
```
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/CustomStorageFlags.kt` line 76 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/349#-N7XZNr4CycBAqDAeYJT:-N7XZNr5BTmPmM4DuxkH:b-saccs5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e86ee4535ea3ac5da94e7cd48c22fb6e6dad556/src/main/kotlin/org/wfanet/panelmatch/client/tools/CustomStorageFlags.kt#L76)):*
> ```Kotlin
>       // Register GcpKmsClient before setting storage folders.
>       GcpKmsClient.register(Optional.of(tinkKeyUri), Optional.empty())
>     } else if (storageType == StorageDetails.PlatformCase.AWS) {
> ```

nit: can do the kotlin switch statement (when) similar to code above.

**Review by jonmolle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/349)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @duliomatos1 and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt` line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/349#-N7XYQ-c1FFxD4vuNF5y:-N7bGTrL1Beb1sFi6zMt:b-1eh3wi) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e86ee4535ea3ac5da94e7cd48c22fb6e6dad556/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt#L136)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Nit: You can do a switch statement (when statement) similar as your code below.
</blockquote></details>

Sure, done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/CustomStorageFlags.kt` line 76 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/349#-N7XZNr4CycBAqDAeYJT:-N7bIMpX8rekGIFu6RJO:bv4ruop) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9e86ee4535ea3ac5da94e7cd48c22fb6e6dad556/src/main/kotlin/org/wfanet/panelmatch/client/tools/CustomStorageFlags.kt#L76)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

nit: can do the kotlin switch statement (when) similar to code above. 
</blockquote></details>

I don't really have an else case here, unlike the other one, so the when statement is a bit too strict for this specific condition.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/349)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @jonmolle)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt` line 156 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/349#-N7boCEv-Np84JvkL-xV:-N7boCEv-Np84JvkL-xW:b-ok70n) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/07d5caae9695b568bb18e2e2e4a1d068b1b4cebe/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt#L156)):*
> ```Kotlin
>       StorageDetails.PlatformCase.AWS ->
>         storageDetails {
>           aws = StorageDetailsKt.awsStorage { bucket = gcsFlags.bucket }
> ```

add a flag for region - https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/25f10dc32b98ced5d6397c75a95c7cc0135cd79f/src/main/kotlin/org/wfanet/panelmatch/client/storage/aws/s3/S3StorageFactory.kt#L34

**Review by jonmolle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/349)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt` line 156 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/349#-N7boCEv-Np84JvkL-xV:-N7wg-Tp36U7uUGcHhn0:bfo7iox) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1eacd687f2359d8cf3780bd46b40ce40e5f4253b/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt#L156)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

add a flag for region - https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/25f10dc32b98ced5d6397c75a95c7cc0135cd79f/src/main/kotlin/org/wfanet/panelmatch/client/storage/aws/s3/S3StorageFactory.kt#L34
</blockquote></details>

Done. Just a quick note, there will need to be another PR to allow S3 to be used as a root backing store in these files, which is intended.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/349)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/349)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle)

**Pull request merged**
