### PR TITLE
Refactor TF deployment to implement some security best practices

### PR DESCRIPTION
**Pull request by jonmolle**
Add some AWS security best practices and grants permissions a bit more clearly than previously.

- - -
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359)

### CODE REVIEW

**Review by bdomen-ggl — COMMENTED** [review]
Looks good from what I can remember, plus what I understand your changes to be.

> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-:-NMVbmmf6GVKFxHj6RQa:b-piu4px)* status: all files reviewed, 9 unresolved discussions (waiting on @jonmolle)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NMVYm9x-4knOm4DfRV4:-NMVYm9x-4knOm4DfRV5:b-8v0ihi) (no related file):*
As a note, a lot of TF files changed, but that was to reorganize them. The original thought was to have these smaller units/modules that were somewhat independent from panel exchange setup so it could possibly be reused elsewhere. However, there's a lot of interconnected dependencies since we need a lot of info to pass to K8S configuration. It made things easier to organize in files vs modules.

After that, there are Jon's changes to better adhere to security practices.

___
___
*[`helper.sh` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NMVZeEz-x0ijevrd6wD:-NMVZeF-AJ7Yw_rjinZK:b-lh404w) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/326a5dacd85a54944ecfb68ab73588d966699491/helper.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

Oops, you can scrap this one. The cert_helper below replaced this and does a better job.

These were to help manage the post-deployment configuration with like applying certs from Kingdom, rebuilding and redeploying manifests.
___
*[`src/main/k8s/dev/example_mp_daemon_aws.cue` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NMV_2cmB9UTUL8tDHKb:-NMV_2cn9weQb5LbtX-a:bg2l8oq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/326a5dacd85a54944ecfb68ab73588d966699491/src/main/k8s/dev/example_mp_daemon_aws.cue#L30)):*
> ```CUE
> }
> 
> _defaultAwsConfig: {
> ```

Just thought about this, but can maybe put a note stating that all these blank strings get auto-populated by Terraform.
___
*[`src/main/terraform/cloudbuild.yaml` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NMV_gHJ1R5I9lWt_Dt2:-NMV_gHJ1R5I9lWt_Dt3:b-lgk2db) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/326a5dacd85a54944ecfb68ab73588d966699491/src/main/terraform/cloudbuild.yaml#L1)):*
> ```YAML
> # Copyright 2022 The Cross-Media Measurement Authors
> ```

You can delete this file. I must have mixed branches, but this was for something else I was looking into.
___
*[`src/main/terraform/main.tf` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NMV_u8j1Ue3zOperwi2:-NMV_u8j1Ue3zOperwi3:b-dlnze0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/326a5dacd85a54944ecfb68ab73588d966699491/src/main/terraform/main.tf#L20)):*
> ```HCL
>   # EKS vars
>   availability_zones_count = 2
>   project = "tftest2"
> ```

You can put back "tftest". The 2 was to test deployments while the original was in use. There are "2"s several places below in this file too.
___
*[`src/main/terraform/manifest.sh` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NMVaK6C7DfKJh_ZSROe:-NMVaK6C7DfKJh_ZSROf:b8iaans) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/326a5dacd85a54944ecfb68ab73588d966699491/src/main/terraform/manifest.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

Can maybe delete this one too. This was specifically to help. update the K8S manifest because we had a lot of problems getting the right certs in the right places.
___
*[`src/main/terraform/provider.tf` line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NMVaWxW1EPK4cw1pETQ:-NMVaWxW1EPK4cw1pETR:b5sipw5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/326a5dacd85a54944ecfb68ab73588d966699491/src/main/terraform/provider.tf#L17)):*
> ```HCL
> terraform {
>   backend "s3" {
>     bucket = "tf-panel-exchange-test-bucket-2"
> ```

Can change these back since they were for testing deployments.
___
*[`src/main/terraform/modules/panel-exchange-client/eks_iam_roles.tf` line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NMVajb5AhRtcx9Y_zsI:-NMVajb5AhRtcx9Y_zsJ:b8npusd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/326a5dacd85a54944ecfb68ab73588d966699491/src/main/terraform/modules/panel-exchange-client/eks_iam_roles.tf#L89)):*
> ```HCL
>       {
>         Action = [
>           "kms:*",
> ```

I think this and S3 below can be made more specific. I'm not sure what exactly though. It's not TOO big a deal since it's only on one item and not all of KMS or S3, and a service role only assumable by the K8S service account.
___
*[`src/main/terraform/modules/panel-exchange-client/k8s_config.tf` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NMVbIMF0XgVXvuxTRBW:-NMVbIMF0XgVXvuxTRBX:b-gp72di) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/326a5dacd85a54944ecfb68ab73588d966699491/src/main/terraform/modules/panel-exchange-client/k8s_config.tf#L1)):*
> ```HCL
> # Copyright 2022 The Cross-Media Measurement Authors
> ```

NOTE: A future thought is to merge this with the script (like just run the script from here maybe?) so efforts aren't duplicated for the user and TF.

**Review by jonmolle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359)* status: 15 of 23 files reviewed, 9 unresolved discussions (waiting on @bdomen-ggl)

___
*[`src/main/k8s/dev/example_mp_daemon_aws.cue` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NMV_2cmB9UTUL8tDHKb:-NM_tG3CBnHoCRamTLoo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/326a5dacd85a54944ecfb68ab73588d966699491/src/main/k8s/dev/example_mp_daemon_aws.cue#L30)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Just thought about this, but can maybe put a note stating that all these blank strings get auto-populated by Terraform.
</blockquote></details>

Done.
___
*[`src/main/terraform/main.tf` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NMV_u8j1Ue3zOperwi2:-NM_AYZq6Yql6S15Hkgj:b-fozyjo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/326a5dacd85a54944ecfb68ab73588d966699491/src/main/terraform/main.tf#L20)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

You can put back "tftest". The 2 was to test deployments while the original was in use. There are "2"s several places below in this file too.
</blockquote></details>

Ah, whoops, I meant to, merging weirdness and all that. All fixed now 
___
*[`src/main/terraform/provider.tf` line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NMVaWxW1EPK4cw1pETQ:-NM_Bi1AC-YPDZuvYJc0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/326a5dacd85a54944ecfb68ab73588d966699491/src/main/terraform/provider.tf#L17)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Can change these back since they were for testing deployments.
</blockquote></details>

Done.
___
*[`src/main/terraform/modules/panel-exchange-client/eks_iam_roles.tf` line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NMVajb5AhRtcx9Y_zsI:-NM_swMB6ywyUIPt3vjB:b-ur5el7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/326a5dacd85a54944ecfb68ab73588d966699491/src/main/terraform/modules/panel-exchange-client/eks_iam_roles.tf#L89)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

I think this and S3 below can be made more specific. I'm not sure what exactly though. It's not TOO big a deal since it's only on one item and not all of KMS or S3, and a service role only assumable by the K8S service account.
</blockquote></details>

I've added some logging to see what actions are actually used and will make a followup to reduce these permissions. That wasn't flagged by a recent pen test and I agree the danger seems fairly low.
___
*[`src/main/terraform/modules/panel-exchange-client/k8s_config.tf` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NMVbIMF0XgVXvuxTRBW:-NNhEl9b4TzN_gA0cbxe:b-qk1ail) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/326a5dacd85a54944ecfb68ab73588d966699491/src/main/terraform/modules/panel-exchange-client/k8s_config.tf#L1)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

NOTE: A future thought is to merge this with the script (like just run the script from here maybe?) so efforts aren't duplicated for the user and TF.
</blockquote></details>

Sounds good, but a bit outside the scope of this. Mostly trying to implement best practicies identified in a recent pen test
___
*[`helper.sh` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NMVZeEz-x0ijevrd6wD:-NM_AHKA0MnN9URCX5CN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/326a5dacd85a54944ecfb68ab73588d966699491/helper.sh#L1)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Oops, you can scrap this one. The cert_helper below replaced this and does a better job.

These were to help manage the post-deployment configuration with like applying certs from Kingdom, rebuilding and redeploying manifests.
</blockquote></details>

Done.
___
*[`src/main/terraform/cloudbuild.yaml` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NMV_gHJ1R5I9lWt_Dt2:-NM_AK9u7Fxsnrji2mHq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/326a5dacd85a54944ecfb68ab73588d966699491/src/main/terraform/cloudbuild.yaml#L1)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

You can delete this file. I must have mixed branches, but this was for something else I was looking into.
</blockquote></details>

Done.
___
*[`src/main/terraform/manifest.sh` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NMVaK6C7DfKJh_ZSROe:-NM_tu9Q4at7Ly0TTz1x:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/326a5dacd85a54944ecfb68ab73588d966699491/src/main/terraform/manifest.sh#L1)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Can maybe delete this one too. This was specifically to help. update the K8S manifest because we had a lot of problems getting the right certs in the right places.
</blockquote></details>

Done.

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 3 of 21 files at r1, 4 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359)* status: 19 of 23 files reviewed, 11 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, and @jonmolle)

___
*[`src/main/terraform/cert_helper.sh` line 18 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NNhvSnz8-9eDh9U_-CX:-NNhvSnz8-9eDh9U_-CY:b2w58bz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2e0d4cd3863879e089b78d42f54a0a7f18bc760e/src/main/terraform/cert_helper.sh#L18)):*
> ```Shell
> set -e
> 
> # These get auto-populated from Terraform
> ```

i'm confused by this comment. How is these auto-populated?
___
*[`src/main/terraform/main.tf` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NNhvjpaBk5ygSXmt9AB:-NNhvjpb2G-H0ukA3C97:bahkrr0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2e0d4cd3863879e089b78d42f54a0a7f18bc760e/src/main/terraform/main.tf#L40)):*
> ```HCL
>   path_to_cue = "../k8s/dev/example_mp_daemon_aws.cue"
>   k8s_account_service_name = "mp-workflow"
>   kingdom_endpoint = "public.kingdom.dev.halo-cmm.org:8443"
> ```

shouldn't this always be a flag

**Review by bdomen-ggl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359)* status: 19 of 23 files reviewed, 11 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

___
*[`src/main/terraform/cert_helper.sh` line 18 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NNhvSnz8-9eDh9U_-CX:-NNhwCWzCYeFWuK2tiJx:big0z4t) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2e0d4cd3863879e089b78d42f54a0a7f18bc760e/src/main/terraform/cert_helper.sh#L18)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i'm confused by this comment. How is these auto-populated?
</blockquote></details>

From some context, this file is a bash script that a user manually runs later after collecting all the certs to update the K8S configuration.

There's a script block (local-exec) that TF runs to populate part of these since they come from TF created resources or were passed into TF as input parameters. Rather than have the user manually go find these or re-enter them, it would be nice if they didn't have to do anything other than run the script since the directions are already quite involved.
___
*[`src/main/terraform/main.tf` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359#-NNhvjpaBk5ygSXmt9AB:-NNhxPtDDUI4ewQ1tMr0:bamaw3o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2e0d4cd3863879e089b78d42f54a0a7f18bc760e/src/main/terraform/main.tf#L40)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't this always be a flag
</blockquote></details>

Sorry, I'm not sure what flag you're referring to. The parameters in this file are to be updated by the operator as per directions in the deployment doc. These are left populated as more a general reference or example. These are like the top level variables that a user will set to configure the panel exchange deployment configuration.

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 5 of 21 files at r1, 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359)* status: 20 of 23 files reviewed, 10 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, and @jonmolle)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 7 of 21 files at r1, 3 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/359)* status: all files reviewed, 10 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, and @jonmolle)

**Pull request merged**
