### PR TITLE
Adds Pepper and CryptoKey SerializableFunctions

### PR DESCRIPTION
**Pull request by jmorrrr**
Adds calls to and placeholder implementation/testing for PepperProvider and CryptoKeyProvider classes

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 5 of 8 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59)* status: all files reviewed, 2 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CryptoKeyProviderTest.kt, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59#-MfEnb2j4wCDw9RMsbNx:-MfEnb2kE2c0L5aoAIne:b2b2tld) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d894ce43125d89d8dee69acf64017487824da17d/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CryptoKeyProviderTest.kt#L27)):*
> ```Kotlin
> 
>   @Test
>   fun HardCoded() {
> ```

`camelCaseFunctionNamesPlease`
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CryptoKeyProviderTest.kt, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59#-MfEnh1p6lCUo_NUUowC:-MfEnh1p6lCUo_NUUowD:b6d0mng) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d894ce43125d89d8dee69acf64017487824da17d/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CryptoKeyProviderTest.kt#L30)):*
> ```Kotlin
>     val cryptokey: ByteString = ByteString.copyFromUtf8("testcryptokey")
>     val result = HardCodedCryptoKeyProvider(cryptokey).apply(null as Void?)
>     assertEquals(result, cryptokey)
> ```

For consistency with other code, prefer `assertThat(result).isEqualTo(cryptoKey)`

**Review by jmorrrr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CryptoKeyProviderTest.kt, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59#-MfEnb2j4wCDw9RMsbNx:-MfEqPihC4g-KF0KQa0C:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d894ce43125d89d8dee69acf64017487824da17d/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CryptoKeyProviderTest.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`camelCaseFunctionNamesPlease`
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CryptoKeyProviderTest.kt, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59#-MfEnh1p6lCUo_NUUowC:-MfEqQ5RDsUh-cWE37ZN:b-el1lkl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d894ce43125d89d8dee69acf64017487824da17d/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CryptoKeyProviderTest.kt#L30)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

For consistency with other code, prefer `assertThat(result).isEqualTo(cryptoKey)`
</blockquote></details>

Done.git

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck and @matthewclegg)

**Review by enfreck — APPROVED** [review]
> Reviewed 3 of 8 files at r1, 3 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg and @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59)* status: all files reviewed, 2 unresolved discussions (waiting on @jmorrrr and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/HardCodedCryptoKeyProvider.kt, line 20 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59#-MfJK3X88owCw6TkRnWi:-MfJK3X88owCw6TkRnWj:b88ux6e) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e029db3ce643f8c0d1ed74532ee75f7d87a5dee4/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/HardCodedCryptoKeyProvider.kt#L20)):*
> ```Kotlin
> import org.apache.beam.sdk.transforms.SerializableFunction
> 
> /** Takes in a cryptokey as ByteString and outputs the same ByteString */
> ```

can this go inside testing subdirectory
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/HardCodedPepperProvider.kt, line 20 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59#-MfJK84Q2cOuMzctug2f:-MfJK84Q2cOuMzctug2g:bvmuo8g) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e029db3ce643f8c0d1ed74532ee75f7d87a5dee4/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/HardCodedPepperProvider.kt#L20)):*
> ```Kotlin
> import org.apache.beam.sdk.transforms.SerializableFunction
> 
> /** Takes in a pepper as ByteString and outputs the same ByteString */
> ```

move to testing subdirectory with testonly

**Review by matthewclegg — APPROVED** [review]

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59)* status: all files reviewed, 2 unresolved discussions (waiting on @jmorrrr, @matthewclegg, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/HardCodedCryptoKeyProvider.kt, line 20 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59#-MfJK3X88owCw6TkRnWi:-MfJNuGFB-0mTlXYbfj3:bvjis0c) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e029db3ce643f8c0d1ed74532ee75f7d87a5dee4/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/HardCodedCryptoKeyProvider.kt#L20)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can this go inside testing subdirectory
</blockquote></details>

Are you OK with letting this be the "production" one until the WFA as a whole figures out its approach to KMSes? It's not totally unreasonable that someone would want to use this in production if they feel like the machines running the Beam pipeline are sufficiently locked down that passing these around in the clear is safe.

Are you OK with Julia just adding a commend here with some caveats about security?

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59)* status: all files reviewed, 2 unresolved discussions (waiting on @jmorrrr and @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @jmorrrr)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/HardCodedCryptoKeyProvider.kt, line 20 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59#-MfJK3X88owCw6TkRnWi:-MfKEjB59kydVf8dnsA8:bxbkqa6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e029db3ce643f8c0d1ed74532ee75f7d87a5dee4/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/HardCodedCryptoKeyProvider.kt#L20)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Are you OK with letting this be the "production" one until the WFA as a whole figures out its approach to KMSes? It's not totally unreasonable that someone would want to use this in production if they feel like the machines running the Beam pipeline are sufficiently locked down that passing these around in the clear is safe.

Are you OK with Julia just adding a commend here with some caveats about security?
</blockquote></details>

What kinds of security issues do you think that introduces? Whatever they are or other caveats should go in the comments.

**Review by jmorrrr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/HardCodedCryptoKeyProvider.kt, line 20 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59#-MfJK3X88owCw6TkRnWi:-MfKO4AN0E9RB6eXY1Ms:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e029db3ce643f8c0d1ed74532ee75f7d87a5dee4/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/HardCodedCryptoKeyProvider.kt#L20)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

What kinds of security issues do you think that introduces? Whatever they are or other caveats should go in the comments.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/HardCodedPepperProvider.kt, line 20 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59#-MfJK84Q2cOuMzctug2f:-MfKO4dz5gOlrRcZQRqW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e029db3ce643f8c0d1ed74532ee75f7d87a5dee4/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/HardCodedPepperProvider.kt#L20)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

move to testing subdirectory with testonly
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/59)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

**Pull request merged**
