### PR TITLE
Add testing binary

### PR DESCRIPTION
**Pull request by stevenwarejones**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/209)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/209)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/testing/BUILD.bazel, line 7 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/209#-MoeIlsOEpojYiLW8rFa:-MoeIlsOEpojYiLW8rFb:bob1b6w) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/df606d188d2682960e06a9d65fb5e50a899325f6/src/main/kotlin/org/wfanet/panelmatch/client/testing/BUILD.bazel#L7)):*
> ```Starlark
> )
> 
> java_binary(
> ```

What is the purpose of this?
___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/BUILD.bazel, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/209#-MoeIh500qwJq63RMU_f:-MoeIh500qwJq63RMU_g:b-sl5zdk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f152ebb5e1bbba7dc25c2e32bde3245f9372b2b4/src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/BUILD.bazel#L17)):*
> ```Starlark
>         "//imports/java/org/apache/beam/runners:direct_runner",
>         "//imports/java/org/hamcrest",
>         "//imports/java/org/slf4j:simple",
> ```

Why is this removed?

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/209)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/testing/BUILD.bazel, line 7 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/209#-MoeIlsOEpojYiLW8rFa:-MoeJRi60554jQu5odqD:b-6wyrt6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/df606d188d2682960e06a9d65fb5e50a899325f6/src/main/kotlin/org/wfanet/panelmatch/client/testing/BUILD.bazel#L7)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What is the purpose of this?
</blockquote></details>

for people importing this repository and want a jar of all the testing libs
___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/BUILD.bazel, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/209#-MoeIh500qwJq63RMU_f:-MoeJHhd-wsQKPEgovU_:b-mw14ny) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f152ebb5e1bbba7dc25c2e32bde3245f9372b2b4/src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/BUILD.bazel#L17)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why is this removed?
</blockquote></details>

i believe its an unnecessary import

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/209)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/BUILD.bazel, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/209#-MoeIh500qwJq63RMU_f:-MoeKKos-RgbkOay-n2J:b-r1a3cy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f152ebb5e1bbba7dc25c2e32bde3245f9372b2b4/src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/BUILD.bazel#L17)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i believe its an unnecessary import
</blockquote></details>

Is it coming from somewhere else?

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/209)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/testing/BUILD.bazel, line 7 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/209#-MoeIlsOEpojYiLW8rFa:-MoeKU8MAuhMXaRJUCQD:b-phsd37) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/df606d188d2682960e06a9d65fb5e50a899325f6/src/main/kotlin/org/wfanet/panelmatch/client/testing/BUILD.bazel#L7)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

for people importing this repository and want a jar of all the testing libs
</blockquote></details>

Can you add a comment saying that? And say why `java_library` does not work too please

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/209)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/testing/BUILD.bazel, line 7 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/209#-MoeIlsOEpojYiLW8rFa:-MoizlT16ZOdNNuYAy7a:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/df606d188d2682960e06a9d65fb5e50a899325f6/src/main/kotlin/org/wfanet/panelmatch/client/testing/BUILD.bazel#L7)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you add a comment saying that? And say why `java_library` does not work too please
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/BUILD.bazel, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/209#-MoeIh500qwJq63RMU_f:-Moj-3aH5VNS0CCyMZgg:bvth56w) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f152ebb5e1bbba7dc25c2e32bde3245f9372b2b4/src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/BUILD.bazel#L17)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is it coming from somewhere else?
</blockquote></details>

reverted

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/209)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
