### PR TITLE
add first half of decryption pipeline - eg remove RLWE

### PR DESCRIPTION
**Pull request by stevenwarejones**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94)* status: all files reviewed, 8 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQYbDN0ZNvtdVcT2Gt:-MhQYbDN0ZNvtdVcT2Gu:b-mt9j9h) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L45)):*
> ```Kotlin
>     encryptedQueryResults: PCollection<ByteString>
>   ): PCollection<ByteString> {
>     return encryptedQueryResults.parDo {
> ```

In long blocks, it's helpful to give a name to the block parameter. Can you write `.parDo { encryptedQueryResult ->`?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQYjI0Ddv5e2KoK7BP:-MhQYjI0Ddv5e2KoK7BQ:b1uucy2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L45)):*
> ```Kotlin
>     encryptedQueryResults: PCollection<ByteString>
>   ): PCollection<ByteString> {
>     return encryptedQueryResults.parDo {
> ```

Can you add a `name = "Something"` to the parDo? `.parDo(name = "something")`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQY-ya2vWMCmcpidUv:-MhQY-ya2vWMCmcpidUw:brzgku4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L47)):*
> ```Kotlin
>     return encryptedQueryResults.parDo {
>       val decryptQueryResultsRequest =
>         DecryptQueriesRequest.newBuilder()
> ```

I *think* we've merged the new Kotlin proto builders, so you should be able to write:

```
val request = decryptQueriesRequest {
  this.parameters = parameters.obliviousQueryParameters
  publicKey = parameters.publicKey
  privateKey = parameters.privateKey
  encryptedQueryResults.add(it)
}
``
```

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQYoRPD5O-vrxHC3cq:-MhQYoRPD5O-vrxHC3cr:bi74fkc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L55)):*
> ```Kotlin
>       val decryptedResults =
>         privateMembershipCryptor.decryptQueryResults(decryptQueryResultsRequest)
>       yieldAll(decryptedResults.getDecryptedQueryResultsList())
> ```

In Kotlin, accessor syntax is preferred: `decryptedResults.decryptedQueryResultsList`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsWorkflow.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQZ0e60kk-lZenLtUJ:-MhQZ0e60kk-lZenLtUK:b-5j6hun) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsWorkflow.kt#L35)):*
> ```Kotlin
>   abstract val privateMembershipCryptor: PrivateMembershipCryptor
>   abstract val privateMembershipCryptorHelper: PrivateMembershipCryptorHelper
>   abstract val encryptedResults: PCollection<ByteString>
> ```

I wonder if instead of a `val`, you actually just want a method in the `Helper` like `fun makeEncryptedResults(plaintexts)`. Otherwise, the `<some data a>` below looks very mysterious
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt, line 74 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQZCI8BIYWTMHcI6rM:-MhQZCI8BIYWTMHcI6rN:b-j4t09z) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt#L74)):*
> ```Kotlin
> 
>   override fun generateKeys(request: GenerateKeysRequest): GenerateKeysResponse {
>     return GenerateKeysResponse.newBuilder()
> ```

Ditto my other proto builder comment
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQZL07AHcDRFXTM3Ub:-MhQZL07AHcDRFXTM3Uc:bminyvj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt#L60)):*
> ```Kotlin
>     val queriedData =
>       listOf(
>         resultOf(
> ```

Would a `fun resultOf(query: Int, payload: String) = resultOf(queryMetadataOf(queryIdOf(query), ByteString.EMPTY), ByteString.copyFromUtf8(payload))` helper be useful?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt, line 83 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQZbMT321tY-QDx6lz:-MhQZbMT321tY-QDx6m-:b-j4t09z) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt#L83)):*
> ```Kotlin
>     val decryptQueriesRequest =
>       DecryptQueriesRequest.newBuilder()
>         .addAllEncryptedQueryResults(queriedData.map { it.toByteString() })
> ```

Ditto my other proto builder comment

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94)* status: all files reviewed, 8 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQYbDN0ZNvtdVcT2Gt:-MhTXnKWD2bHOh3ng9vT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L45)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

In long blocks, it's helpful to give a name to the block parameter. Can you write `.parDo { encryptedQueryResult ->`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQYjI0Ddv5e2KoK7BP:-MhTXncSBaKqZMrsAO0S:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L45)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you add a `name = "Something"` to the parDo? `.parDo(name = "something")`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQY-ya2vWMCmcpidUv:-MhTa0Vy-SSPeOM6D5oy:b8w0199) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I *think* we've merged the new Kotlin proto builders, so you should be able to write:

```
val request = decryptQueriesRequest {
  this.parameters = parameters.obliviousQueryParameters
  publicKey = parameters.publicKey
  privateKey = parameters.privateKey
  encryptedQueryResults.add(it)
}
``
</blockquote></details>

+1. changed the ones you mentioned plus a couple more. Will need to do a follow-up PR with many more.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQYoRPD5O-vrxHC3cq:-MhTYJWP4vJWDwwBmeqP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L55)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

In Kotlin, accessor syntax is preferred: `decryptedResults.decryptedQueryResultsList`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsWorkflow.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQZ0e60kk-lZenLtUJ:-MhU1uS21hOSjjkD0rT0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsWorkflow.kt#L35)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I wonder if instead of a `val`, you actually just want a method in the `Helper` like `fun makeEncryptedResults(plaintexts)`. Otherwise, the `<some data a>` below looks very mysterious
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt, line 74 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQZCI8BIYWTMHcI6rM:-MhTd7VNCb52Bael-i_H:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt#L74)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto my other proto builder comment
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQZL07AHcDRFXTM3Ub:-MhU21LJ1boNDrxE9J0F:bo48tcx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt#L60)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Would a `fun resultOf(query: Int, payload: String) = resultOf(queryMetadataOf(queryIdOf(query), ByteString.EMPTY), ByteString.copyFromUtf8(payload))` helper be useful?
</blockquote></details>

moved the creation of the encrypted data to the helper. I don't think that new helper function needs the helper you're referring to but take a look
```
  override fun makeEncryptedResults(plaintexts: List<Pair<Int, String>>): List<ByteString> {
    return plaintexts.map {
      requireNotNull(
        resultOf(
            queryMetadataOf(queryIdOf(it.first), ByteString.EMPTY),
            ByteString.copyFromUtf8(it.second)
          )
          .toByteString()
      )
    }
  }
```
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt, line 83 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQZbMT321tY-QDx6lz:-MhTchDcCH10jL42S12-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt#L83)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto my other proto builder comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

**Review by efoxepstein — APPROVED** [review]
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94)* status: all files reviewed, 10 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQY-ya2vWMCmcpidUv:-MhU5PPf1TLSJA0ozNsn:bauxdv4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L47)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

+1. changed the ones you mentioned plus a couple more. Will need to do a follow-up PR with many more.
</blockquote></details>

Note that `this.` isn't needed (and is generally omitted) if there's no conflicting variable name.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhU8mxI78mooV-U_Zsk:-MhU8mxJ3AnUVKMHMM_x:b9jo0hs) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c7a6673e2b8c5c88fc8a70aded759fec8180ce83/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L50)):*
> ```Kotlin
>         this.publicKey = obliviousQueryParameters.publicKey
>         this.privateKey = obliviousQueryParameters.privateKey
>         this.encryptedQueryResults.add(encryptedQueryResult)
> ```

Something I forgot about: to add to a list with the new Kotlin proto DSL, it's preferred to do `encryptedQueryResults += encryptedQueryResult`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt, line 74 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQZCI8BIYWTMHcI6rM:-MhU94x8ByAvODm4lahH:bblxmyz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt#L74)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ditto, `this.` not needed
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt, line 90 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhU97ix78qiyRMx6ohb:-MhU97ix78qiyRMx6ohc:b69eqgy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c7a6673e2b8c5c88fc8a70aded759fec8180ce83/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt#L90)):*
> ```Kotlin
>     val unencryptedQueries = request.unencryptedQueryList
>     return encryptQueriesResponse {
>       this.ciphertexts.addAll(
> ```

`+=` instead of `addAll` please (and no `this.` needed)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt, line 103 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhU9CuP9g4JaZRrXsCG:-MhU9CuP9g4JaZRrXsCH:bqfzsg3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c7a6673e2b8c5c88fc8a70aded759fec8180ce83/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt#L103)):*
> ```Kotlin
>     val encryptedQueryResults = request.encryptedQueryResultsList
>     return decryptQueriesResponse {
>       this.decryptedQueryResults.addAll(
> ```

Ditto (`this.` and `addAll`)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt, line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhU9j46CU35JNNCd_xp:-MhU9j46CU35JNNCd_xq:bqwc8nz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c7a6673e2b8c5c88fc8a70aded759fec8180ce83/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt#L46)):*
> ```Kotlin
>     val queryBundleList = queryBundle.queryMetadataList
>     val bucketValuesList =
>       ListValue.parseFrom(queryBundle.payload).getValuesList().map { it.stringValue.toInt() }
> ```

`.valuesList.map`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhU9b-EAS0u9gH92yVz:-MhU9b-EAS0u9gH92yW-:b-bd5alx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c7a6673e2b8c5c88fc8a70aded759fec8180ce83/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt#L54)):*
> ```Kotlin
>   override fun makeEncryptedResults(plaintexts: List<Pair<Int, String>>): List<ByteString> {
>     return plaintexts.map {
>       requireNotNull(
> ```

OOC, how can `toByteString()` return null?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt, line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhU9vAa7H2D9tPOOpYg:-MhU9vAa7H2D9tPOOpYh:btzls1s) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c7a6673e2b8c5c88fc8a70aded759fec8180ce83/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt#L34)):*
> ```Kotlin
> interface PrivateMembershipCryptorHelper : Serializable {
> 
>   /** Takes a list of plaintexts and return an encrypted list of ByteString */
> ```

It's not clear to me what the entries in each Pair mean -- can you document?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt, line 35 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhUA92z0KokdNMneGXs:-MhUA92z0KokdNMneGXt:b-3ofmyk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c7a6673e2b8c5c88fc8a70aded759fec8180ce83/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt#L35)):*
> ```Kotlin
>   fun `encryptQueries with multiple shards`() {
>     val encryptQueriesRequest = encryptQueriesRequest {
>       this.unencryptedQuery.addAll(
> ```

`unencryptedQuery +=` please
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt, line 64 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhUAMRy-lEeY9v8C60i:-MhUAMRy-lEeY9v8C60j:b-kwwdyn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c7a6673e2b8c5c88fc8a70aded759fec8180ce83/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt#L64)):*
> ```Kotlin
>     val queriedEncryptedResults = privateMembershipCryptorHelper.makeEncryptedResults(plaintexts)
>     val decryptQueriesRequest = decryptQueriesRequest {
>       this.encryptedQueryResults.addAll(queriedEncryptedResults)
> ```

Ditto for `this.` and `+=` please

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94)* status: all files reviewed, 10 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQY-ya2vWMCmcpidUv:-MhUq4fV33hUKgC5Cmre:bb7p5eq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Note that `this.` isn't needed (and is generally omitted) if there's no conflicting variable name.
</blockquote></details>

thx!
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt, line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhU8mxI78mooV-U_Zsk:-MhUqHy5EmLND-B0rAXV:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c7a6673e2b8c5c88fc8a70aded759fec8180ce83/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResultsWorkflow.kt#L50)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Something I forgot about: to add to a list with the new Kotlin proto DSL, it's preferred to do `encryptedQueryResults += encryptedQueryResult`
</blockquote></details>

+1
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt, line 74 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhQZCI8BIYWTMHcI6rM:-MhUqMqc0ZiSpoF4ms62:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1da09e173c1b1ad881646390226651ab961b8cd2/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt#L74)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto, `this.` not needed
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt, line 90 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhU97ix78qiyRMx6ohb:-MhUquzH1IwfrIyv3q0o:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c7a6673e2b8c5c88fc8a70aded759fec8180ce83/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt#L90)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`+=` instead of `addAll` please (and no `this.` needed)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt, line 103 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhU9CuP9g4JaZRrXsCG:-MhUquk7E-v0o5DDivJ4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c7a6673e2b8c5c88fc8a70aded759fec8180ce83/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptor.kt#L103)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto (`this.` and `addAll`)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt, line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhU9j46CU35JNNCd_xp:-MhUr1oX59odJs8triib:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c7a6673e2b8c5c88fc8a70aded759fec8180ce83/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt#L46)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`.valuesList.map`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhU9b-EAS0u9gH92yVz:-MhUELE-4iphW15yBCsx:b-ulyce9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c7a6673e2b8c5c88fc8a70aded759fec8180ce83/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorHelper.kt#L54)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

OOC, how can `toByteString()` return null?
</blockquote></details>

I added it while looking at something. removed it.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt, line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhU9vAa7H2D9tPOOpYg:-MhUrc7K0kNZLsWpI3nF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c7a6673e2b8c5c88fc8a70aded759fec8180ce83/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt#L34)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's not clear to me what the entries in each Pair mean -- can you document?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt, line 35 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhUA92z0KokdNMneGXs:-MhUuSvG35UdJhtLnY-s:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c7a6673e2b8c5c88fc8a70aded759fec8180ce83/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt#L35)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`unencryptedQuery +=` please
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt, line 64 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/94#-MhUAMRy-lEeY9v8C60i:-MhUuSdC5f_hIKtwaDDE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c7a6673e2b8c5c88fc8a70aded759fec8180ce83/src/test/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PlaintextPrivateMembershipCryptorTest.kt#L64)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto for `this.` and `+=` please
</blockquote></details>

Done.

**Pull request merged**
