### PR TITLE
add hybrid cryptor steps

### PR DESCRIPTION
**Pull request by stevenwarejones**
Currently does not use a KMS
Contains todos to add a KMS but design is probably needed first.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/252)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/252)* status: all files reviewed, 6 unresolved discussions (waiting on @stevenwarejones)

___
*[build/repositories.bzl, line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/252#-MsWAAoy617QmLrSy-Gw:-MsWAAoy617QmLrSy-Gx:bwi16s4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c2f08758ad305e9c862c018a72dd8c40fc3dd597/build/repositories.bzl#L65)):*
> ```Starlark
>     http_archive(
>         name = "wfa_measurement_proto",
>         sha256 = "2acad48b56cfe2c251580bbaa3cbb37d093fbee553ccfd67e72d42e9ea4d931c",
> ```

Switch to release before merging?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/252#-MsWAOGS1XyIpGyqAjHP:-MsWAOGS1XyIpGyqAjHQ:b-5xf024) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c2f08758ad305e9c862c018a72dd8c40fc3dd597/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L27)):*
> ```Kotlin
>       @Suppress("WHEN_ENUM_CAN_BE_NULL_IN_JAVA")
>       when (step.stepCase) {
>         StepCase.ENCRYPT_STEP -> commutativeEncrypt()
> ```

Should we rename these in the API to COMMUTATIVE_ENCRYPT_STEP, etc?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/252#-MsWAR_k8YKR1KHjKROt:-MsWAR_k8YKR1KHjKROu:b-4n33ik) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c2f08758ad305e9c862c018a72dd8c40fc3dd597/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L42)):*
> ```Kotlin
>         StepCase.COPY_FROM_SHARED_STORAGE_STEP -> copyFromSharedStorage()
>         StepCase.COPY_TO_SHARED_STORAGE_STEP -> copyToSharedStorage()
>         StepCase.ENCRYPT_BLOB_STEP -> encryptBlob()
> ```

And should this be HYBRID_ENCRYPT_BLOB_STEP?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateHybridEncryptionKeysTask.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/252#-MsWAltZDeoFE3Shsn8l:-MsWAltZDeoFE3Shsn8m:b-863b3n) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c2f08758ad305e9c862c018a72dd8c40fc3dd597/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateHybridEncryptionKeysTask.kt#L32)):*
> ```Kotlin
> private const val PUBLIC_KEY_LABEL = "public-key-handle"
> 
> class GenerateHybridEncryptionKeysTask : ExchangeTask {
> ```

KDoc?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateHybridEncryptionKeysTask.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/252#-MsWAoef2AKhWq98xIcZ:-MsWAoef2AKhWq98xIc_:bbmwgr0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c2f08758ad305e9c862c018a72dd8c40fc3dd597/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateHybridEncryptionKeysTask.kt#L32)):*
> ```Kotlin
> private const val PUBLIC_KEY_LABEL = "public-key-handle"
> 
> class GenerateHybridEncryptionKeysTask : ExchangeTask {
> ```

Would `GenerateHybridEncryptionKeyPairTask` be more precise?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/HybridEncryptTask.kt, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/252#-MsWB-R59caSydnFyPih:-MsWB-R59caSydnFyPii:br9eqla) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c2f08758ad305e9c862c018a72dd8c40fc3dd597/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/HybridEncryptTask.kt#L43)):*
> ```Kotlin
>     val publicKeysetHandle = KeysetHandle.readNoSecret(publicKeyData.toByteArray())
>     val hybridEncrypt = publicKeysetHandle.getPrimitive(HybridEncrypt::class.java)
>     val encryptedData = hybridEncrypt.encrypt(inputData.toByteArray(), null).toByteString()
> ```

Maybe make `null` into a constant like `private val NO_ASSOCIATED_DATA: ByteArray? = null` so it's clear to the reader what the null means.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/252)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[build/repositories.bzl, line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/252#-MsWAAoy617QmLrSy-Gw:-Ms_Ko5mAPw7nTWfzL8Y:bb70exs) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c2f08758ad305e9c862c018a72dd8c40fc3dd597/build/repositories.bzl#L65)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Switch to release before merging?
</blockquote></details>

yep - for sure
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/252#-MsWAOGS1XyIpGyqAjHP:-Ms_Kr5Z3aoFwh-tXXvD:b-isxmf5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c2f08758ad305e9c862c018a72dd8c40fc3dd597/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Should we rename these in the API to COMMUTATIVE_ENCRYPT_STEP, etc?
</blockquote></details>

how about COMMUTATIVE_DETERMINISTIC_ENCRYPT_STEP?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/252#-MsWAR_k8YKR1KHjKROt:-Ms_M5Ok1T_W7XK_RY5k:b-b0vx6q) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c2f08758ad305e9c862c018a72dd8c40fc3dd597/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapper.kt#L42)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

And should this be HYBRID_ENCRYPT_BLOB_STEP?
</blockquote></details>

how about HYBRID_ENCRYPT_STEP?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateHybridEncryptionKeysTask.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/252#-MsWAoef2AKhWq98xIcZ:-Ms_MSawD7L6DinfVLYg:b-438ch3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c2f08758ad305e9c862c018a72dd8c40fc3dd597/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateHybridEncryptionKeysTask.kt#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Would `GenerateHybridEncryptionKeyPairTask` be more precise?
</blockquote></details>

sounds good. I don't really have an opinion either way.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/HybridEncryptTask.kt, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/252#-MsWB-R59caSydnFyPih:-Ms_Nwac2UegBq-I2j3K:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c2f08758ad305e9c862c018a72dd8c40fc3dd597/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/HybridEncryptTask.kt#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe make `null` into a constant like `private val NO_ASSOCIATED_DATA: ByteArray? = null` so it's clear to the reader what the null means.
</blockquote></details>

done

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/252)* status: 1 of 32 files reviewed, 6 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateHybridEncryptionKeysTask.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/252#-MsWAltZDeoFE3Shsn8l:-Ms_bHmc0PElp7zIr8xQ:b-fh17gy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c2f08758ad305e9c862c018a72dd8c40fc3dd597/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateHybridEncryptionKeysTask.kt#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

KDoc?
</blockquote></details>

Lots of tasks were missing kdocs. Added a bunch.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 31 of 31 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/252)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[build/repositories.bzl, line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/252#-MsWAAoy617QmLrSy-Gw:-Ms_dSyu7A01GviOF3mi:byi4bqh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c2f08758ad305e9c862c018a72dd8c40fc3dd597/build/repositories.bzl#L65)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yep - for sure
</blockquote></details>

OK, I'll leave this open until then

**Pull request merged**
