### PR TITLE
Add step for decrypting private membership results

### PR DESCRIPTION
**Pull request by duliomatos1**
Connecting step to `DecryptPrivateMembershipResultsTask`
Built on top of PR #151

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/common/UncompressedDictionaryBuilder.kt, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156#-Mlv-1ca7DHs8iH0u33H:-Mlv-1cb4JBVBiRzTCfz:blko780) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd6ab639e96397d11ad8d34c0b71b7d9d747922d/src/main/kotlin/org/wfanet/panelmatch/client/common/UncompressedDictionaryBuilder.kt#L39)):*
> ```Kotlin
> }
> 
> class NoOpCompressorFactory : CompressorFactory() {
> ```

Could you move this to its own file please?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156#-Mlv-Ci86K38HQrzUE1l:-Mlv-Ci86K38HQrzUE1m:b-z8o3rw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd6ab639e96397d11ad8d34c0b71b7d9d747922d/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L33)):*
> ```Kotlin
> 
> /** Maps join key exchange steps to exchange tasks */
> class ExchangeTaskMapperForJoinKeyExchange(
> ```

I'm wondering if we should just make this an abstract class with all of these constructor parameters as abstract vals or functions. WDYT?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156#-Mlv-UfNAunffcnqvL2W:-Mlv-UfNAunffcnqvL2X:bneqbgr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd6ab639e96397d11ad8d34c0b71b7d9d747922d/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L37)):*
> ```Kotlin
>   private val getDeterministicCommutativeCryptor: () -> DeterministicCommutativeCipher,
>   private val getPrivateMembershipCryptor: (ByteString) -> PrivateMembershipCryptor,
>   private val getQueryResultsDecryptor: () -> QueryResultsDecryptor,
> ```

Is there a reason we need this to be a factory instead of just passing in a QueryResultsDecryptor? (Same question applies to `getDeterministicCommutativeCryptor`)

**Review by duliomatos1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/common/UncompressedDictionaryBuilder.kt, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156#-Mlv-1ca7DHs8iH0u33H:-MlvJhVwEfsmTPkAYXEY:b-wtspaw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd6ab639e96397d11ad8d34c0b71b7d9d747922d/src/main/kotlin/org/wfanet/panelmatch/client/common/UncompressedDictionaryBuilder.kt#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Could you move this to its own file please?
</blockquote></details>

sure thing
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156#-Mlv-Ci86K38HQrzUE1l:-MlvJkAn8hXFG8dXzY-E:bp5gm0x) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd6ab639e96397d11ad8d34c0b71b7d9d747922d/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'm wondering if we should just make this an abstract class with all of these constructor parameters as abstract vals or functions. WDYT?
</blockquote></details>

yeah it got too unwieldy, your suggestion makes more sense, as was done with the `ExchangeWorkflowDaemon`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156#-Mlv-UfNAunffcnqvL2W:-MlvJtyq1mh5dcktsqMf:b-d36kr7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd6ab639e96397d11ad8d34c0b71b7d9d747922d/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is there a reason we need this to be a factory instead of just passing in a QueryResultsDecryptor? (Same question applies to `getDeterministicCommutativeCryptor`)
</blockquote></details>

that's true, should pass the build jni wrapper directly for both

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @jonmolle)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156#-Mlv-UfNAunffcnqvL2W:-MlvPKGc3bs0rfUMzQtI:b-alqvhq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd6ab639e96397d11ad8d34c0b71b7d9d747922d/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L37)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

that's true, should pass the build jni wrapper directly for both
</blockquote></details>

i kind of like passing in the factory. No reason to instantiate them if they're not needed.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156#-Mlv-Ci86K38HQrzUE1l:-MlvZz9_7JQEw3UXvlAD:b387pib) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd6ab639e96397d11ad8d34c0b71b7d9d747922d/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L33)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

yeah it got too unwieldy, your suggestion makes more sense, as was done with the `ExchangeWorkflowDaemon`
</blockquote></details>

Cool, let me know when it's ready for review
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156#-Mlv-UfNAunffcnqvL2W:-MlvZwBY1Vq3WsELSUdG:bfteqbm) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd6ab639e96397d11ad8d34c0b71b7d9d747922d/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L37)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

if we go the route of transforming `ExchangeTaskMapperForJoinKeyExchange` into an abstract class these can become immutable lazy props using `by lazy {}`. I can add a todo and tackle it next
</blockquote></details>

That sounds good to me

**Review by duliomatos1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156#-Mlv-Ci86K38HQrzUE1l:-MlvnUkJBYds_-wswieL:bqdbvui) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd6ab639e96397d11ad8d34c0b71b7d9d747922d/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L33)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Cool, let me know when it's ready for review
</blockquote></details>

Let me do this change in a separate PR on top of the stack, if you will. Adding a TODO here

**Review by duliomatos1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156#-Mlv-UfNAunffcnqvL2W:-MlvpMo60APp8mqoxHMo:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fd6ab639e96397d11ad8d34c0b71b7d9d747922d/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTaskMapperForJoinKeyExchange.kt#L37)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

will do on top of stack, adding a TODO at the top
</blockquote></details>

done

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle and @stevenwarejones)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/156)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle and @stevenwarejones)

**Pull request merged**
