### PR TITLE
Create an example daemon for running on AWS

### PR DESCRIPTION
**Pull request by jonmolle**
in-progress commit for AWS daemon support

- - -
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354)

### CODE REVIEW

**Review by bdomen-ggl — APPROVED** [review]

**Review by duliomatos1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354)* status: all files reviewed, 3 unresolved discussions (waiting on @jonmolle and @sandip80)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 108 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NAp74LO19uZkcoATHBJ:-NAp74LO19uZkcoATHBK:b-z33ia2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/219523cb4446ab847852929e6510d29fc8d136d8/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L108)):*
> ```Kotlin
> 
>   override val rootStorageClient: StorageClient by lazy {
>     S3StorageClient(S3Client.builder().region(Region.of(s3Region)).build(), s3Bucket)
> ```

ditto below
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt` line 145 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NAp6BX68nzALXG2qHiH:-NAp6BX68nzALXG2qHiI:by17k4h) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/219523cb4446ab847852929e6510d29fc8d136d8/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt#L145)):*
> ```Kotlin
>       StorageDetails.PlatformCase.GCS -> GcsStorageClient.fromFlags(GcsFromFlags(gcsFlags))
>       StorageDetails.PlatformCase.AWS ->
>         S3StorageClient(S3Client.builder().region(Region.of(s3Region)).build(), s3Bucket)
> ```

nit: you could just pass region and bucket and have `S3StorageClient` create `S3Client` (or `S3AsyncClient` per TODO)
```
 S3StorageClient(s3Region, s3Bucket)
```



_Code quote:_
```Kotlin
 S3StorageClient(S3Client.builder().region(Region.of(s3Region)).build(), s3Bucket)
```
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/CustomStorageFlags.kt` line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NAp76zo6duKb44Um2if:-NAp76zo6duKb44Um2ig:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/219523cb4446ab847852929e6510d29fc8d136d8/src/main/kotlin/org/wfanet/panelmatch/client/tools/CustomStorageFlags.kt#L82)):*
> ```Kotlin
>       StorageDetails.PlatformCase.GCS -> GcsStorageClient.fromFlags(GcsFromFlags(gcsFlags))
>       StorageDetails.PlatformCase.AWS ->
>         S3StorageClient(S3Client.builder().region(Region.of(s3Region)).build(), s3Bucket)
> ```

ditto

**Review by sandip80 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354)* status: all files reviewed, 4 unresolved discussions (waiting on @jonmolle)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NApcFEEC3GsqBlGwddX:-NApbwXu5Jq4f8Rog71C:bqphtqs) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/219523cb4446ab847852929e6510d29fc8d136d8/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L80)):*
> ```Kotlin
>     names = ["--s3-from-beam"],
>     description = ["Whether to configure s3 access from Apache Beam."],
>     defaultValue = "false"
> ```

We should set this to true by default right since we will be running the beam jobs on top of s3 objects.

**Review by jonmolle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @sandip80)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NApcFEEC3GsqBlGwddX:-NApuiPyDzvo7gcqLy8T:bnd4krl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/219523cb4446ab847852929e6510d29fc8d136d8/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L80)):*
<details><summary><i>Previously, sandip80 (Sandip Samantaray) wrote…</i></summary><blockquote>

We should set this to true by default right since we will be running the beam jobs on top of s3 objects.
</blockquote></details>

Sure, but I think these should inherit from the environment in AWS. Either way, done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 108 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NAp74LO19uZkcoATHBJ:-NApusgKDKYsEWNiZSco:b5aq3dc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/219523cb4446ab847852929e6510d29fc8d136d8/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L108)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

ditto below
</blockquote></details>

answered elsewhere
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt` line 145 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NAp6BX68nzALXG2qHiH:-NApuvvV3akWTrMkNDW9:bynlicj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/219523cb4446ab847852929e6510d29fc8d136d8/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt#L145)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

nit: you could just pass region and bucket and have `S3StorageClient` create `S3Client` (or `S3AsyncClient` per TODO)
```
 S3StorageClient(s3Region, s3Bucket)
```
</blockquote></details>

That requires an update to the version of common-jvm we use and potentially S3StorageClient itself. I'm doing the former in an immediate followup PR, but that's not in-scope here really.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/CustomStorageFlags.kt` line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NAp76zo6duKb44Um2if:-NApvE1u0pHzrO13l0F7:b5aq3dc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/219523cb4446ab847852929e6510d29fc8d136d8/src/main/kotlin/org/wfanet/panelmatch/client/tools/CustomStorageFlags.kt#L82)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

answered elsewhere

**Review by sandip80 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-:-NAuV7Ei9SAwZLj4E96A:bnfp4nl)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @sandip80)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @sandip80)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NApcFEEC3GsqBlGwddX:-NBHulhUBXJbn-J8GFl8:b-d1uv4p) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/219523cb4446ab847852929e6510d29fc8d136d8/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L80)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

Sure, but I think these should inherit from the environment in AWS. Either way, done.
</blockquote></details>

is this flag even needed on aws? Do we need to pass in creds to the beam runner on AWS in order to access s3 buckets?
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 87 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NBHvMhT0uZ_bmP6sRen:-NBHvMhT0uZ_bmP6sReo:b-kxy34c) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f5c1da603374e10f7198af5217d43eceddf6ae46/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L87)):*
> ```Kotlin
>     val baseOptions =
>       PipelineOptionsFactory.`as`(BeamOptions::class.java).apply {
>         runner = DirectRunner::class.java
> ```

we shouldn't be using the DirectRunner here
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 88 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NBHvQQ4C8LZ4EQIysNo:-NBHvQQ4C8LZ4EQIysNp:b-871das) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f5c1da603374e10f7198af5217d43eceddf6ae46/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L88)):*
> ```Kotlin
>       PipelineOptionsFactory.`as`(BeamOptions::class.java).apply {
>         runner = DirectRunner::class.java
>         defaultSdkHarnessLogLevel = SdkHarnessOptions.LogLevel.DEBUG
> ```

INFO?

**Review by jonmolle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @duliomatos1, @sandip80, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NApcFEEC3GsqBlGwddX:-NBJ-C-t2j4ISnJiJiiQ:b-ohhb1u) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/219523cb4446ab847852929e6510d29fc8d136d8/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L80)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is this flag even needed on aws? Do we need to pass in creds to the beam runner on AWS in order to access s3 buckets?
</blockquote></details>

I agree with you, Steven, I think this should be inherited from the environment in AWS, and currently this doesn't really do much, but I'm working on a downstream PR to fix Beam usage. Right now there is placeholder code to use the DirectRunner so we can deploy and test.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 87 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NBHvMhT0uZ_bmP6sRen:-NBJ-Vzx9c1kA8Nc0P00:bvywmqi) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f5c1da603374e10f7198af5217d43eceddf6ae46/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L87)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

we shouldn't be using the DirectRunner here
</blockquote></details>

I have a downstream PR for this, I agree with you. AWS has a very different structure from GCP dataflow and it will take a bit more time. My goal here was mostly to strip out any GCP code and avoid crashes.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 88 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NBHvQQ4C8LZ4EQIysNo:-NBJBCAB6BOgy0dLmlnl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f5c1da603374e10f7198af5217d43eceddf6ae46/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L88)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

INFO?
</blockquote></details>

Done.

**Comment by sandip80** [comment]
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 87 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NBHvMhT0uZ_bmP6sRen:-NBJGcZq5p_lVJ1vDi6_:b-4lyzkw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f5c1da603374e10f7198af5217d43eceddf6ae46/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L87)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

I have a downstream PR for this, I agree with you. AWS has a very different structure from GCP dataflow and it will take a bit more time. My goal here was mostly to strip out any GCP code and avoid crashes.
</blockquote></details>

This is a temporary fix to run the runners locally without failing on AWS env. We need to setup a separate runner infra on AWS (flink/spark cluster) which can leveraged for beam jobs. I am working on setting this up on AWS.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354)* status: all files reviewed, 5 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @sandip80)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NApcFEEC3GsqBlGwddX:-NBJQRCz4MNlaFD6yn1e:b6isrb8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/219523cb4446ab847852929e6510d29fc8d136d8/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L80)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

I agree with you, Steven, I think this should be inherited from the environment in AWS, and currently this doesn't really do much, but I'm working on a downstream PR to fix Beam usage. Right now there is placeholder code to use the DirectRunner so we can deploy and test.
</blockquote></details>

can you add comments to that effect with a TODO?
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 87 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NBHvMhT0uZ_bmP6sRen:-NBJRcd2ABw463wfD1aB:b-jkvqjn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f5c1da603374e10f7198af5217d43eceddf6ae46/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L87)):*
<details><summary><i>Previously, sandip80 (Sandip Samantaray) wrote…</i></summary><blockquote>

This is a temporary fix to run the runners locally without failing on AWS env. We need to setup a separate runner infra on AWS (flink/spark cluster) which can leveraged for beam jobs. I am working on setting this up on AWS.
</blockquote></details>

I think we kind of previously agreed on using Kinesis Analytics - I believe that uses the Flink Runner
https://docs.aws.amazon.com/kinesisanalytics/latest/java/examples-beam.html
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 89 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NBJQf0Y5e3F4iFBxaWI:-NBJQf0ZA2muvUyEx1Ql:bnzqtfc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5f7df86ce36bdf7019f8faa82d53d315832d68eb/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L89)):*
> ```Kotlin
>       PipelineOptionsFactory.`as`(BeamOptions::class.java).apply {
>         runner = DirectRunner::class.java
>         defaultSdkHarnessLogLevel = SdkHarnessOptions.LogLevel.INFO
> ```

can you add a comment to pass in machine type preferences?

**Comment by sandip80** [comment]
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 87 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NBHvMhT0uZ_bmP6sRen:-NBJvjCP-K8ggSp8LZtB:bduooyr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f5c1da603374e10f7198af5217d43eceddf6ae46/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L87)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I think we kind of previously agreed on using Kinesis Analytics - I believe that uses the Flink Runner
https://docs.aws.amazon.com/kinesisanalytics/latest/java/examples-beam.html
</blockquote></details>

Kinesis Analytics only support standalone beam application (we need to compile, jar the beam job & submit it). This won't work in our case since we are submitting beam jobs at runtime.

**Review by duliomatos1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354)* status: all files reviewed, 3 unresolved discussions (waiting on @jonmolle, @sandip80, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt` line 145 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NAp6BX68nzALXG2qHiH:-NBXmhve-uLo3U-xSTfj:b-q8jzb0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/219523cb4446ab847852929e6510d29fc8d136d8/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt#L145)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

That requires an update to the version of common-jvm we use and potentially S3StorageClient itself. I'm doing the former in an immediate followup PR, but that's not in-scope here really.
</blockquote></details>

got it

**Review by jonmolle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354)* status: all files reviewed, 3 unresolved discussions (waiting on @sandip80 and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NApcFEEC3GsqBlGwddX:-NBK2oCC7nKsFpMkrUtA:bktrv8v) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/219523cb4446ab847852929e6510d29fc8d136d8/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L80)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add comments to that effect with a TODO?
</blockquote></details>

Already done
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 87 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NBHvMhT0uZ_bmP6sRen:-NBK2qAO-yuSZGT9ni2b:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f5c1da603374e10f7198af5217d43eceddf6ae46/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L87)):*
<details><summary><i>Previously, sandip80 (Sandip Samantaray) wrote…</i></summary><blockquote>

Kinesis Analytics only support standalone beam application (we need to compile, jar the beam job & submit it). This won't work in our case since we are submitting beam jobs at runtime.
</blockquote></details>

+1
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt` line 89 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NBJQf0Y5e3F4iFBxaWI:-NBK2ufs2fENjhLpL9eA:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5f7df86ce36bdf7019f8faa82d53d315832d68eb/src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/aws/AwsExampleDaemon.kt#L89)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add a comment to pass in machine type preferences?
</blockquote></details>

Done
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt` line 145 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354#-NAp6BX68nzALXG2qHiH:-NC3qX21-1kQa_K8I4DA:bhssbqj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/219523cb4446ab847852929e6510d29fc8d136d8/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt#L145)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

got it
</blockquote></details>

Actually, update on this after being out sick for a week. Sanjay Vas has an update to support the newer version of common-jvm, so once that goes in I can make a quick followup PR for this. I'd still like to keep it separate.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/354)* status: all files reviewed, 2 unresolved discussions (waiting on @sandip80 and @stevenwarejones)

**Pull request merged**
