### PR TITLE
Create Empty Shards Faster

### PR DESCRIPTION
**Pull request by stevenwarejones**
- Create empty file shards faster
- Create empty query shards faster
- Break fusion on read/write sharded files

Converting breakFusion from an extension function into a PTransform also fixes the following error that only happens on Readh/Write ShardedData that happens for currently unknown reasons.
```
  java.lang.InternalError: Malformed class name
  at java.lang.Class.getSimpleName(Class.java:1330)
  at org.apache.beam.sdk.transforms.display.DisplayData$Type$7.format(DisplayData.java:620)
  at org.apache.beam.sdk.transforms.display.DisplayData$Type.safeFormat(DisplayData.java:654)
  at org.apache.beam.sdk.transforms.display.DisplayData$ItemSpec$Builder.setRawValue(DisplayData.java:445)
  at org.apache.beam.sdk.transforms.display.DisplayData$ItemSpec.create(DisplayData.java:365)
  at org.apache.beam.sdk.transforms.display.DisplayData$ItemSpec.access$1300(DisplayData.java:313)
  at org.apache.beam.sdk.transforms.display.DisplayData.item(DisplayData.java:926)
  at org.apache.beam.sdk.transforms.display.DisplayData.item(DisplayData.java:910)
  at org.apache.beam.sdk.transforms.ParDo.displayDataForFn(ParDo.java:407)
  at org.apache.beam.sdk.transforms.ParDo.of(ParDo.java:403)
```

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamContext.kt` line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1iB2pZCAC0G4BEmGI6:-N1iB2pZCAC0G4BEmGI7:b-8j5368) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c522c0c8647df256dfe8d873b6fee28711643b70/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamContext.kt#L79)):*
> ```Kotlin
>   }
> 
>   inline fun <reified T : Message> PCollection<T>.writeShardedFiles(manifestLabel: String) {
> ```

This change should be unnecessary, just borrow this.coder if you're trying to get a coder for T.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamContext.kt` line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1iBff3-9kOHIlV_-h_:-N1iBff3-9kOHIlV_-ha:b3q4wr9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c522c0c8647df256dfe8d873b6fee28711643b70/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamContext.kt#L79)):*
> ```Kotlin
>   }
> 
>   inline fun <reified T : Message> PCollection<T>.writeShardedFiles(manifestLabel: String) {
> ```

I think you're getting that weird class name error because this is inline and thus being inlined into a JUnit test method whose name has a space in it. If you can make this non-inline per my other comment the naming issue should disappear 
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 112 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1iB_eFCbAllQlQ54jc:-N1iB_eFCbAllQlQ54jd:bid5il5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c522c0c8647df256dfe8d873b6fee28711643b70/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L112)):*
> ```Kotlin
>   }
> 
>   private fun addMissingShardGroups(
> ```

I don't quite follow the logic here, can you add a comment explaining the general approach?

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @robinsons)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamContext.kt` line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1iBff3-9kOHIlV_-h_:-N1j2xbZ0JtFJswfZjjG:b-2ngz9t) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c522c0c8647df256dfe8d873b6fee28711643b70/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamContext.kt#L79)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think you're getting that weird class name error because this is inline and thus being inlined into a JUnit test method whose name has a space in it. If you can make this non-inline per my other comment the naming issue should disappear 
</blockquote></details>

the issue is independent of this change. I was just trying to make the coder more explicit, but I can leave it as is.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamContext.kt` line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1iB2pZCAC0G4BEmGI6:-N1j3ur4DfA352WaOzGs:b-zcv2cf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c522c0c8647df256dfe8d873b6fee28711643b70/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamContext.kt#L79)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This change should be unnecessary, just borrow this.coder if you're trying to get a coder for T.
</blockquote></details>

See my comment below. I agree its unnecessary. I prefer having an explicit coder (which requires passing in some type information about T) but I can leave it as-is if you have a strong opinion.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 112 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1iB_eFCbAllQlQ54jc:-N1j3BK20M0ipp1dt6wQ:b-vaydp8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c522c0c8647df256dfe8d873b6fee28711643b70/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L112)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I don't quite follow the logic here, can you add a comment explaining the general approach?
</blockquote></details>

sure. Imagine 10 shards. Initially, only 1 shard is filled, shard 5. Imagine, I split the shards into groups of 4. If I just use the addMissingShards function, it will take all existing shards mod 4 and then fill in the rest. The problem with that approach is that only 1 shard exists, so it will only fill in shards 1 and 5 (5 exists already and 1 as empty).

So, I added logic before that which goes ahead and fills in shards 0-3 in this example as empty. Then with the 2nd function, addMissingShards, runs, it will fill in 4, 6, 7, 8, 9 as empty.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/ReadShardedData.kt` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1iCNsg0Y1z78blVLib:-N1j37BFD9l8yKdDl6OC:b-3mp8kw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c522c0c8647df256dfe8d873b6fee28711643b70/src/main/kotlin/org/wfanet/panelmatch/common/beam/ReadShardedData.kt#L48)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

BreakFusion please 
</blockquote></details>

breakFusion causes that weird class name error above
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt` line 142 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1iCmwn4TMPamyTlr8g:-N1j3AFTEm7u57bC1sl6:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c522c0c8647df256dfe8d873b6fee28711643b70/src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt#L142)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

BreakFusion please 
</blockquote></details>

ditto

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @robinsons)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamContext.kt` line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1iBff3-9kOHIlV_-h_:-N1j4K1p8xYtkweIK-Oj:bur643r) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c522c0c8647df256dfe8d873b6fee28711643b70/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamContext.kt#L79)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

the issue is independent of this change. I was just trying to make the coder more explicit, but I can leave it as is.
</blockquote></details>

just to clarify, the weird class name error only pops up currently if one uses breakFusion function on read or write shards. The above change does not cause or fix this error. The error happens in both scala tests as well as on the spark runner. Its definitely an issue with how scala handles certain jvm variables.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @robinsons, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamContext.kt` line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1iBff3-9kOHIlV_-h_:-N1j6h_sDX0ei6HwaUAE:b-509wim) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c522c0c8647df256dfe8d873b6fee28711643b70/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamContext.kt#L79)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

just to clarify, the weird class name error only pops up currently if one uses breakFusion function on read or write shards. The above change does not cause or fix this error. The error happens in both scala tests as well as on the spark runner. Its definitely an issue with how scala handles certain jvm variables.
</blockquote></details>

Rather than this hack, can we make BreakFusion into a PTransform maybe so that it works with Scala?

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @robinsons)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamContext.kt` line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1iBff3-9kOHIlV_-h_:-N1jMxFA7Aq9UXUKyKes:b-femhz1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c522c0c8647df256dfe8d873b6fee28711643b70/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamContext.kt#L79)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

sure. thats a good idea. I will try that. Just to be clear, break fusion isn't causing issues anywhere other than in read/write shards. Do you want me to revert more explicit coder logic? I like being explicit but if you don't like it, I can revert.
</blockquote></details>

alternatively, reshuffle performs just fine with none of the problems of the current breakFusion

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337)* status: 15 of 16 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @robinsons, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamContext.kt` line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1iB2pZCAC0G4BEmGI6:-N1k0c628P0F2Biz72jy:b1d88lt) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c522c0c8647df256dfe8d873b6fee28711643b70/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ApacheBeamContext.kt#L79)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

See my comment below. I agree its unnecessary. I prefer having an explicit coder (which requires passing in some type information about T) but I can leave it as-is if you have a strong opinion.
</blockquote></details>

I'd prefer to leave as is please 
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 112 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1iB_eFCbAllQlQ54jc:-N1kFWrD4KrmcA76pcDn:b2kjfs8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c522c0c8647df256dfe8d873b6fee28711643b70/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L112)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

sure. Imagine 10 shards. Initially, only 1 shard is filled, shard 5. Imagine, I split the shards into groups of 4. If I just use the addMissingShards function, it will take all existing shards mod 4 and then fill in the rest. The problem with that approach is that only 1 shard exists, so it will only fill in shards 1 and 5 (5 exists already and 1 as empty).

So, I added logic before that which goes ahead and fills in shards 0-3 in this example as empty. Then with the 2nd function, addMissingShards, runs, it will fill in 4, 6, 7, 8, 9 as empty.
</blockquote></details>

Could it be simpler to just generate a list of all shard ids then subtract away the present ones, then generate the empty shards for what's left?

That would at least allow a generic `fun <T> PCollection<T>.setMinus(other: PCollection<T>): PCollection<T>` that's easier to test/reason about.

Something like:

```
fun <T> PCollection<T>.setMinus(other: PCollection<T>): PCollection<T> {
  return map { kvOf(it, 1) }.join(other.map { kvOf(it, 2) }) { key, lefts, rights ->
    if (lefts.hasNext() && !rights.hasNext()) yield(key)
  }.setCoder(coder)
}
```

And also something like:

```
fun Pipeline.createSequence(name: String, n: Int, parallelism: Int = 1000): PCollection<Int> {
  return apply("$name/Create Seeds", Create.of((0...parallelism).toList()))
    .parDo { emitAll((0..n/parallelism).toList()) }
   .filter { it < n }
}
```
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 132 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1kEkAQ5jb1TuEivICT:-N1kEkAR18T00RDXkfGx:b-y05n1b) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac4f27f9cb7083cde186f777fb2db5ea0f4df08f/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L132)):*
> ```Kotlin
>         }
>         .setCoder(
>           KvCoder.of(
> ```

You can just use `shards.coder` here, I think, to make it clear that we're using the same coder?
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 165 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1kF28aCpmz_3ImmXWH:-N1kF28b7PXeNAOaUbT5:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac4f27f9cb7083cde186f777fb2db5ea0f4df08f/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L165)):*
> ```Kotlin
>         }
>         .setCoder(
>           KvCoder.of(
> ```

Ditto
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 197 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1kFJiP4RyOJ38r5ic4:-N1kFJiP4RyOJ38r5ic5:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ac4f27f9cb7083cde186f777fb2db5ea0f4df08f/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L197)):*
> ```Kotlin
>       .setCoder(
>         KvCoder.of(
>           ProtoCoder.of(ShardId::class.java),
> ```

Ditto

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337)* status: 15 of 16 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @robinsons, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 112 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1iB_eFCbAllQlQ54jc:-N1kRmu0-dnbdmVsQx4L:b6m0kz6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c522c0c8647df256dfe8d873b6fee28711643b70/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L112)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Could it be simpler to just generate a list of all shard ids then subtract away the present ones, then generate the empty shards for what's left?

That would at least allow a generic `fun <T> PCollection<T>.setMinus(other: PCollection<T>): PCollection<T>` that's easier to test/reason about.

Something like:

```
fun <T> PCollection<T>.setMinus(other: PCollection<T>): PCollection<T> {
  return map { kvOf(it, 1) }.join(other.map { kvOf(it, 2) }) { key, lefts, rights ->
    if (lefts.hasNext() && !rights.hasNext()) yield(key)
  }.setCoder(coder)
}
```

And also something like:

```
fun Pipeline.createSequence(name: String, n: Int, parallelism: Int = 1000): PCollection<Int> {
  return apply("$name/Create Seeds", Create.of((0...parallelism).toList()))
    .parDo { emitAll((0..n/parallelism).toList()) }
   .filter { it < n }
}
```
</blockquote></details>

I'm not sure if thats any simpler but I'm open to that impl or the current one I have up. Is the join on that going to be heavier than what I currently have, or do we even care since we're probably talking a max of 1 million files probably.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337)* status: 15 of 16 files reviewed, 5 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 112 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1iB_eFCbAllQlQ54jc:-N1kUx6k7J4J4-N7X4zW:b8e6i7y) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c522c0c8647df256dfe8d873b6fee28711643b70/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L112)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm not sure if thats any simpler but I'm open to that impl or the current one I have up. Is the join on that going to be heavier than what I currently have, or do we even care since we're probably talking a max of 1 million files probably.
</blockquote></details>

Join and GBK are equivalent.

I think it's simpler because it breaks it down into elemental generic operations

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337)* status: all files reviewed, 6 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt` line 285 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1ooAN_5QMeNGKh2GdZ:-N1ooAN_5QMeNGKh2Gd_:b-texj57) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7493fd780d82dec835e32c1adabf13260921c0b5/src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt#L285)):*
> ```Kotlin
>   name: String = "Minus"
> ): PCollection<T> {
>   return PCollectionList.of(this).and(other).apply("$name/Subtract Other", Minus()).setCoder(coder)
> ```

Just name? Why also Subtract Other?
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/BreakFusion.kt` line 40 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1onPUyA1Uj2LgrwLYu:-N1onPV4--v9kcaHPz-8:bd6y0jx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0487a29d221b48c2e6706857e31cdc0e1e0d1add/src/main/kotlin/org/wfanet/panelmatch/common/beam/BreakFusion.kt#L40)):*
> ```Kotlin
>   override fun expand(input: PCollection<T>): PCollection<T> {
>     return input
>       .keyBy("$name/KeyByUUID") { UUID.randomUUID().toString() }
> ```

I believe $name/ is added automatically because this is within a PTransform. You shouldn't need it here
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/Minus.kt` line 27 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1on_4k91mf6zYXqAaT:-N1on_4k91mf6zYXqAaU:br610rm) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0487a29d221b48c2e6706857e31cdc0e1e0d1add/src/main/kotlin/org/wfanet/panelmatch/common/beam/Minus.kt#L27)):*
> ```Kotlin
> class Minus<T : Any> : PTransform<PCollectionList<T>, PCollection<T>>() {
> 
>   override fun expand(input: PCollectionList<T>): PCollection<T> {
> ```

Can you assert only two input collections were provided?
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/Minus.kt` line 30 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1onYHA6DdjtfsdoyrE:-N1onYHBEs9g_UazdRWb:bmbklgb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0487a29d221b48c2e6706857e31cdc0e1e0d1add/src/main/kotlin/org/wfanet/panelmatch/common/beam/Minus.kt#L30)):*
> ```Kotlin
>     val items = input.get(0)
>     val otherItems = input.get(1)
>     return items.map("$name/MapLeft") { kvOf(it, 1) }.join(
> ```

Ditto $name/
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt` line 72 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1onv-a9Lp74P_BfIuS:-N1onv-a9Lp74P_BfIuT:bribuze) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0487a29d221b48c2e6706857e31cdc0e1e0d1add/src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt#L72)):*
> ```Kotlin
>         .apply("Group by Blob", GroupByKey.create())
> 
>     val sequence =
> ```

Maybe a more accurate name is allShardIndexes?
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt` line 80 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1onp3685npYRcrhLsd:-N1onp3685npYRcrhLse:b-10glxb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0487a29d221b48c2e6706857e31cdc0e1e0d1add/src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt#L80)):*
> ```Kotlin
>     val missingFiles =
>       PCollectionList.of(sequence)
>         .and(groupedData.map { it.key })
> ```

.keys()?

**Review by robinsons — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 12 files at r4, 3 of 8 files at r5, 4 of 8 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337)* status: all files reviewed, 9 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 135 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1owduS8Apfz1jntpL5:-N1owduS8Apfz1jntpL6:bn7r19a) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7493fd780d82dec835e32c1adabf13260921c0b5/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L135)):*
> ```Kotlin
>       .flatten("Flatten queries+missingQueries")
>       .breakFusion("Break fusion before EqualizeQueriesPerShardFn")
>       .setCoder(queries.coder)
> ```

nit: Is this `setCoder()` necessary? I thought that `breakFusion()` does this already.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt` line 268 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1oy8Ue7FgQC7DMghaB:-N1oy8Ue7FgQC7DMghaC:bz44rou) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7493fd780d82dec835e32c1adabf13260921c0b5/src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt#L268)):*
> ```Kotlin
> }
> 
> fun Pipeline.createSequence(
> ```

nit: Can you add a brief doc comment to these new functions?
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt` line 274 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1oxoAYD4KyEpv-gujt:-N1oxoAYD4KyEpv-guju:be3fg22) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7493fd780d82dec835e32c1adabf13260921c0b5/src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt#L274)):*
> ```Kotlin
> ): PCollection<Int> {
>   val numPerBatch: Int = ceil(n / parallelism.toFloat()).toInt()
>   return apply("$name/Create", Create.of((0..parallelism).toList())).parDo("$name/ParDo") {
> ```

Is this creating `parallelism + 1` things? Should it be `0 until parallelism`?



_Code quote:_
```Kotlin
0..parallelism)
```

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337)* status: all files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @robinsons)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt` line 274 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1oxoAYD4KyEpv-gujt:-N1pZ3lUBiNoYnM-0WhB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7493fd780d82dec835e32c1adabf13260921c0b5/src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt#L274)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Is this creating `parallelism + 1` things? Should it be `0 until parallelism`?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt` line 285 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1ooAN_5QMeNGKh2GdZ:-N1pZBrA5k5q8Bb_FSCY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7493fd780d82dec835e32c1adabf13260921c0b5/src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt#L285)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Just name? Why also Subtract Other?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/BreakFusion.kt` line 40 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1onPUyA1Uj2LgrwLYu:-N1pZP5n23N_qzYIS2fI:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0487a29d221b48c2e6706857e31cdc0e1e0d1add/src/main/kotlin/org/wfanet/panelmatch/common/beam/BreakFusion.kt#L40)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I believe $name/ is added automatically because this is within a PTransform. You shouldn't need it here
</blockquote></details>

Done
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/Minus.kt` line 27 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1on_4k91mf6zYXqAaT:-N1ssvsD-IsYi3-SgKgS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0487a29d221b48c2e6706857e31cdc0e1e0d1add/src/main/kotlin/org/wfanet/panelmatch/common/beam/Minus.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you assert only two input collections were provided?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/Minus.kt` line 30 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1onYHA6DdjtfsdoyrE:-N1srcX_1Sn-0uYn2iy_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0487a29d221b48c2e6706857e31cdc0e1e0d1add/src/main/kotlin/org/wfanet/panelmatch/common/beam/Minus.kt#L30)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto $name/
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt` line 72 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1onv-a9Lp74P_BfIuS:-N1srkTuAmePOYzJWOC0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0487a29d221b48c2e6706857e31cdc0e1e0d1add/src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt#L72)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe a more accurate name is allShardIndexes?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt` line 80 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337#-N1onp3685npYRcrhLsd:-N1srlHo-CFi7GUha8jf:b-jwnatl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0487a29d221b48c2e6706857e31cdc0e1e0d1add/src/main/kotlin/org/wfanet/panelmatch/common/beam/WriteShardedData.kt#L80)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

.keys()?
</blockquote></details>

+1 Done

**Review by robinsons — APPROVED** [review]
> Reviewed 6 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/337)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein)

**Pull request merged**
