### PR TITLE
Add Brotli compression to Event Preprocessing pipeline

### PR DESCRIPTION
**Pull request by efoxepstein**
https://rally1.rallydev.com/#/?detail=/userstory/607785049547&fdp=true

This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113)

### CODE REVIEW

**Review by jonmolle — APPROVED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, @oliver-amzn, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113#-MjH1U18DaN_napIlcus:-MjH1U18DaN_napIlcut:bmlxard) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f3684ac6ea85f9e3ff589bf89b929494afcb79/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/PreprocessEventsInPipeline.kt#L27)):*
> ```Kotlin
>  * The basic steps are:
>  *
>  * 1. Aggregate values per key using an [EventCompressor] produced by [eventCompressorTrainer].
> ```

Nit: Compress values?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113)* status: all files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @oliver-amzn)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/LoadLibrary.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113#-MjUBmPR3otRVnG4M94g:-MjUBmPR3otRVnG4M94h:b-6pp5fh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f3684ac6ea85f9e3ff589bf89b929494afcb79/src/main/kotlin/org/wfanet/panelmatch/common/LoadLibrary.kt#L29)):*
> ```Kotlin
>  * @param resourcePathPrefix the resource path to the directory containing the library
>  */
> fun loadLibraryFromResource(libraryName: String, resourcePathPrefix: String) {
> ```

should this go in common-jvm?
___
*[src/main/kotlin/org/wfanet/panelmatch/common/compression/BUILD.bazel, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113#-MjUCBOy8mcstxdwc7zf:-MjUCBOy8mcstxdwc7zg:b-1ebo4v) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f3684ac6ea85f9e3ff589bf89b929494afcb79/src/main/kotlin/org/wfanet/panelmatch/common/compression/BUILD.bazel#L15)):*
> ```Starlark
>     name = "swig_resources",
>     resources = [
>         "//src/main/swig/wfanet/panelmatch/common/compression:libbrotli.so",
> ```

so, do we need to do this for other swig files, as well?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CompressByKey.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113#-MjUBKlv1LpwcrECQXou:-MjUBKlv1LpwcrECQXov:bqef3vz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f3684ac6ea85f9e3ff589bf89b929494afcb79/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CompressByKey.kt#L61)):*
> ```Kotlin
>   val eventAggregatorView = trainedEventCompressor.map { it.compressor }.apply(View.asSingleton())
> 
>   val aggregatedEvents: PCollection<KV<ByteString, ByteString>> =
> ```

compressedEvent or compressedAggregatedEvents?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventCompressorTrainer.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113#-MjUBQrPAg29U57_lVxs:-MjUBQrPAg29U57_lVxt:b-87uo1s) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f3684ac6ea85f9e3ff589bf89b929494afcb79/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventCompressorTrainer.kt#L25)):*
> ```Kotlin
>  *
>  * This is to enable dictionary-based compression. The output dictionary should be provided to
>  * whichever library needs to disaggregate.
> ```

uncompress
___
*[src/main/kotlin/org/wfanet/panelmatch/common/compression/NoOpCompressor.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113#-MjUCWtOC4Tqe6bxVIEb:-MjUCWtOC4Tqe6bxVIEc:bys4h48) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f3684ac6ea85f9e3ff589bf89b929494afcb79/src/main/kotlin/org/wfanet/panelmatch/common/compression/NoOpCompressor.kt#L25)):*
> ```Kotlin
>  * environments.
>  */
> class NoOpCompressor : Compressor {
> ```

it should still aggregate though, right?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113)* status: 14 of 20 files reviewed, 5 unresolved discussions (waiting on @duliomatos1, @jonmolle, @oliver-amzn, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/LoadLibrary.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113#-MjUBmPR3otRVnG4M94g:-MjVKgr908OhMYh9dgml:bwnrs1k) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f3684ac6ea85f9e3ff589bf89b929494afcb79/src/main/kotlin/org/wfanet/panelmatch/common/LoadLibrary.kt#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should this go in common-jvm?
</blockquote></details>

I'll add a TODO to do that.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/compression/BUILD.bazel, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113#-MjUCBOy8mcstxdwc7zf:-MjVKtAs-ZExaE_avRGE:blh3b8c) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f3684ac6ea85f9e3ff589bf89b929494afcb79/src/main/kotlin/org/wfanet/panelmatch/common/compression/BUILD.bazel#L15)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

so, do we need to do this for other swig files, as well?
</blockquote></details>

Only if it's used in Beam
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CompressByKey.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113#-MjUBKlv1LpwcrECQXou:-MjVKT4h2MENoAKW52nv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f3684ac6ea85f9e3ff589bf89b929494afcb79/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/CompressByKey.kt#L61)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

compressedEvent or compressedAggregatedEvents?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventCompressorTrainer.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113#-MjUBQrPAg29U57_lVxs:-MjVKWhy4Y1kPCMwfqq2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f3684ac6ea85f9e3ff589bf89b929494afcb79/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EventCompressorTrainer.kt#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

uncompress
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/compression/NoOpCompressor.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113#-MjUCWtOC4Tqe6bxVIEb:-MjVKxLHE7dSCudU_lP7:b-qotkn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f3684ac6ea85f9e3ff589bf89b929494afcb79/src/main/kotlin/org/wfanet/panelmatch/common/compression/NoOpCompressor.kt#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

it should still aggregate though, right?
</blockquote></details>

Aggregation happens in `compressByKey` -- `Compressor` is now oblivious to how events are aggregated.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113)* status: 16 of 20 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, @jonmolle, @oliver-amzn, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/compression/BUILD.bazel, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113#-MjUCBOy8mcstxdwc7zf:-MjVfCxvClbdtWjROfKl:b-bzsh86) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f3684ac6ea85f9e3ff589bf89b929494afcb79/src/main/kotlin/org/wfanet/panelmatch/common/compression/BUILD.bazel#L15)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Only if it's used in Beam
</blockquote></details>

could that go in a comment some where?i know you already told me that but I already forgot.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113)* status: 16 of 20 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @jonmolle, @oliver-amzn, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/compression/BUILD.bazel, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113#-MjUCBOy8mcstxdwc7zf:-MjVq6X3DM7a0svC4uGC:bkayvd8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f3684ac6ea85f9e3ff589bf89b929494afcb79/src/main/kotlin/org/wfanet/panelmatch/common/compression/BUILD.bazel#L15)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

could that go in a comment some where?i know you already told me that but I already forgot.
</blockquote></details>

Added this reason to the referenced bug.

**Review by efoxepstein — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113)* status: 16 of 20 files reviewed, all discussions resolved (waiting on @duliomatos1, @jonmolle, @oliver-amzn, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/compression/BUILD.bazel, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/113#-MjUCBOy8mcstxdwc7zf:-MjVqGMs-0Z4Icj4PgHR:b-wx9tys) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f3684ac6ea85f9e3ff589bf89b929494afcb79/src/main/kotlin/org/wfanet/panelmatch/common/compression/BUILD.bazel#L15)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Added this reason to the referenced bug.
</blockquote></details>

Also added a comment in the Bazel

**Pull request merged**
