### PR TITLE
Add AddAllResources to simplify loading configurations

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/289)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/289)* status: all files reviewed, 1 unresolved discussion (waiting on @robinsons and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/BUILD.bazel, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/289#-MywuXrVAEIjlkSr2AKV:-MywtTnnDATwpWpBoy41:bw4sme0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/20e0b32c9bfccd28ccefcbeac2de9ed7908f8c48/src/main/kotlin/org/wfanet/panelmatch/client/tools/BUILD.bazel#L24)):*
> ```Starlark
>     name = "add_resource",
>     srcs = [
>         "AddAllResources.kt",
> ```

Can you move all the other commands to their own files too?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/289)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @robinsons)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/BUILD.bazel, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/289#-MywuXrVAEIjlkSr2AKV:-MyxQYKT-hQebQ_LeVVn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/20e0b32c9bfccd28ccefcbeac2de9ed7908f8c48/src/main/kotlin/org/wfanet/panelmatch/client/tools/BUILD.bazel#L24)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you move all the other commands to their own files too?
</blockquote></details>

Done.

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/289)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @robinsons, and @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/289)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @robinsons, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt, line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/289#-Mz1ZMYl1gX0NpjBN5dl:-Mz1ZMYl1gX0NpjBN5dm:b-d4k2ik) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/27477874d91f75863b253a0732a7e5059b5fb3c9/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt#L58)):*
> ```Kotlin
> 
>   @CommandLine.Option(
>     names = ["--exchange-workflow-file"],
> ```

--serialized-exchange-workflow-file
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddWorkflow.kt, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/289#-Mz1Z1tW-3gIYHbFpUWf:-Mz1Z1tW-3gIYHbFpUWg:bqgqopp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/27477874d91f75863b253a0732a7e5059b5fb3c9/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddWorkflow.kt#L36)):*
> ```Kotlin
> 
>   @CommandLine.Option(
>     names = ["--exchange-workflow-file"],
> ```

nit: `--serialized-exchange-workflow-file`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/CustomStorageFlags.kt, line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/289#-Mz1ZEGcDLoBFPVaiFqC:-Mz1ZEGcDLoBFPVaiFqD:b-57913q) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/27477874d91f75863b253a0732a7e5059b5fb3c9/src/main/kotlin/org/wfanet/panelmatch/client/tools/CustomStorageFlags.kt#L66)):*
> ```Kotlin
>         FileSystemStorageClient(privateStorageRoot)
>       }
>       else -> throw IllegalArgumentException("Unsupported storage type")
> ```

can you add s3?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/289)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt, line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/289#-Mz1ZMYl1gX0NpjBN5dl:-Mz1mXm560sBkaUuKgqL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/27477874d91f75863b253a0732a7e5059b5fb3c9/src/main/kotlin/org/wfanet/panelmatch/client/tools/AddAllResources.kt#L58)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

--serialized-exchange-workflow-file
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/CustomStorageFlags.kt, line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/289#-Mz1ZEGcDLoBFPVaiFqC:-Mz1mak826q8qkDZ3JMu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/27477874d91f75863b253a0732a7e5059b5fb3c9/src/main/kotlin/org/wfanet/panelmatch/client/tools/CustomStorageFlags.kt#L66)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add s3?
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/289)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @robinsons, and @stevenwarejones)

**Review by robinsons — APPROVED** [review]
> Reviewed 5 of 8 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/289)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

**Review by yunyeng — COMMENTED** [review]
> Dismissed @efoxepstein and @stevenwarejones from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/289)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/289)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
