### PR TITLE
Create tool to parse decrypted query results.

### PR DESCRIPTION
**Pull request by robinsons**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/317)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/317)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @robinsons)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/ParseDecryptedEventData.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/317#-N0744Ix6CrHrb1YHBDf:-N0744Ix6CrHrb1YHBDg:b-imspkx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9da6d1acb81f986c98a84e0d2cac63191616ccb5/src/main/kotlin/org/wfanet/panelmatch/client/tools/ParseDecryptedEventData.kt#L41)):*
> ```Kotlin
>     val shardedFileName = ShardedFileName(fileSpec)
>     val parsedShards = shardedFileName.parseAllShards(KeyedDecryptedEventDataSet.parser())
>     val dataProviderEventSet = dataProviderEventSet {
> ```

Can we avoid this by just printing each KeyedDecryptedEventDataSet individually? In other words:

```
outputFile.outputStream().use { outputStream ->
  PrintWriter(outputStream).use { printer -> {
    for (keyedDecryptedEventDataSet in shardedFileName.parseAllShards(...)) {
      printer.println(keyedDecryptedEventDataSet.toDataProviderEventSetEntry())
    }
  }
}
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/ParseDecryptedEventData.kt, line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/317#-N073ptQ-JTbxTdl2G5U:-N073ptQ-JTbxTdl2G5V:bg08nz0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9da6d1acb81f986c98a84e0d2cac63191616ccb5/src/main/kotlin/org/wfanet/panelmatch/client/tools/ParseDecryptedEventData.kt#L64)):*
> ```Kotlin
>       fileNames.forEach { fileName ->
>         val shardFile = manifestFile.parentFile.resolve(fileName)
>         shardFile.inputStream().use {
> ```

`BufferedInputStream` wrapper?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/317)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @robinsons)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/317#-N075cj51Db3ofQzT00M:-N075cj60pmURM3SI1PI:b-ioh7z2) (no related file):*
Would it be useful to add a flag to filter which shards are processed? Or to add a limit? Just to make debugging easier?

---

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/317)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @robinsons)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/ParseDecryptedEventData.kt, line 61 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/317#-N07CUBV808vtDSIADtz:-N07CUBW0PmK7FWB0b9_:b-mrewim) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3f51c7f1559fd5f9548b59335c14dfece75fa2b7/src/main/kotlin/org/wfanet/panelmatch/client/tools/ParseDecryptedEventData.kt#L61)):*
> ```Kotlin
>     PrintWriter(outputFile.outputStream()).use {
>       for (keyedDecryptedEventDataSet in parsedShards) {
>         it.println(keyedDecryptedEventDataSet.toDataProviderEventSetEntry().toJson())
> ```

I really only like `it` when it's immediately used, consider naming this

**Review by duliomatos1 — APPROVED** [review]
:lgtm: 

> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/317#-:-N07nUCX0uExFr0KZOpq:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @robinsons)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/ParseDecryptedEventData.kt, line 61 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/317#-N07CUBV808vtDSIADtz:-N07mttq9rEM1UNrWZTY:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3f51c7f1559fd5f9548b59335c14dfece75fa2b7/src/main/kotlin/org/wfanet/panelmatch/client/tools/ParseDecryptedEventData.kt#L61)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I really only like `it` when it's immediately used, consider naming this
</blockquote></details>

+1

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/317)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @duliomatos1 and @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/ParseDecryptedEventData.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/317#-N0744Ix6CrHrb1YHBDf:-N079NB9CEf3i-0f76P7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9da6d1acb81f986c98a84e0d2cac63191616ccb5/src/main/kotlin/org/wfanet/panelmatch/client/tools/ParseDecryptedEventData.kt#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can we avoid this by just printing each KeyedDecryptedEventDataSet individually? In other words:

```
outputFile.outputStream().use { outputStream ->
  PrintWriter(outputStream).use { printer -> {
    for (keyedDecryptedEventDataSet in shardedFileName.parseAllShards(...)) {
      printer.println(keyedDecryptedEventDataSet.toDataProviderEventSetEntry())
    }
  }
}
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/tools/ParseDecryptedEventData.kt, line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/317#-N073ptQ-JTbxTdl2G5U:-N079Nja1QaYrA3rq_Ep:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9da6d1acb81f986c98a84e0d2cac63191616ccb5/src/main/kotlin/org/wfanet/panelmatch/client/tools/ParseDecryptedEventData.kt#L64)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`BufferedInputStream` wrapper?
</blockquote></details>

Done.

**Pull request merged**
