### PR TITLE
Update deps.

### PR DESCRIPTION
**Pull request by robinsons**
Adds script deps to all targets, and removes some unneeded deps.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/106)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/106)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle)

**Review by jonmolle — APPROVED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/106)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn and @stevenwarejones)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/106)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 29 of 29 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/106)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @robinsons)

**Pull request merged**
