### PR TITLE
Parse different events within a single decrypted query result

### PR DESCRIPTION
**Pull request by stevenwarejones**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115)

### CODE REVIEW

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjWGJguCFKBZzkWOIfB:-MjWGJgv-YDAEIaFw-b2:b-ar4l7e) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ed11a654d2b52e58fcda2c802484eea5772071e/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L89)):*
> ```cpp
>     QueryResult query_results;
>     query_results.ParseFromString(client_decrypted_query_result.result());
>     for (const std::string& query_result : query_results.ciphertexts()) {
> ```

@efoxepstein - is there a better way to just parse them and swap them in? I wasn't sure.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115)* status: all files reviewed, 5 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjWGJguCFKBZzkWOIfB:-MjWI1xl7rcjV8RAjQRA:b-b148zs) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ed11a654d2b52e58fcda2c802484eea5772071e/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L89)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@efoxepstein - is there a better way to just parse them and swap them in? I wasn't sure.
</blockquote></details>

Something like this should work:

```
*decrypt_event_data_request.mutable_encrypted_event_data()->mutable_ciphertexts() = *query_results.mutable_ciphertexts();
```

as RepeatedPtrField does have a move-assign operator. If that doesn't work, `decrypt_event_data_request.mutable_encrypted_event_data()->Swap(query_results.mutable_ciphertexts())` should.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjWK60SCL_Z7Rfx0EX-:-MjWK60SCL_Z7Rfx0EX0:b-bwq59y) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ed11a654d2b52e58fcda2c802484eea5772071e/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L54)):*
> ```cpp
>   for (const std::string& encrypted_event :
>        request.encrypted_event_data().ciphertexts()) {
>     absl::StatusOr<std::string> plaintext_or_status = aes_hkdf.Decrypt(
> ```

https://abseil.io/tips/181 -- please don't suffix with `_or_status`
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjWJHJID-UHU0CrNgeJ:-MjWJHJID-UHU0CrNgeK:b-hrnlm6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ed11a654d2b52e58fcda2c802484eea5772071e/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L58)):*
> ```cpp
>         SecretDataFromStringView(request.single_blinded_joinkey().key()),
>         SecretDataFromStringView(request.hkdf_pepper()));
>     if (plaintext_or_status.ok()) {
> ```

If it's not OK, should we log the error or return it or anything?
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjWK8kb5fU7CEC_zHqj:-MjWK8kb5fU7CEC_zHqk:b-9q0c6n) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ed11a654d2b52e58fcda2c802484eea5772071e/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L61)):*
> ```cpp
>       DecryptedEventData* decrypted_event_data =
>           response.add_decrypted_event_data();
>       decrypted_event_data->set_plaintext(plaintext_or_status.value()),
> ```

https://abseil.io/tips/181 -- `set_plaintext(*std::move(plaintext))`
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjWKGMcAbGolQkl9sIk:-MjWKGMcAbGolQkl9sIl:bdz1kuh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ed11a654d2b52e58fcda2c802484eea5772071e/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L62)):*
> ```cpp
>           response.add_decrypted_event_data();
>       decrypted_event_data->set_plaintext(plaintext_or_status.value()),
>           decrypted_event_data->mutable_query_id()->CopyFrom(
> ```

Typically: `*foo->mutable_bar() = baz;`

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjWJHJID-UHU0CrNgeJ:-MjWigcz3l44H76tLDz0:b-h16tc0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ed11a654d2b52e58fcda2c802484eea5772071e/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L58)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

If it's not OK, should we log the error or return it or anything?
</blockquote></details>

i think this will happen *a lot*. Doesn't seem worth logging to me.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115)* status: all files reviewed, 5 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjWJHJID-UHU0CrNgeJ:-MjWkPHj3Gdn4Hgil_JT:b912o08) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ed11a654d2b52e58fcda2c802484eea5772071e/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L58)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i think this will happen *a lot*. Doesn't seem worth logging to me.
</blockquote></details>

Should we count it then?

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjWGJguCFKBZzkWOIfB:-MjZew0E-skBkdRNwK7d:b-e1lw51) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ed11a654d2b52e58fcda2c802484eea5772071e/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L89)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Something like this should work:

```
*decrypt_event_data_request.mutable_encrypted_event_data()->mutable_ciphertexts() = *query_results.mutable_ciphertexts();
```

as RepeatedPtrField does have a move-assign operator. If that doesn't work, `decrypt_event_data_request.mutable_encrypted_event_data()->Swap(query_results.mutable_ciphertexts())` should.
</blockquote></details>

The former works. Thx! I had previously tried to latter and had some issues.
Should I be using `*decrypt_event_data_request.mutable_encrypted_event_data()->mutable_ciphertexts() = *std::move(query_results.mutable_ciphertexts());`?
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjWK60SCL_Z7Rfx0EX-:-MjZVHR-9WPRqlX2hEtB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ed11a654d2b52e58fcda2c802484eea5772071e/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L54)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

https://abseil.io/tips/181 -- please don't suffix with `_or_status`
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjWJHJID-UHU0CrNgeJ:-MjZfoAh2Z-M3IBpy9gS:b-6re76v) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ed11a654d2b52e58fcda2c802484eea5772071e/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L58)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Should we count it then?
</blockquote></details>

Not sure. The EDP should know the ratio of this data, themselves. If we do want to track, should we pass around some tuples to keep track of valid/invalid ciphertexts? That feels a little messy to me.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjWK8kb5fU7CEC_zHqj:-MjZYw5QDGDuOd_QV8tc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ed11a654d2b52e58fcda2c802484eea5772071e/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L61)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

https://abseil.io/tips/181 -- `set_plaintext(*std::move(plaintext))`
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjWKGMcAbGolQkl9sIk:-MjZ_WuQ2AvD8TU4rnFN:b3lkly3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ed11a654d2b52e58fcda2c802484eea5772071e/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L62)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Typically: `*foo->mutable_bar() = baz;`
</blockquote></details>

I am copying this data multiple times in the for loop. Don't I need to make a copy?

I could also do something like if you prefer
`decrypted_event_data->mutable_query_id()->set_id(request.encrypted_event_data().query_id().id());`

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjWGJguCFKBZzkWOIfB:-Mj_7S8z96eJd-eCMhUE:b-rh7ky9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ed11a654d2b52e58fcda2c802484eea5772071e/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L89)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

The former works. Thx! I had previously tried to latter and had some issues.
Should I be using `*decrypt_event_data_request.mutable_encrypted_event_data()->mutable_ciphertexts() = *std::move(query_results.mutable_ciphertexts());`?
</blockquote></details>

Ah yeah, probably want the `std::move`
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 71 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-Mj_7e6JDs2fDlsXJ4sm:-Mj_7e6JDs2fDlsXJ4sn:bnotvak) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e15ccc9e846a9dda97bcae3f6cc7a8b6d8bc58b0/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L71)):*
> ```cpp
> }
> 
> absl::StatusOr<DecryptQueryResultsResponse> RemoveAes(
> ```

This function is getting pretty long -- would it be hard to pull the body of the for-loop out into a helper function?
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-Mj_7yqg2N810AvBDvuL:-Mj_7yqg2N810AvBDvuM:b-i2gp4m) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e15ccc9e846a9dda97bcae3f6cc7a8b6d8bc58b0/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L93)):*
> ```cpp
>     ASSIGN_OR_RETURN(DecryptEventDataResponse decrypt_event_data_response,
>                      DecryptEventData(decrypt_event_data_request));
>     for (DecryptedEventData decrypted_event_data :
> ```

I think we can get rid of the loop here:

```
*result.mutable_decrypted_event_data() = *std::move(decrypt_event_data_response).mutable_decrypted_event_data();
```
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjWJHJID-UHU0CrNgeJ:-Mj_8LJe88UKBillCdpf:b-kkz5os) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ed11a654d2b52e58fcda2c802484eea5772071e/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L58)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Not sure. The EDP should know the ratio of this data, themselves. If we do want to track, should we pass around some tuples to keep track of valid/invalid ciphertexts? That feels a little messy to me.
</blockquote></details>

OK, let's leave it as is.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjWKGMcAbGolQkl9sIk:-Mj_8PNRDhOYF33zMLJq:bjr33yv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ed11a654d2b52e58fcda2c802484eea5772071e/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L62)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I am copying this data multiple times in the for loop. Don't I need to make a copy?

I could also do something like if you prefer
`decrypted_event_data->mutable_query_id()->set_id(request.encrypted_event_data().query_id().id());`
</blockquote></details>

My recommendation will use the copy-assign operator because `request.encrypted_event_data().query_id()` is a const ref.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 71 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-Mj_7e6JDs2fDlsXJ4sm:-Mj_yD__9vd0s5QNkVj2:bqu9spg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e15ccc9e846a9dda97bcae3f6cc7a8b6d8bc58b0/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L71)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This function is getting pretty long -- would it be hard to pull the body of the for-loop out into a helper function?
</blockquote></details>

pulled it out into a different helper function
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-Mj_7yqg2N810AvBDvuL:-Mj_U3Ln65bkQ_RiLYRI:bd5j06c) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e15ccc9e846a9dda97bcae3f6cc7a8b6d8bc58b0/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L93)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think we can get rid of the loop here:

```
*result.mutable_decrypted_event_data() = *std::move(decrypt_event_data_response).mutable_decrypted_event_data();
```
</blockquote></details>

I don't think that works because it's adding to an existing list. Would love an easy one-liner to add to an existing repeated.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjWKGMcAbGolQkl9sIk:-Mj_JmKV7NCz_Lr1m_-R:buf7dp3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ed11a654d2b52e58fcda2c802484eea5772071e/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L62)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

My recommendation will use the copy-assign operator because `request.encrypted_event_data().query_id()` is a const ref.
</blockquote></details>

I didn't think `*foo->mutable_bar() = baz;` was copy-assign. Is it? If it is, what's the advantage over `CopyFrom`?

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-Mj_7yqg2N810AvBDvuL:-Mja5bIjEZpaJZgTX18K:brc0o4o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e15ccc9e846a9dda97bcae3f6cc7a8b6d8bc58b0/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L93)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I don't think that works because it's adding to an existing list. Would love an easy one-liner to add to an existing repeated.
</blockquote></details>

RepeatedPtrFieldBackInserter. https://github.com/google/private-membership/blob/main/private_membership/rlwe/batch/cpp/server/server.cc#L657
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 71 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-Mja5EeCESRWl58YmVcG:-Mja5EeCESRWl58YmVcH:b-rl96nq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5e25ffab17e0dd5356419bc20bbd782478cf97db/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L71)):*
> ```cpp
> }
> 
> absl::StatusOr<DecryptEventDataResponse> RemoveAesFromDecryptedQueryResult(
> ```

This (and some other stuff not declared in the headers) can be put in an anonymous namespace
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 90 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-Mja4uDV1I194jlYJ4k9:-Mja4uDV1I194jlYJ4kA:bvxd0bj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5e25ffab17e0dd5356419bc20bbd782478cf97db/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L90)):*
> ```cpp
>       *std::move(query_results.mutable_ciphertexts());
>   ASSIGN_OR_RETURN(DecryptEventDataResponse decrypt_event_data_response,
>                    DecryptEventData(decrypt_event_data_request));
> ```

Just `return DecryptEventData(decrypt_event_data_request);` No ASSIGN_OR_RETURN needed.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjWKGMcAbGolQkl9sIk:-Mja686k7uu_a6rwTwoM:b-4cwl7r) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ed11a654d2b52e58fcda2c802484eea5772071e/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L62)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I didn't think `*foo->mutable_bar() = baz;` was copy-assign. Is it? If it is, what's the advantage over `CopyFrom`?
</blockquote></details>

There's no inherent advantage. However: if `baz` turns out to be an xvalue, it'll use the move-assign operator. Furthermore, it reads more like normal C++ (`int x = 5;`)

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-Mj_7yqg2N810AvBDvuL:-MjaCxiYDsxBowhu-Q0Q:b7rf1il) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e15ccc9e846a9dda97bcae3f6cc7a8b6d8bc58b0/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L93)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

RepeatedPtrFieldBackInserter. https://github.com/google/private-membership/blob/main/private_membership/rlwe/batch/cpp/server/server.cc#L657
</blockquote></details>

```absl::c_move(*result.mutable_decrypted_event_data(), google::protobuf::RepeatedPtrFieldBackInserter(decrypt_event_data_response.mutable_decrypted_event_data()));```

like that? having issues with it. That example code doesn't looking like its merging.

I ended up stumbling upon MergeFrom. Shortens it to one line. Does that work for you?
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 71 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-Mja5EeCESRWl58YmVcG:-Mja7eOY96xWHENduvSp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5e25ffab17e0dd5356419bc20bbd782478cf97db/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L71)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This (and some other stuff not declared in the headers) can be put in an anonymous namespace
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 90 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-Mja4uDV1I194jlYJ4k9:-Mja7_4f4xYJeK0aPK_P:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5e25ffab17e0dd5356419bc20bbd782478cf97db/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L90)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Just `return DecryptEventData(decrypt_event_data_request);` No ASSIGN_OR_RETURN needed.
</blockquote></details>

Done.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjWKGMcAbGolQkl9sIk:-MjaE1p7CqV1oQqw8Loz:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ed11a654d2b52e58fcda2c802484eea5772071e/src/main/cc/wfa/panelmatch/client/privatemembership/event_data_decryptor.cc#L62)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

There's no inherent advantage. However: if `baz` turns out to be an xvalue, it'll use the move-assign operator. Furthermore, it reads more like normal C++ (`int x = 5;`)
</blockquote></details>

done

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-Mj_7yqg2N810AvBDvuL:-MjahB8SEuwk8tZTv4dX:b-ee9bo3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e15ccc9e846a9dda97bcae3f6cc7a8b6d8bc58b0/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L93)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

```absl::c_move(*result.mutable_decrypted_event_data(), google::protobuf::RepeatedPtrFieldBackInserter(decrypt_event_data_response.mutable_decrypted_event_data()));```

like that? having issues with it. That example code doesn't looking like its merging.

I ended up stumbling upon MergeFrom. Shortens it to one line. Does that work for you?
</blockquote></details>

I think you have the parameters backwards there. The BackInserter takes in the destination. The first argument to c_move is the source.

MergeFrom is fine too, though it will make copies. It doesn't have an `&&` overload.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 43 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjagyoG6GI1TErDzECz:-MjagyoG6GI1TErDzED-:b3vgx29) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3aa8eb47bbcb9ebb304d26b31a30d922899bc702/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L43)):*
> ```cpp
> using ::private_membership::batch::DecryptQueries;
> 
> namespace {
> ```

Please put the using aliases in the anonymous namespace too
___
*[src/test/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results_test.cc, line 200 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-Mjahe8U9kK0mB3VNcgz:-Mjahe8U9kK0mB3VNch-:bc3oij) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3aa8eb47bbcb9ebb304d26b31a30d922899bc702/src/test/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results_test.cc#L200)):*
> ```cpp
>                                                    serialized_bucket_result3};
> 
>   auto status = CreateTestDecryptQueriesRequest(kTestBuckets).status();
> ```

These two lines can be deleted -- they should have been removed before.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-Mj_7yqg2N810AvBDvuL:-MjdSiFfElqfHeeGzf_G:b-cxgnxd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e15ccc9e846a9dda97bcae3f6cc7a8b6d8bc58b0/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L93)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think you have the parameters backwards there. The BackInserter takes in the destination. The first argument to c_move is the source.

MergeFrom is fine too, though it will make copies. It doesn't have an `&&` overload.
</blockquote></details>

Done. Thx for the tips about c_move and also about how MergeFrom is making copies. good to know.
___
*[src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc, line 43 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-MjagyoG6GI1TErDzECz:-MjdS27a50lo5hBF_X5z:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3aa8eb47bbcb9ebb304d26b31a30d922899bc702/src/main/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results.cc#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please put the using aliases in the anonymous namespace too
</blockquote></details>

Done.
___
*[src/test/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results_test.cc, line 200 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115#-Mjahe8U9kK0mB3VNcgz:-MjdRWDh5EP_BFolhe9p:b1uyubn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3aa8eb47bbcb9ebb304d26b31a30d922899bc702/src/test/cc/wfa/panelmatch/client/privatemembership/decrypt_query_results_test.cc#L200)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

These two lines can be deleted -- they should have been removed before.
</blockquote></details>

yeah. i had meant to ask you why it was added in. missed it on the review but caught it on the rebase. done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/115)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
