### PR TITLE
add uncompressByKey

### PR DESCRIPTION
**Pull request by stevenwarejones**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 35 of 35 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122)* status: all files reviewed, 11 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/UncompressByKey.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-8uyc0InS6NpwMjBU:-Mk-8uyc0InS6NpwMjBV:b-3x3ubn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/main/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/UncompressByKey.kt#L28)):*
> ```Kotlin
> import org.wfanet.panelmatch.common.compression.Compressor
> 
> fun uncompressByKey(
> ```

"decompress"?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/UncompressByKey.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-9D3_38KzgcB6UZaj:-Mk-9D3_38KzgcB6UZak:b5d1g0o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/main/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/UncompressByKey.kt#L28)):*
> ```Kotlin
> import org.wfanet.panelmatch.common.compression.Compressor
> 
> fun uncompressByKey(
> ```

KDoc please
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/BUILD.bazel, line 6 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-9glUEveooYC6iIlA:-Mk-9glV7vBTEnLx-cF3:b-4ptxee) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/BUILD.bazel#L6)):*
> ```Starlark
>     default_testonly = True,
>     default_visibility = [
>         "//src/main/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/testing:__subpackages__",
> ```

Should we just move this stuff to `client/common/testing` if it's used by multiple subdirectories of `client`? This seems like it's a weird dependency.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/compression/BrotliCompressor.kt, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-9yhe6Rl-mS6RgRNK:-Mk-9yhf5maw4sidAMGD:b-kn3jwj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/main/kotlin/org/wfanet/panelmatch/common/compression/BrotliCompressor.kt#L34)):*
> ```Kotlin
>   }
> 
>   override fun uncompress(compressedEvents: ByteString): ByteString {
> ```

`decompress`?
___
*[src/main/kotlin/org/wfanet/panelmatch/common/compression/BrotliCompressor.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-A5L64CoVVIJROPNX:-Mk-A5L7E299AHUWlomm:b-mtp3r6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/main/kotlin/org/wfanet/panelmatch/common/compression/BrotliCompressor.kt#L42)):*
> ```Kotlin
>       Brotli.brotliDecompressWrapper(request.toByteArray())
>     }
>     val response = CompressResponse.parseFrom(serializedResponse)
> ```

`DecompressResponse`?
___
*[src/main/kotlin/org/wfanet/panelmatch/common/compression/Compressor.kt, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-A9ZY6OF02_2WBHmA:-Mk-A9ZY6OF02_2WBHmB:b-kn3jwj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/main/kotlin/org/wfanet/panelmatch/common/compression/Compressor.kt#L24)):*
> ```Kotlin
>   fun compress(events: ByteString): ByteString
> 
>   fun uncompress(compressedEvents: ByteString): ByteString
> ```

`decompress`?
___
*[src/main/kotlin/org/wfanet/panelmatch/common/compression/testing/AbstractCompressorTest.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-AEA2DOzbQDK7FhVf:-Mk-AEA2DOzbQDK7FhVg:b-svlhp9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/main/kotlin/org/wfanet/panelmatch/common/compression/testing/AbstractCompressorTest.kt#L25)):*
> ```Kotlin
> abstract class AbstractCompressorTest {
>   protected abstract val compressor: Compressor
>   protected abstract val events: CombinedEvents
> ```

Why does this need to be abstract? I feel like this class can just hardcode what this is.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/compression/testing/FakeCompressor.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-ATMZ4umvi2HlUsjx:-Mk-ATMZ4umvi2HlUsjy:bbr5hb9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/main/kotlin/org/wfanet/panelmatch/common/compression/testing/FakeCompressor.kt#L26)):*
> ```Kotlin
>     val x = CombinedEvents.parseFrom(events)
>     for (f in x.serializedEventsList) {
>       require(f.size() == 1) { "FakeCompressor only works on events of length 1" }
> ```

This kind of seems like an unnecessary restriction, no? Not sure I understand it
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/testing/FakeCompressorUncompressByKeyTest.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-AdYW4focEqbmN_L6:-Mk-AdYW4focEqbmN_L7:b-dgow5x) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/test/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/testing/FakeCompressorUncompressByKeyTest.kt#L27)):*
> ```Kotlin
> class FakeCompressorUncompressByKeyTest : AbstractUncompressByKeyTest() {
>   override val eventCompressorTrainer = FakeEventCompressorTrainer()
>   override val getCompressor =
> ```

`override val getCompressor = {  FakeCompressor() }` should work
___
*[src/test/kotlin/org/wfanet/panelmatch/common/compression/BrotliCompressorTest.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-B-r86WJPAPsqseBP:-Mk-B-r86WJPAPsqseBQ:b3gjijw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/test/kotlin/org/wfanet/panelmatch/common/compression/BrotliCompressorTest.kt#L27)):*
> ```Kotlin
> @RunWith(JUnit4::class)
> class BrotliCompressorTest : AbstractCompressorTest() {
>   val dictionary = "".toByteString()
> ```

`ByteString.EMPTY` is more canonical
___
*[src/test/kotlin/org/wfanet/panelmatch/common/compression/NoOpCompressorTest.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-BFgvDyULjlLfO8tE:-Mk-BFgvDyULjlLfO8tF:b-ux32iu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/test/kotlin/org/wfanet/panelmatch/common/compression/NoOpCompressorTest.kt#L26)):*
> ```Kotlin
> 
> @RunWith(JUnit4::class)
> class NoOpCompressorTest : AbstractCompressorTest() {
> ```

Why do we need both no-op and fake compressor?

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122)* status: all files reviewed, 11 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/UncompressByKey.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-8uyc0InS6NpwMjBU:-Mk2CNDs99dhxwE6SJU3:b8lzez) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/main/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/UncompressByKey.kt#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

"decompress"?
</blockquote></details>

Yeah - I dunno. The terms are synonymous and interchangeably used throughout the same documentation for various compressors. Do you have a strong opinion here?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/UncompressByKey.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-9D3_38KzgcB6UZaj:-Mk2ENi5-Zy7XNh15sEC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/main/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/UncompressByKey.kt#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

KDoc please
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/BUILD.bazel, line 6 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-9glUEveooYC6iIlA:-Mk2Ec-KEYPseMLbeOQO:bpdl4v) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/testing/BUILD.bazel#L6)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Should we just move this stuff to `client/common/testing` if it's used by multiple subdirectories of `client`? This seems like it's a weird dependency.
</blockquote></details>

Not sure. The reason it is the way it is is that preprocessing needs a preprocessed pipeline set up in order to properly process it. Otherwise, all the CompressorTrainers need to move over to common. I went ahead and did that but can undo if you don't like it.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/compression/testing/AbstractCompressorTest.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-AEA2DOzbQDK7FhVf:-Mk2ChtF7ksK-Q_Lum7m:beh2rt2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/main/kotlin/org/wfanet/panelmatch/common/compression/testing/AbstractCompressorTest.kt#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why does this need to be abstract? I feel like this class can just hardcode what this is.
</blockquote></details>

Different compressors might work differently on different pieces of text. For example, the brotli compressor performs worse than the no-op compressor given certain events. My concern is that tweaks in the event stream of one compressor test might end up causing the tests of another compressor in the future to fail.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/compression/testing/FakeCompressor.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-ATMZ4umvi2HlUsjx:-Mk2CrXe18-dMfgLLaM_:b-fvllv9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/main/kotlin/org/wfanet/panelmatch/common/compression/testing/FakeCompressor.kt#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This kind of seems like an unnecessary restriction, no? Not sure I understand it
</blockquote></details>

i copied this over from your existing FakeCompressor. You're right that it's an unnecessary restriction. I suggest if you want the Fake Compressor improved, I can add a TODO.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/testing/FakeCompressorUncompressByKeyTest.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-AdYW4focEqbmN_L6:-Mk2DRtV25xCoRW0v5E0:b-k2yhh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/test/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/testing/FakeCompressorUncompressByKeyTest.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`override val getCompressor = {  FakeCompressor() }` should work
</blockquote></details>

compiler complains about it not being a subtype of the overridden property since we aren't passing in a ByteString.
___
*[src/test/kotlin/org/wfanet/panelmatch/common/compression/BrotliCompressorTest.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-B-r86WJPAPsqseBP:-Mk2DI4HEhkmMogOFrrS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/test/kotlin/org/wfanet/panelmatch/common/compression/BrotliCompressorTest.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`ByteString.EMPTY` is more canonical
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/common/compression/NoOpCompressorTest.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-BFgvDyULjlLfO8tE:-Mk2D4Sq5Pmom7yChm7X:b-j2wh4z) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/test/kotlin/org/wfanet/panelmatch/common/compression/NoOpCompressorTest.kt#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why do we need both no-op and fake compressor?
</blockquote></details>

These were both already present. Fake is test-only. No-Op is something you set up for providers that might not want to use compression for whatever reason.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122)* status: 18 of 40 files reviewed, 11 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/testing/FakeCompressorUncompressByKeyTest.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-AdYW4focEqbmN_L6:-Mk2UCm77evK_Th11j7p:b-8veemp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/test/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/testing/FakeCompressorUncompressByKeyTest.kt#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

compiler complains about it not being a subtype of the overridden property since we aren't passing in a ByteString.
</blockquote></details>

{_: ByteString -> FakeCompressor() }

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122)* status: 18 of 40 files reviewed, 11 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/testing/FakeCompressorUncompressByKeyTest.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-AdYW4focEqbmN_L6:-Mk2f2U5Bx8wrTNse5fO:bej77sw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/test/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/testing/FakeCompressorUncompressByKeyTest.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

{_: ByteString -> FakeCompressor() }
</blockquote></details>

thx! done

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 21 of 22 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/UncompressByKey.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-8uyc0InS6NpwMjBU:-Mk2nj405n1_qyhr_C6H:bb710yj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/main/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/UncompressByKey.kt#L28)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Yeah - I dunno. The terms are synonymous and interchangeably used throughout the same documentation for various compressors. Do you have a strong opinion here?
</blockquote></details>

Nope
___
*[src/main/kotlin/org/wfanet/panelmatch/common/compression/testing/AbstractCompressorTest.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-AEA2DOzbQDK7FhVf:-Mk2oCyfBKsBLCxNICUo:b-ucfknh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/main/kotlin/org/wfanet/panelmatch/common/compression/testing/AbstractCompressorTest.kt#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Different compressors might work differently on different pieces of text. For example, the brotli compressor performs worse than the no-op compressor given certain events. My concern is that tweaks in the event stream of one compressor test might end up causing the tests of another compressor in the future to fail.
</blockquote></details>

Thanks!
___
*[src/main/kotlin/org/wfanet/panelmatch/common/compression/testing/FakeCompressor.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-ATMZ4umvi2HlUsjx:-Mk2oG94Cg1jsTKfqI8X:bjvy896) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/main/kotlin/org/wfanet/panelmatch/common/compression/testing/FakeCompressor.kt#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i copied this over from your existing FakeCompressor. You're right that it's an unnecessary restriction. I suggest if you want the Fake Compressor improved, I can add a TODO.
</blockquote></details>

Let's leave it as is

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/UncompressByKey.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/122#-Mk-8uyc0InS6NpwMjBU:-Mk2p6QFBbwQAdNq812c:b-7mro24) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/047544548e09cf66b8feb50f61e601ffcc3ea428/src/main/kotlin/org/wfanet/panelmatch/client/eventpostprocessing/UncompressByKey.kt#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Nope
</blockquote></details>

leaving as is for now. We can revisit later.

**Pull request merged**
