### PR TITLE
Clarify abstractions for ExchangeTasks, JNI, CommutativeEncryption, etc.

### PR DESCRIPTION
**Pull request by efoxepstein**
1. Adds a common base class for EncryptTask, DecryptTask, ReEncryptTask
to factor out common logic.

2. Injects CommutativeEncryption instance as a dependency instead of
relying on the concrete JNI implementation.

3. Converts tests for EncryptTask, DecryptTask, ReEncryptTask to use
mock CommutativeEncryption instances so actual values can be inspected.

4. Misc code cleanups.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 6 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15)* status: 6 of 20 files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/BUILD.bazel, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaFYymFBPScLl2P9O3s:-MaFYymGAA0iLNDHf34R:b-dwscsf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/BUILD.bazel#L4)):*
> ```Starlark
> 
> kt_jvm_test(
>     name = "EncryptTaskTest",
> ```

is there an easier way to just say all 3 of theses tests have the same dependencies?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaFZamkB20-6ZeUR-fe:-MaFZamkB20-6ZeUR-ff:beu6het) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d858901ba31c1c169b4a182683653f4e26aa0121/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt#L1)):*
> ```Kotlin
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

What are you thinking of integration tests? Would we want to leave this in as one of the integration tests? I'm seeing how you are setting up all the unit tests with dependency injection which is good but separate integration tests are also good.
___
*[src/test/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryptionTest.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaFZOV120eDcH5uReOn:-MaFZOV120eDcH5uReOo:b-prucb8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/test/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryptionTest.kt#L23)):*
> ```Kotlin
> @RunWith(JUnit4::class)
> class JniCommutativeEncryptionTest : AbstractCommutativeEncryptionTest() {
>   override val commutativeEncryption: CommutativeEncryption = JniCommutativeEncryption()
> ```

Why completely remove the old test? It is a base integration test to show that errors are properly bubbling up.
___
*[src/main/kotlin/org/wfanet/panelmatch/protocol/common/SharedInputs.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaFZkYsEuR7DO0JlaEp:-MaFZkYsEuR7DO0JlaEq:bod7kc0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/main/kotlin/org/wfanet/panelmatch/protocol/common/SharedInputs.kt#L27)):*
> ```Kotlin
> /** Deserializes [data] as a [SharedInputs] proto and returns its `data` field. */
> fun parseSerializedSharedInputs(data: ByteString): List<ByteString> {
>   return SharedInputs.parseFrom(data).dataList
> ```

is there an advantage to doing it this way?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15)* status: 6 of 20 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/BUILD.bazel, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaFYymFBPScLl2P9O3s:-MaFaNtp5Sx25jTjVKGf:b-nuol0a) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/BUILD.bazel#L4)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is there an easier way to just say all 3 of theses tests have the same dependencies?
</blockquote></details>

Yes -- the deps could be pulled out into a variable. But that makes some tooling worse, so in general we avoid that. I think it's OK to be pretty verbose in BUILD.bazel files. If we add a bunch more tests all with the same deps than maybe it will become worthwhile.

The other option is to try to pull out some of the common logic into a base test class. Then only the library for the base test class would need those deps. The tests look similar enough that this should be doable. I'll think about it.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaFZamkB20-6ZeUR-fe:-MaFasje7l7_WmrREzcG:b-qbbgg5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d858901ba31c1c169b4a182683653f4e26aa0121/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTasksTest.kt#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

What are you thinking of integration tests? Would we want to leave this in as one of the integration tests? I'm seeing how you are setting up all the unit tests with dependency injection which is good but separate integration tests are also good.
</blockquote></details>

I was imagining an integration test a little higher up (maybe at the wrapper level)? I definitely want to make sure the label translation logic is included in the integration test.
___
*[src/test/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryptionTest.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaFZOV120eDcH5uReOn:-MaFles0Cln9gZwIOffA:bw16bty) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/test/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryptionTest.kt#L23)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Why completely remove the old test? It is a base integration test to show that errors are properly bubbling up.
</blockquote></details>

Done -- please take a look.
___
*[src/main/kotlin/org/wfanet/panelmatch/protocol/common/SharedInputs.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaFZkYsEuR7DO0JlaEp:-MaFa9Bt7qqW7DSPMgYY:blk6dui) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/main/kotlin/org/wfanet/panelmatch/protocol/common/SharedInputs.kt#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is there an advantage to doing it this way?
</blockquote></details>

What are you referring to? The `.dataList` vs `.getDataList()`? IntelliJ (and me) prefers to use property accessor syntax when possible.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15)* status: 5 of 20 files reviewed, 12 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CommutativeEncryptionExchangeTask.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaTlY3G4Q4DNzUBbCZX:-MaTlY3G4Q4DNzUBbCZY:b-xh0jwt) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CommutativeEncryptionExchangeTask.kt#L25)):*
> ```Kotlin
>   private val commutativeEncryption: CommutativeEncryption
> ) : ExchangeTask {
>   abstract val inputLabel: String
> ```

why not have `inputDataLabel` and `inputCryptoKeyLabel` ? The cryptoKeyLabel could actually be set with a default value too but be overriden if needed.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CommutativeEncryptionExchangeTask.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaTlYg2E_odO6ui2tnp:-MaTlYg2E_odO6ui2tnq:b-c1vf6b) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CommutativeEncryptionExchangeTask.kt#L26)):*
> ```Kotlin
> ) : ExchangeTask {
>   abstract val inputLabel: String
>   abstract val outputLabel: String
> ```

`outputDataLabel`?
___
*[src/main/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryption.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaToLEQ5fgYOSbs13Mn:-MaToLEQ5fgYOSbs13Mo:ba1dndk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/main/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryption.kt#L33)):*
> ```Kotlin
>     request: ApplyCommutativeEncryptionRequest
>   ): ApplyCommutativeEncryptionResponse {
>     return ApplyCommutativeEncryptionResponse.parseFrom(
> ```

I've been thinking about this and I think the three functions here should all have try catch that throw a particular error indicating the error occurred in c++ or something. Right now, its just throwing runtime exception errors. I don't really like this. It should be something more specific. If it can't parse the protobuf from c++, we need a better error to indicate to the future developer that this error happened in c++ land.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptTaskTest.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaTn-oY3he3R-TJF-M4:-MaTn-oY3he3R-TJF-M5:b9qi8r1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptTaskTest.kt#L33)):*
> ```Kotlin
> private val KEY: ByteString = ByteString.copyFromUtf8("some-key")
> 
> private val PLAINTEXTS: List<ByteString> =
> ```

same here about if its really needed to explicitly declare type
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/EncryptTaskTest.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaTn48h18MMbEiCXAVg:-MaTn48h18MMbEiCXAVh:bps1s89) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/EncryptTaskTest.kt#L33)):*
> ```Kotlin
> private val KEY: ByteString = ByteString.copyFromUtf8("some-key")
> 
> private val PLAINTEXTS: List<ByteString> =
> ```

here too
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/EncryptTaskTest.kt, line 73 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaTnRaA5wWsN8fPZmHz:-MaTnRaA5wWsN8fPZmI-:b-lir4o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/EncryptTaskTest.kt#L73)):*
> ```Kotlin
>   fun `encryptTask with crypto error`() {
>     whenever(commutativeEncryption.encrypt(any(), any()))
>       .thenThrow(IllegalArgumentException("Something went wrong"))
> ```

does it throw an illegalargumentexception in reality? I think it actually throws a runtimeexception currently.
___
*[src/test/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryptionUtilityTest.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaTnoY-CHoaRddxm71x:-MaTnoY-CHoaRddxm71y:b-nojwhs) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d858901ba31c1c169b4a182683653f4e26aa0121/src/test/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryptionUtilityTest.kt#L32)):*
> ```Kotlin
>           .applyCommutativeEncryption(ApplyCommutativeEncryptionRequest.getDefaultInstance())
>       }
>     assertThat(e.message).contains("Failed to create the protocol cipher")
> ```

still not seeing this code inserted back in.
___
*[src/main/kotlin/org/wfanet/panelmatch/protocol/common/SharedInputs.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaFZkYsEuR7DO0JlaEp:-MaTlvtF63A_q_GL8VRq:bxw86wj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/main/kotlin/org/wfanet/panelmatch/protocol/common/SharedInputs.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What are you referring to? The `.dataList` vs `.getDataList()`? IntelliJ (and me) prefers to use property accessor syntax when possible.
</blockquote></details>

Hmm.... it seems like Java prefers the opposite which I had been looking at. Good to know.
___
*[src/main/kotlin/org/wfanet/panelmatch/protocol/common/testing/AbstractCommutativeEncryptionTest.kt, line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaTmcG6D2YlLKnJAj1L:-MaTmcG6D2YlLKnJAj1M:bf4z78t) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1b740c796e5c47758f26b7cf648c577b6039fee4/src/main/kotlin/org/wfanet/panelmatch/protocol/common/testing/AbstractCommutativeEncryptionTest.kt#L28)):*
> ```Kotlin
> import wfanet.panelmatch.protocol.protobuf.ReApplyCommutativeEncryptionRequest
> 
> private val PLAINTEXTS: List<ByteString> =
> ```

seems unneeded to declare the type that is easily found in the next line on the rhs, right?
___
*[src/main/kotlin/org/wfanet/panelmatch/protocol/common/testing/AbstractCommutativeEncryptionTest.kt, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaTmo3D4EU4mngmpQIe:-MaTmo3D4EU4mngmpQIf:bj2wsrw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1b740c796e5c47758f26b7cf648c577b6039fee4/src/main/kotlin/org/wfanet/panelmatch/protocol/common/testing/AbstractCommutativeEncryptionTest.kt#L37)):*
> ```Kotlin
>   )
> 
> private val CIPHERTEXTS: List<ByteString> =
> ```

same here - do we need to explicitly declare the type if its also on the rhs?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15)* status: 5 of 20 files reviewed, 12 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CommutativeEncryptionExchangeTask.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaTlY3G4Q4DNzUBbCZX:-MaUPuV7353ug4-RFVN9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CommutativeEncryptionExchangeTask.kt#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why not have `inputDataLabel` and `inputCryptoKeyLabel` ? The cryptoKeyLabel could actually be set with a default value too but be overriden if needed.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CommutativeEncryptionExchangeTask.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaTlYg2E_odO6ui2tnp:-MaUPuj-1gLwLF_YKc2i:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CommutativeEncryptionExchangeTask.kt#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`outputDataLabel`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryption.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaToLEQ5fgYOSbs13Mn:-MaUPwrw9Mxg2uidwYMb:bwtgglu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/main/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryption.kt#L33)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I've been thinking about this and I think the three functions here should all have try catch that throw a particular error indicating the error occurred in c++ or something. Right now, its just throwing runtime exception errors. I don't really like this. It should be something more specific. If it can't parse the protobuf from c++, we need a better error to indicate to the future developer that this error happened in c++ land.
</blockquote></details>

Sure -- done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptTaskTest.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaTn-oY3he3R-TJF-M4:-MaUShO_Ba63Xugqp3B_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptTaskTest.kt#L33)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

same here about if its really needed to explicitly declare type
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/EncryptTaskTest.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaTn48h18MMbEiCXAVg:-MaUShlp7Bj6h9GNJWS8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/EncryptTaskTest.kt#L33)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

here too
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/EncryptTaskTest.kt, line 73 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaTnRaA5wWsN8fPZmHz:-MaUSi8x5qbp12YOhGZz:b-xl72y) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/test/kotlin/org/wfanet/panelmatch/client/exchangetasks/EncryptTaskTest.kt#L73)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

does it throw an illegalargumentexception in reality? I think it actually throws a runtimeexception currently.
</blockquote></details>

Since `CommutativeEncryption` is an interface, it makes no promises about what runtime exceptions could be thrown. So -- theoretically some implementation of CommutativeEncryption could throw this.

Note that exceptions thrown from JNI are tested in `JniCommutativeEncryptionTest`.
___
*[src/test/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryptionUtilityTest.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaTnoY-CHoaRddxm71x:-MaUenTZ-0xQiz0yru-6:b-rj7gfa) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d858901ba31c1c169b4a182683653f4e26aa0121/src/test/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryptionUtilityTest.kt#L32)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

still not seeing this code inserted back in.
</blockquote></details>

This is tested in `JniCommutativeEncryptionTest`. Is there a test case you think is missing?
___
*[src/main/kotlin/org/wfanet/panelmatch/protocol/common/testing/AbstractCommutativeEncryptionTest.kt, line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaTmcG6D2YlLKnJAj1L:-MaUSgbV6cM1hsi0EiaE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1b740c796e5c47758f26b7cf648c577b6039fee4/src/main/kotlin/org/wfanet/panelmatch/protocol/common/testing/AbstractCommutativeEncryptionTest.kt#L28)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

seems unneeded to declare the type that is easily found in the next line on the rhs, right?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/protocol/common/testing/AbstractCommutativeEncryptionTest.kt, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaTmo3D4EU4mngmpQIe:-MaUSgrD4b56pWX9eCpk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1b740c796e5c47758f26b7cf648c577b6039fee4/src/main/kotlin/org/wfanet/panelmatch/protocol/common/testing/AbstractCommutativeEncryptionTest.kt#L37)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

same here - do we need to explicitly declare the type if its also on the rhs?
</blockquote></details>

Done.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15)* status: 4 of 21 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryptionTest.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaFZOV120eDcH5uReOn:-MaUqcYUEgq0w9KFFy4L:bf4emsn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/test/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryptionTest.kt#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Done -- please take a look.
</blockquote></details>

I must be missing something. where is the jniexception test? did you forget to commit?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15)* status: 4 of 21 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/test/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryptionTest.kt, line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15#-MaFZOV120eDcH5uReOn:-MaUzWBdBw2KsfEmkxOH:b-hoavp8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d28e9766a3dad5e2fcd6440467e4a48ee9bd86c7/src/test/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryptionTest.kt#L23)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I must be missing something. where is the jniexception test? did you forget to commit?
</blockquote></details>

Oops -- done.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/15)* status: 3 of 21 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

**Pull request merged**
