### PR TITLE
Migrate macros dependency to common_cpp

### PR DESCRIPTION
**Pull request by enfreck**
Migrate macros dependency to common_cpp

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/58)

### CODE REVIEW

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/58)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/BUILD.bazel, line 11 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/58#-MfE6jUC1Y_o93D9QpF1:-MfE6jUDDMka3nIsCpZX:bufx6l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/111aa1b0451d3ab9529ab5128366ccecb177fd47/src/main/cc/wfa/panelmatch/client/eventpreprocessing/BUILD.bazel#L11)):*
> ```Starlark
>     strip_include_prefix = "/src/main/cc",
>     deps = [
>         "//src/main/cc/wfa/panelmatch/common:macros",
> ```

Can this PR also delete `src/main/cc/wfa/panelmatch/common:macros`?

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/58)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/BUILD.bazel, line 11 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/58#-MfE6jUC1Y_o93D9QpF1:-MfEPg_34I7L0Qr_Jw_2:becjda6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/111aa1b0451d3ab9529ab5128366ccecb177fd47/src/main/cc/wfa/panelmatch/client/eventpreprocessing/BUILD.bazel#L11)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can this PR also delete `src/main/cc/wfa/panelmatch/common:macros`?
</blockquote></details>

I don't think I follow.  I don't think I have any dependencies on any macros.h besides common_cpp.  I get errors when trying to delete the panel-exchange-client macros.h file about the textual header.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/58)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/BUILD.bazel, line 11 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/58#-MfE6jUC1Y_o93D9QpF1:-MfE_ZD93XDyYEdGmUCT:bali308) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/111aa1b0451d3ab9529ab5128366ccecb177fd47/src/main/cc/wfa/panelmatch/client/eventpreprocessing/BUILD.bazel#L11)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

I don't think I follow.  I don't think I have any dependencies on any macros.h besides common_cpp.  I get errors when trying to delete the panel-exchange-client macros.h file about the textual header.
</blockquote></details>

Did you figure this one out?

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/58)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck and @jmorrrr)

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/58)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @jmorrrr)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/BUILD.bazel, line 11 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/58#-MfE6jUC1Y_o93D9QpF1:-MfJKzpnAxcnoyrHLoLi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/111aa1b0451d3ab9529ab5128366ccecb177fd47/src/main/cc/wfa/panelmatch/client/eventpreprocessing/BUILD.bazel#L11)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Did you figure this one out?
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/58)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmorrrr)

**Review by jmorrrr — APPROVED** [review]
> Reviewed 4 of 4 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/58)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Pull request merged**
