### PR TITLE
Update ExchangeTaskExecutor to use the latest proto

### PR DESCRIPTION
**Pull request by jonmolle**
Now it requires the entire ExchangeStep to run execute()

Fixes bug DE2

Reads the proper Step from the included serialized ExchangeWorkflow

Previously these were using a version of the proto that included the
Step details in ExchangeStep

There's a reasonable place to validate the ExchangeWorkflow in execute() now, as well

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/124)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/124)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/124#-Mk90Lb5-Al6BwX2yK_J:-Mk90Lb5-Al6BwX2yK_K:b-oylrw5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3355d22eaff44e44604101daae8a775a28bbbd40/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L72)):*
> ```Kotlin
> fun buildWorkflow(
>   testedStep: ExchangeWorkflow.Step,
>   edpName: String,
> ```

`dataProviderName` please
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 73 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/124#-Mk90Niz0ZMNxnqv_SdK:-Mk90Niz0ZMNxnqv_SdL:bmjr4z8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3355d22eaff44e44604101daae8a775a28bbbd40/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L73)):*
> ```Kotlin
>   testedStep: ExchangeWorkflow.Step,
>   edpName: String,
>   mpName: String
> ```

`modelProviderName` please
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/124#-Mk90E7r4jJ_iQSRqFye:-Mk90E7r4jJ_iQSRqFyf:bfoi73j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3355d22eaff44e44604101daae8a775a28bbbd40/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L75)):*
> ```Kotlin
>   mpName: String
> ): ExchangeWorkflow {
>   return ExchangeWorkflow.newBuilder().addSteps(testedStep).build()
> ```

Can you please use the Kotlin DSL for building protos?

```
return exchangeWorkflow { steps += testedStep }
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 123 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/124#-Mk90PTX-hnBKxU3MJBT:-Mk90PTX-hnBKxU3MJBU:bqd5k8b) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3355d22eaff44e44604101daae8a775a28bbbd40/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L123)):*
> ```Kotlin
>   testedStep: ExchangeWorkflow.Step
> ): ExchangeStep {
>   return ExchangeStep.newBuilder()
> ```

Ditto:

```
return exchangeStep {
  this.stepIndex = stepIndex
  this.name = name
  signedExchangeWorkflow = signedExchangeWorkflow {
    serializedWorkflow = ...
  }
}
```

**Review by stevenwarejones — APPROVED** [review]
just take care of the DSL stuff and I'm good

> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/124#-:-Mk9oaZe8MO37o43QQ00:bdz0l15)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1 and @jonmolle)

**Review by jonmolle — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/124#-:-MkEvpXm4HnN6E3Hq7Ok:bb6un1j)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/124#-Mk90Lb5-Al6BwX2yK_J:-MkE6FZwBMyqk2rEESfK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3355d22eaff44e44604101daae8a775a28bbbd40/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L72)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`dataProviderName` please
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 73 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/124#-Mk90Niz0ZMNxnqv_SdK:-MkE6FtO0V2Jc-QsAPb0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3355d22eaff44e44604101daae8a775a28bbbd40/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L73)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`modelProviderName` please
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/124#-Mk90E7r4jJ_iQSRqFye:-MkEvrae8Pb0fGkFZqtk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3355d22eaff44e44604101daae8a775a28bbbd40/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L75)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you please use the Kotlin DSL for building protos?

```
return exchangeWorkflow { steps += testedStep }
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 123 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/124#-Mk90PTX-hnBKxU3MJBT:-MkEvsH03beAvimI4H7R:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3355d22eaff44e44604101daae8a775a28bbbd40/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L123)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto:

```
return exchangeStep {
  this.stepIndex = stepIndex
  this.name = name
  signedExchangeWorkflow = signedExchangeWorkflow {
    serializedWorkflow = ...
  }
}
```
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/124)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @jonmolle)

___
*[src/main/proto/wfa/panelmatch/protocol/exchangesteps/exchangesteps.proto, line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/124#-MkEwGnE4Raw0ra_Z8Ie:-MkEwGnF8BhlLEE2SNMD:bdq7tzr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/22cd242b05c9038d116417cfaac0157f12847761/src/main/proto/wfa/panelmatch/protocol/exchangesteps/exchangesteps.proto#L32)):*
> ```protobuf
> // can verify that the proper number of chunks (and no duplicate chunks) are
> // included.
> message MultipartInput {
> ```

This doesn't really look like it belongs in this PR?

**Review by efoxepstein — APPROVED** [review]
:lgtm: once removing the proto that doesn't seem like it belongs

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/124#-:-MkEwTTH1eI5EJ1ZvO4P:b-ogyim5)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @jonmolle)

**Review by jonmolle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/124)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, and @stevenwarejones)

___
*[src/main/proto/wfa/panelmatch/protocol/exchangesteps/exchangesteps.proto, line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/124#-MkEwGnE4Raw0ra_Z8Ie:-MkIaT5GDdXSAxZlz_V9:ba9o4t8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/22cd242b05c9038d116417cfaac0157f12847761/src/main/proto/wfa/panelmatch/protocol/exchangesteps/exchangesteps.proto#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This doesn't really look like it belongs in this PR?
</blockquote></details>

It does not, fixed

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/124)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Pull request merged**
