### PR TITLE
Add cue file for example daemon

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250)* status: all files reviewed, 5 unresolved discussions (waiting on @wangyaopw and @yunyeng)

___
*[src/main/docker/BUILD.bazel, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr4-Ij1DfMY3wh2of0X:-Mr4-Ij1DfMY3wh2of0Y:bomtkru) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/635b58c6bd0c7825c30fd8bb49f84a7f0e6f5135/src/main/docker/BUILD.bazel#L4)):*
> ```Starlark
> load(":images.bzl", "ALL_GKE_IMAGES")
> 
> package(default_testonly = True)  #TODO: delete when InMemoryKeyStore and FakeHybridCipher are not used.
> ```

I think you can remove this line?
___
*[src/main/docker/images.bzl, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr40okr7vdBhNkwU5rZ:-Mr40okr7vdBhNkwU5r_:b-k17f4b) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/635b58c6bd0c7825c30fd8bb49f84a7f0e6f5135/src/main/docker/images.bzl#L27)):*
> ```Starlark
>         name = "google_cloud_example_daemon_image",
>         image = "//src/main/kotlin/org/wfanet/panelmatch/client/deploy/example/gcloud:google_cloud_example_daemon_image",
>         repository = _PREFIX + "/example-daemon",
> ```

Maybe `/example-panel-exchange-daemon`?
___
*[src/main/k8s/BUILD.bazel, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr4-ZUJBlunEZPiIi2A:-Mr4-ZUJBlunEZPiIi2B:b-9ycpc5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/635b58c6bd0c7825c30fd8bb49f84a7f0e6f5135/src/main/k8s/BUILD.bazel#L44)):*
> ```Starlark
>     name = "k8s_deployer",
>     packages = [
>         "//src/main/kotlin/org/wfanet/measurement/tools/...",
> ```

This needs updating I would guess
___
*[src/main/k8s/example_daemon_gke.cue, line 116 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr40VATAXoL0Ygg1jf4:-Mr40VATAXoL0Ygg1jf5:big6ikl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/635b58c6bd0c7825c30fd8bb49f84a7f0e6f5135/src/main/k8s/example_daemon_gke.cue#L116)):*
> ```CUE
> 
> example_daemon_deployment: "example_daemon_deployment": #Deployment & {
>   _args: [
> ```

We should probably have variables with tags for some of these flags
___
*[src/main/k8s/macros.bzl, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr40bfa8dtftZMU4WJB:-Mr40bfa8dtftZMU4WJC:bx74dfy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/635b58c6bd0c7825c30fd8bb49f84a7f0e6f5135/src/main/k8s/macros.bzl#L19)):*
> ```Starlark
> load("@wfa_measurement_system//build/cue:defs.bzl", "cue_export")
> 
> def cue_dump(name, srcs, cue_tags = None):
> ```

Instead of defining this file here can we just reference `@wfa_measurement_system/src/main/k8s:macros.bzl`?

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250)* status: all files reviewed, 4 unresolved discussions (waiting on @wangyaopw and @yunyeng)

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250)* status: 6 of 7 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @wangyaopw)

___
*[src/main/docker/BUILD.bazel, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr4-Ij1DfMY3wh2of0X:-Mr4DjfMAt9swibDaeaN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/635b58c6bd0c7825c30fd8bb49f84a7f0e6f5135/src/main/docker/BUILD.bazel#L4)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think you can remove this line?
</blockquote></details>

Done.
___
*[src/main/k8s/BUILD.bazel, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr4-ZUJBlunEZPiIi2A:-Mr4DmGD-4M5S2M5Ml5C:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/635b58c6bd0c7825c30fd8bb49f84a7f0e6f5135/src/main/k8s/BUILD.bazel#L44)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This needs updating I would guess
</blockquote></details>

Done.
___
*[src/main/k8s/example_daemon_gke.cue, line 116 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr40VATAXoL0Ygg1jf4:-Mr4DmwQ3Z1LiEZCI1X_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/635b58c6bd0c7825c30fd8bb49f84a7f0e6f5135/src/main/k8s/example_daemon_gke.cue#L116)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

We should probably have variables with tags for some of these flags
</blockquote></details>

Done.
___
*[src/main/k8s/macros.bzl, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr40bfa8dtftZMU4WJB:-Mr4DndK7pZcJYhpKST5:b57mh44) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/635b58c6bd0c7825c30fd8bb49f84a7f0e6f5135/src/main/k8s/macros.bzl#L19)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Instead of defining this file here can we just reference `@wfa_measurement_system/src/main/k8s:macros.bzl`?
</blockquote></details>

One suggestion was creating common-cue. WDYT? @wangyaopw @sanjayvas

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

**Review by wangyaopw — CHANGES_REQUESTED** [review]
Can you try deploying this daemon to GKE to verify that it actually works? Otherwise, the example doesn't  really help.
You can use the google GCP project before you are added to the WFA project.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-:-Mr4EgqLD2sKWGarRa6G:b1gu4pj)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @yunyeng)

___
*[build/variables.bzl, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr4Aa8mCDL0Bq9eTwmb:-Mr4Aa8n7kMv7nbaFX79:b-qfnlo3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f5a6c72c242fa537c7e2f0c9de1d7a821b29f536/build/variables.bzl#L27)):*
> ```Starlark
>     container_registry = "gcr.io",
>     # Common prefix of all images.
>     repository_prefix = "halo-panel-dev",
> ```

There is no such project.

If you only want to give an example, replace it with `TBD` or `name_of_the_gcp_project`

All values used in cross-media-measurement are real ones.



_Code quote:_
```Starlark
halo-panel-dev
```
___
*[build/variables.bzl, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr4CCVICUk0yLyphUYx:-Mr4CCVICUk0yLyphUYy:bgb8q0s) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f5a6c72c242fa537c7e2f0c9de1d7a821b29f536/build/variables.bzl#L36)):*
> ```Starlark
> )
> 
> EXAMPLE_DAEMON_CONFIG = struct(
> ```

If there is only one cue_dump using this, maybe just hardcode the value there.  No need to define them in the variables.bzl



_Code quote:_
```Starlark
EXAMPLE_DAEMON_CONFIG 
```
___
*[src/main/k8s/BUILD.bazel, line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr4FZDDAPjcXq1IRJjR:-Mr4FZDDAPjcXq1IRJjS:b8e3pv3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/09b89f0523fa93d93a518491bca91d7eb1405a20/src/main/k8s/BUILD.bazel#L26)):*
> ```Starlark
> 
> filegroup(
>     name = "all_archives",
> ```

This is not used anywhere in this PR.

If you have another PR that uses it. Either move this to that PR or merge these two PRs.
___
*[src/main/k8s/example_daemon_gke.cue, line 116 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr40VATAXoL0Ygg1jf4:-Mr4DPM1AY4qKUFlvLRB:b-bmjgzh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/635b58c6bd0c7825c30fd8bb49f84a7f0e6f5135/src/main/k8s/example_daemon_gke.cue#L116)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

We should probably have variables with tags for some of these flags
</blockquote></details>

Yep.

See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/k8s/dev/kingdom_gke.cue#L24 for example.
___
*[src/main/k8s/example_daemon_gke.cue, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr4CpOz20wYu53WOA18:-Mr4CpOz20wYu53WOA19:bgbz4i7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f5a6c72c242fa537c7e2f0c9de1d7a821b29f536/src/main/k8s/example_daemon_gke.cue#L40)):*
> ```CUE
> #AppName: "panel-exchange"
> 
> #Deployment: {
> ```

Is it possible to import the base.cue from cross-media-measurement?

If not, this template should be defined outside this file.



_Code quote:_
```CUE
#Deployment: 
```
___
*[src/main/k8s/example_daemon_gke.cue, line 118 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr4Df1r2Ysr6ay1uGL1:-Mr4Df1r2Ysr6ay1uGL2:b-syxwrk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f5a6c72c242fa537c7e2f0c9de1d7a821b29f536/src/main/k8s/example_daemon_gke.cue#L118)):*
> ```CUE
>     "--storage-signing-algorithm=EC",
>     "--task-timeout=24h",
>     "--exchange-api-target=localhost",
> ```

All configurable values should be from the tags I think.



_Code quote:_
```CUE
localhost
```

**Review by wangyaopw — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @yunyeng)

___
*[src/main/k8s/macros.bzl, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr40bfa8dtftZMU4WJB:-Mr4H0KJCcjsOEk4rj7k:bg704sf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/635b58c6bd0c7825c30fd8bb49f84a7f0e6f5135/src/main/k8s/macros.bzl#L19)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

One suggestion was creating common-cue. WDYT? @wangyaopw @sanjayvas 
</blockquote></details>

You don't need to define a `cue_dump`, you can use `cue_export` directly in src/main/k8s/BUILD.bazel, which is already in common-jvm.

or you can add the `cue_dump`definition next to the `cue_export` in common-jvm

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250)* status: 3 of 8 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @SanjayVas, @wangyaopw, and @yunyeng)

___
*[src/main/k8s/macros.bzl, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr40bfa8dtftZMU4WJB:-Mr4QIjGDdeq-XU-0idb:b4zcxep) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/635b58c6bd0c7825c30fd8bb49f84a7f0e6f5135/src/main/k8s/macros.bzl#L19)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

You don't need to define a `cue_dump`, you can use `cue_export` directly in src/main/k8s/BUILD.bazel, which is already in common-jvm.

or you can add the `cue_dump`definition next to the `cue_export` in common-jvm
</blockquote></details>

+1 to Yao's suggestion

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 2 of 4 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @yunyeng)

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @SanjayVas, @wangyaopw, and @yunyeng)

___
*[build/variables.bzl, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr4Aa8mCDL0Bq9eTwmb:-Mr4TGHI-bfX2P2ryWe6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f5a6c72c242fa537c7e2f0c9de1d7a821b29f536/build/variables.bzl#L27)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

There is no such project.

If you only want to give an example, replace it with `TBD` or `name_of_the_gcp_project`

All values used in cross-media-measurement are real ones.
</blockquote></details>

Done.
___
*[build/variables.bzl, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr4CCVICUk0yLyphUYx:-Mr4THu-CFUZgN6lRz_A:b-vbcaek) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f5a6c72c242fa537c7e2f0c9de1d7a821b29f536/build/variables.bzl#L36)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

If there is only one cue_dump using this, maybe just hardcode the value there.  No need to define them in the variables.bzl
</blockquote></details>

We should have one for EDP and one for MP. So this can be utilized.
___
*[src/main/k8s/BUILD.bazel, line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr4FZDDAPjcXq1IRJjR:-Mr4TMLc0JKsLBHTrVRV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/09b89f0523fa93d93a518491bca91d7eb1405a20/src/main/k8s/BUILD.bazel#L26)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

This is not used anywhere in this PR.

If you have another PR that uses it. Either move this to that PR or merge these two PRs.
</blockquote></details>

Done.
___
*[src/main/k8s/example_daemon_gke.cue, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250#-Mr4CpOz20wYu53WOA18:-Mr4TNtSEH7qizeRhiR8:b-b1ml3c) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f5a6c72c242fa537c7e2f0c9de1d7a821b29f536/src/main/k8s/example_daemon_gke.cue#L40)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Is it possible to import the base.cue from cross-media-measurement?

If not, this template should be defined outside this file.


</blockquote></details>

Moved it outisde.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/250)* status: all files reviewed, 5 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @yunyeng)

**Pull request closed without merging**
