### PR TITLE
Add additional Dataflow flags

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/310)

### CODE REVIEW

**Review by robinsons — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/310)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/k8s/dev/example_daemon_gke.cue, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/310#-N-ZUH92-GvNRV1p5uY1:-N-ZUH92-GvNRV1p5uY2:b-quf4vo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4a82c2c7c366f8b10edb38bf165288a3c2b5c5c/src/main/k8s/dev/example_daemon_gke.cue#L82)):*
> ```CUE
> 		"--dataflow-temp-location=\(dataflow.tempLocation)",
> 		"--dataflow-worker-machine-type=\(dataflow.workerMachineType)",
> 		"--dataflow-disk-size=30",
> ```

Should `--dataflow-disk-size` have a corresponding entry in the `dataflow` map above, similar to what the worker machine type has?

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/310)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/310)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @robinsons and @stevenwarejones)

___
*[src/main/k8s/dev/example_daemon_gke.cue, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/310#-N-ZUH92-GvNRV1p5uY1:-N-_hPaR9sEIRAt5rt5j:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a4a82c2c7c366f8b10edb38bf165288a3c2b5c5c/src/main/k8s/dev/example_daemon_gke.cue#L82)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Should `--dataflow-disk-size` have a corresponding entry in the `dataflow` map above, similar to what the worker machine type has?
</blockquote></details>

Done.

**Review by robinsons — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/310)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
