### PR TITLE
Adds Batching DoFn

### PR DESCRIPTION
**Pull request by jmorrrr**
Adds DoFn to split inputted data into fixed size MutableList<T> to prepare for encryption

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42)

### CODE REVIEW

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @jmorrrr)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt, line 71 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-MeWL8kf1v1IHsovNRol:-MeWL8kf1v1IHsovNRom:b-uz61iq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e9ef89bb8993ef9db9fb84856e3a21fef7e05495/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt#L71)):*
> ```Kotlin
>     context: ProcessContext,
>   ) {
>     size += getElementByteSize(element)
> ```

Look at SerializableFunction's API: https://beam.apache.org/releases/javadoc/2.30.0/org/apache/beam/sdk/transforms/SerializableFunction.html

You can see it has this `apply` method -- you want to use that here: `getElementByteSize.apply(element)`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt, line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-MeWL1kiBpqNnv8GDZ6q:-MeWL1kiBpqNnv8GDZ6r:b-83og4a) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e9ef89bb8993ef9db9fb84856e3a21fef7e05495/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt#L79)):*
> ```Kotlin
>     buffer.add(element)
>   }
>   //Do I Implement this here?
> ```

Nope!
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt, line 93 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-MeWLHPY5qU1GovZGkgK:-MeWLHPY5qU1GovZGkgL:b-ha2jxa) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e9ef89bb8993ef9db9fb84856e3a21fef7e05495/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt#L93)):*
> ```Kotlin
>     context: FinishBundleContext
>   ) {
>     if (batchCells > 0) {
> ```

`finishBundle` should just output `buffer` if it's not empty

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @jmorrrr)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-MejyZiiDRjydQfXZbHP:-MejyZiiDRjydQfXZbHQ:b-i1xgnd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/05b76ebc0a7f98e485d575a3a6cd8556ca239cbf/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt#L38)):*
> ```Kotlin
>     if (size + currElementSize > maxByteSize) {
>       c.output(buffer)
>       buffer.clear()
> ```

Can you either (a) change `var buffer` to `val buffer` or (b) change this line to `buffer = mutableListOf()`?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt, line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mejyo8f3BcufnYtYBcN:-Mejyo8f3BcufnYtYBcO:b-x07wxa) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/05b76ebc0a7f98e485d575a3a6cd8556ca239cbf/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt#L50)):*
> ```Kotlin
>   fun FinishBundle(context: FinishBundleContext) {
>     if (!buffer.isEmpty()) {
>       context.output(buffer, Instant.now(), GlobalWindow.INSTANCE)
> ```

Please clear buffer and size after this.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 9 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-MejywEd3KyrgYJBtseW:-MejywEd3KyrgYJBtseX:b-1m9vzo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/05b76ebc0a7f98e485d575a3a6cd8556ca239cbf/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L9)):*
> ```Starlark
>     srcs = glob(
>         ["*.kt"],
>         exclude = ["BatchingDoFn*.kt"],
> ```

This can just be `exclude = ["BatchingDoFn.kt"],` (no star needed)

**Review by jmorrrr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-MejyZiiDRjydQfXZbHP:-MekMQ3W3sUdosMmQETI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/05b76ebc0a7f98e485d575a3a6cd8556ca239cbf/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you either (a) change `var buffer` to `val buffer` or (b) change this line to `buffer = mutableListOf()`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt, line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mejyo8f3BcufnYtYBcN:-MekMY5fDeNl2IjyMGO0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/05b76ebc0a7f98e485d575a3a6cd8556ca239cbf/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt#L50)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please clear buffer and size after this.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 9 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-MejywEd3KyrgYJBtseW:-MekMcL11IxW4gVxEAgO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/05b76ebc0a7f98e485d575a3a6cd8556ca239cbf/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L9)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This can just be `exclude = ["BatchingDoFn.kt"],` (no star needed)
</blockquote></details>

Done.

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 1 of 6 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42)* status: all files reviewed, 1 unresolved discussion (waiting on @jmorrrr)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-MekR14H2BqPMGuRocxx:-MekR14I2UyhjYIj5AtR:bdztd7j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cc23eac20e95e1a1d8fa1c9fc9915bd282c9dba1/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt#L32)):*
> ```Kotlin
>   fun process(c: ProcessContext) {
>     val currElementSize: Int = getElementByteSize.apply(c.element())
>     if (currElementSize > maxByteSize) {
> ```

This should be `>=` I think -- if it's exactly the max size, you can take a shortcut by just emitting a list of just this one item

**Review by jmorrrr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-MekR14H2BqPMGuRocxx:-Meka8ZK0hycaQplPIk3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/cc23eac20e95e1a1d8fa1c9fc9915bd282c9dba1/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This should be `>=` I think -- if it's exactly the max size, you can take a shortcut by just emitting a list of just this one item
</blockquote></details>

Done.

**Review by efoxepstein — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmorrrr)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42)* status: all files reviewed, 6 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt, line 37 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf3t__3Elt3UpipCTtb:-Mf3t__3Elt3UpipCTtc:ba9l0wn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8e4be5c33b3fcf068aa1d2b48c991cf0b3724f17/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt#L37)):*
> ```Kotlin
>     }
>     if (size + currElementSize > maxByteSize) {
>       val buffercopy = buffer
> ```

This doesn't actually do anything. You can keep it as `c.output(buffer)`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt, line 51 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf3uhzqEIGV8cRaweCx:-Mf3uhzqEIGV8cRaweCy:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8e4be5c33b3fcf068aa1d2b48c991cf0b3724f17/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt#L51)):*
> ```Kotlin
>   fun FinishBundle(context: FinishBundleContext) {
>     if (!buffer.isEmpty()) {
>       val buffercopy = buffer
> ```

Ditto
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt, line 39 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf3upwE5MgAs-gf84ob:-Mf3upwE5MgAs-gf84oc:bxbcbdr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8e4be5c33b3fcf068aa1d2b48c991cf0b3724f17/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt#L39)):*
> ```Kotlin
>       TestStream.create(StringUtf8Coder.of())
>         .addElements("1", "2", "3")
>         .advanceWatermarkToInfinity()
> ```

Can you make a helper function like:

```
private fun makeSingleBundlePCollection(item: String, vararg items: String): PCollection<String> {
  val testStream = TestStream.create(StringUft8Coder.of()).addElements(item, *items).advanceWatermarkToInfinity()
  return pipeline.apply(testStream)
}

```
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt, line 55 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf3w92lCnZXBCL6JwUV:-Mf3w92m1Reg5FpZTceW:b-6obu5b) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8e4be5c33b3fcf068aa1d2b48c991cf0b3724f17/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt#L55)):*
> ```Kotlin
>         .addElements("1", "2", "3")
>         .advanceWatermarkToInfinity()
>     val batchSize2 = 3
> ```

Can you get rid of all the numbers after the variable names? They're not necessary and just add clutter.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt, line 72 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf3w44mDtW9zXE7hxZA:-Mf3w44mDtW9zXE7hxZB:bkxakda) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8e4be5c33b3fcf068aa1d2b48c991cf0b3724f17/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt#L72)):*
> ```Kotlin
>     val doFn3: DoFn<String, MutableList<String>> = BatchingDoFn(batchSize3, StringLengthSize)
>     var result3: PCollection<MutableList<String>>
>     pipeline.apply(testStream3).apply { result3 = this.apply(ParDo.of(doFn3)) }
> ```

This is pretty weird. How about: `val result3 = pipeline.apply(testStream3).apply(ParDo.of(doFn3))`
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt, line 87 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf3wE5aBnUrAMN8-Oo8:-Mf3wE5aBnUrAMN8-Oo9:b-yc0sft) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8e4be5c33b3fcf068aa1d2b48c991cf0b3724f17/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt#L87)):*
> ```Kotlin
>     var result4: PCollection<MutableList<String>>
>     pipeline.apply(testStream4).apply { result4 = this.apply(ParDo.of(doFn4)) }
>     pipeline.run()
> ```

I don't think that you need to call `pipeline.run()`

**Review by enfreck — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42)* status: all files reviewed, 7 unresolved discussions (waiting on @jmorrrr and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt, line 22 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf3znFa9Li2Obqu9R1e:-Mf3znFa9Li2Obqu9R1f:b-tmoxvx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8e4be5c33b3fcf068aa1d2b48c991cf0b3724f17/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt#L22)):*
> ```Kotlin
> import org.joda.time.Instant
> 
> class BatchingDoFn<T>(
> ```

Class or function level comment(s)

**Review by jmorrrr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42)* status: all files reviewed, 7 unresolved discussions (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt, line 22 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf3znFa9Li2Obqu9R1e:-Mf4FWA86k940sCNxn8U:bagqci9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8e4be5c33b3fcf068aa1d2b48c991cf0b3724f17/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt#L22)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Class or function level comment(s)
</blockquote></details>

Done.git sat
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt, line 37 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf3t__3Elt3UpipCTtb:-Mf3wXeV6Ry0wKZZIhKW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8e4be5c33b3fcf068aa1d2b48c991cf0b3724f17/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This doesn't actually do anything. You can keep it as `c.output(buffer)`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt, line 51 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf3uhzqEIGV8cRaweCx:-Mf3wYGDDA1zVZ6rdw56:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8e4be5c33b3fcf068aa1d2b48c991cf0b3724f17/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt#L51)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt, line 39 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf3upwE5MgAs-gf84ob:-Mf4643D5u0Ytj9F2hBA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8e4be5c33b3fcf068aa1d2b48c991cf0b3724f17/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you make a helper function like:

```
private fun makeSingleBundlePCollection(item: String, vararg items: String): PCollection<String> {
  val testStream = TestStream.create(StringUft8Coder.of()).addElements(item, *items).advanceWatermarkToInfinity()
  return pipeline.apply(testStream)
}

```
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt, line 55 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf3w92lCnZXBCL6JwUV:-Mf3wo4i7SS2q3N56Sc6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8e4be5c33b3fcf068aa1d2b48c991cf0b3724f17/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt#L55)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you get rid of all the numbers after the variable names? They're not necessary and just add clutter.
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt, line 72 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf3w44mDtW9zXE7hxZA:-Mf465D00gA7TI7l6a-D:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8e4be5c33b3fcf068aa1d2b48c991cf0b3724f17/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt#L72)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is pretty weird. How about: `val result3 = pipeline.apply(testStream3).apply(ParDo.of(doFn3))`
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt, line 87 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf3wE5aBnUrAMN8-Oo8:-Mf3wkQx3FPv5JPboO_7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8e4be5c33b3fcf068aa1d2b48c991cf0b3724f17/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt#L87)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I don't think that you need to call `pipeline.run()`
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42)* status: all files reviewed, 5 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt, line 23 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf4GtE56LZygKaDd7Ba:-Mf4GtE56LZygKaDd7Bb:bog88rv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ab2d193e26895dcf5033435d540c9149ea959188/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt#L23)):*
> ```Kotlin
> 
> /**
>  * Takes in elements <T>, whose size is determined by SerializableFunction<T,Int>, and batches them
> ```

How about something like:

```
/**
 * Batches [T]s into lists.
 *
 * The sum of [getElementByteSize] involved on each item of an output list is at most [maxByteSize].
 */
```
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt, line 65 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf4I3jWD_mSfnScj2S-:-Mf4I3jWD_mSfnScj2S0:b-2dpy9g) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ab2d193e26895dcf5033435d540c9149ea959188/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt#L65)):*
> ```Kotlin
> 
>   @Test
>   fun multipleBundles() {
> ```

I think this won't quite test what you want to test because each call to `makeSingleBundleParDoDoFn` creates a new BatchingDoFn instance.

Instead, I think you want:

```
    val testStream =
      TestStream.create(StringUtf8Coder.of())
          .addElements("stuff", "in", "bundle", "one")
          .addElements("stuff", "in", "bundle", "two")
          .addElements("and", "bundle", "three")
          .advanceWatermarkToInfinity()

```
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt, line 74 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf4HmHy5wVm0vf5lg3J:-Mf4HmHy5wVm0vf5lg3K:b-91oy2g) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ab2d193e26895dcf5033435d540c9149ea959188/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt#L74)):*
> ```Kotlin
>   }
> 
>   private fun makeSingleBundleParDoDoFn(
> ```

This name is a little confusing to me. How about `batchSingleBundle`?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt, line 83 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf4Hd4a3izhjtYm05Q1:-Mf4Hd4a3izhjtYm05Q2:b-6uwyj8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ab2d193e26895dcf5033435d540c9149ea959188/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt#L83)):*
> ```Kotlin
>     return pipeline.apply(testStream).apply(ParDo.of(BatchingDoFn(batchSize, StringLengthSize)))
>   }
>   private fun makeEmptyBundleParDoDoFn(batchSize: Int): PCollection<MutableList<String>> {
> ```

This one can be simpler -- it's just `pcollectionOf<String>("Empty")` I think

**Review by jmorrrr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt, line 23 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf4GtE56LZygKaDd7Ba:-Mf4O-fvBW0tG3T1Bu0h:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ab2d193e26895dcf5033435d540c9149ea959188/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFn.kt#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

How about something like:

```
/**
 * Batches [T]s into lists.
 *
 * The sum of [getElementByteSize] involved on each item of an output list is at most [maxByteSize].
 */
```
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt, line 65 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf4I3jWD_mSfnScj2S-:-Mf4NYsGCJHZnKtFiQXs:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ab2d193e26895dcf5033435d540c9149ea959188/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt#L65)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think this won't quite test what you want to test because each call to `makeSingleBundleParDoDoFn` creates a new BatchingDoFn instance.

Instead, I think you want:

```
    val testStream =
      TestStream.create(StringUtf8Coder.of())
          .addElements("stuff", "in", "bundle", "one")
          .addElements("stuff", "in", "bundle", "two")
          .addElements("and", "bundle", "three")
          .advanceWatermarkToInfinity()

```
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt, line 74 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf4HmHy5wVm0vf5lg3J:-Mf4Iy4eAvmPOrWA_UGM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ab2d193e26895dcf5033435d540c9149ea959188/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt#L74)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This name is a little confusing to me. How about `batchSingleBundle`?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt, line 83 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-Mf4Hd4a3izhjtYm05Q1:-Mf4JnnbAuj1QuiGRE9F:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ab2d193e26895dcf5033435d540c9149ea959188/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BatchingDoFnTest.kt#L83)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This one can be simpler -- it's just `pcollectionOf<String>("Empty")` I think
</blockquote></details>

Done.

**Review by enfreck — APPROVED** [review]
> Reviewed 1 of 6 files at r2, 1 of 2 files at r3, 2 of 4 files at r5, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @matthewclegg)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Review by efoxepstein — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42#-:-Mf4hJjU5r3ADk7ect2G:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 6 files at r2, 1 of 2 files at r3, 1 of 4 files at r5, 2 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/42)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Pull request merged**
