### PR TITLE
Generate separate K8s manifests for EDP/MP dev example daemon.

### PR DESCRIPTION
**Pull request by SanjayVas**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279)

### CODE REVIEW

**Comment by SanjayVas** [comment]
I've been working on this while @yunyeng has been out. This partially replaces #273.

**Comment by SanjayVas** [comment]
TODO: Add network policy.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/k8s/base.cue, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279#-Mx4qUN-64ViGbU_9p63:-Mx4qUN-64ViGbU_9p64:bvl76ls) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f61cfd37c253c61efbabf07f0b4cca0e2b7171/src/main/k8s/base.cue#L42)):*
> ```CUE
> 	name:       string
> 	secretName: string
> 	mountPath:  string | *"/var/run/secrets/files"
> ```

is it standard to put these in /var and /etc?
___
*[src/main/k8s/dev/example_daemon_gke.cue, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279#-Mx4q12i9RR7m94GRRcd:-Mx4q12jBMhZ0ggqbRb6:b-fzwpdm) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f61cfd37c253c61efbabf07f0b4cca0e2b7171/src/main/k8s/dev/example_daemon_gke.cue#L31)):*
> ```CUE
> 		limits: {
> 			cpu:    "400m"
> 			memory: "512Mi"
> ```

i could see us exceeding this limit - 1 or 2 gb is safer
___
*[src/main/k8s/dev/example_edp_daemon_gke.cue, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279#-Mx4qKUe9vuP-nu6NtyD:-Mx4qKUe9vuP-nu6NtyE:b-e93zkz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f61cfd37c253c61efbabf07f0b4cca0e2b7171/src/main/k8s/dev/example_edp_daemon_gke.cue#L25)):*
> ```CUE
> 		keyFile:  "/var/run/secrets/files/edp1_tls.key"
> 	}
> 	tinkKeyUri: "gcp-kms://projects/halo-cmm-dev/locations/us-central1/keyRings/test-key-ring/cryptoKeys/test-aes-key"
> ```

shouldn't this be provided via a flag?
___
*[src/main/k8s/dev/example_edp_daemon_gke.cue, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279#-Mx4qPBs446W1ISc8jkJ:-Mx4qPBs446W1ISc8jkK:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f61cfd37c253c61efbabf07f0b4cca0e2b7171/src/main/k8s/dev/example_edp_daemon_gke.cue#L26)):*
> ```CUE
> 	}
> 	tinkKeyUri: "gcp-kms://projects/halo-cmm-dev/locations/us-central1/keyRings/test-key-ring/cryptoKeys/test-aes-key"
> 	privateCa: {
> ```

ditto
___
*[src/main/k8s/dev/example_mp_daemon_gke.cue, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279#-Mx4qRzM-jF9926KV72_:-Mx4qRzM-jF9926KV72a:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f61cfd37c253c61efbabf07f0b4cca0e2b7171/src/main/k8s/dev/example_mp_daemon_gke.cue#L25)):*
> ```CUE
> 		keyFile:  "/var/run/secrets/files/edp2_tls.key"
> 	}
> 	tinkKeyUri: "gcp-kms://projects/halo-cmm-dev/locations/us-central1/keyRings/test-key-ring/cryptoKeys/test-aes-key"
> ```

ditto

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/k8s/base.cue, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279#-Mx4qUN-64ViGbU_9p63:-Mx5jxNd7Xvw1KvJkmdT:b-48ad4j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f61cfd37c253c61efbabf07f0b4cca0e2b7171/src/main/k8s/base.cue#L42)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is it standard to put these in /var and /etc?
</blockquote></details>

`/etc` is normal spot for configuration on POSIX machines, and is what the K8s docs use in their samples for ConfigMaps so I continued to use that.

I copied use of `/var/run/secrets` for Secrets from Yao's previous work in the CMM repo. `/var/run` is the normal spot for run-time data on POSIX machines. e.g. it's where PID files go. Seems like a more reasonable spot than `/etc` for private keys, as `/etc` is generally world-readable.
___
*[src/main/k8s/dev/example_daemon_gke.cue, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279#-Mx4q12i9RR7m94GRRcd:-Mx5mTQ45360ccOxW0WV:b-ws4ogx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f61cfd37c253c61efbabf07f0b4cca0e2b7171/src/main/k8s/dev/example_daemon_gke.cue#L31)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i could see us exceeding this limit - 1 or 2 gb is safer
</blockquote></details>

Done.

Our deployment docs so far call out that one should adjust these according to expected load.
___
*[src/main/k8s/dev/example_edp_daemon_gke.cue, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279#-Mx4qKUe9vuP-nu6NtyD:-Mx60QSk80Nb4rwxyGa3:bniuqep) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f61cfd37c253c61efbabf07f0b4cca0e2b7171/src/main/k8s/dev/example_edp_daemon_gke.cue#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't this be provided via a flag?
</blockquote></details>

No. This is hard-coded config for the `dev` environment (i.e. `halo-cmm-dev` Google Cloud project). Anyone using this as a base for their own configuration should change this.

As background, anyone deploying this is expected to come up with their own K8s manifests. The repo contains code for specific environments (e.g. local/KiND and dev), that happen to be useful as a base to get people started.
___
*[src/main/k8s/dev/example_edp_daemon_gke.cue, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279#-Mx4qPBs446W1ISc8jkJ:-Mx60m2bDDacrNEMoFfr:b-redf51) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f61cfd37c253c61efbabf07f0b4cca0e2b7171/src/main/k8s/dev/example_edp_daemon_gke.cue#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Same answer.
___
*[src/main/k8s/dev/example_mp_daemon_gke.cue, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279#-Mx4qRzM-jF9926KV72_:-Mx61Z_76_qnjTLST93v:b-redf51) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f61cfd37c253c61efbabf07f0b4cca0e2b7171/src/main/k8s/dev/example_mp_daemon_gke.cue#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Same answer.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/k8s/dev/example_daemon_gke.cue, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279#-Mx4q12i9RR7m94GRRcd:-Mx6_Th77cGoyokrlrWm:blsb2vl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f61cfd37c253c61efbabf07f0b4cca0e2b7171/src/main/k8s/dev/example_daemon_gke.cue#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Done.

Our deployment docs so far call out that one should adjust these according to expected load.
</blockquote></details>

yeah - i'd just like our reference example to not crash :)
___
*[src/main/k8s/dev/example_edp_daemon_gke.cue, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279#-Mx4qKUe9vuP-nu6NtyD:-Mx6__i-0PorBou8zFVm:bvg6jmo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f61cfd37c253c61efbabf07f0b4cca0e2b7171/src/main/k8s/dev/example_edp_daemon_gke.cue#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

No. This is hard-coded config for the `dev` environment (i.e. `halo-cmm-dev` Google Cloud project). Anyone using this as a base for their own configuration should change this.

As background, anyone deploying this is expected to come up with their own K8s manifests. The repo contains code for specific environments (e.g. local/KiND and dev), that happen to be useful as a base to get people started.
</blockquote></details>

Is this documented anywhere in this file or in the instructions?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/k8s/dev/example_edp_daemon_gke.cue, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279#-Mx4qKUe9vuP-nu6NtyD:-Mx6pyR07AwHdzg3f2DH:b-isevb1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f61cfd37c253c61efbabf07f0b4cca0e2b7171/src/main/k8s/dev/example_edp_daemon_gke.cue#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Is this documented anywhere in this file or in the instructions?
</blockquote></details>

We don't have a deployment guide written for panel-exchange-client, but it's mentioned in the docs for the CMMS. It's the same `dev` environment in both cases.

e.g. https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/kingdom-deployment.md#step-8-create-the-k8s-manifest

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[src/main/k8s/dev/example_edp_daemon_gke.cue, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279#-Mx4qKUe9vuP-nu6NtyD:-MxAKpN53kres42zFaXT:b-myf44f) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f61cfd37c253c61efbabf07f0b4cca0e2b7171/src/main/k8s/dev/example_edp_daemon_gke.cue#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We don't have a deployment guide written for panel-exchange-client, but it's mentioned in the docs for the CMMS. It's the same `dev` environment in both cases.

e.g. https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/kingdom-deployment.md#step-8-create-the-k8s-manifest
</blockquote></details>

Can you add a TODO to add it to the deployment guide?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[src/main/k8s/dev/example_edp_daemon_gke.cue, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279#-Mx4qKUe9vuP-nu6NtyD:-MxApROACS6Ou3w2JGIM:b-9msol2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f61cfd37c253c61efbabf07f0b4cca0e2b7171/src/main/k8s/dev/example_edp_daemon_gke.cue#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Can you add a TODO to add it to the deployment guide?
</blockquote></details>

Adding a deployment guide for the panel exchange workflow daemon is the thing we're building towards here, and it would of course mention this in the same way that the Kingdom deployment guide does.

I'm not sure where this TODO would live?

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @stevenwarejones)

___
*[src/main/k8s/dev/example_edp_daemon_gke.cue, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279#-Mx4qKUe9vuP-nu6NtyD:-MxB2gNW-JOoyxjkwgW8:bd9e3sa) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/30f61cfd37c253c61efbabf07f0b4cca0e2b7171/src/main/k8s/dev/example_edp_daemon_gke.cue#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Adding a deployment guide for the panel exchange workflow daemon is the thing we're building towards here, and it would of course mention this in the same way that the Kingdom deployment guide does.

I'm not sure where this TODO would live?
</blockquote></details>

I updated the README in this package to make this point more clear.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/279)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Pull request merged**
