### PR TITLE
Add DataflowPipelineOptions' required parameters

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/294)

### CODE REVIEW

**Review by robinsons — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/294)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/k8s/dev/example_daemon_gke.cue, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/294#-MzpHwNF8AF5PDp_5RQh:-MzpHwNF8AF5PDp_5RQi:b-saxfxz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bace2393d851e9843ddd8e15f67d6ca72628f815/src/main/k8s/dev/example_daemon_gke.cue#L58)):*
> ```CUE
> 
> 	dataflow: {
> 		projectId:    #GcloudProject | string
> ```

Not sure if it's a typo or someone being clever, but above this is `#GloudProject` (no `c`).



_Code quote:_
```CUE
#GcloudProject
```

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/294)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @robinsons, @stevenwarejones, and @yunyeng)

___
*[src/main/k8s/dev/example_daemon_gke.cue, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/294#-MzpHwNF8AF5PDp_5RQh:-MzpZC_EDnFjVg_JPG0Y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/bace2393d851e9843ddd8e15f67d6ca72628f815/src/main/k8s/dev/example_daemon_gke.cue#L58)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Not sure if it's a typo or someone being clever, but above this is `#GloudProject` (no `c`).
</blockquote></details>

Done.

**Review by robinsons — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/294)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @yunyeng)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/294)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Review by yunyeng — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/294)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Pull request merged**
