### PR TITLE
Fix dev deployment configuration to match current state.

### PR DESCRIPTION
**Pull request by SanjayVas**
This adds separate secret generation.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282)

### CODE REVIEW

**Review by yunyeng — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/k8s/dev/example_daemon_gke.cue, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282#-MxHLwJQA4Vjf8uduDjv:-MxHLwJQA4Vjf8uduDjw:b-wx7t1m) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8779870fe739c98eb9a1e2608e4eb51d3536d97b/src/main/k8s/dev/example_daemon_gke.cue#L59)):*
> ```CUE
> 		"--id=\(_partyId)",
> 		"--party-type=\(partyType)",
> 		"--recurring-exchange-id=\(recurringExchangeName)",
> ```

recurringExchangeId

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/k8s/dev/example_daemon_gke.cue, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282#-MxHLwJQA4Vjf8uduDjv:-MxHi69l2UJbwxt5saeg:bc1x9j9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8779870fe739c98eb9a1e2608e4eb51d3536d97b/src/main/k8s/dev/example_daemon_gke.cue#L59)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

recurringExchangeId
</blockquote></details>

It doesn't look like this is even used by `GoogleCloudExampleDaemon`. Can we just delete the flag from there, or is there a bug?

**Review by yunyeng — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282)* status: 0 of 19 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/k8s/dev/example_daemon_gke.cue, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282#-MxHLwJQA4Vjf8uduDjv:-MxJ8P1P3nGNNVZ4EkcP:bs1ihk2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8779870fe739c98eb9a1e2608e4eb51d3536d97b/src/main/k8s/dev/example_daemon_gke.cue#L59)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It doesn't look like this is even used by `GoogleCloudExampleDaemon`. Can we just delete the flag from there, or is there a bug?
</blockquote></details>

#281 added that into GoogleCloudExampleDaemon.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/k8s/dev/example_daemon_gke.cue, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282#-MxHLwJQA4Vjf8uduDjv:-MxKrsB10h22jL2YF2Wm:b-ovsii0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8779870fe739c98eb9a1e2608e4eb51d3536d97b/src/main/k8s/dev/example_daemon_gke.cue#L59)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

#281 added that into GoogleCloudExampleDaemon.
</blockquote></details>

What I mean is the flag *value* doesn't appear to be currently used for anything.

**Review by yunyeng — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

**Review by yunyeng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/k8s/dev/example_daemon_gke.cue, line 82 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282#-MxLVp8n0ZxD_DlVGObc:-MxLVp8n0ZxD_DlVGObd:breb2c4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42d916457a80edc27cd6fea4f908ab6c0ffda9f8/src/main/k8s/dev/example_daemon_gke.cue#L82)):*
> ```CUE
> }
> deployments: {
> 	"example-panel-exchange-daemon": {
> ```

nit: Can we add the party name or id here? If we are running EDP and MP together would be nice to see which daemon is which.

**Review by yunyeng — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/k8s/dev/example_daemon_gke.cue, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282#-MxLWlJ2-7BLqLediboG:-MxLWlJ3-SsmVfCahhww:bbqi0or) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2f1c1e346c98c1068b30cd0d41a639033a29e351/src/main/k8s/dev/example_daemon_gke.cue#L20)):*
> ```CUE
> 
> #GloudProject:            "halo-cmm-dev"
> #SpannerInstance:         "halo-panelmatch-demo-instance"
> ```

We can delete this I believe.

**Review by SanjayVas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282)* status: 16 of 22 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/k8s/dev/example_daemon_gke.cue, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282#-MxLWlJ2-7BLqLediboG:-MxL_iTr6daTFu9vn52D:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2f1c1e346c98c1068b30cd0d41a639033a29e351/src/main/k8s/dev/example_daemon_gke.cue#L20)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

We can delete this I believe.
</blockquote></details>

Done.
___
*[src/main/k8s/dev/example_daemon_gke.cue, line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282#-MxHLwJQA4Vjf8uduDjv:-MxLZxk0DFL1VxA2kRAI:bgwfh4t) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2f1c1e346c98c1068b30cd0d41a639033a29e351/src/main/k8s/dev/example_daemon_gke.cue#L59)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What I mean is the flag *value* doesn't appear to be currently used for anything.
</blockquote></details>

Dropped unused flag.
___
*[src/main/k8s/dev/example_daemon_gke.cue, line 82 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282#-MxLVp8n0ZxD_DlVGObc:-MxL_2BP5WDoowdEXyTj:bw3ggfx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/42d916457a80edc27cd6fea4f908ab6c0ffda9f8/src/main/k8s/dev/example_daemon_gke.cue#L82)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

nit: Can we add the party name or id here? If we are running EDP and MP together would be nice to see which daemon is which.
</blockquote></details>

They are run by separate parties (i.e. separate cloud projects). For testing, we emulate this by at least using separate clusters. Therefore, the distinction isn't necessary.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 14 of 19 files at r1, 1 of 2 files at r2, 5 of 6 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/282)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
