### PR TITLE
Add Kotlin DSL for Apache Beam

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 11 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27)* status: 8 of 11 files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[WORKSPACE, line 141 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27#-MctxBqjDLebairKhoVB:-MctxBqjDLebairKhoVC:b-r9ytdr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/85cdb5a7961636e20ab4d6359bc5be40e6713fcd/WORKSPACE#L141)):*
> ```
>     "org.hamcrest:hamcrest-library": "1.3",
>     "org.hamcrest:hamcrest-core": "1.3",
>     "org.slf4j:slf4j-simple": "1.7.9",
> ```
Where are we using these deps? I don't expect to use Hamcrest or SLF4J in any of our code, and the Maven targets should already include any transitive deps.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27#-Mcu-R3-DwE6HR2PdRoP:-Mcu-R3-DwE6HR2PdRoQ:b-ly29dc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/85cdb5a7961636e20ab4d6359bc5be40e6713fcd/src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt#L37)):*
> ```
> toKv
> ```
nit: maybe `toValue` would read more naturally for this infix function, since this appears to be trying to parallel the `to` infix function for `Pair` without conflicting with it.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt, line 56 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27#-MctyKlG1b6T76VZzeoC:-MctyKlG1b6T76VZzeoD:bkwuxp3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/85cdb5a7961636e20ab4d6359bc5be40e6713fcd/src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt#L56)):*
> ```
> block
> ```
nit: prefer more specific naming when it makes sense. Perhaps `processElement`?
___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt, line 174 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27#-Mcu3VcNAWlvgwZqj5gS:-Mcu3VcNAWlvgwZqj5gT:b-xnwtjy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/85cdb5a7961636e20ab4d6359bc5be40e6713fcd/src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt#L174)):*
> ```
> block
> ```
nit: specific name when it makes sense. Maybe `combine`?
___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/Coders.kt, line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27#-Mcu4Bx34cfxPOAP4Ca1:-Mcu4Bx41Xcw5GiAZ5O_:b-s86je9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/85cdb5a7961636e20ab4d6359bc5be40e6713fcd/src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/Coders.kt#L21)):*
> ```Kotlin
> import org.apache.beam.sdk.coders.Coder
> 
> class CoderResult<T>(val encodedData: ByteArray, val result: T)
> ```

Was this meant to be a data class?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27)* status: 8 of 11 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[WORKSPACE, line 141 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27#-MctxBqjDLebairKhoVB:-McuC5te9NyQ1_SmkDwh:b-fzd8kt) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/85cdb5a7961636e20ab4d6359bc5be40e6713fcd/WORKSPACE#L141)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>     "org.hamcrest:hamcrest-library": "1.3",
>     "org.hamcrest:hamcrest-core": "1.3",
>     "org.slf4j:slf4j-simple": "1.7.9",
> ```
Where are we using these deps? I don't expect to use Hamcrest or SLF4J in any of our code, and the Maven targets should already include any transitive deps.
</blockquote></details>

Alas, these are "optional" deps somehow. If you don't explicitly add them, Apache Beam just won't use them and things will break. I think Apache Beam tries to load them dynamically or something.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27)* status: 8 of 11 files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[WORKSPACE, line 141 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27#-MctxBqjDLebairKhoVB:-McuDq-FAzE6dx7ZH13z:b-61me7m) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/85cdb5a7961636e20ab4d6359bc5be40e6713fcd/WORKSPACE#L141)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Alas, these are "optional" deps somehow. If you don't explicitly add them, Apache Beam just won't use them and things will break. I think Apache Beam tries to load them dynamically or something.
</blockquote></details>

If this is the case, then we should be able to specify them as runtime_deps in targets rather than in deps.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[WORKSPACE, line 141 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27#-MctxBqjDLebairKhoVB:-McuGGe490K8HwaPbCrQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/85cdb5a7961636e20ab4d6359bc5be40e6713fcd/WORKSPACE#L141)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If this is the case, then we should be able to specify them as runtime_deps in targets rather than in deps.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27#-Mcu-R3-DwE6HR2PdRoP:-McuGB_BBVdGEQkpQQKR:bncokc4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/85cdb5a7961636e20ab4d6359bc5be40e6713fcd/src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> toKv
> ```
nit: maybe `toValue` would read more naturally for this infix function, since this appears to be trying to parallel the `to` infix function for `Pair` without conflicting with it.
</blockquote></details>

Changed to `kvOf`, not infix. `toValue` is just too long to make me happy.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/Coders.kt, line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27#-Mcu4Bx34cfxPOAP4Ca1:-McuD6m--sEH-PLU4I7W:b26omfg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/85cdb5a7961636e20ab4d6359bc5be40e6713fcd/src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/Coders.kt#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Was this meant to be a data class?
</blockquote></details>

Actually, no! ByteArray doesn't play nice with data classes: IntelliJ says that you then need to manually override equals() and hashCode() because arrays are weird.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 11 files at r1, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/Coders.kt, line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27#-Mcu4Bx34cfxPOAP4Ca1:-McuJCdZ5UXqEKfFy6_P:bc78e2i) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/85cdb5a7961636e20ab4d6359bc5be40e6713fcd/src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/Coders.kt#L21)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Actually, no! ByteArray doesn't play nice with data classes: IntelliJ says that you then need to manually override equals() and hashCode() because arrays are weird.
</blockquote></details>

Would you be opposed to using `ByteString` instead? That's generally a better type for an immutable collection of bytes, with the main downside being having to depend on protobuf. We already do elsewhere in this repo, so that seems fine.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/BUILD.bazel, line 11 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27#-MczHFI50RHMqU7LHn2M:-MczHFI61vIDXKlILGe6:br6pgw7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3cf62c99dc5b6f080d12a4ceb185a7746fa85d6d/src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/BUILD.bazel#L11)):*
> ```Starlark
>     srcs = glob(["*.kt"]),
>     runtime_deps = [
>         "//imports/java/org/apache/beam:direct_runner",
> ```

you mentioned earlier that we're not going to need spark_runner. Can you unpack that a little more?
___
*[src/test/kotlin/org/wfanet/panelmatch/common/beam/BeamTest.kt, line 93 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27#-Md3jvvGBpPjJnm8jDZG:-Md3jvvGBpPjJnm8jDZH:b9gc829) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3cf62c99dc5b6f080d12a4ceb185a7746fa85d6d/src/test/kotlin/org/wfanet/panelmatch/common/beam/BeamTest.kt#L93)):*
> ```Kotlin
>   @Test
>   fun join() {
>     val rightHandSide = pcollectionOf("right-hand side", kvOf(1, 'a'), kvOf(1, 'b'), kvOf(4, 'c'))
> ```

make this a private instance variable since its used multiple times
___
*[src/test/kotlin/org/wfanet/panelmatch/common/beam/BeamTest.kt, line 123 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27#-Md3k3G62UO-f6694DuA:-Md3k3G62UO-f6694DuB:bsfu411) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3cf62c99dc5b6f080d12a4ceb185a7746fa85d6d/src/test/kotlin/org/wfanet/panelmatch/common/beam/BeamTest.kt#L123)):*
> ```Kotlin
>   @Test
>   fun toPCollectionList() {
>     val list =
> ```

private instance variable

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/BUILD.bazel, line 11 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27#-MczHFI50RHMqU7LHn2M:-Md3vwvs3eiSINBrgEQ9:b-2n46o0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3cf62c99dc5b6f080d12a4ceb185a7746fa85d6d/src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/BUILD.bazel#L11)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

you mentioned earlier that we're not going to need spark_runner. Can you unpack that a little more?
</blockquote></details>

Well, we might have a main function that runs it on spark, but we can cross that bridge when we get there. Basically, I'm trying to keep the minimum set of deps necessary and that's not yet necessary.
___
*[src/test/kotlin/org/wfanet/panelmatch/common/beam/BeamTest.kt, line 93 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27#-Md3jvvGBpPjJnm8jDZG:-Md44dgX8Ggzl8UPy5B5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3cf62c99dc5b6f080d12a4ceb185a7746fa85d6d/src/test/kotlin/org/wfanet/panelmatch/common/beam/BeamTest.kt#L93)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

make this a private instance variable since its used multiple times
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/common/beam/BeamTest.kt, line 123 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27#-Md3k3G62UO-f6694DuA:-Md45jQcAXxQnj6LQZQu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3cf62c99dc5b6f080d12a4ceb185a7746fa85d6d/src/test/kotlin/org/wfanet/panelmatch/common/beam/BeamTest.kt#L123)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

private instance variable
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/BUILD.bazel, line 11 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27#-MczHFI50RHMqU7LHn2M:-MdIP5GbCN3T73gVhbyM:b-3zgttc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3cf62c99dc5b6f080d12a4ceb185a7746fa85d6d/src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/BUILD.bazel#L11)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Well, we might have a main function that runs it on spark, but we can cross that bridge when we get there. Basically, I'm trying to keep the minimum set of deps necessary and that's not yet necessary.
</blockquote></details>

sounds good. Trying to clarify if you were saying we weren't ever going to need it.

**Review by efoxepstein — COMMENTED** [review]
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/BUILD.bazel, line 11 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/27#-MczHFI50RHMqU7LHn2M:-MdIPQVT-3ZlLGXNKMqP:bp48q84) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3cf62c99dc5b6f080d12a4ceb185a7746fa85d6d/src/main/kotlin/org/wfanet/panelmatch/common/beam/testing/BUILD.bazel#L11)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

sounds good. Trying to clarify if you were saying we weren't ever going to need it.
</blockquote></details>

I *think* we'll need it but we'll want to make sure it's only built into binaries that need it.

**Pull request merged**
