### PR TITLE
Client tasks

### PR DESCRIPTION
**Pull request by stevenwarejones**
Client Tasks for
* Encrypt
* Rencrypt
* Decrypt

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 14 of 15 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11)* status: all files reviewed, 15 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/BUILD.bazel, line 12 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gVEIcDPNpUMlvoZHg:-M_gVEIcDPNpUMlvoZHh:b-ontybj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/BUILD.bazel#L12)):*
> ```Starlark
>     ],
>     deps = [
>         "//src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks",
> ```

You can (and probably should) just write ":exchangetasks" for a library in the same BUILD.bazel file.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/BUILD.bazel, line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gVPBmDgijmMANkH0O:-M_gVPBn8Q2FEvWg-O0c:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/BUILD.bazel#L23)):*
> ```Starlark
>     ],
>     deps = [
>         "//src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks",
> ```

Ditto
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DataProviderTasks.kt, line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gVSxH6BFv1l83GLda:-M_gVSxH6BFv1l83GLdb:b-jzvqrj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DataProviderTasks.kt#L23)):*
> ```Kotlin
> import wfanet.panelmatch.protocol.protobuf.SharedInputs
> 
> class DataProviderTasks : ExchangeTask {
> ```

How about a separate subclass per ExchangeTask type? In other words, `class IntersectAndValidate`, `class EncryptAndShare`, etc?

The switch on the ExchangeWorkflow.Step.getStepCase() will happen before this.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DataProviderTasks.kt, line 41 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gWUQd-zMyzx7dkp9o:-M_gWUQd-zMyzx7dkp9p:b-nccxzf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DataProviderTasks.kt#L41)):*
> ```
> error
> ```

Just a heads up about kotlin's TODO function (which throws some Unimplemented exception)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt, line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gWaTF7PV5SPQze_lg:-M_gWaTF7PV5SPQze_lh:b-rpz8n7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ExchangeTask.kt#L35)):*
> ```Kotlin
>     step: ExchangeWorkflow.Step,
>     input: Map<String, ByteString>
>     // TODO sendDebugLog: suspend (String) -> Unit
> ```

??

If you need a fake one of these, you can always create one like this:

```
val fakeSendDebugLog: suspend (String) -> Unit = {}
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ModelProviderTasks.kt, line 24 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gdyub7MufOHnEWDXL:-M_gdyub7MufOHnEWDXM:b-jcob6o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ModelProviderTasks.kt#L24)):*
> ```Kotlin
> import wfanet.panelmatch.protocol.protobuf.SharedInputs
> 
> class ModelProviderTasks : ExchangeTask {
> ```

Unit tests please
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ModelProviderTasks.kt, line 52 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gX7T04psm_Wv9jzKD:-M_gX7T04psm_Wv9jzKE:bymhjiu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/ModelProviderTasks.kt#L52)):*
> ```Kotlin
>         return mapOf(
>           "result" to
>             SharedInputs.newBuilder()
> ```

How about a helper function?

```
fun makeSharedInputs(data: List<ByteString>): SharedInputs {
  return SharedInputs.newBuilder().addAllData(data).build().toByteString()
}
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 45 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gXiAXCrVWwKCyOv5Z:-M_gXiAXCrVWwKCyOv5_:b6vemiq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L45)):*
> ```Kotlin
>    * validates it, and starts executing. If not found simply returns.
>    */
>   suspend fun findAndRunExchangeStep(): Map<String, ByteString> {
> ```

I'm not sure I like this change. In general, the running of the exchangeStep could happen in a different process or on a different machine, so I'd rather not assume we can get the outputs back.

Looking ahead, I see that this change is to support testing. Here's a counterproposal: let's build the classes/interfaces that Yunus proposed (JobStarter, ExchangeTaskWrapper) so that you don't have to majorly refactor all your tests once those are in place.

My recommendation (and maybe Yunus owns some of these things):

1. Split up this PR -- for now, just add the ExchangeTask subclasses and unit tests.
2. Define a `JobStarter` interface
3. ExchangeStepLauncher. Then `runExchangeStep` just calls out to that.
4. Define an `ExchangeTaskWrapper` class that has injected InputReader and OutputWriters.
5. You can do testing by injecting fake `InputReader` and `OutputWriter` that provide particular inputs or capture outputs.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 46 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gXi_P8hbzBjjIICZC:-M_gXi_P8hbzBjjIICZD:b-3qgp1w) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L46)):*
> ```Kotlin
>    */
>   suspend fun findAndRunExchangeStep(): Map<String, ByteString> {
>     val exchangeStep = findExchangeStep() ?: error("No available exchange step")
> ```

I don't think this should be an error. There's no problem with not finding any work to do.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 99 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gXwT_1nisXxMpQp4o:-M_gXwT_1nisXxMpQp4p:b9d2wr3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L99)):*
> ```Kotlin
>    * @param exchangeStep [ExchangeStep].
>    */
>   internal fun runExchangeStep(exchangeStep: ExchangeStep): Map<String, ByteString> = runBlocking {
> ```

This function should probably just be suspend instead of using runBlocking. That way you don't need to use async in it either.
___
*[src/main/proto/wfanet/panelmatch/protocol/crypto/cryptor.proto, line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gYQSa5rCRWKfsboZW:-M_gYQSa5rCRWKfsboZX:b-19f6dn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/proto/wfanet/panelmatch/protocol/crypto/cryptor.proto#L26)):*
> ```protobuf
> message SharedInputs {
>   repeated bytes data = 1;
>   map<string, bytes> shared_inputs = 4;
> ```

What is the purpose of this field? The usage looked like `SharedInputs` was used as the value in a map, so I'm not sure what a map in a map would mean
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt, line 57 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gYeii92AdKT-PR3Mn:-M_gYeii92AdKT-PR3Mo:b-rf1z5q) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt#L57)):*
> ```Kotlin
> private val RESPONSE =
>   ClaimReadyExchangeStepResponse.newBuilder().setExchangeStep(EXCHANGE_STEP).build()
> private val EMPTY_RESPONSE = ClaimReadyExchangeStepResponse.newBuilder().build()
> ```

`Foo.getDefaultInstance()` gives an empty Foo
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt, line 71 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gYmfj-xiUQZ84u7pZ:-M_gYmfj-xiUQZ84u7p_:b7vpb4w) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncherTest.kt#L71)):*
> ```Kotlin
> 
>   @Test
>   fun `findExchangeStep with dataProvider`() {
> ```

Name is out of date?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepTasksTest.kt, line 46 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gYqn9Bk3_9fRlgWR1:-M_gYqn9Bk3_9fRlgWR2:btsq1vx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepTasksTest.kt#L46)):*
> ```Kotlin
> private const val DATA_PROVIDER_ID = "1"
> private const val MODEL_PROVIDER_ID = "2"
> private const val EXCHANGE_ID = "1"
> ```

probably best to use distinct values for DATA_PROVIDER_ID and EXCHANGE_ID
___
*[src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepTasksTest.kt, line 50 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gYxGv3lujG9v_UjGo:-M_gYxGv3lujG9v_UjGp:b-k02ff3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/test/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepTasksTest.kt#L50)):*
> ```Kotlin
> @RunWith(JUnit4::class)
> class ExchangeTasksTest {
>   private val DP_0_SECRET_KEY = ByteString.copyFromUtf8("random-edp-string-0")
> ```

Any reason these are within the class instead of above it like the other constants?

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11)* status: all files reviewed, 16 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryption.kt, line 66 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gf4CBAX7D9dtBKzK4:-M_gf4CBAX7D9dtBKzK5:b-ji9otf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryption.kt#L66)):*
> ```Kotlin
> }
> 
> fun applyCommutativeEncryptionHelper(
> ```

Up to you, but I'd consider removing `Helper` from the name of these. `applyCommutativeEncryption(key, plaintexts)` seems cleaner.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11)* status: all files reviewed, 16 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DataProviderTasks.kt, line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gVSxH6BFv1l83GLda:-M_ghaJEAZekN0KqjpaF:b-we2vhn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DataProviderTasks.kt#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

How about a separate subclass per ExchangeTask type? In other words, `class IntersectAndValidate`, `class EncryptAndShare`, etc?

The switch on the ExchangeWorkflow.Step.getStepCase() will happen before this.
</blockquote></details>

were you thinking the switch to choose with subClass to run would happen within this interface like I did it or higher up?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DataProviderTasks.kt, line 41 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gWUQd-zMyzx7dkp9o:-M_ghl8NAHoUjLa3FtiB:b-cwmfid) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DataProviderTasks.kt#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

> ```
> error
> ```

Just a heads up about kotlin's TODO function (which throws some Unimplemented exception)
</blockquote></details>

Does having a TODO mean I don't need that error then?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 99 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gXwT_1nisXxMpQp4o:-M_gi-R-0wmceIizPqSP:b-vmds0e) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L99)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This function should probably just be suspend instead of using runBlocking. That way you don't need to use async in it either.
</blockquote></details>

if this function is suspend then which function ultimately is higher level function is ultimately runblocking?
___
*[src/main/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryption.kt, line 66 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gf4CBAX7D9dtBKzK4:-M_gi9HE5lq9JiV2COec:bvgq0on) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/protocol/common/JniCommutativeEncryption.kt#L66)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Up to you, but I'd consider removing `Helper` from the name of these. `applyCommutativeEncryption(key, plaintexts)` seems cleaner.
</blockquote></details>

yeah, I thought about doing it that way. I'm fine with that too.
___
*[src/main/proto/wfanet/panelmatch/protocol/crypto/cryptor.proto, line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gYQSa5rCRWKfsboZW:-M_giGT1DXnQPFfWiztZ:b-12zqlp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/proto/wfanet/panelmatch/protocol/crypto/cryptor.proto#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What is the purpose of this field? The usage looked like `SharedInputs` was used as the value in a map, so I'm not sure what a map in a map would mean
</blockquote></details>

I was using it to serialize map<string, bytes> into ByteString. It was what I was asking on Slack. There's probably a better way to do this.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11)* status: all files reviewed, 16 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 45 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gXiAXCrVWwKCyOv5Z:-M_gjUIFCMzznyRDZUaq:b-9gh3pp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L45)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'm not sure I like this change. In general, the running of the exchangeStep could happen in a different process or on a different machine, so I'd rather not assume we can get the outputs back.

Looking ahead, I see that this change is to support testing. Here's a counterproposal: let's build the classes/interfaces that Yunus proposed (JobStarter, ExchangeTaskWrapper) so that you don't have to majorly refactor all your tests once those are in place.

My recommendation (and maybe Yunus owns some of these things):

1. Split up this PR -- for now, just add the ExchangeTask subclasses and unit tests.
2. Define a `JobStarter` interface
3. ExchangeStepLauncher. Then `runExchangeStep` just calls out to that.
4. Define an `ExchangeTaskWrapper` class that has injected InputReader and OutputWriters.
5. You can do testing by injecting fake `InputReader` and `OutputWriter` that provide particular inputs or capture outputs.
</blockquote></details>

I realized you might not like the the task itself returning a value... I thought that might be an okay interim option with a TODO to use use inputreader and outputwriter.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11)* status: all files reviewed, 16 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DataProviderTasks.kt, line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gVSxH6BFv1l83GLda:-M_gnF_o6-vN4jPFCw58:bcudl7y) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DataProviderTasks.kt#L23)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

were you thinking the switch to choose with subClass to run would happen within this interface like I did it or higher up?
</blockquote></details>

`ExchangeTaskWrapper` will handle it I think.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DataProviderTasks.kt, line 41 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gWUQd-zMyzx7dkp9o:-M_gnN017CnVQCr9Zh7a:b-ptny9g) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DataProviderTasks.kt#L41)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Does having a TODO mean I don't need that error then?
</blockquote></details>

You can think of the TODO function as:

```
fun TODO(message: String): Nothing {
  throw UnimplementedException(message)
}
```

So you can just write `TODO("Not implemented")` here instead of `error(...)` and the `// TODO` comment
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 45 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gXiAXCrVWwKCyOv5Z:-M_gnggNC4hs2_DpKEUa:bcoixy5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L45)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I realized you might not like the the task itself returning a value... I thought that might be an okay interim option with a TODO to use use inputreader and outputwriter.
</blockquote></details>

The `ExchangeTask` subclasses themselves can return stuff -- that's expected
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 99 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gXwT_1nisXxMpQp4o:-M_gnvDw3LtY4SPnjszG:b-uz49my) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L99)):*
Generally we want `runBlocking` to be as close to `main` as possible.

https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/run-blocking.html

> It is designed to bridge regular blocking code to libraries that are written in suspending style, to be used in main functions and in tests.
___
*[src/main/proto/wfanet/panelmatch/protocol/crypto/cryptor.proto, line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gYQSa5rCRWKfsboZW:-M_goCwE2w5xfSkkwAFL:b38tpzq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/proto/wfanet/panelmatch/protocol/crypto/cryptor.proto#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I was using it to serialize map<string, bytes> into ByteString. It was what I was asking on Slack. There's probably a better way to do this.
</blockquote></details>

I guess I don't quite follow why you need to serialize a Map into a ByteString -- let's chat on Slack

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11)* status: all files reviewed, 16 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt, line 99 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gXwT_1nisXxMpQp4o:-M_gpDEb0Gg0jwwkFyqK:b-qj21ee) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeStepLauncher.kt#L99)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Generally we want `runBlocking` to be as close to `main` as possible.

https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/run-blocking.html

> It is designed to bridge regular blocking code to libraries that are written in suspending style, to be used in main functions and in tests.
</blockquote></details>

i agree with that. I just wasn't seeing any of the merged code so far with suspend attached higher up so I kind of went with what was there and only moved it up one level.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11)* status: all files reviewed, 16 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DataProviderTasks.kt, line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gVSxH6BFv1l83GLda:-M_uvBG_D4yR0DpcvgPt:brtktwy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DataProviderTasks.kt#L23)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`ExchangeTaskWrapper` will handle it I think.
</blockquote></details>

One thing I like about structuring it this way is this format prevents you from executing the wrong step that one party should never execute.... eg bucket them into model tasks and separate bucket for data provider. What do you think?

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11)* status: all files reviewed, 16 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DataProviderTasks.kt, line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/11#-M_gVSxH6BFv1l83GLda:-M_uwC48BHNqpedAP5hU:bbxn9ad) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/481a5369a365df196aef9f7f82c3aa709dd8e80a/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DataProviderTasks.kt#L23)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

One thing I like about structuring it this way is this format prevents you from executing the wrong step that one party should never execute.... eg bucket them into model tasks and separate bucket for data provider. What do you think?
</blockquote></details>

I could also do the same with some assert statements. Not sure what you think.

**Pull request closed without merging**
