### PR TITLE
add golden test data

### PR DESCRIPTION
**Pull request by stevenwarejones**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/259)

### CODE REVIEW

**Review by stevenwarejones — COMMENTED** [review]
LMK your thoughts on this. I filtered a bunch of what look like non-deterministic steps. Also, the hybrid decrypt ones are getting a weird Tink error.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/259#-:-Mt9IvyeCPXJy0MgEn5q:b-5ekklk)* status: 0 of 97 files reviewed, all discussions resolved (waiting on @efoxepstein)

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/259)* status: 0 of 97 files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt, line 86 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/259#-MtKlq3j458B3oK9GSyN:-MuHKrlH8UXJ0_Prjw2i:b-dxff3d) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c702b2a609e8c9a0f0c7e5475ffa38f3e97c3b4c/src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt#L86)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What's this for?
</blockquote></details>

its the exact steps for that test..... maybe name it workflowStepsToTest ? Its normally the entire text proto but could be overriden to be a filtered portion.

**Review by efoxepstein — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/259)* status: 0 of 97 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt, line 86 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/259#-MtKlq3j458B3oK9GSyN:-MuHLaaC0FW8NFkIh-mZ:bjic004) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c702b2a609e8c9a0f0c7e5475ffa38f3e97c3b4c/src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt#L86)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

its the exact steps for that test..... maybe name it workflowStepsToTest ? Its normally the entire text proto but could be overriden to be a filtered portion.
</blockquote></details>

This seems a lot more complicated than just:

```
abstract val workflow: ExchangeWorkflow

protected fun readExchangeWorkflowTextproto(resourcePath: String): ExchangeWorkflow {
  ...
}
```

So subclasses can do:

```
override val workflow by lazy { readExchangeWorkflow(...).whateverTransformationsTheyWant() }
```

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/259)* status: 0 of 100 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt, line 86 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/259#-MtKlq3j458B3oK9GSyN:-Mv0cKMJ90Dv1WU3OkZF:bbxxdjg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c702b2a609e8c9a0f0c7e5475ffa38f3e97c3b4c/src/main/kotlin/org/wfanet/panelmatch/integration/AbstractInProcessPanelMatchIntegrationTest.kt#L86)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This seems a lot more complicated than just:

```
abstract val workflow: ExchangeWorkflow

protected fun readExchangeWorkflowTextproto(resourcePath: String): ExchangeWorkflow {
  ...
}
```

So subclasses can do:

```
override val workflow by lazy { readExchangeWorkflow(...).whateverTransformationsTheyWant() }
```
</blockquote></details>

Changed the workflow to be as you described. However, I moved the read function to the companion object because the Single Step Test reads these outside the test itself. Wdyt @yunyeng

**Review by robinsons — APPROVED** [review]
> Reviewed 94 of 97 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/259)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @yunyeng)

**Pull request merged**
