### PR TITLE
Move key generation into CertificateAuthority

### PR DESCRIPTION
**Pull request by efoxepstein**
This enables simplifications like using CAs that generate key pairs for you.

https://rally1.rallydev.com/#/?detail=/userstory/613928346229&fdp=true

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/201)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/201)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/certificates/CertificateAuthority.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/201#-MnmLf3E2BTECPisdBzu:-MnmLf3FBxbMoxq5dv9K:b-niukg8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b3b5d584fc0371a33a599b97d363e9247dfebe01/src/main/kotlin/org/wfanet/panelmatch/common/certificates/CertificateAuthority.kt#L27)):*
> ```
> Pair<X509Certificate, PrivateKey>
> ```
This should return a SigningKeyHandle to limit access to the private key material.

This could be a TODO if it's too much downstream code to change in this PR.
___
*[src/main/kotlin/org/wfanet/panelmatch/common/certificates/V2AlphaCertificateManager.kt, line 116 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/201#-MnmM1Ym2aAY2ogkrSzH:-MnmM1Ym2aAY2ogkrSzI:b-g6ewve) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b3b5d584fc0371a33a599b97d363e9247dfebe01/src/main/kotlin/org/wfanet/panelmatch/common/certificates/V2AlphaCertificateManager.kt#L116)):*
> ```
> // Proto parsing is lightweight
> ```
nit: I think it's more that it's in-memory, so it shouldn't actually be doing blocking I/O.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/201)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/certificates/CertificateAuthority.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/201#-MnmLf3E2BTECPisdBzu:-Mo-43gjBIkYsqfFiT1D:b-iwmm5x) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b3b5d584fc0371a33a599b97d363e9247dfebe01/src/main/kotlin/org/wfanet/panelmatch/common/certificates/CertificateAuthority.kt#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Pair<X509Certificate, PrivateKey>
> ```
This should return a SigningKeyHandle to limit access to the private key material.

This could be a TODO if it's too much downstream code to change in this PR.
</blockquote></details>

Added TODO
___
*[src/main/kotlin/org/wfanet/panelmatch/common/certificates/V2AlphaCertificateManager.kt, line 116 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/201#-MnmM1Ym2aAY2ogkrSzH:-Mo-49eU7AvmvBiMjYAd:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b3b5d584fc0371a33a599b97d363e9247dfebe01/src/main/kotlin/org/wfanet/panelmatch/common/certificates/V2AlphaCertificateManager.kt#L116)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> // Proto parsing is lightweight
> ```
nit: I think it's more that it's in-memory, so it shouldn't actually be doing blocking I/O.
</blockquote></details>

Done

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/201)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

**Review by SanjayVas — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/201)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Pull request merged**
