### PR TITLE
Add example daemon for GCP

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/226)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 14 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/226)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/BUILD.bazel, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/226#-MpmXBSp5fq4RE_27gY_:-MpmXBSp5fq4RE_27gYa:bgk9d4e) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0953193e299ec06ec829f8ca967bec0d86279b8c/src/main/kotlin/org/wfanet/panelmatch/client/deploy/BUILD.bazel#L51)):*
> ```Starlark
> 
> java_binary(
>     name = "ExchangeWorkflowDaemonMain",
> ```

i'd prefer to keep this as a cross-cloud version
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt, line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/226#-MpmXpmV8XLqGIf6y_rj:-MpmXpmV8XLqGIf6y_rk:b-tqa2xq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a7cb58326e662a8775a77d6008218f44639b3bd7/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt#L55)):*
> ```Kotlin
> 
>   /** Apache Beam options. */
>   protected abstract val pipelineOptions: PipelineOptions
> ```

i realize this is just an example but this makes an assumption the consumer will use beam.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/226)* status: 14 of 15 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/BUILD.bazel, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/226#-MpmXBSp5fq4RE_27gY_:-Mpm_JKO7FAh-DRh_2j6:bh748bf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0953193e299ec06ec829f8ca967bec0d86279b8c/src/main/kotlin/org/wfanet/panelmatch/client/deploy/BUILD.bazel#L51)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i'd prefer to keep this as a cross-cloud version
</blockquote></details>

The base class, ExampleDaemon, is fully cross cloud.
Would you like me to add an instantiation of it that just say uses filesystem for storage?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt, line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/226#-MpmXpmV8XLqGIf6y_rj:-Mpm_QEd6EiKGMrOPFbC:b-heryo9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a7cb58326e662a8775a77d6008218f44639b3bd7/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt#L55)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i realize this is just an example but this makes an assumption the consumer will use beam.
</blockquote></details>

This isn't new to this PR. Can we fix it separately if you need an abstraction around the pipeline runner?

**Review by yunyeng — APPROVED** [review]
> Reviewed 1 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/226)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @stevenwarejones)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/226)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/BUILD.bazel, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/226#-MpmXBSp5fq4RE_27gY_:-Mpmvgy42eUsg0ZhHt1r:bw4p5f7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/0953193e299ec06ec829f8ca967bec0d86279b8c/src/main/kotlin/org/wfanet/panelmatch/client/deploy/BUILD.bazel#L51)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The base class, ExampleDaemon, is fully cross cloud.
Would you like me to add an instantiation of it that just say uses filesystem for storage?
</blockquote></details>

Added `FilesystemExampleDaemonMain` too

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/226)* status: 14 of 19 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt, line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/226#-MpmXpmV8XLqGIf6y_rj:-MpvpuDEAn6aj8-ndXbZ:b7e4gj0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a7cb58326e662a8775a77d6008218f44639b3bd7/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt#L55)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This isn't new to this PR. Can we fix it separately if you need an abstraction around the pipeline runner?
</blockquote></details>

okay - mark a TODO please

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/226)* status: 14 of 19 files reviewed, all discussions resolved (waiting on @duliomatos1 and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt, line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/226#-MpmXpmV8XLqGIf6y_rj:-Mpw7EIF39-7rzlygCwT:bkx1t77) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a7cb58326e662a8775a77d6008218f44639b3bd7/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt#L55)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

okay - mark a TODO please
</blockquote></details>

We have a task in Rally for this. See DE17.

**Pull request merged**
