### PR TITLE
Update common-jvm to 0.28.0.

### PR DESCRIPTION
**Pull request by SanjayVas**
This also updates cross-media-measurement to world-federation-of-advertisers/cross-media-measurement#438.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/271)

### CODE REVIEW

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/271)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Comment by SanjayVas** [comment]
Waiting on https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/438 to be merged so that this can reference a commit of that repo that has been merged into main.

**Review by kungfucraig — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/271)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[build/repositories.bzl, line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/271#-MvKloTz-yiVa_iWLnkH:-MvKloTz-yiVa_iWLnkI:b-48x8r6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f2ab7345c7b465cb17ee8c621be66c84cada1763/build/repositories.bzl#L52)):*
> ```Starlark
>         url = "https://github.com/world-federation-of-advertisers/common-jvm/archive/refs/tags/v0.28.0.tar.gz",
>         strip_prefix = "common-jvm-0.28.0",
>         sha256 = "791bff86bf2534af24f485342af7272e90e4df3d4ebbf0646bd7f715a1688eab",
> ```

nit: keep args in same order across http_archive calls

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/271)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)

**Pull request merged**
