### PR TITLE
sync files tree with xmm repo

### PR DESCRIPTION
**Pull request by Marco-Premier**
[Rally task](https://rally1.rallydev.com/#/604612930531d/search?detail=%2Ftask%2F691273137535&keywords=413)

[xmm repo PR](https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/999)

### CODE REVIEW

**Comment by wfa-reviewable** [comment]
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368)

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 46 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368)* status: 3 of 46 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`AUTHORS` line 10 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368#-NVAsMjQ8ugO05QpD7fx:-NVAsMjQ8ugO05QpD7fy:b-6858xk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/25ad6647872e5c0a5aea15006f69798a6e61cef1/AUTHORS#L10)):*
> ```
> Google LLC
> Facebook, Inc.
> Amazon.com Services LLC
> ```

Is this true for this repo?

Note that the requirement isn't that all files in common paths are totally synced, but rather that everything will still build if you were to replace the files in those common paths with the versions from the destination repo.
___
*[`WORKSPACE` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368#-NVAt3Xf8tRTeY7NDV1b:-NVAt3Xf8tRTeY7NDV1c:b-nnv0hn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/25ad6647872e5c0a5aea15006f69798a6e61cef1/WORKSPACE#L27)):*
> ```Starlark
> common_cpp_deps()
> 
> load("//build:deps.bzl", "panel_exchange_client_deps")
> ```

Resolve this comment once the related comments from world-federation-of-advertisers/cross-media-measurement#999 have been resolved.

**Review by SanjayVas — COMMENTED** [review]
> Reviewed 1 of 46 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368)* status: all files reviewed, 6 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`build/platforms/constraints.bzl` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368#-NV_A87ODkuFGw-wF3XV:-NVapas26qjLmrAyc8xI:b-q6nosu) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/25ad6647872e5c0a5aea15006f69798a6e61cef1/build/platforms/constraints.bzl#L21)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@SanjayVas - should this be coming from common-jvm?
</blockquote></details>

No, the platforms are defined in cross-media-measurement since they're for container images using JNI. We don't have any  JNI container images in common-jvm.
___
*[`src/main/docker/images.bzl` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368#-NV_AX1y81VQvyF8qZtZ:-NVaq9YC2SoZv-3oWUPj:buwtxjo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/33a9f2042b4d6f1ea0609a655d72de780fce936b/src/main/docker/images.bzl#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

these shouldnt be deleted
</blockquote></details>

This is going to be a problem for the repo merge, as it's a common file path that has distinct contents that only apply to this repo. What you likely need to do instead is to move the targets/defs to different file paths in this repo.

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`AUTHORS` line 10 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368#-NVAsMjQ8ugO05QpD7fx:-NVEwuLK29vUxGazLGXv:bzba5dn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/25ad6647872e5c0a5aea15006f69798a6e61cef1/AUTHORS#L10)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this true for this repo?

Note that the requirement isn't that all files in common paths are totally synced, but rather that everything will still build if you were to replace the files in those common paths with the versions from the destination repo.
</blockquote></details>

well it's not actually true. I removed Amazon from this list.
___
*[`WORKSPACE` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368#-NVAt3Xf8tRTeY7NDV1b:-NVeCM-G68AZNycW-xtR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/25ad6647872e5c0a5aea15006f69798a6e61cef1/WORKSPACE#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Resolve this comment once the related comments from world-federation-of-advertisers/cross-media-measurement#999 have been resolved.
</blockquote></details>

Done.
___
*[`build/variables.bzl` line 95 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368#-NV_9rvU1PyLi_40lSbJ:-NVdzf1Y3eIm3O5Gcot9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/25ad6647872e5c0a5aea15006f69798a6e61cef1/build/variables.bzl#L95)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

sync this my comments on the other repo
</blockquote></details>

Done.
___
*[`src/main/docker/images.bzl` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368#-NV_AX1y81VQvyF8qZtZ:-NW8FaUU6_OxmbsiHYl2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/33a9f2042b4d6f1ea0609a655d72de780fce936b/src/main/docker/images.bzl#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is going to be a problem for the repo merge, as it's a common file path that has distinct contents that only apply to this repo. What you likely need to do instead is to move the targets/defs to different file paths in this repo.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/page_token.proto` line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368#-NV_B28I6wwHMGH45LCO:-NVeCneQA6N95vcmxaPW:b-kj9s56) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/25ad6647872e5c0a5aea15006f69798a6e61cef1/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L59)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why is this file needed?
</blockquote></details>

this was an error. Removed it

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/docker/panel_exchange_client/images.bzl` line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368#-NW9NKFL008XllxUzCS8:-NW9NKFL008XllxUzCS9:b-o11073) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d345d8414e0188271f90b752fe241b642bd2f55c/src/main/docker/panel_exchange_client/images.bzl#L21)):*
> ```Starlark
> _PREFIX = IMAGE_REPOSITORY_SETTINGS.repository_prefix
> 
> # List of specs for all Docker containers to push to a container registry.
> ```

mark a TODO to merge this with the other images.bzl later

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 31 of 46 files at r1, 13 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier)

___
*[`WORKSPACE` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368#-NVAt3Xf8tRTeY7NDV1b:-NW9i7Zo32fByEzEpF_x:b-c8wamj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/25ad6647872e5c0a5aea15006f69798a6e61cef1/WORKSPACE#L27)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

That PR has new related comments.
___
*[`src/main/k8s/panelmatch/base.cue` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368#-NW9iqQL8GKgS3OQyt0I:-NW9iqQMD52hyz9xJxJT:bpknl6h) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d345d8414e0188271f90b752fe241b642bd2f55c/src/main/k8s/panelmatch/base.cue#L15)):*
> ```CUE
> // limitations under the License.
> 
> package k8s
> ```

Similarly add a TODO to reconcile this with the other base.cue.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`WORKSPACE` line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368#-NVAt3Xf8tRTeY7NDV1b:-NWDWsTx9lDTBiwXqyV7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/25ad6647872e5c0a5aea15006f69798a6e61cef1/WORKSPACE#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That PR has new related comments.
</blockquote></details>

Done.
___
*[`src/main/k8s/panelmatch/base.cue` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368#-NW9iqQL8GKgS3OQyt0I:-NWDf1cL67YkLU7MpVp4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d345d8414e0188271f90b752fe241b642bd2f55c/src/main/k8s/panelmatch/base.cue#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Similarly add a TODO to reconcile this with the other base.cue.
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Review by Marco-Premier — COMMENTED** [review]
> Reviewed 33 of 46 files at r1, 7 of 14 files at r2, 5 of 9 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/368)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

**Pull request merged**
