### PR TITLE
Break fusion of Dataflow stages before and after query encryption.

### PR DESCRIPTION
**Pull request by robinsons**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323)* status: all files reviewed, 1 unresolved discussion (waiting on @robinsons, @stevenwarejones, and @yunyeng)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/BreakFusion.kt` line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323#-N0bbJEJ4yKZDhhqeAx8:-N0bbJEJ4yKZDhhqeAx9:bw95ki9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7ff3eec2fd30b7d9754e71746e1e6ddb3283611a/src/main/kotlin/org/wfanet/panelmatch/common/beam/BreakFusion.kt#L41)):*
> ```Kotlin
>       .apply("Pair With Placeholder", ParDo.of(PairWithPlaceholderFn()))
>       .groupByKey()
>       .keys()
> ```

Will this erase multiplicities in the inputs? Would it be better to make KV<T, UUID> keys?

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/BreakFusion.kt` line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323#-N0bbJEJ4yKZDhhqeAx8:-N0bpXwf0ZxboJDumDNO:b3x2yy0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/7ff3eec2fd30b7d9754e71746e1e6ddb3283611a/src/main/kotlin/org/wfanet/panelmatch/common/beam/BreakFusion.kt#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Will this erase multiplicities in the inputs? Would it be better to make KV<T, UUID> keys?
</blockquote></details>

Moved this to be an extension function in `Beam.kt` so that I could take advantage of some of the other extensions with reified type parameters. Also applied your suggestion to key by UUID.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @yunyeng)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323)* status: all files reviewed, 2 unresolved discussions (waiting on @robinsons and @yunyeng)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 211 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323#-N0finNtAXMJL_UZ_czI:-N0finNu1Xc38Ph91kSR:b-83jtb2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/141ca9328359c63f53fe346fc7ffbf641aab404c/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L211)):*
> ```Kotlin
>   ): PCollection<EncryptedQueryBundle> {
>     return unencryptedQueries
>       .breakFusion("Break Fusion Before Encrypt")
> ```

nit: can you put a more specific name here `Break Fusion before Encrypt Queries`
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 217 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323#-N0fiuqG8YoSKEJumjoY:-N0fiuqG8YoSKEJumjoZ:btglzpr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/141ca9328359c63f53fe346fc7ffbf641aab404c/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L217)):*
> ```Kotlin
>           .withSideInputs(privateMembershipKeys)
>       )
>       .breakFusion("Break Fusion After Encrypt")
> ```

should we be breaking fusion after a heavy job? Won't the groupByKey be expensive and memory intensive here? Alternatively, you could reshuffle here to break fusion

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 211 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323#-N0finNtAXMJL_UZ_czI:-N0fkvJv4RYe9Gxzp0Al:bewqx6t) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/141ca9328359c63f53fe346fc7ffbf641aab404c/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L211)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

nit: can you put a more specific name here `Break Fusion before Encrypt Queries`
</blockquote></details>

Remember that this is within the scope of the CreateQueries PTransform, so the name of that is already present. I disagree with this suggestion.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 217 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323#-N0fiuqG8YoSKEJumjoY:-N0fl7B11_apNN0g7GiV:b-e8ax0e) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/141ca9328359c63f53fe346fc7ffbf641aab404c/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L217)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should we be breaking fusion after a heavy job? Won't the groupByKey be expensive and memory intensive here? Alternatively, you could reshuffle here to break fusion
</blockquote></details>

Reshuffle is deprecated and does the exact same thing.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 217 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323#-N0fiuqG8YoSKEJumjoY:-N0flEn1DmIlY4XZ1DzC:bwfweso) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/141ca9328359c63f53fe346fc7ffbf641aab404c/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L217)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

sorry - took a 2nd look at the code -- not memory intensive. what I guess I'm wondering why we need the fusion break here as well. 
</blockquote></details>

(We also have experimental evidence of massive performance gains by doing this, despite the heavy GBL stage)

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 211 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323#-N0finNtAXMJL_UZ_czI:-N0flLdw6ZWCYz-D4Z-i:b-vypjs6) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/141ca9328359c63f53fe346fc7ffbf641aab404c/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L211)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Remember that this is within the scope of the CreateQueries PTransform, so the name of that is already present. I disagree with this suggestion.
</blockquote></details>

On our spark runner, I was seeing complaints in pipeline names are duplicated. Would that not apply to breaking fusion elsewhere in the Create Queries?

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 217 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323#-N0fiuqG8YoSKEJumjoY:-N0flW0zCaETfdP9qJjW:b-aitt4k) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/141ca9328359c63f53fe346fc7ffbf641aab404c/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L217)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

(We also have experimental evidence of massive performance gains by doing this, despite the heavy GBL stage)
</blockquote></details>

experimented with fusion breaks on both sides?

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323)* status: all files reviewed, 3 unresolved discussions (waiting on @robinsons, @stevenwarejones, and @yunyeng)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 211 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323#-N0finNtAXMJL_UZ_czI:-N0gglGN-Qf5cHGqV5r-:b-j4jjp0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/141ca9328359c63f53fe346fc7ffbf641aab404c/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L211)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

On our spark runner, I was seeing complaints in pipeline names are duplicated. Would that not apply to breaking fusion elsewhere in the Create Queries?
</blockquote></details>

I guess only if they chose to use the same names?
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 217 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323#-N0fiuqG8YoSKEJumjoY:-N0gfwFM9SZaHlI4tsqC:bfwkm85) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/141ca9328359c63f53fe346fc7ffbf641aab404c/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L217)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

experimented with fusion breaks on both sides?
</blockquote></details>

The first `breakFusion` takes basically no time. In our experiment, breaking fusion took <5% of the time that it took to run `"Encrypt Queries per Shard"`. By adding it on both sides, this allows Apache Beam to ensure that the workers are 100% CPU-saturated in "Encrypt Queries per Shard". Fusing with a downstream stage could cause I/O to become a blocker and thus fail to saturate CPUs.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt` line 274 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323#-N0ggbmn4aVGBXmSIPkA:-N0ggbmo7iq7UdpQ_RRg:br3e45i) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/141ca9328359c63f53fe346fc7ffbf641aab404c/src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt#L274)):*
> ```Kotlin
>       yield(kvOf(UUID.randomUUID().toString(), it))
>     }
>     .groupByKey()
> ```

Can you give names to all of these steps? Like `.groupByKey("$name/GBK").flatMap("$name/FlatMap") { it.value }`?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 217 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323#-N0fiuqG8YoSKEJumjoY:-N0gi5NA61pqylmMQLA3:bp0bieq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/141ca9328359c63f53fe346fc7ffbf641aab404c/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L217)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The first `breakFusion` takes basically no time. In our experiment, breaking fusion took <5% of the time that it took to run `"Encrypt Queries per Shard"`. By adding it on both sides, this allows Apache Beam to ensure that the workers are 100% CPU-saturated in "Encrypt Queries per Shard". Fusing with a downstream stage could cause I/O to become a blocker and thus fail to saturate CPUs.
</blockquote></details>

okay - so it sounds like we should do this on the other pipelines as well?
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt` line 274 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323#-N0ggbmn4aVGBXmSIPkA:-N0giFeD1YMtmFK8flvT:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/141ca9328359c63f53fe346fc7ffbf641aab404c/src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt#L274)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you give names to all of these steps? Like `.groupByKey("$name/GBK").flatMap("$name/FlatMap") { it.value }`?
</blockquote></details>

+1

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323)* status: all files reviewed, 2 unresolved discussions (waiting on @robinsons and @yunyeng)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 217 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323#-N0fiuqG8YoSKEJumjoY:-N0gs48RED8F525Vg746:bdhp7qg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/141ca9328359c63f53fe346fc7ffbf641aab404c/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L217)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

okay - so it sounds like we should do this on the other pipelines as well?
</blockquote></details>

`EvaluateQueries` already has a CoGBK right before the expensive part. It's possible a `breakFusion` after it would be helpful! We haven't focused on benchmarking this because we have an internal re-implementation of it.

`DecryptQueryResults` has a CoGBK right before and a GBK afterwards so there won't be any unfortunate fusion in that.

@robinsons -- want to throw a `breakFusion` at the end of `EvaluateQueries`?

**Comment by stevenwarejones** [comment]
What about preprocess events as well?

**Review by robinsons — COMMENTED** [review]
Added one at the end. Feel free to move it around based on your testing if that's not the right spot. As Eli mentioned, we have an internal re-implementation of preprocess, so I haven't witnessed the performance of the open source version.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323#-:-N0hGUtYAJjfVEK2o5mr:b-icke0t)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @yunyeng)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 211 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323#-N0finNtAXMJL_UZ_czI:-N0hH1Bw9odwYqbkeQDp:b-ghjqp9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/141ca9328359c63f53fe346fc7ffbf641aab404c/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L211)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I guess only if they chose to use the same names?
</blockquote></details>

Applied the suggestion.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt` line 274 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323#-N0ggbmn4aVGBXmSIPkA:-N0hHzM67EBGUlx-8Vqw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/141ca9328359c63f53fe346fc7ffbf641aab404c/src/main/kotlin/org/wfanet/panelmatch/common/beam/Beam.kt#L274)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/323)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
