### PR TITLE
Add HKDF Pepper to Pipeline

### PR DESCRIPTION
**Pull request by jmorrrr**
Adds pipeline configurations to accept an HKDF Pepper as well as renames "pepper" to be more specific as "identifier hash pepper"

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/87)

### CODE REVIEW

**Review by enfreck — APPROVED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/87)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein and @matthewclegg)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/87)* status: all files reviewed, 1 unresolved discussion (waiting on @jmorrrr and @matthewclegg)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/87#-Mh02DPL9VGlBslxnSzY:-Mh02DPL9VGlBslxnSzZ:b7rvwul) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f8e5d8f4dd1b9f052d19877a44e09957c504f3ac/src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc#L62)):*
> ```cpp
>   if (request.identifier_hash_pepper().empty()) {
>     return absl::InvalidArgumentError(
>         "INVALID ARGUMENT: Empty Identifier Hash Pepper");
> ```

Can you remove the "INVALID ARGUMENT:" part of the strings?

**Review by jmorrrr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/87)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @matthewclegg, @oliver-amzn, and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/87#-Mh02DPL9VGlBslxnSzY:-Mh03yyC9bHBncRD7w3M:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f8e5d8f4dd1b9f052d19877a44e09957c504f3ac/src/main/cc/wfa/panelmatch/client/eventpreprocessing/preprocess_events.cc#L62)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you remove the "INVALID ARGUMENT:" part of the strings?
</blockquote></details>

Done.

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 14 of 16 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/87)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @matthewclegg, and @stevenwarejones)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/87)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 14 of 16 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/87)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Pull request merged**
