### PR TITLE
 move GCS tests into separate path and explicitly map dependencies

### PR DESCRIPTION
**Pull request by jonmolle**
- Other than moving GcsVerifiedStorageClientTest to a gcloud
 subdirectory, this is all a no-op. That move is, too, but technically
 redoes some dependencies.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/241)

### CODE REVIEW

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/241)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein and @robinsons)

**Review by robinsons — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/241)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/241)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle)

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/241)* status: all files reviewed, 1 unresolved discussion (waiting on @jonmolle)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/storage/gcloud/BUILD.bazel, line 7 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/241#-MqWUCsw6ZfZuO6PutEo:-MqWUCsw6ZfZuO6PutEp:b-pb5uuv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9a9dbd60957149a27789ee297a95f8c375d09b9b/src/test/kotlin/org/wfanet/panelmatch/client/storage/gcloud/BUILD.bazel#L7)):*
> ```Starlark
>     timeout = "short",
>     srcs = ["GcsVerifiedStorageClientTest.kt"],
>     test_class = "org.wfanet.panelmatch.client.storage.GcsVerifiedStorageClientTest",
> ```

Update this package?

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/241)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle)

**Review by jonmolle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/241)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @robinsons, and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/panelmatch/client/storage/gcloud/BUILD.bazel, line 7 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/241#-MqWUCsw6ZfZuO6PutEo:-MqWY1-U1Nv18D4TKtpj:b-4kak82) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9a9dbd60957149a27789ee297a95f8c375d09b9b/src/test/kotlin/org/wfanet/panelmatch/client/storage/gcloud/BUILD.bazel#L7)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Update this package?
</blockquote></details>

Yeah, just noticed this, done.

**Pull request merged**
