### PR TITLE
Refactor ExchangeWorkflowDaemon to use CoroutineLauncher.

### PR DESCRIPTION
**Pull request by efoxepstein**
- ExchangeWorkflowDaemon is now an abstract class -- a Runnable that
subclasses will override for specific StorageClient implementations.

- ExchangeTaskExecutorImpl renamed to ExchangeTaskExecutor.

https://rally1.rallydev.com/#/604612930531ud/workviews?detail=%2Ftask%2F607702371149&view=295a0465-1160-4b45-92f5-4c1c70030166&fdp=true?fdp=true

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/99)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/99)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, @jonmolle, and @oliver-amzn)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/99#-MiNDYch8Ivtr3DbYP1K:-MiNDYch8Ivtr3DbYP1L:bfte3hh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/faa0b0f59e4261ec65cfb54dba725af270c3469b/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L68)):*
> ```Kotlin
> }
> 
> fun main(args: Array<String>) = commandLineMain(::run, args)
> ```

don't we still need a main function in the implementation of this abstract class? Is that a follow-up PR?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/99)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @jonmolle, @oliver-amzn, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/99#-MiNDYch8Ivtr3DbYP1K:-MiNgBkm-DKpPBNlG0fZ:b-rbfnqx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/faa0b0f59e4261ec65cfb54dba725af270c3469b/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L68)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

don't we still need a main function in the implementation of this abstract class? Is that a follow-up PR?
</blockquote></details>

Yes -- we'll still need a main function. This change introduces an abstract Runnable -- then follow-up PRs can add an implementation of it.

This PR punts on the question of how storage is set up -- but handles all the other details. This is because customizing storage is going to be basically the only thing that most EDPs will need to do.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/99)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @jonmolle, @oliver-amzn, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/99#-MiNDYch8Ivtr3DbYP1K:-MiNj3oU51FClYi-t1L_:b5pnigf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/faa0b0f59e4261ec65cfb54dba725af270c3469b/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L68)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Yes -- we'll still need a main function. This change introduces an abstract Runnable -- then follow-up PRs can add an implementation of it.

This PR punts on the question of how storage is set up -- but handles all the other details. This is because customizing storage is going to be basically the only thing that most EDPs will need to do.
</blockquote></details>

I should also point out that `ExchangeWorkflowDaemon` as an abstract class will make it easier to run our in-process end-to-end test or have a customized `main` for a test on KinD.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/99)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @efoxepstein, @jonmolle, and @oliver-amzn)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/99#-MiNDYch8Ivtr3DbYP1K:-MiORVHd3Hz-4fufiuV0:bt2p84j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/faa0b0f59e4261ec65cfb54dba725af270c3469b/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L68)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I should also point out that `ExchangeWorkflowDaemon` as an abstract class will make it easier to run our in-process end-to-end test or have a customized `main` for a test on KinD.
</blockquote></details>

sounds good. please add TODOs around storage and the follow up pr that implements this abstract class.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/99)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @jonmolle, @oliver-amzn, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/99#-MiNDYch8Ivtr3DbYP1K:-MiOdZMy4io5cYygAvE6:byf2zpe) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/faa0b0f59e4261ec65cfb54dba725af270c3469b/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L68)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

sounds good. please add TODOs around storage and the follow up pr that implements this abstract class.
</blockquote></details>

Done -- and added a stub of a `main`.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/99)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @jonmolle, @oliver-amzn, and @stevenwarejones)

**Pull request merged**
