### PR TITLE
Add kt_jvm_proto_library targets.

### PR DESCRIPTION
**Pull request by efoxepstein**
For future reference, the hard work was done with a find/replace:

Find regex: `(java_proto_library\([^)]+name = "(.+)_java_proto[^)]+deps = (\[[^\]]+\])[^)]+\))`
Replace regex: `$1\nkt_jvm_proto_library(name = "$2_kt_jvm_proto", srcs = $3, deps = [":$2_java_proto"])`

Then `java_proto` was replaced by `kt_jvm_proto` in the `//src/{main,test}/kotlin/` subtrees.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/92)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/92)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @wangyaopw)

**Review by wangyaopw — APPROVED** [review]
Can you please educate me the main benefit of this? it kt_jvm_proto much more efficient in kotlin? I am wonder why we bother to do this now.

**Review by efoxepstein — COMMENTED** [review]
This enables using special Kotlin methods. For example:

```
val something  =
  Foo.newBuilder()
    .apply {
      someBarBuilder.apply {
        mango = 1
        addPeaches(2)
     }
  }
  .build()
```

becomes the simpler, more idiomatic Kotlin:

```
val something = foo {
  someBar = bar {
    mango = 1
    peaches += 2
  } 
}
```

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/92#-:-MhLFNey5UsSO6tLaryz:b-v6xlti)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by wangyaopw — COMMENTED** [review]
Awesome~! Looking forwards to trying the new way.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/92#-:-MhLJJOE3y4lkUT8Lmlr:b9l1jtk)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 23 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/92)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Review by SanjayVas — APPROVED** [review]
As an added benefit, nested type-safe builders are more tightly scoped.

e.g. 

```
message Foo {
  message Bar {
    int64 mango = 1;
    repeated int64 peaches = 2;
  }
  string baz = 2;
}
```

The Kotlin scope function (e.g. `apply` or `also`) allows you to do the following:

```
val something  =
  Foo.newBuilder()
    .apply {
      someBarBuilder.apply {
        mango = 1
        addPeaches(2)
        baz = "Misleadingly setting a Foo field from Bar builder"
     }
  }
  .build()
```

The Kotlin type-safe proto builders don't allow you to do this unless you explicitly reference the other scope using `this@`.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/92#-:-MhLWz-P8i163hct_fyr:b-3xjmd8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Pull request merged**
