### PR TITLE
Add E2E test for double blinding sub-protocol

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/217)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 5 of 9 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/217)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/Maps.kt, line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/217#-Mp8fhgPDvcGW3xPqS7_:-Mp8fhgPDvcGW3xPqS7a:betm9v5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbc53e11c41b601615f1ab24537ecf2e2026921b/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/Maps.kt#L4)):*
> ```Kotlin
> 
> /** Convenience function for throwing an [IllegalArgumentException] if a map key is missing. */
> fun <K, V> Map<K, V>.getRequired(key: K): V {
> ```

how about we pass in a message as well?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt, line 69 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/217#-Mp8gbOC4_i4aQRRNH7e:-Mp8gbOC4_i4aQRRNH7f:bghjcww) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbc53e11c41b601615f1ab24537ecf2e2026921b/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt#L69)):*
> ```Kotlin
>       val blob = privateStorage.getBlob(blobKey)
>       if (blob == null) {
>         logger.addToTaskLog("Input label '$label' with blob key '$blobKey' missing", Level.WARNING)
> ```

why only a warning and not throw an error?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/217)* status: 7 of 10 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/Maps.kt, line 4 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/217#-Mp8fhgPDvcGW3xPqS7_:-Mp8q1cW50AIelBgvOdn:bumbn73) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbc53e11c41b601615f1ab24537ecf2e2026921b/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/Maps.kt#L4)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

how about we pass in a message as well?
</blockquote></details>

Removed this -- found a better way.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt, line 69 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/217#-Mp8gbOC4_i4aQRRNH7e:-Mp8ngwyCrUlpVlzE0tj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/dbc53e11c41b601615f1ab24537ecf2e2026921b/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt#L69)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why only a warning and not throw an error?
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 8 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/217)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CustomIOExchangeTask.kt, line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/217#-Mp8rF5I-425uCRk7gui:-Mp8rF5I-425uCRk7guj:b-jvcvc7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1a423c991fb2aafb7cf6ecbf693f54e09fe51dca/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CustomIOExchangeTask.kt#L26)):*
> ```Kotlin
>     input: Map<String, StorageClient.Blob>
>   ): Map<String, Flow<ByteString>> {
>     require(input.isEmpty())
> ```

didn't you just remove this?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/217)* status: 11 of 13 files reviewed, all discussions resolved (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CustomIOExchangeTask.kt, line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/217#-Mp8rF5I-425uCRk7gui:-Mp8s5Nq4jpXBkih5QW0:bahhwgy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1a423c991fb2aafb7cf6ecbf693f54e09fe51dca/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CustomIOExchangeTask.kt#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

didn't you just remove this?
</blockquote></details>

Yes, yes I did. But now I'm adding it back. Alas, I'm a gardener, not an architect. It took some tinkering but I think it's better with this here.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/217)* status: 11 of 13 files reviewed, all discussions resolved (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CustomIOExchangeTask.kt, line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/217#-Mp8rF5I-425uCRk7gui:-Mp8sll_73viGCRRMfkl:b32vhw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1a423c991fb2aafb7cf6ecbf693f54e09fe51dca/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CustomIOExchangeTask.kt#L26)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Yes, yes I did. But now I'm adding it back. Alas, I'm a gardener, not an architect. It took some tinkering but I think it's better with this here.
</blockquote></details>

:)

**Review by yunyeng — APPROVED** [review]
> Reviewed 2 of 10 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/217)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
