### PR TITLE
Refactor Cryptor

### PR DESCRIPTION
**Pull request by efoxepstein**
(1) This REMOVES the batch methods Cryptor -- they add unnecessary
     complexity. One reason they originally existed was to make the class
    threadsafe but that's not needed. Instead, it's explicitly documented as
    not threadsafe.
    
(2) Renames Cryptor to DeterministicCommutativeCipher to be more
    specific.
    
(3) Misc code clean-ups, such as removing assumptions about error
    messages.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/91)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 7 of 27 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/91)* status: 7 of 27 files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/91#-MhLSZW53yw3AGfQtOZt:-MhLSZW53yw3AGfQtOZu:b-j58etc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a335cc64e9acfced1bca3b0f5d456c2a62daff56/-- commits#L7)):*
I thought one of the main reasons was to minimize the number of JNI calls since they involve serialization and are semi-expensive.
___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/91#-MhLSk7M1qEShFzU_oeH:-MhLSk7N52y2r3AdWFE1:br5xcgk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a335cc64e9acfced1bca3b0f5d456c2a62daff56/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L42)):*
> ```cpp
> using ::wfa::panelmatch::common::crypto::GetSha256Hkdf;
> using ::wfa::panelmatch::common::crypto::Hkdf;
> using ::wfa::panelmatch::common::crypto::NewDeterministicCommutativeCipher;
> ```

help me here. whats a new cipher?

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/91)* status: 7 of 27 files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/91#-MhLSZW53yw3AGfQtOZt:-MhOSVbv03evNjWzzL1O:b5lsfcr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a335cc64e9acfced1bca3b0f5d456c2a62daff56/-- commits#L7)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I thought one of the main reasons was to minimize the number of JNI calls since they involve serialization and are semi-expensive.
</blockquote></details>

I see how this batching kind of conflicts with the batching in Beam. Was that the impetus for this? We could batch process them only for join key exchange but not for preprocess. That seems like an option too.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/91)* status: 7 of 27 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/91#-MhLSk7M1qEShFzU_oeH:-MhOi9Fw3cO2bc64ZEBZ:bgaf55e) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a335cc64e9acfced1bca3b0f5d456c2a62daff56/src/main/cc/wfa/panelmatch/client/eventpreprocessing/tools/encrypted_event_decrypter_main.cc#L42)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

help me here. whats a new cipher?
</blockquote></details>

This is just what I renamed CreateCipherFromKey.

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/91)* status: 7 of 27 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/91#-MhLSZW53yw3AGfQtOZt:-MhQYN-4-X9CA4cK8sAX:bibhsmr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a335cc64e9acfced1bca3b0f5d456c2a62daff56/-- commits#L7)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This PR doesn't change the number of JNI calls.
</blockquote></details>

i know. I was just wondering if that would be in follow-ups.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/91)* status: 7 of 27 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[-- commits, line 7 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/91#-MhLSZW53yw3AGfQtOZt:-MhQZgQA7fJ0XZmKkvnz:b-19l4jo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a335cc64e9acfced1bca3b0f5d456c2a62daff56/-- commits#L7)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i know. I was just wondering if that would be in follow-ups. 
</blockquote></details>

No, the number of JNI calls will not change in follow-up PRs. This PR is about making a more ergonomic interface -- since my thinking has changed since we originally built it.

**Pull request merged**
