### PR TITLE
Add WorkflowExchangeTask to run Beam pipelines

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @jonmolle)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDabuS45FudZ00b43o:-MkDabuS45FudZ00b43p:b-v96aa3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L25)):*
> ```Kotlin
> 
> /** Executes workflows (e.g. Apache Beam pipelines) in an [ExchangeTask]. */
> class WorkflowExchangeTask(private val workflow: Workflow) : ExchangeTask {
> ```

how do you propose to test this?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDaPUB36LdgiuYqiLy:-MkDaPUB36LdgiuYqiLz:befnczm) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L46)):*
> ```Kotlin
> 
> private suspend fun makeInput(blob: VerifiedBlob): String {
>   return blob.read().flatten().toStringUtf8()
> ```

it would be nice to keep it as a flow and convert the flow on the fly to PCollections. Is that possible?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDa_Mk1pdeP53NPQZo:-MkDa_Mk1pdeP53NPQZp:b-2guby3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L49)):*
> ```Kotlin
> }
> 
> private fun makeOutputBlob(uri: String): Flow<ByteString> {
> ```

same here

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDaPUB36LdgiuYqiLy:-MkDbsph4qhG-fmUv1t0:b458448) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L46)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

it would be nice to keep it as a flow and convert the flow on the fly to PCollections. Is that possible?
</blockquote></details>

That's infeasible for large PCollections because a single thread would be reading gigabytes of data.

The idea here is that the blob encodes a URI from which Beam can efficiently load a PCollection in parallel.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDnvA40tJ89_sjjDGm:-MkDnvA5-TjjFpHDqIbb:b11lnri) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L40)):*
> ```Kotlin
>   override suspend fun execute(input: Map<String, VerifiedBlob>): Map<String, Flow<ByteString>> {
>     val inputUris = input.mapValues { makeInput(it.value) }
>     val outputUris = workflow.execute(inputUris)
> ```

don't we want to pass in inputUris and outputUris to the workflow?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDn2LI3UXDVY5RarzF:-MkDn2LJ53CfBM78xIyh:b-s38za4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L41)):*
> ```Kotlin
>     val inputUris = input.mapValues { makeInput(it.value) }
>     val outputUris = workflow.execute(inputUris)
>     return outputUris.mapValues { makeOutputBlob(it.value) }
> ```

don't we just want to return `emptyMap` here?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDaPUB36LdgiuYqiLy:-MkDkXK6CoBBXEM0FHWx:bf3cpou) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L46)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

That's infeasible for large PCollections because a single thread would be reading gigabytes of data.

The idea here is that the blob encodes a URI from which Beam can efficiently load a PCollection in parallel.
</blockquote></details>

so, we're just reading a uri from blob storage and passing it to beam? If so elaborate on your existing comments to put something like that in. Maybe something about about this interface exists for exchange tasks that take care of their own I/O.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDa_Mk1pdeP53NPQZo:-MkDoNJB7MYx4dE_-BSg:b-913dmz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L49)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

same here
</blockquote></details>

do we need a makeOutputBlob? Isn't the workflow going to take care of that?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @jonmolle)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDabuS45FudZ00b43o:-MkDoa9l1rccvAT9AIsY:btegqn5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L25)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

I think having a mock workflow implementation should be fine, but I would like to see that in this or a followup PR as well. I would think the workflows themselves should be tested to make sure they can run reading in some mocked set of input URIs
</blockquote></details>

sounds good to me. I'd still like to see that test as part of this PR.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @jonmolle)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130)* status: 2 of 24 files reviewed, 5 unresolved discussions (waiting on @duliomatos1 and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDabuS45FudZ00b43o:-MkDwcqXDLQ0FA8mCH64:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L25)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

sounds good to me. I'd still like to see that test as part of this PR.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDnvA40tJ89_sjjDGm:-MkDwfKOCLCBPPTyuRZO:b-vmkr1n) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L40)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

don't we want to pass in inputUris and outputUris to the workflow?
</blockquote></details>

I don't understand this comment, can you clarify?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDn2LI3UXDVY5RarzF:-MkDwj072SD7_27qk2qy:b-ptmygq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L41)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

don't we just want to return `emptyMap` here?
</blockquote></details>

Nope -- these blobs are manifests of the outputs from the workflow.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDaPUB36LdgiuYqiLy:-MkDwr9pDP9BTeiOd_eT:bmfvh1n) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L46)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

so, we're just reading a uri from blob storage and passing it to beam? If so elaborate on your existing comments to put something like that in. Maybe something about about this interface exists for exchange tasks that take care of their own I/O.
</blockquote></details>

The blobs that we're reading here are effectively manifests for the inputs to the workflow.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDa_Mk1pdeP53NPQZo:-MkE1iyB2b9DEeugvIKH:bb71pro) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L49)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do we need a makeOutputBlob? Isn't the workflow going to take care of that?
</blockquote></details>

PTAL

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130)* status: 2 of 24 files reviewed, 5 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDnvA40tJ89_sjjDGm:-MkE3jVLAU6INDHmjIjb:b-ix7zlk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L40)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I don't understand this comment, can you clarify?
</blockquote></details>

If I'm understanding this correctly, then we want to pass in inputUris and outputUris to the workflow so that that, for example, Apache Beam knows where to read its PCollection from and *also* where to write the output PCollection too as well.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDn2LI3UXDVY5RarzF:-MkE3x5nCaJKftVKGp1m:bwmpc2t) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Nope -- these blobs are manifests of the outputs from the workflow.
</blockquote></details>

do you have an example? Aren't the outputs generally going to be written directly the workflow, itself?

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 16 of 22 files at r2, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130)* status: 20 of 25 files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @stevenwarejones)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130)* status: 20 of 25 files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDnvA40tJ89_sjjDGm:-MkE4wc-DtymdxN5vugn:be7h6wx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L40)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

If I'm understanding this correctly, then we want to pass in inputUris and outputUris to the workflow so that that, for example, Apache Beam knows where to read its PCollection from and *also* where to write the output PCollection too as well.
</blockquote></details>

inputUris is passed to the workflow. The workflow can put its outputs wherever it wants as long as it returns the right manifest.

Maybe Workflow should take in some URI prefix for there to put its blobs, like `s3://some-bucket/some-prefix/`? I don't really want WorkflowExchangeTask to have to know exactly what outputs Workflow will have -- unless maybe we make that a property of `Workflow` that `WorkflowExchangeTask` can use?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130)* status: 20 of 25 files reviewed, 4 unresolved discussions (waiting on @duliomatos1 and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDnvA40tJ89_sjjDGm:-MkEGtAHDYsZO0nabawJ:b-9zvkqh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L40)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`The workflow can put its outputs wherever it wants` - Not sure I like that - the storage it reads from won't necessarily be the same storage it writes to. unless we make it a condition that these workflows don't operate on sharedStorage. They just read in from a single privateStorage and writeback to the same storage. In that case, we do need at least a prefix or something to delineate where to write to.

Why don't you want WorkflowExchangeTask to know where to write to?
</blockquote></details>

Added a prefix. We can sort out later where it's allowed to write to.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDn2LI3UXDVY5RarzF:-MkECfoRD6dNO0nYNFx7:brsdk64) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L41)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do you have an example? Aren't the outputs generally going to be written directly the workflow, itself?
</blockquote></details>

The manifests won't be. And the workflow might have some small blobs that it can just return in-memory instead of writing out itself.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkDaPUB36LdgiuYqiLy:-MkEDFuFEJiBgBpJ9sEc:b7t1qm7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/307cb6b851e34c812f140d94f4158f15560408c9/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L46)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i agree. just thought that should be in a comment.
</blockquote></details>

I believe this is covered by the comments now, PTAL
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 48 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkE759d-uaVfitZ0Wrd:-MkEC9AF392TfcvUx6l9:b-chredh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1905961b7262950661e00446b84062775f03c69e/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L48)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't execute just kick off the workflow and exit? It shouldn't wait around for data to be written. There should just be another inputTask waiting for the previous job to have completed, right?
</blockquote></details>

Why? I see no issue with just waiting. Otherwise, how do you know whether it completed successfully or not? (This is no different from InputTask, which can be extremely long-lived.)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130)* status: 20 of 25 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 48 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkE759d-uaVfitZ0Wrd:-MkEVDBsDWYiyiBubTuZ:b-996k7y) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1905961b7262950661e00446b84062775f03c69e/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L48)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why? I see no issue with just waiting. Otherwise, how do you know whether it completed successfully or not? (This is no different from InputTask, which can be extremely long-lived.)
</blockquote></details>

well, the inputtask can fail and restart easily or timeout and restart over time. This can't.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130)* status: 20 of 25 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt, line 48 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-MkE759d-uaVfitZ0Wrd:-MkEVh3A00XYpmbXQkJG:b514g51) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1905961b7262950661e00446b84062775f03c69e/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/WorkflowExchangeTask.kt#L48)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

well, the inputtask can fail and restart easily or timeout and restart over time. This can't.
</blockquote></details>

Again, how do you know if it completed successfully or not?

**Review by stevenwarejones — APPROVED** [review]
Thanks for bearing with me on this one.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/130#-:-MkEdq_g0VE1jNm0HAAl:bjoji6q)* status: 20 of 25 files reviewed, all discussions resolved (waiting on @duliomatos1)

**Pull request merged**
