### PR TITLE
Adds a proto to created a signed index of multipart data

### PR DESCRIPTION
**Pull request by jonmolle**
Things like pcollection are too large to validate at once. This is a
simple wrapper proto that can be used to validate that a selection of
SignedData objects has the correct number of objects and no duplicates.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/126)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/126)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @jonmolle, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/126#-Mk9c8Mo9zpts5mFxWK4:-Mk9c8Mp2O4obrlsQ2_O:b-fnle20) (no related file):*
This looks like it also includes changes from another PR of yours. Can you remove those changes from this PR?

---

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/126)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @jonmolle)

___
*[-- commits, line 14 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/126#-Mk9nzgV5RYwV2br1f30):*
is it possible to just have a converter that works on a Flow<ByteString> to PCollection<ByteString> and vice versa so we don't have to worry about multi-part downloads and chunk indices?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/126)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @jonmolle)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/126#-MkEeGHU6rW3uDPyDPMe:-MkEeGHU6rW3uDPyDPMf:b-vuzs8h) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c2f1a37fed208b8fc64305ae85700fa7efd41964/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L70)):*
> ```Kotlin
> }
> 
> fun buildWorkflow(
> ```

i think this is part of another pr. can you remove here?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt, line 116 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/126#-MkEeLG62cS710L7QNa0:-MkEeLG702yorpPp4TU6:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c2f1a37fed208b8fc64305ae85700fa7efd41964/src/main/kotlin/org/wfanet/panelmatch/client/launcher/testing/TestStep.kt#L116)):*
> ```Kotlin
> }
> 
> fun buildExchangeStep(
> ```

ditto

**Comment by jonmolle** [comment]
Not necessary with Eli's implementation

**Pull request closed without merging**
