### PR TITLE
Build Queries Step Outputs Discarded Join Keys

### PR DESCRIPTION
**Pull request by stevenwarejones**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345)

### CODE REVIEW

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @robinsons)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 80 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345#-N5CBpjSCfJIPPl_qMt3:-N5LKNUh62iGX2oBA5h5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d12768bb8fe4a929c77764d6349a7d82c9fc30b5/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L80)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

As these are join keys, should we rename `discardedQueries` to `discardedJoinKeys` throughout?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345#-N5CFNon4nRimF9UEXa4:-N5HtL4S-zf786EzJgQX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d12768bb8fe4a929c77764d6349a7d82c9fc30b5/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L136)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Can you add braces around the body of the if statement?
</blockquote></details>

Done.



_Code quote:_
```Kotlin
if (!parameters.padQueries)
```
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 298 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345#-N5CFiUM8GYOpSMr9lC1:-N5Ht8eK9_jM8t0eXRIP:bmje37z) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/d12768bb8fe4a929c77764d6349a7d82c9fc30b5/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L298)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Could we choose a more descriptive name than `discardStatus`, like `isDiscarded` or something? When I see "status" I'm inclined to look for an associated enum with values like `KEEP` and `DISCARD`.
</blockquote></details>

+1. Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345)* status: all files reviewed, 6 unresolved discussions (waiting on @robinsons and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345#-N6JIYCaDUuYlNZFuqYM:-N6JIYCaDUuYlNZFuqYN:binchj) (no related file):*
Given that this PR is _not_ backwards compatible with existing ExchangeWorkflows, what's the rollout plan? I'm wondering if ProductionExchangeTaskMapper can look for the existence of the output label and then only output the discarded queries if it exists?

___
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 90 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345#-N6JIHn9618voRcyIH31:-N6JIHn9618voRcyIH32:b-dmdw4u) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c1a0cd497c152d7b86a20278e4981a640916d448/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L90)):*
> ```Kotlin
>   override fun expand(input: PCollection<LookupKeyAndId>): PCollectionTuple {
>     val queriesByShard = shardLookupKeys(input)
>     val allQueriesByShard = addPaddedQueries(queriesByShard)
> ```

`DoFn` in Apache Beam supports multiple output PCollections: https://beam.apache.org/documentation/programming-guide/#additional-outputs

To me, that seems like a cleaner way to implement EqualizeQueriesPerShardFn. WDYT?
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt` line 56 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345#-N6JIMu93f3CFvCiZSdC:-N6JIMu93f3CFvCiZSdD:bhet8gr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c1a0cd497c152d7b86a20278e4981a640916d448/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L56)):*
> ```Kotlin
>  */
> fun List<JoinKeyAndId>.removeDiscardedJoinKeys(
>   discardedJoinKeys: List<JoinKeyIdentifier>
> ```

This could potentially be a very large list, right? Would a set be more efficient?

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein and @robinsons)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345#-N6JIYCaDUuYlNZFuqYM:-N6UBG_IBeJjw-RIYc_I:b-9303rn) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Given that this PR is _not_ backwards compatible with existing ExchangeWorkflows, what's the rollout plan? I'm wondering if ProductionExchangeTaskMapper can look for the existence of the output label and then only output the discarded queries if it exists?
</blockquote></details>

I don't think you can just do this in the ProductionExchangeTaskMapper. I took care of it on the task level too. I have one workflow with discarded-queries in it and another without so legacy workflows are tested too. wdyt?

___
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 90 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345#-N6JIHn9618voRcyIH31:-N6Tzq0i5_o8kUMqDBw5:b-ygu3ah) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c1a0cd497c152d7b86a20278e4981a640916d448/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L90)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`DoFn` in Apache Beam supports multiple output PCollections: https://beam.apache.org/documentation/programming-guide/#additional-outputs

To me, that seems like a cleaner way to implement EqualizeQueriesPerShardFn. WDYT?
</blockquote></details>

I searched for this feature when building this PR but couldn't find it. Great find. Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt` line 56 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345#-N6JIMu93f3CFvCiZSdC:-N6U-fEe-vQi3mjhQLBY:b5ohibo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c1a0cd497c152d7b86a20278e4981a640916d448/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/DecryptQueryResults.kt#L56)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This could potentially be a very large list, right? Would a set be more efficient?
</blockquote></details>

done. converted discardedJoinKeys to a set.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345)* status: all files reviewed, 5 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt` line 140 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345#-N6ULd9i9cSIVaBftcYi:-N6ULd9i9cSIVaBftcYj:bq1x010) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c81627ac165ff8cb67e8fdcde92d710d6e41588a/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt#L140)):*
> ```Kotlin
>         padQueries = stepDetails.addPaddingQueries,
>       )
>     // For backwards compatibility for workflows without discarded-join-keys
> ```

Maybe: `TODO: remove this functionality v2.0.0` or something?
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 327 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345#-N6UMPXk3TEKSK6vWpzV:-N6UMPXk3TEKSK6vWpzW:byfjg1y) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c81627ac165ff8cb67e8fdcde92d710d6e41588a/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L327)):*
> ```Kotlin
>       if (queryCountDelta > 0) {
>         allQueries.takeLast(queryCountDelta).forEach { bucketQuery ->
>           out.get(CreateQueries.discardedJoinKeysTag).output(bucketQuery.joinKeyIdentifier)
> ```

I suspect it's not super efficient to call `MultiOutputReceiver.get` in a loop, maybe save it to a variable? `val discardedJoinKeyOutput = out[CreateQueries.discardedJoinKeysTag]`

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @robinsons)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt` line 140 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345#-N6ULd9i9cSIVaBftcYi:-N6UNQcS7c-EXdYTijoN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c81627ac165ff8cb67e8fdcde92d710d6e41588a/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt#L140)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe: `TODO: remove this functionality v2.0.0` or something?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt` line 327 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345#-N6UMPXk3TEKSK6vWpzV:-N6UN3tE-bmJXOTQ94LB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c81627ac165ff8cb67e8fdcde92d710d6e41588a/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueries.kt#L327)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I suspect it's not super efficient to call `MultiOutputReceiver.get` in a loop, maybe save it to a variable? `val discardedJoinKeyOutput = out[CreateQueries.discardedJoinKeysTag]`
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345)* status: all files reviewed, 3 unresolved discussions (waiting on @robinsons)

**Review by robinsons — APPROVED** [review]
> Reviewed 4 of 10 files at r2, 5 of 9 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/345)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
