### PR TITLE
ByteStringSize Implementation

### PR DESCRIPTION
**Pull request by jmorrrr**
Adds implementation for the SerializableFunction for use with BatchingDoFn

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/60)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/60)* status: all files reviewed, 3 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/60#-MfJ7n068xRA5OsGuhCW:-MfJ7n068xRA5OsGuhCX:bid4yzi) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c5cd98a5bda1fac9770e6e5a2d2e4eb5872d5075/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L13)):*
> ```Starlark
>             "EncryptEvents.kt",
>             "EncryptionEventsDoFn.kt",
>             "MaxByteSize.kt",
> ```

It's getting a little annoying to have to list all these exceptions. How about we just collapse this into a single kt_jvm_library? In other words, just have `eventpreprocessing` and don't exclude anything.

We can always split up again later if needed.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/MaxByteSize.kt, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/60#-MfJ7NFODeOcUA9A-6Co:-MfJ7NFODeOcUA9A-6Cp:b6q80qk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c5cd98a5bda1fac9770e6e5a2d2e4eb5872d5075/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/MaxByteSize.kt#L21)):*
> ```Kotlin
> 
> /** Takes in a ByteString and returns its size in bytes */
> object MaxByteSize : SerializableFunction<ByteString, Int> {
> ```

Why `Max`? Can I suggest renaming this class to `ByteStringSize`?
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/MaxByteSizeTest.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/60#-MfJ7XNrCOAlNqJbbUXL:-MfJ7XNrCOAlNqJbbUXM:bxleana) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c5cd98a5bda1fac9770e6e5a2d2e4eb5872d5075/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/MaxByteSizeTest.kt#L27)):*
> ```Kotlin
>   @Test
>   fun empty() {
>     val test: ByteString = ByteString.copyFromUtf8("")
> ```

Can you use `ByteString.EMPTY` to get an empty bytestring?

**Review by jmorrrr — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/60)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @enfreck, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/60#-MfJ7n068xRA5OsGuhCW:-MfJ9vQu3YVzdWEGZ77g:b-3kytrb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c5cd98a5bda1fac9770e6e5a2d2e4eb5872d5075/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L13)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's getting a little annoying to have to list all these exceptions. How about we just collapse this into a single kt_jvm_library? In other words, just have `eventpreprocessing` and don't exclude anything.

We can always split up again later if needed.
</blockquote></details>

I don't know why I was using exclude so much but I just made it so that jvm_library had two sources  so I don't have to do the exclude anymore but if you think I should just make one big library I can do that.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/MaxByteSize.kt, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/60#-MfJ7NFODeOcUA9A-6Co:-MfJ9KHb2mMr4Ec5FfJl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c5cd98a5bda1fac9770e6e5a2d2e4eb5872d5075/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/MaxByteSize.kt#L21)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why `Max`? Can I suggest renaming this class to `ByteStringSize`?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/MaxByteSizeTest.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/60#-MfJ7XNrCOAlNqJbbUXL:-MfJ9PTgC8Rdn_-2-EvV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c5cd98a5bda1fac9770e6e5a2d2e4eb5872d5075/src/test/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/MaxByteSizeTest.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you use `ByteString.EMPTY` to get an empty bytestring?
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/60)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @enfreck, @matthewclegg, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/60#-MfJ7n068xRA5OsGuhCW:-MfJJWtYAeui-6Bs3pfx:b69e62k) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c5cd98a5bda1fac9770e6e5a2d2e4eb5872d5075/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L13)):*
<details><summary><i>Previously, jmorrrr (Julia Morrissey) wrote…</i></summary><blockquote>

I don't know why I was using exclude so much but I just made it so that jvm_library had two sources  so I don't have to do the exclude anymore but if you think I should just make one big library I can do that.
</blockquote></details>

i agree. not seeing the change yet though.

**Review by enfreck — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/60)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @matthewclegg)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/60)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel, line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/60#-MfJ7n068xRA5OsGuhCW:-MfJNcZa1fLarsf-cZ6Z:b-wg09v7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/c5cd98a5bda1fac9770e6e5a2d2e4eb5872d5075/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/BUILD.bazel#L13)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i agree. not seeing the change yet though.
</blockquote></details>

Ah, this is fine too for me

**Review by matthewclegg — APPROVED** [review]

**Pull request merged**
