### PR TITLE
add parameters to create workflow now that protos are set

### PR DESCRIPTION
**Pull request by stevenwarejones**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 223 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129#-MkDM7CFEIS8-cUlM59o:-MkDM7CG8u3Bm4VqfcWv:b277r6x) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/87b09f64dc177e1804fec6024202093ed698980e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L223)):*
> ```Kotlin
>         name = "Map to EncryptQueriesResponse"
>       ) {
>       val encryptQueriesRequest = privateMembershipEncryptRequest {
> ```

Here's a counter-proposal to what we have here:

1. Change `PrivateMembershipCryptor`'s interface: `fun encryptQueries(unencryptedQueries: Iterable<UnencryptedQuery>)`
2. Change `JniPrivateMembershipCryptor` to take in the parameters, public/private keys in the constructor
3. Change `JniPrivateMembershipCryptor::encryptQueries` to use `JniPrivateMembership` instead of directly using `PrivateMembershipWrapper`.

Since `PrivateMembershipEncryptRequest` never crosses the JNI barrier and doesn't get serialized to a ByteString (as far as I can tell), it doesn't make sense to me to use a proto for this.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 223 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129#-MkDM7CFEIS8-cUlM59o:-MkHl4rf5YBXuyoY9s8g:bc63wjj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/87b09f64dc177e1804fec6024202093ed698980e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L223)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Here's a counter-proposal to what we have here:

1. Change `PrivateMembershipCryptor`'s interface: `fun encryptQueries(unencryptedQueries: Iterable<UnencryptedQuery>)`
2. Change `JniPrivateMembershipCryptor` to take in the parameters, public/private keys in the constructor
3. Change `JniPrivateMembershipCryptor::encryptQueries` to use `JniPrivateMembership` instead of directly using `PrivateMembershipWrapper`.

Since `PrivateMembershipEncryptRequest` never crosses the JNI barrier and doesn't get serialized to a ByteString (as far as I can tell), it doesn't make sense to me to use a proto for this.
</blockquote></details>

The main point of this PR is to fix a current defect where the pipeline wasn't properly passing parameters to the PrivateMembershipCryptor.

To your point, I think I agree. However, we are using a lot of protos that never cross the JNI layer. Things like QueryId, QueryBundle, DatabaseShard don't cross the JNI layer either. What is your opinion on the continued use of those?

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 223 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129#-MkDM7CFEIS8-cUlM59o:-MkI4ot86Y1YBV1q_BPe:b-izummj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/87b09f64dc177e1804fec6024202093ed698980e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L223)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

The main point of this PR is to fix a current defect where the pipeline wasn't properly passing parameters to the PrivateMembershipCryptor.

To your point, I think I agree. However, we are using a lot of protos that never cross the JNI layer. Things like QueryId, QueryBundle, DatabaseShard don't cross the JNI layer either. What is your opinion on the continued use of those?
</blockquote></details>

Those get serialized by Beam. If they never get serialized by anything, we shouldn't use them.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 37 of 37 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1 and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/PrivateMembershipCryptor.kt, line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129#-Mkd5OlHEC-hbYFH8ECL:-Mkd5OlHEC-hbYFH8ECM:bv5kn7h) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ff102b71c78573bbee96969a1a84fd4094a8ddb/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/PrivateMembershipCryptor.kt#L29)):*
> ```Kotlin
>  * retrieval
>  */
> abstract class PrivateMembershipCryptor(private val serializedParameters: ByteString) :
> ```

If this is private and unused, what is the purpose of serializedParameters? I think it's inaccessible. I'd just keep the interface the way it was.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsWorkflowTest.kt, line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129#-Mkd5i3C1kSOHYkuLqE1:-Mkd5i3C1kSOHYkuLqE2:b-yhv2sg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ff102b71c78573bbee96969a1a84fd4094a8ddb/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractDecryptQueryResultsWorkflowTest.kt#L45)):*
> ```Kotlin
> private val PLAINTEXTS: List<Pair<Int, List<Plaintext>>> =
>   listOf(
>     Pair(1, listOf(plaintextOf("<some long data a>"), plaintextOf("<some long data b>"))),
> ```

Very optional: usually I find `x to y` syntax easier to read than `Pair(x, y)`
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractQueryEvaluatorTest.kt, line 92 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129#-Mkd5rEj1y4nsjyxXRfP:-Mkd5rEj1y4nsjyxXRfQ:bd805cn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ff102b71c78573bbee96969a1a84fd4094a8ddb/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractQueryEvaluatorTest.kt#L92)):*
> ```Kotlin
>   }
> 
>   private fun queryBundleOf(shard: Int, queries: List<Pair<Int, Int>>): EncryptedQueryBundle {
> ```

`encryptedQueryBundleOf`?

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129)* status: 17 of 44 files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 223 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129#-MkDM7CFEIS8-cUlM59o:-Mklk6gv5j5PCTif6psw:b-cj5ib) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/87b09f64dc177e1804fec6024202093ed698980e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L223)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Those get serialized by Beam. If they never get serialized by anything, we shouldn't use them.
</blockquote></details>

done. except i only take the parameters in the constructor. Kept keys in the methods.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/PrivateMembershipCryptor.kt, line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129#-Mkd5OlHEC-hbYFH8ECL:-MklkEIUDAAZnyyDfQFJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ff102b71c78573bbee96969a1a84fd4094a8ddb/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/PrivateMembershipCryptor.kt#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

If this is private and unused, what is the purpose of serializedParameters? I think it's inaccessible. I'd just keep the interface the way it was.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractQueryEvaluatorTest.kt, line 92 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129#-Mkd5rEj1y4nsjyxXRfP:-MklkXPNA7T8kt8akU9X:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2ff102b71c78573bbee96969a1a84fd4094a8ddb/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/AbstractQueryEvaluatorTest.kt#L92)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`encryptedQueryBundleOf`?
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 26 of 27 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptPrivateMembershipResultsTask.kt, line 69 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129#-MklpVqs6pFaDh_mOSGk:-MklpVqs6pFaDh_mOSGl:b-q1yk0i) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1f86b2990dd991405f596a5927b99857841f4327/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptPrivateMembershipResultsTask.kt#L69)):*
> ```Kotlin
>     val hkdfPepper = input.getValue("hkdf-pepper").toByteString()
> 
>     val DecryptedEventDataSet: PCollection<DecryptedEventDataSet> =
> ```

lowercase d? (Probably don't want a local variable name to use PascalCase)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/PrivateMembershipCryptor.kt, line 32 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129#-Mklq-yA1ws-5AEy-5qT:-Mklq-yA1ws-5AEy-5qU:b-stvbv1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1f86b2990dd991405f596a5927b99857841f4327/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/PrivateMembershipCryptor.kt#L32)):*
> ```Kotlin
> 
>   /** Generates a public and private key for query compression and expansion */
>   abstract fun generateKeys(): PrivateMembershipKeys
> ```

Remove keyword "abstract"?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt, line 38 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129#-MklqLaoEgfdtVs5zwHi:-MklqLaoEgfdtVs5zwHj:b-3i8iy4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1f86b2990dd991405f596a5927b99857841f4327/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt#L38)):*
> ```Kotlin
> 
>   /** Constructs an encrypted query bundle */
>   abstract fun makeEncryptedQueryBundle(
> ```

No need for "abstract" keyword in interfaces, I don't think

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129)* status: all files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptPrivateMembershipResultsTask.kt, line 69 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129#-MklpVqs6pFaDh_mOSGk:-MkmAp_q-TEMPG1d2jb4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1f86b2990dd991405f596a5927b99857841f4327/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/DecryptPrivateMembershipResultsTask.kt#L69)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

lowercase d? (Probably don't want a local variable name to use PascalCase)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/PrivateMembershipCryptor.kt, line 32 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129#-Mklq-yA1ws-5AEy-5qT:-MkmB4SZCnFc2nf2FoGK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1f86b2990dd991405f596a5927b99857841f4327/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/PrivateMembershipCryptor.kt#L32)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Remove keyword "abstract"?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt, line 38 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129#-MklqLaoEgfdtVs5zwHi:-MkmB5Hp4JUG2aE0MtQP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/1f86b2990dd991405f596a5927b99857841f4327/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/PrivateMembershipCryptorHelper.kt#L38)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

No need for "abstract" keyword in interfaces, I don't think
</blockquote></details>

Done.

**Review by stevenwarejones — COMMENTED** [review]
> Dismissed @efoxepstein from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/129)* status: 41 of 44 files reviewed, all discussions resolved (waiting on @duliomatos1 and @efoxepstein)

**Pull request merged**
