### PR TITLE
Add HKDF Wrapper class for user data encryption

### PR DESCRIPTION
**Pull request by enfreck**
Add implementation and test cases for HKDF for generating an AES key.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34)* status: all files reviewed, 4 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34#-MdT2HbDBQRLKvCq98DF:-MdT2HbDBQRLKvCq98DG:by5ahr3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3894decceb1ab2f2cbdea068203ac950bfb7a34e/src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h#L34)):*
> ```objc
> };
> 
> const Hkdf& GetHkdf();
> ```

Can you rename this to `GetSha256Hkdf()` and add a brief comment?
___
*[src/main/cc/wfanet/panelmatch/common/crypto/hkdf.cc, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34#-MdT2RdU2y4CnjaPE63h:-MdT2RdU2y4CnjaPE63i:bysggdv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3894decceb1ab2f2cbdea068203ac950bfb7a34e/src/main/cc/wfanet/panelmatch/common/crypto/hkdf.cc#L22)):*
> ```cpp
> 
> namespace wfanet::panelmatch::common::crypto {
> ```

Please add an anonymous namespace in here.

See e.g. https://github.com/world-federation-of-advertisers/any-sketch/blob/main/src/main/cc/any_sketch/fingerprinters.cc#L22 -- and https://abseil.io/tips/186. Basically, only the declarations in the header that you're defining in the CC file should be outside the anonymous namespace. The structure is usually:

```
#include stuff

namespace some::namespace {
namespace {
// Stuff in here not declared in the .h file
}  // namespace

// Stuff here was declared in the .h file

}  // namespace some::namespace

```
___
*[src/test/cc/wfanet/panelmatch/common/crypto/hkdf_test.cc, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34#-MdT2xDADD0-fmxj7M1r:-MdT2xDADD0-fmxj7M1s:b6utwwx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3894decceb1ab2f2cbdea068203ac950bfb7a34e/src/test/cc/wfanet/panelmatch/common/crypto/hkdf_test.cc#L39)):*
> ```cpp
>       SecretData result,
>       hkdf.ComputeHkdf(SecretDataFromStringView(HexDecodeOrDie(
>                            "0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b")),
> ```

Let's extract some of this stuff that's repeated:

```
SecretData GetInputKeyMaterial() {
  return SecretDataFromStringView(HexDecodeOrDie("0b0b0..."));
}
```
___
*[src/test/cc/wfanet/panelmatch/common/crypto/hkdf_test.cc, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34#-MdT3dSJ0Qx2v2UOCS2P:-MdT3dSJ0Qx2v2UOCS2Q:blvoicc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3894decceb1ab2f2cbdea068203ac950bfb7a34e/src/test/cc/wfanet/panelmatch/common/crypto/hkdf_test.cc#L42)):*
> ```cpp
>                        42));
>   EXPECT_EQ(HexEncode(SecretDataAsStringView(result)),
>             "8da4e775a563c18f715f802a063c5a31b8a11f5c5ee1879ec3454e5f3c738d2d9d"
> ```

Please add a comment saying where this magical string comes from.

**Review by efoxepstein — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34#-:-MdTBQUx6vLw_OhkRGM7:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @enfreck, @jmorrrr, @matthewclegg, and @oliver-amzn)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h, line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34#-MdTAcXn4mgJcUD6hvgr:-MdTAcXn4mgJcUD6hvgs:b-wk88y5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/420a7d05ead729a2d7caf2d63763c32b5beeb415/src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h#L34)):*
> ```objc
> };
> 
> // Returns an instance of the Sha256Hkdf class
> ```

Maybe `// Returns an Hkdf that uses SHA-256 as the hash function`. This is because `Sha256Hkdf` the class is hidden away in the .cc file so we don't want to discuss it here. Instead, we want to say what this function accomplishes, which is giving an Hkdf instance that always uses SHA256.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/hkdf.cc, line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34#-MdTBIzC0Un36iN1CaI-:-MdTBIzC0Un36iN1CaI0:bujkm2b) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/420a7d05ead729a2d7caf2d63763c32b5beeb415/src/main/cc/wfanet/panelmatch/common/crypto/hkdf.cc#L48)):*
> ```cpp
> }  // namespace
> 
> // Returns an instance of the Sha256Hkdf class
> ```

Since you have a comment in the `.h` file you don't need one here.

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34)* status: all files reviewed, 6 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34#-MdT2HbDBQRLKvCq98DF:-MdTC6NyAKLO_OupvaC_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3894decceb1ab2f2cbdea068203ac950bfb7a34e/src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h#L34)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you rename this to `GetSha256Hkdf()` and add a brief comment?
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/hkdf.cc, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34#-MdT2RdU2y4CnjaPE63h:-MdTC23pCN10F-hpTd7E:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3894decceb1ab2f2cbdea068203ac950bfb7a34e/src/main/cc/wfanet/panelmatch/common/crypto/hkdf.cc#L22)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please add an anonymous namespace in here.

See e.g. https://github.com/world-federation-of-advertisers/any-sketch/blob/main/src/main/cc/any_sketch/fingerprinters.cc#L22 -- and https://abseil.io/tips/186. Basically, only the declarations in the header that you're defining in the CC file should be outside the anonymous namespace. The structure is usually:

```
#include stuff

namespace some::namespace {
namespace {
// Stuff in here not declared in the .h file
}  // namespace

// Stuff here was declared in the .h file

}  // namespace some::namespace

```
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/hkdf_test.cc, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34#-MdT2xDADD0-fmxj7M1r:-MdTC3ZC6jIJZi3xZUD2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3894decceb1ab2f2cbdea068203ac950bfb7a34e/src/test/cc/wfanet/panelmatch/common/crypto/hkdf_test.cc#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Let's extract some of this stuff that's repeated:

```
SecretData GetInputKeyMaterial() {
  return SecretDataFromStringView(HexDecodeOrDie("0b0b0..."));
}
```
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/hkdf_test.cc, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34#-MdT3dSJ0Qx2v2UOCS2P:-MdTC434D0S7s29Ui3-7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/3894decceb1ab2f2cbdea068203ac950bfb7a34e/src/test/cc/wfanet/panelmatch/common/crypto/hkdf_test.cc#L42)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please add a comment saying where this magical string comes from.
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34)* status: all files reviewed, 2 unresolved discussions (waiting on @enfreck, @jmorrrr, and @matthewclegg)

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @jmorrrr, and @matthewclegg)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h, line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34#-MdTAcXn4mgJcUD6hvgr:-MdTD7CF9Xdx2O1-KeFk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/420a7d05ead729a2d7caf2d63763c32b5beeb415/src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h#L34)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe `// Returns an Hkdf that uses SHA-256 as the hash function`. This is because `Sha256Hkdf` the class is hidden away in the .cc file so we don't want to discuss it here. Instead, we want to say what this function accomplishes, which is giving an Hkdf instance that always uses SHA256.
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/hkdf.cc, line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34#-MdTBIzC0Un36iN1CaI-:-MdTD6Zi3vSyPkhoHhm7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/420a7d05ead729a2d7caf2d63763c32b5beeb415/src/main/cc/wfanet/panelmatch/common/crypto/hkdf.cc#L48)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Since you have a comment in the `.h` file you don't need one here.
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmorrrr and @matthewclegg)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jmorrrr and @matthewclegg)

**Review by jmorrrr — APPROVED** [review]
> Reviewed 3 of 6 files at r1, 1 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/34)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)

**Review by matthewclegg — APPROVED** [review]

**Pull request merged**
