### PR TITLE
Add SWIG wrapper for Brotli

### PR DESCRIPTION
**Pull request by efoxepstein**
https://rally1.rallydev.com/#/?detail=/userstory/607785049547&fdp=true

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/109)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/109)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @jonmolle, and @oliver-amzn)

___
*[src/main/cc/wfa/panelmatch/common/compression/brotli.cc, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/109#-MjC9EGa-yRsTxYRpM-p:-MjC9EGa-yRsTxYRpM-q:bnw5q0o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/059519dddb18e83344a76daed8ad46d97d6feadf/src/main/cc/wfa/panelmatch/common/compression/brotli.cc#L29)):*
> ```cpp
> #include "wfa/panelmatch/common/compression/compression.pb.h"
> 
> namespace wfa::panelmatch {
> ```

do you not want a more specific namespace?
___
*[src/main/cc/wfa/panelmatch/common/compression/brotli.cc, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/109#-MjCB_V62pK8euAkafL0:-MjCB_V62pK8euAkafL1:beu28ai) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/059519dddb18e83344a76daed8ad46d97d6feadf/src/main/cc/wfa/panelmatch/common/compression/brotli.cc#L47)):*
> ```cpp
>                          BrotliWriterBase::Options::kMaxCompressionLevel)
>                      .set_dictionaries(BrotliWriterBase::Dictionaries().add_raw(
>                          request.dictionary()));
> ```

A little curious why we aren't using something like this to generate the dictionary? 
https://github.com/google/brotli/blob/master/research/dictionary_generator.cc
___
*[src/main/cc/wfa/panelmatch/common/compression/brotli_wrapper.h, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/109#-MjC7rfK7PJij8nduRI2:-MjC7rfK7PJij8nduRI3:b-awkk2g) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/059519dddb18e83344a76daed8ad46d97d6feadf/src/main/cc/wfa/panelmatch/common/compression/brotli_wrapper.h#L27)):*
> ```objc
> namespace wfa::panelmatch {
> 
> absl::StatusOr<std::string> BrotliCompress(
> ```

do you want to call these `BrotliCompressWrapper` to match how the rest of the repo does these?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/109)* status: 8 of 11 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @jonmolle, @oliver-amzn, and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/common/compression/brotli.cc, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/109#-MjC9EGa-yRsTxYRpM-p:-MjCOltj4bUBKFA91EcJ:bmguuci) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/059519dddb18e83344a76daed8ad46d97d6feadf/src/main/cc/wfa/panelmatch/common/compression/brotli.cc#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do you not want a more specific namespace?
</blockquote></details>

I don't (and style guides prefer less deeply nested namespaces) but I'm happy to change this for now until we refactor everything.
___
*[src/main/cc/wfa/panelmatch/common/compression/brotli.cc, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/109#-MjCB_V62pK8euAkafL0:-MjCOXZ7AR7FAGAZy8r1:btgyzan) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/059519dddb18e83344a76daed8ad46d97d6feadf/src/main/cc/wfa/panelmatch/common/compression/brotli.cc#L47)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

A little curious why we aren't using something like this to generate the dictionary? 
https://github.com/google/brotli/blob/master/research/dictionary_generator.cc
</blockquote></details>

Given the directory name, I don't believe that's production quality code. The approach here was recommended by the Brotli team in an internal discussion.

**Review by jonmolle — APPROVED** [review]
lgtm pending steven's comment

> Reviewed 2 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/109#-:-MjFjHFd0Q37AqRRnq4h:b-keilwq)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @oliver-amzn, and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/common/compression/brotli_wrapper.h, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/109#-MjC7rfK7PJij8nduRI2:-MjFjCoE0AVYYg8SvOTI:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/059519dddb18e83344a76daed8ad46d97d6feadf/src/main/cc/wfa/panelmatch/common/compression/brotli_wrapper.h#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do you want to call these `BrotliCompressWrapper` to match how the rest of the repo does these?
</blockquote></details>

+1

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/109)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @oliver-amzn, and @stevenwarejones)

___
*[src/main/cc/wfa/panelmatch/common/compression/brotli_wrapper.h, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/109#-MjC7rfK7PJij8nduRI2:-MjGA_9s8tebnAyO1ENC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/059519dddb18e83344a76daed8ad46d97d6feadf/src/main/cc/wfa/panelmatch/common/compression/brotli_wrapper.h#L27)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by duliomatos1 — APPROVED** [review]
lgtm 

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/109#-:-MjGAb2tEQpV3rwSGLri:b-7nbn21)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @oliver-amzn, and @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/109)* status: 9 of 11 files reviewed, all discussions resolved (waiting on @duliomatos1, @oliver-amzn, and @stevenwarejones)

**Pull request merged**
