### PR TITLE
Clean up and simplify some test code

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/257)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 4 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/257)* status: 4 of 16 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt, line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/257#-Mt475uG-_9U8j7XDow8:-Mt475uG-_9U8j7XDow9:b-l535no) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/29e09e40a49b27af44e199003a5b1e950df478c3/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt#L84)):*
> ```Kotlin
>   override suspend fun ExchangeContext.generateCommutativeDeterministicEncryptionKey():
>     ExchangeTask {
>     return GenerateSymmetricKeyTask(JniDeterministicCommutativeCipher())
> ```

I thought the previous was a little more flexible in that it didn't require the class to contain a specific function
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateAsymmetricKeyPairTask.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/257#-Mt46sccE0aDOaC4shu7:-Mt46sccE0aDOaC4shu8:ba181kw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/00fc7eb3c3bd3afbd8adbb53b8cb056ebb966472/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateAsymmetricKeyPairTask.kt#L35)):*
> ```Kotlin
>     input: Map<String, StorageClient.Blob>
>   ): Map<String, Flow<ByteString>> {
>     logger.addToTaskLog("Executing generate asymmetric keys")
> ```

why are all these getting removed?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/257)* status: 4 of 16 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateAsymmetricKeyPairTask.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/257#-Mt46sccE0aDOaC4shu7:-Mt482Dk4hwMYyGq8OPz:b5fy0y5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/00fc7eb3c3bd3afbd8adbb53b8cb056ebb966472/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateAsymmetricKeyPairTask.kt#L35)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why are all these getting removed?
</blockquote></details>

https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/kotlin/org/wfanet/panelmatch/client/launcher/ExchangeTaskExecutor.kt#L104

**Review by stevenwarejones — COMMENTED** [review]
> Reviewed 10 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/257)* status: 14 of 16 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/257)* status: 14 of 16 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateSymmetricKeyTask.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/257#-Mt4hkKJ4qbgWKN-hK4n:-Mt4hkKJ4qbgWKN-hK4o:b-wui7m4) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/29e09e40a49b27af44e199003a5b1e950df478c3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateSymmetricKeyTask.kt#L26)):*
> ```Kotlin
> 
> /** A task for generating an symmetric key for a [DeterministicCommutativeCipher]. */
> class GenerateSymmetricKeyTask(private val cipher: DeterministicCommutativeCipher) : ExchangeTask {
> ```

my original thinking what this same task could be used by different ciphers in the future, not just deterministic commutative.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/257)* status: 12 of 19 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt, line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/257#-Mt475uG-_9U8j7XDow8:-Mt56cWm1vCi9UcWsKqJ:b-s21six) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/29e09e40a49b27af44e199003a5b1e950df478c3/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt#L84)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I thought the previous was a little more flexible in that it didn't require the class to contain a specific function
</blockquote></details>

Taking this to the extreme... what do you think of the second commit?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateSymmetricKeyTask.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/257#-Mt4hkKJ4qbgWKN-hK4n:-Mt56aSq1QiQtBWOSy9P:b3krz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/29e09e40a49b27af44e199003a5b1e950df478c3/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateSymmetricKeyTask.kt#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

my original thinking what this same task could be used by different ciphers in the future, not just deterministic commutative.
</blockquote></details>

T

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/257)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Pull request merged**
