### PR TITLE
Add Panel Match flags and /tools to deploy

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268)

### CODE REVIEW

**Review by wangyaopw — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268)* status: 0 of 7 files reviewed, 5 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/main/k8s/BUILD.bazel, line 7 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MuqnHGj0VsZ0o_Z_j8A:-MuqnHGj0VsZ0o_Z_j8B:b-xsusiw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/k8s/BUILD.bazel#L7)):*
> ```Starlark
> 
> cue_export(
>     name = "example_daemon_from_cue_gke",
> ```

If this is an example, possible put this somewhere under src/main/k8s/demo or dev or example



_Code quote:_
```Starlark
example_daemon_from_cue_gke
```
___
*[src/main/k8s/BUILD.bazel, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MuqnXLDBdWqIDmiVrM4:-MuqnXLDBdWqIDmiVrM5:b-sl6j54) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/k8s/BUILD.bazel#L15)):*
> ```Starlark
>         "secret_name": "TBD",
>         "party_type": "DATA_PROVIDER",
>         "tink_key_uri": "gcp-kms://projects/ads-open-measurement/locations/us/keyRings/test-key-ring/cryptoKeys/test-aes-key/cryptoKeyVersions/1",
> ```

does this work outside Google? if not, it shouldn't be checked in.

All this cue_tags can be set using mark variables I think.



_Code quote:_
```Starlark
ads-open-measurement/
```
___
*[src/main/k8s/README.md, line 8 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-Muqo64_DBRdHqZZHpsc:-Muqo64_DBRdHqZZHpsd:b-13baog) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/k8s/README.md#L8)):*
> ```Markdown
> the result.
> 
> ```shell
> ```

These don't apply to this repo. Update the readme?



_Code quote:_
```Markdown
This is a job that tests correctness by creating a Measurement and validating
the result.

```shell
bazel run //src/main/k8s/local:mc_frontend_simulator_kind \
  --define=k8s_secret_name=certs-and-configs-k8888kc6gg \
  --define=mc_name=measurementConsumers/FS1n8aTrck0
```
```
___
*[src/main/kotlin/org/wfanet/panelmatch/tools/BUILD.bazel, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MuqoSpNAWLhQ5EgJODx:-MuqoSpNAWLhQ5EgJODy:brvyqyb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/kotlin/org/wfanet/panelmatch/tools/BUILD.bazel#L21)):*
> ```Starlark
> )
> 
> kt_jvm_library(
> ```

If possible, please reuse the tools defined in the cross-media-measurement repo?



_Code quote:_
```Starlark
kt_jvm_library(
```
___
*[src/main/kotlin/org/wfanet/panelmatch/tools/DeployToGke.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MuqoONKDXyw71dBSi1q:-MuqoONKDXyw71dBSi1r:b2nhews) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/kotlin/org/wfanet/panelmatch/tools/DeployToGke.kt#L25)):*
> ```Kotlin
> import picocli.CommandLine.Command
> 
> @Command(name = "deploy_to_kind", description = ["Deploys containers on gcr.io to GKE"])
> ```

GKE



_Code quote:_
```Kotlin
kind
```

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268)* status: 6 of 7 files reviewed, 9 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/k8s/BUILD.bazel, line 2 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MuqlNWT55kYnsZkQ-5Y:-MuqlNWT55kYnsZkQ-5Z:b-psgi6c) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/k8s/BUILD.bazel#L2)):*
> ```Starlark
> load("//src/main/docker:images.bzl", "ALL_GKE_IMAGES")
> load("@wfa_measurement_system//build/cue:defs.bzl", "cue_export")
> ```

As an aside, we need to move the canonical CUE rules into common-jvm or something. Panel Match should not be depending on cross-media-measurement repo.

I just spotted that there's an old copy of the CUE rules in common-jvm :(
___
*[src/main/k8s/BUILD.bazel, line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MuqlZOWDXl_YaB16H-G:-MuqlZOWDXl_YaB16H-H:bkifyhb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/k8s/BUILD.bazel#L13)):*
> ```Starlark
>     ],
>     cue_tags = {
>         "secret_name": "TBD",
> ```

Use a Make variable here.



_Code quote:_
```Starlark
"TBD",
```
___
*[src/main/k8s/BUILD.bazel, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MuqlchOATZ1dXplQSy8:-MuqlchOATZ1dXplQSy9:b-q0kt7j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/k8s/BUILD.bazel#L22)):*
> ```Starlark
>     expression = "listObject",
>     filetype = "yaml",
>     outfile = "example_daemon_from_cue_gke.yaml",
> ```

FYI this attribute no longer exists as of https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/428
___
*[src/main/k8s/base.cue, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-Muqmfq30Z6khh_i8ftF:-Muqmfq30Z6khh_i8ftG:bi2froy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/k8s/base.cue#L54)):*
> ```CUE
> 	_restartPolicy:         string | *"Always"
> 	_imagePullPolicy:       string | *"Never"
> 	_jvm_flags:             string | *""
> ```

Since we're writing new files here, let's be consistent with naming patterns. Since CUE is meant to output to YAML/JSON, let's stick with lowerCamelCase for fields and UpperCamelCase for definitions.



_Code quote:_
```CUE
_jvm_flags
```
___
*[src/main/k8s/README.md, line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MuqoIFz8BB9QSSNxtkC:-MuqoIFz8BB9QSSNxtkD:b-58nt1) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/k8s/README.md#L5)):*
> ```Markdown
> ## Deploy Panel Match
> 
> This is a job that tests correctness by creating a Measurement and validating
> ```

I don't think this is the intended content for Panel Match.
___
*[src/main/kotlin/org/wfanet/panelmatch/tools/DeployToGke.kt, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MuqobCeC9WWjgb_sK-U:-MuqobCeC9WWjgb_sK-V:b-ge59b0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/kotlin/org/wfanet/panelmatch/tools/DeployToGke.kt#L1)):*
> ```Kotlin
> // Copyright 2022 The Cross-Media Measurement Authors
> ```

I would ask that this be moved to common-jvm since it's used by both this and cross-media-measurement, but the intent is to get rid of this. We might want to move to https://github.com/bazelbuild/rules_k8s.

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268)* status: 1 of 11 files reviewed, 9 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/k8s/BUILD.bazel, line 2 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MuqlNWT55kYnsZkQ-5Y:-MurobTh0UbiOuI2Xqsb:b-82iumq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/k8s/BUILD.bazel#L2)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

As an aside, we need to move the canonical CUE rules into common-jvm or something. Panel Match should not be depending on cross-media-measurement repo.

I just spotted that there's an old copy of the CUE rules in common-jvm :(
</blockquote></details>

Unfortunately, panel match depends few things from cross-media-measurement now. I believe theres an open issue to remove that dep in the long term. I just updated the version. Can we just submit this to unblock?
___
*[src/main/k8s/BUILD.bazel, line 7 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MuqnHGj0VsZ0o_Z_j8A:-Murorl17rutxojz4rdP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/k8s/BUILD.bazel#L7)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

If this is an example, possible put this somewhere under src/main/k8s/demo or dev or example
</blockquote></details>

Done.
___
*[src/main/k8s/BUILD.bazel, line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MuqlZOWDXl_YaB16H-G:-MurosNJ07vXAiv2r9CO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/k8s/BUILD.bazel#L13)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use a Make variable here.
</blockquote></details>

Done.
___
*[src/main/k8s/BUILD.bazel, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MuqnXLDBdWqIDmiVrM4:-MurouTi1gTEwX5Sl5_F:bvy39yn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/k8s/BUILD.bazel#L15)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

does this work outside Google? if not, it shouldn't be checked in.

All this cue_tags can be set using mark variables I think.
</blockquote></details>

Making it come from a tag now. It should be only necessary for GKE deployment.
___
*[src/main/k8s/base.cue, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-Muqmfq30Z6khh_i8ftF:-Murp1YT5o-21kjdy0Hz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/k8s/base.cue#L54)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Since we're writing new files here, let's be consistent with naming patterns. Since CUE is meant to output to YAML/JSON, let's stick with lowerCamelCase for fields and UpperCamelCase for definitions.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/tools/BUILD.bazel, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MuqoSpNAWLhQ5EgJODx:-Murp3VI5qfA0YuA0xGj:b-avpq55) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/kotlin/org/wfanet/panelmatch/tools/BUILD.bazel#L21)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

If possible, please reuse the tools defined in the cross-media-measurement repo?
</blockquote></details>

There's some hardcoded paths in the library. Can I create an issue for now and come back to it later?
___
*[src/main/kotlin/org/wfanet/panelmatch/tools/DeployToGke.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MuqoONKDXyw71dBSi1q:-MurpD805wWmmqt40exI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/kotlin/org/wfanet/panelmatch/tools/DeployToGke.kt#L25)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

GKE
</blockquote></details>

Done.
___
*[src/main/k8s/README.md, line 5 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MuqoIFz8BB9QSSNxtkC:-MurpEtF20efxsfvEx1-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/k8s/README.md#L5)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this is the intended content for Panel Match.
</blockquote></details>

Done.
___
*[src/main/k8s/README.md, line 8 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-Muqo64_DBRdHqZZHpsc:-MurpEYt15KnGOwO71Yu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/k8s/README.md#L8)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

These don't apply to this repo. Update the readme?
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268)* status: 9 of 11 files reviewed, 9 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/k8s/BUILD.bazel, line 2 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MuqlNWT55kYnsZkQ-5Y:-Murx9nEAy_NIo7cl0pT:b8d1o5d) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/k8s/BUILD.bazel#L2)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Unfortunately, panel match depends few things from cross-media-measurement now. I believe theres an open issue to remove that dep in the long term. I just updated the version. Can we just submit this to unblock?
</blockquote></details>

Yes. This was listed as an FYI comment, not intending to block.

I've started working on splitting out the CUE rules to a separate repo. See https://github.com/world-federation-of-advertisers/rules_cue/pull/1
___
*[src/main/k8s/dev/BUILD.bazel, line 9 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MurxycJ5_mlSswtraBi:-MurxycJ5_mlSswtraBj:be3mkna) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a844512210840eb8331859d78cf91cd89646ada8/src/main/k8s/dev/BUILD.bazel#L9)):*
> ```Starlark
>     srcs = ["example_daemon_gke.cue"],
>     cue_tags = {
>         "secret_name": "SomeSecretName",
> ```

Secret names tend to end in a hash, so this should be a Make var so it can be specified per-build.



_Code quote:_
```Starlark
"secret_name": "SomeSecretName",
```
___
*[src/main/k8s/dev/README.md, line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-Murzpmh0MVlema26gfc:-Murzpmh0MVlema26gfd:b-s12c78) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a844512210840eb8331859d78cf91cd89646ada8/src/main/k8s/dev/README.md#L17)):*
> ```Markdown
> bazel run src/main/kotlin/org/wfanet/panelmatch/tools:deploy_panelmatch_dev_to_gke \
>   --define=secret_name=certs-and-configs-k8888kc6gg \
>   --define=mc_name=measurementConsumers/FS1n8aTrck0
> ```

Shouldn't this also be using the same container_registry and image_repo_prefix vars so they match up (referenced as cue tags)?
___
*[src/main/k8s/dev/example_daemon_gke.cue, line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-Muryw1FCY_E4tw2SZia:-Muryw1FCY_E4tw2SZib:b-3qqkwj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a844512210840eb8331859d78cf91cd89646ada8/src/main/k8s/dev/example_daemon_gke.cue#L42)):*
> ```CUE
> 	replicas:              1
> 	resourceRequestCpu:    "100m"
>   resourceLimitCpu:      "400m"
> ```

Run `cue fmt` on this file. Make sure your local version of cue is current (v0.4.1)

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268)* status: 5 of 11 files reviewed, 8 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/k8s/dev/BUILD.bazel, line 9 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MurxycJ5_mlSswtraBi:-MuvAJBACawgOKpJE1GT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a844512210840eb8331859d78cf91cd89646ada8/src/main/k8s/dev/BUILD.bazel#L9)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Secret names tend to end in a hash, so this should be a Make var so it can be specified per-build.
</blockquote></details>

Done.
___
*[src/main/k8s/dev/README.md, line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-Murzpmh0MVlema26gfc:-MuvAKqVEDs64sj2pdyW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a844512210840eb8331859d78cf91cd89646ada8/src/main/k8s/dev/README.md#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't this also be using the same container_registry and image_repo_prefix vars so they match up (referenced as cue tags)?
</blockquote></details>

Done.
___
*[src/main/k8s/dev/example_daemon_gke.cue, line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-Muryw1FCY_E4tw2SZia:-MuvAK-i-8XTu6y8VZvF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a844512210840eb8331859d78cf91cd89646ada8/src/main/k8s/dev/example_daemon_gke.cue#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Run `cue fmt` on this file. Make sure your local version of cue is current (v0.4.1)
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268)* status: all files reviewed, 6 unresolved discussions (waiting on @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/k8s/dev/README.md, line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-Murzpmh0MVlema26gfc:-Muvhu1T0wc_zID2BjYa:bbuf3u5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a844512210840eb8331859d78cf91cd89646ada8/src/main/k8s/dev/README.md#L17)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Err, the push image target doesn't need the k8s secret name. What I was saying was that the deploy target should also have the container registry and image repo prefix as Make vars and use them in the CUE file.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 10 files at r2, 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268)* status: all files reviewed, 6 unresolved discussions (waiting on @wangyaopw and @yunyeng)

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268)* status: 9 of 11 files reviewed, 6 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/k8s/dev/README.md, line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-Murzpmh0MVlema26gfc:-Mux--Sl4PyM5b_bszzn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a844512210840eb8331859d78cf91cd89646ada8/src/main/k8s/dev/README.md#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Err, the push image target doesn't need the k8s secret name. What I was saying was that the deploy target should also have the container registry and image repo prefix as Make vars and use them in the CUE file.
</blockquote></details>

Done.

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268)* status: all files reviewed, 6 unresolved discussions (waiting on @wangyaopw and @yunyeng)

___
*[src/main/k8s/dev/README.md, line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-Murzpmh0MVlema26gfc:-Mux29vj7GZFfJ70bXT4:b-ui96nt) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a844512210840eb8331859d78cf91cd89646ada8/src/main/k8s/dev/README.md#L17)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I see this change in the readme, but not the corresponding change to pass the Make vars as CUE tags and updates to the CUE file. Additionally, don't flag such as k8s_secret_name need to still be specified for the deploy command?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268)* status: 8 of 11 files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/k8s/dev/README.md, line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-Murzpmh0MVlema26gfc:-Mux4_uX-3E1gDAiBRnE:brrowng) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/a844512210840eb8331859d78cf91cd89646ada8/src/main/k8s/dev/README.md#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I see this change in the readme, but not the corresponding change to pass the Make vars as CUE tags and updates to the CUE file. Additionally, don't flag such as k8s_secret_name need to still be specified for the deploy command?
</blockquote></details>

Done. PTAL. I need to send ResourceSetup binary in cmm, then I can always come back here to update missing items etc.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268)* status: all files reviewed, 5 unresolved discussions (waiting on @wangyaopw)

**Review by wangyaopw — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268)* status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/panelmatch/tools/BUILD.bazel, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/268#-MuqoSpNAWLhQ5EgJODx:-Mv-uZCV5UBiuoBfEqJc:bb7oryy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/fa5be3ba4e0965112fa454994cd7923896cb811f/src/main/kotlin/org/wfanet/panelmatch/tools/BUILD.bazel#L21)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

There's some hardcoded paths in the library. Can I create an issue for now and come back to it later?
</blockquote></details>

sure

**Pull request merged**
