### PR TITLE
Add storage tasks to task mapper

### PR DESCRIPTION
**Pull request by duliomatos1**
* Introduce `privateVerifiedStorageClient` as the counterpart to `sharedVerifiedStorageClient`
* Rename variables for `VerifiedStorageClient` and `StorageFactory` so
  they are more distinguishable

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171)

### CODE REVIEW

**Review by duliomatos1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @efoxepstein, @jonmolle, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171#-Mm4nA6I9rvD8cLVJW6g:-Mm4oGAF9pATP3nxrTAm:b52614) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you hold off on this PR until after @jonmolle's StorageSelector PR?
</blockquote></details>

Sure thing

---
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171#-Mm4n1Gb3aYLTFEIVehF:-Mm4oQx19BES3KotKDod:b-s9z5uw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ab787be2e67d52fcd0c054d2c2a1206b77778aeb/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt#L44)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Note that for private storage, we're just using normal StorageClient.
</blockquote></details>

probably will need to change either `SharedStorageTask` or `StorageClient` interface to make them compatible

**Review by efoxepstein — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @jonmolle)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171#-Mm4nA6I9rvD8cLVJW6g:-Mn1B6H_AlDVIr2A78lK:bltfct0) (no related file):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Is this ready to get rebased or is it waiting on other stuff still @efoxepstein ?
</blockquote></details>

@jonmolle ?

---

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @jonmolle)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171#-Mm4nA6I9rvD8cLVJW6g:-MnENIgC48wOrcRbgOQi:bkmdshe) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@jonmolle ?
</blockquote></details>

This should be unblocked now.

---

**Review by duliomatos1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @jonmolle)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171#-Mm4nA6I9rvD8cLVJW6g:-MnSF2ja2BKet6j2Jk4I:biv9ssm) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This should be unblocked now.
</blockquote></details>

Thanks, will update soon

---

**Review by duliomatos1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @jonmolle)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171#-Mm4nA6I9rvD8cLVJW6g:-MnSTEeQ3TBCfmVxph8d:b-mj2j3a) (no related file):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

Thanks, will update soon
</blockquote></details>

@jonmolle @stevenwarejones @efoxepstein , in these tasks are we copying from private storage to shared storage and vice-versa? I understand that shared storage is of type `VerifiedStorageClient` and private storage of type `StorageClient` which are not compatible

---

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @duliomatos1 and @jonmolle)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171#-Mm4nA6I9rvD8cLVJW6g:-MnSa6yd7YvV_imSiDOB:bh63mra) (no related file):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

@jonmolle @stevenwarejones @efoxepstein , in these tasks are we copying from private storage to shared storage and vice-versa? I understand that shared storage is of type `VerifiedStorageClient` and private storage of type `StorageClient` which are not compatible
</blockquote></details>

You might want to just split it into two separate classes: `CopyToSharedStorage` and `CopyFromSharedStorage`

---

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 3 of 14 files at r2, 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171)* status: 4 of 24 files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @efoxepstein, and @jonmolle)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonMain.kt, line 49 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171#-Mnho_OM754hdDrTKCcz:-Mnho_ON4jx7yO9PG_cK:b1clnkl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/07d319bc672250216aecbc68bb23d7fe00ad07c6/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonMain.kt#L49)):*
> ```Kotlin
>   //  based on flags. To start this should support our existing StorageFactory implementations
>   //  and call a helper function to choose based on storage details (similar to
>   //  privateStorageSelector, which we unfortunately can't use here as it depends on some of these.)
> ```

should we provide a different selector that works here then? maybe make your todo slightly more explicit that we should build that and provide it.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 54 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171#-Mnhq3uZ9P48Ca4Tms3k:-Mnhq3u_9CrzniVBBACK:b1vas0l) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/07d319bc672250216aecbc68bb23d7fe00ad07c6/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L54)):*
> ```Kotlin
>     names = ["--storage-signing-algorithm"],
>     defaultValue = "EC",
>     description = ["The algorithm used in signing data written to shaerd storage."],
> ```

nit: `shared`

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171)* status: 4 of 24 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @jonmolle, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonMain.kt, line 49 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171#-Mnho_OM754hdDrTKCcz:-MnkSsh98HDs509ep9bS:b-4ahmz5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/07d319bc672250216aecbc68bb23d7fe00ad07c6/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonMain.kt#L49)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should we provide a different selector that works here then? maybe make your todo slightly more explicit that we should build that and provide it.
</blockquote></details>

Updated in downstream PR
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 54 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171#-Mnhq3uZ9P48Ca4Tms3k:-MnlEjOoCSAniCb-ESb9:b-4ahmz5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/07d319bc672250216aecbc68bb23d7fe00ad07c6/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L54)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

nit: `shared`
</blockquote></details>

Updated in downstream PR

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/171)* status: 0 of 24 files reviewed, all discussions resolved (waiting on @efoxepstein, @jonmolle, and @stevenwarejones)

**Pull request merged**
