### PR TITLE
Implement GenerateLookupKeysTask.

### PR DESCRIPTION
**Pull request by efoxepstein**
This also fixes some issues in BuildPrivateMembershipQueriesTask.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/221)

### CODE REVIEW

**Review by yunyeng — APPROVED** [review]
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/221)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateLookupKeysTask.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/221#-MpCwowqCJt96JsiJIJC:-MpCwowqCJt96JsiJIJD:b-gdjafy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f8f57663cee1b463e20bf612dfc7b6a6aee0def0/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateLookupKeysTask.kt#L25)):*
> ```Kotlin
> import org.wfanet.panelmatch.common.storage.toByteString
> 
> class GenerateLookupKeysTask : ExchangeTask {
> ```

Single line kdoc explains this task?

**Review by duliomatos1 — APPROVED** [review]
lgtm

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/221#-:-MpCzhs87PBdss8NQ0Hi:bb7k0qh)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/221)* status: 6 of 9 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateLookupKeysTask.kt, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/221#-MpCwowqCJt96JsiJIJC:-MpD8pCR2Xusz7OWvesv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/f8f57663cee1b463e20bf612dfc7b6a6aee0def0/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/GenerateLookupKeysTask.kt#L25)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Single line kdoc explains this task?
</blockquote></details>

Done.

**Review by yunyeng — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/221)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)

**Pull request merged**
