### PR TITLE
Add example exchange workflow

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285#-Mx_5iDZ8r7VpIVXC80z:-Mx_5iD_53xQh5nwF1ia:bfibebf) (no related file):*
Why this would be in secretfiles, given that the textproto is never read in by the daemon. Did you maybe want to put this elsewhere under `testing`?

---

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285#-Mx_5iDZ8r7VpIVXC80z:-Mx_8w2_26V0IN3yi5ud:b-dbpl4i) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why this would be in secretfiles, given that the textproto is never read in by the daemon. Did you maybe want to put this elsewhere under `testing`?
</blockquote></details>

Done. This is just for documentation. This is not read by any daemon or other code.

---

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/k8s/testing/workflows/mini_exchange_workflow.textproto, line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285#-MxaQj_BB5qE1S3NYk8x:-MxaQj_C4X9sM_cjyzpb:bx6cwai) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9ed1c6849fc926262390ae9a680581630fdc93d5/src/main/k8s/testing/workflows/mini_exchange_workflow.textproto#L1)):*
> ```
> # EDP generates a certificate.
> ```

Do we need both this and this: https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/test/kotlin/org/wfanet/panelmatch/integration/config/mini_exchange_workflow.textproto

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/k8s/testing/workflows/mini_exchange_workflow.textproto, line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285#-MxaQj_BB5qE1S3NYk8x:-MxaSC6d0colQd4cBSP6:b-lj5o7o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9ed1c6849fc926262390ae9a680581630fdc93d5/src/main/k8s/testing/workflows/mini_exchange_workflow.textproto#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Do we need both this and this: https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/test/kotlin/org/wfanet/panelmatch/integration/config/mini_exchange_workflow.textproto
</blockquote></details>

Yes. One in testing does not have exchange identifiers and exchange date. This one should be almost production ready and are used in documentations.

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/k8s/testing/workflows/mini_exchange_workflow.textproto, line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285#-MxaQj_BB5qE1S3NYk8x:-MxaTPNq7R43bXvsHn7H:b1i77lh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9ed1c6849fc926262390ae9a680581630fdc93d5/src/main/k8s/testing/workflows/mini_exchange_workflow.textproto#L1)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Yes. One in testing does not have exchange identifiers and exchange date. This one should be almost production ready and are used in documentations.
</blockquote></details>

Also, later we should be pointing out to this folder from testing as well if we need to keep only one copy.

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[src/main/k8s/testing/workflows/mini_exchange_workflow.textproto, line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285#-MxaQj_BB5qE1S3NYk8x:-Mxb9U6PBDTNSn3Or3M4:bajqluk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9ed1c6849fc926262390ae9a680581630fdc93d5/src/main/k8s/testing/workflows/mini_exchange_workflow.textproto#L1)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Also, later we should be pointing out to this folder from testing as well if we need to keep only one copy.
</blockquote></details>

Additionally, integration/config/mini_exchange_workflow.textproto does not have generate certificate steps.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/k8s/testing/workflows/mini_exchange_workflow.textproto, line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285#-Mxkpv8M-fEDkrrjP080:-Mxkpv8NDg0m1ax-jCf5:b-yaq8u9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9ed1c6849fc926262390ae9a680581630fdc93d5/src/main/k8s/testing/workflows/mini_exchange_workflow.textproto#L20)):*
> ```
>     value: "mp-certificate-resource-name"
>   }
>   generate_certificate_step {}
> ```

@yunyeng @sanjayvas - is this same certificate also supposed to be used for mTLS?

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/k8s/testing/workflows/mini_exchange_workflow.textproto, line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285#-Mxkpv8M-fEDkrrjP080:-MxlQrwt0m5SnIW4IDmD:b-os397r) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9ed1c6849fc926262390ae9a680581630fdc93d5/src/main/k8s/testing/workflows/mini_exchange_workflow.textproto#L20)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@yunyeng @sanjayvas - is this same certificate also supposed to be used for mTLS?
</blockquote></details>

By the time this step is being executed, it looks like the daemon has already set up an mTLS channel with the Kingdom. In fact, executing this step appears to involve calling the Kingdom's Certificates service.

That said, if this is using the same CA that the provider has already given the Kingdom the root cert to, there's nothing preventing this cert from also being used for mTLS.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/k8s/testing/workflows/mini_exchange_workflow.textproto, line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285#-Mxkpv8M-fEDkrrjP080:-MxnuXKc16ndD0kycDg0:b-164ptp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9ed1c6849fc926262390ae9a680581630fdc93d5/src/main/k8s/testing/workflows/mini_exchange_workflow.textproto#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

By the time this step is being executed, it looks like the daemon has already set up an mTLS channel with the Kingdom. In fact, executing this step appears to involve calling the Kingdom's Certificates service.

That said, if this is using the same CA that the provider has already given the Kingdom the root cert to, there's nothing preventing this cert from also being used for mTLS.
</blockquote></details>

Right - if the daemon, itself, generates this cert, then we don't need these generate steps here.

**Review by SanjayVas — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/k8s/testing/workflows/mini_exchange_workflow.textproto, line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285#-Mxkpv8M-fEDkrrjP080:-MxpCGYy7m43IubcPbTq:b7kci2i) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/9ed1c6849fc926262390ae9a680581630fdc93d5/src/main/k8s/testing/workflows/mini_exchange_workflow.textproto#L20)):*
> if the daemon, itself, generates this cert,

Not sure quite what you mean. This step is what causes the daemon to generate a cert. Or are you referring to a separate cert that the provider may have generated ahead of time for TLS?

Reading through the code for the generate step, it's two parts:
1. Actually generating a new cert from the CA.
2. Registering the generated cert in the Kingdom API.

I don't know enough about how panel exchange uses these certs, but at the very least I assume that even if you've generated certs separately then you'd still need to register them with the Kingdom API.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/285)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yunyeng)

**Pull request merged**
