### PR TITLE
Implement S3StorageFactory

### PR DESCRIPTION
**Pull request by efoxepstein**
This PR also does misc code health and grammatical cleanups.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/245)

### CODE REVIEW

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/245)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[build/repositories.bzl, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/245#-MqutgO72FPEdeUzXu1e:-MqutgO72FPEdeUzXu1f:b-fpvn2h) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b920e771f4ddbc395bc3003efeca0ec19d28cc15/build/repositories.bzl#L51)):*
> ```Starlark
>         name = "wfa_common_jvm",
>         sha256 = "406381ca072804d21d360a60d4f711b5d6adced15f171c7c77db5f13bb6f25c4",
>         strip_prefix = "common-jvm-6450863fb9d2a2e689023d6bfd460cd352af9123",
> ```

version please
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CryptorExchangeTask.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/245#-MqutoRg2GvqPL087cxa:-MqutoRg2GvqPL087cxb:b5m5099) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b920e771f4ddbc395bc3003efeca0ec19d28cc15/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CryptorExchangeTask.kt#L52)):*
> ```Kotlin
>     val results = operation(cryptoKey, joinKeys)
> 
>     // For now, we assume the join keys are output in the same order that they were input.
> ```

nit: maybe this should go in the kdoc at the top of the function
___
*[src/main/kotlin/org/wfanet/panelmatch/client/storage/aws/s3/S3StorageFactory.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/245#-MqutzFa-SnWrkT-v7LQ:-MqutzFa-SnWrkT-v7LR:bb7s76d) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b920e771f4ddbc395bc3003efeca0ec19d28cc15/src/main/kotlin/org/wfanet/panelmatch/client/storage/aws/s3/S3StorageFactory.kt#L31)):*
> ```Kotlin
> 
>   override fun build(): StorageClient {
>     return S3StorageClient(S3Client.create(), storageDetails.aws.bucket)
> ```

yay!

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/245)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[build/repositories.bzl, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/245#-MqutgO72FPEdeUzXu1e:-Mquy-oG0lu088U2kOge:b-5t4gi2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b920e771f4ddbc395bc3003efeca0ec19d28cc15/build/repositories.bzl#L51)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

version please
</blockquote></details>

So -- common-jvm is about to have a couple of PRs merged. I'll keep this comment open until that's done so we don't need to make too many releases.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CryptorExchangeTask.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/245#-MqutoRg2GvqPL087cxa:-Mquxzad1O554kIPTR-n:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b920e771f4ddbc395bc3003efeca0ec19d28cc15/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/CryptorExchangeTask.kt#L52)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

nit: maybe this should go in the kdoc at the top of the function
</blockquote></details>

Done

**Review by stevenwarejones — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/245)* status: 14 of 18 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[build/repositories.bzl, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/245#-MqutgO72FPEdeUzXu1e:-Mqy_Z-p033VXLALGgX_:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b920e771f4ddbc395bc3003efeca0ec19d28cc15/build/repositories.bzl#L51)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

So -- common-jvm is about to have a couple of PRs merged. I'll keep this comment open until that's done so we don't need to make too many releases.
</blockquote></details>

+1

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/245)* status: 13 of 30 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[build/repositories.bzl, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/245#-MqutgO72FPEdeUzXu1e:-Mqzt4fu2n11YvBpaBS6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/b920e771f4ddbc395bc3003efeca0ec19d28cc15/build/repositories.bzl#L51)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 13 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/245)* status: 28 of 30 files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Pull request merged**
