### PR TITLE
add query padding

### PR DESCRIPTION
**Pull request by stevenwarejones**
cleanup

lint

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110)* status: all files reviewed, 6 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjFnNaoDIKLI4Jranll:-MjFnNapCvi3bhymA0GV:bvc5x7k) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/576e7db6c74191a77aa1c536dc65a84250dfc43e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L75)):*
> ```Kotlin
>       totalQueriesPerShard = totalQueriesPerShard,
>       numQueries =
>         if (totalQueriesPerShard == null) {
> ```

Can we just require that this is specified? This feels weird.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 102 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjFnWl7E2ajF1FK3A4l:-MjFnWl8-J65n2dZqsib:bb752ax) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/576e7db6c74191a77aa1c536dc65a84250dfc43e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L102)):*
> ```Kotlin
>   }
> 
>   /** Deteremines shard and bucket for a [JoinKey]. */
> ```

Typo
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 120 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjFneDsBMy1siJFt5y9:-MjFneDsBMy1siJFt5yA:b-asavt0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/576e7db6c74191a77aa1c536dc65a84250dfc43e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L120)):*
> ```Kotlin
>     if (parameters.totalQueriesPerShard == null) return data.map { kvOf(true, it) }
>     val totalQueriesPerShard = requireNotNull(parameters.totalQueriesPerShard)
>     return data.keyBy { it.shardId }.groupByKey("Group into shards").parDo<
> ```

This is pretty bizarre formatting here. Maybe just pull out the body into a DoFn proper.

```
class EqualizeQueriesPerShardFn : DoFn<KV<ShardId, Iterable<ShardedData>>, KV<Boolean, ShardedData>> {
  @ProcessElement
  fun processElement(...) { ... }
}
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 127 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjFo44t10iHM-jku4Ac:-MjFo44t10iHM-jku4Ad:brwagw3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/576e7db6c74191a77aa1c536dc65a84250dfc43e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L127)):*
> ```Kotlin
>       /** Filter out any real queries above the limit */
>       it.value.asSequence().forEach {
>         if (total < totalQueriesPerShard) {
> ```

Do we want to have a `Metric` to count when we overflow here?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjFonNR-8F5zCIRHWks:-MjFonNR-8F5zCIRHWkt:bkq4rfg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/576e7db6c74191a77aa1c536dc65a84250dfc43e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L136)):*
> ```Kotlin
>         yield(
>           kvOf(
>             false,
> ```

Do we really need the boolean? Can't we just infer this from the panelist key or empty joinkey?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 180 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjFpAdk2iV3lxTOVhxE:-MjFpAdk2iV3lxTOVhxF:b-kpf1dt) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/576e7db6c74191a77aa1c536dc65a84250dfc43e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L180)):*
> ```Kotlin
>   ): PCollection<KV<QueryId, PanelistKey>> {
>     return data.parDo<KV<QueryId, KV<Boolean, ShardedData>>, KV<QueryId, PanelistKey>> {
>       if (it.value.key) {
> ```

Add a `filter` helper function to `Beam.kt` please:

```
fun <T> PCollection<T>.filter(predicate: (T) -> Boolean): PCollection<T> {
  return parDo { if (predicate(it)) yield(it) }
}
```

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110)* status: 3 of 7 files reviewed, 6 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjFnNaoDIKLI4Jranll:-MjFqsN4-Zt8aFUIOSmv:bl650oe) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/576e7db6c74191a77aa1c536dc65a84250dfc43e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L75)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can we just require that this is specified? This feels weird.
</blockquote></details>

it not being set is like not having padding. Do we want to disallow that option? Even for debugging?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 102 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjFnWl7E2ajF1FK3A4l:-MjFr17OAxJd0lBeR7vn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/576e7db6c74191a77aa1c536dc65a84250dfc43e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L102)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Typo
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 120 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjFneDsBMy1siJFt5y9:-MjGKv1R7-GZUGrZFY16:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/576e7db6c74191a77aa1c536dc65a84250dfc43e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L120)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is pretty bizarre formatting here. Maybe just pull out the body into a DoFn proper.

```
class EqualizeQueriesPerShardFn : DoFn<KV<ShardId, Iterable<ShardedData>>, KV<Boolean, ShardedData>> {
  @ProcessElement
  fun processElement(...) { ... }
}
```
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 127 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjFo44t10iHM-jku4Ac:-MjG-i5jBNc7my1UaC8e:b-ue90gz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/576e7db6c74191a77aa1c536dc65a84250dfc43e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L127)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Do we want to have a `Metric` to count when we overflow here?
</blockquote></details>

agreed. done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 136 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjFonNR-8F5zCIRHWks:-MjFtuaN14ocEsiYz0UE:b-vod8el) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/576e7db6c74191a77aa1c536dc65a84250dfc43e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L136)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Do we really need the boolean? Can't we just infer this from the panelist key or empty joinkey?
</blockquote></details>

Done. I thought I would keep it flexible but I'm happy with using a zeroed panelist key.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 180 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjFpAdk2iV3lxTOVhxE:-MjFzDZM6VNOuiZXHzoQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/576e7db6c74191a77aa1c536dc65a84250dfc43e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L180)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Add a `filter` helper function to `Beam.kt` please:

```
fun <T> PCollection<T>.filter(predicate: (T) -> Boolean): PCollection<T> {
  return parDo { if (predicate(it)) yield(it) }
}
```
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110)* status: all files reviewed, 7 unresolved discussions (waiting on @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjGSE26AWpycESGkmzm:-MjGSE26AWpycESGkmzn:b-dkgyc9) (no related file):*
Approving -- feel free to merge after resolving remaining comments.

---
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjFnNaoDIKLI4Jranll:-MjGQJhx1Edowc_vjUFC:b9e81r0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/576e7db6c74191a77aa1c536dc65a84250dfc43e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L75)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

it not being set is like not having padding. Do we want to disallow that option? Even for debugging?
</blockquote></details>

That's a fair point. The number here seems pretty arbitrary, though. Should it be null in this case maybe? Or Int.MAX_VALUE?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjGNVoN4ZySeO3R1GQe:-MjGNVoN4ZySeO3R1GQf:b-tpqci2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ca6e9916f59fde977f766f8806d3bb243564508b/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L70)):*
> ```Kotlin
>       require(numShards > 0)
>       require(numBucketsPerShard > 0)
>       totalQueriesPerShard?.let { require(totalQueriesPerShard >= numBucketsPerShard) }
> ```

In general this condition will not be true and is not needed.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 117 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjGQlqK91sZFAokgew_:-MjGQlqK91sZFAokgewa:b-dlw70m) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ca6e9916f59fde977f766f8806d3bb243564508b/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L117)):*
> ```Kotlin
>   }
> 
>   /** Wrapper function to add in the necessary number of padded queries */
> ```

I think there's a little terminology misalignment here. I say *padding* queries because it pads the number of queries within a particular shard to be a particular number. So I'd name this `addPaddingQueries` and maybe even rename `EqualizeQueriesPerShardFn` to `PadShardFn` (optional, your call)
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 135 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjGRGUzEdIKXQxE0-Rg:-MjGRGUzEdIKXQxE0-Rh:b-hm7epj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ca6e9916f59fde977f766f8806d3bb243564508b/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L135)):*
> ```Kotlin
>   private class EqualizeQueriesPerShardFn(
>     private val totalQueriesPerShard: Int,
>   ) : DoFn<KV<ShardId, Iterable<@JvmWildcard ShardedData>>, ShardedData>() {
> ```

Sometimes we've needed to use `MutableIterable<Foo>` instead of `Iterable<@JvmWildcard Foo>` -- but if this works, that's fine
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 149 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjGRTe0B7fL_gDvYUOq:-MjGRTe0B7fL_gDvYUOr:bkpi2b8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ca6e9916f59fde977f766f8806d3bb243564508b/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L149)):*
> ```Kotlin
>       var discardedQueries: Long = 0
>       /** Filter out any real queries above the limit */
>       data.value.asSequence().forEach { shardedData ->
> ```

`Iterable` should have a for-each method on it, so you shouldn't need `.asSequence()`, I wouldn't think. But also, maybe the cleanest way is:

```
for (shardedData in data.value) {
```
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 184 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjGNuCm-UCDCVmJv5b0:-MjGNuCm-UCDCVmJv5b1:bz4fpem) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/ca6e9916f59fde977f766f8806d3bb243564508b/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L184)):*
> ```Kotlin
>         val seen = BitSet()
>         while (seen.cardinality() < parameters.numQueries) {
>           val id = abs(Random.nextInt())
> ```

I know this is old code but it looks like it'll take up around 150MiB to store `seen` because it's not sparse.

While you're editing code around here, can you add a TODO to use a smarter data structure or just swap it out for a normal MutableSet? (Observe that you would need around 100M queries before the BitSet would be worth it.)

Alternatively and maybe easier, pick ids in [0, 2^28), which would use up a much more reasonable 4MiB: `val id = Integer.remainderUnsigned(Random.nextInt(), 1 shl 28)`

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110)* status: all files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 75 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjFnNaoDIKLI4Jranll:-MjGTIB2Brx9Ev-r2O24:b-yf3mjx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/576e7db6c74191a77aa1c536dc65a84250dfc43e/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L75)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

That's a fair point. The number here seems pretty arbitrary, though. Should it be null in this case maybe? Or Int.MAX_VALUE?
</blockquote></details>

The iterator calculates this many query Ids. I had previously set it to Int.MAX_VALUE but you thought I should set it to like 100k. I now agree with your 100k suggestion. 
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjGNVoN4ZySeO3R1GQe:-MjGTBVp49qIdVMKAqgM:biryswn) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/65156fbf837c76c70bc869153b0f01d5d79a1c77/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L70)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

In general this condition will not be true and is not needed.
</blockquote></details>

i just thought it was an easy way to misconfigure things and get a result that is hard to debug. I'd like to leave it.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 117 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjGQlqK91sZFAokgew_:-MjGV2v657i27paqgNu7:b-yxlxo2) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/65156fbf837c76c70bc869153b0f01d5d79a1c77/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L117)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think there's a little terminology misalignment here. I say *padding* queries because it pads the number of queries within a particular shard to be a particular number. So I'd name this `addPaddingQueries` and maybe even rename `EqualizeQueriesPerShardFn` to `PadShardFn` (optional, your call)
</blockquote></details>

sometimes it actually removes queries which is why I also like the name equalize. We can revisit this later.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 135 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjGRGUzEdIKXQxE0-Rg:-MjGTrz0EyFTMGHF8yd6:b-vhqy9s) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/65156fbf837c76c70bc869153b0f01d5d79a1c77/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L135)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Sometimes we've needed to use `MutableIterable<Foo>` instead of `Iterable<@JvmWildcard Foo>` -- but if this works, that's fine
</blockquote></details>

Changing it to MutableIterable doesn't fix it. Leaving this as is.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 149 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjGRTe0B7fL_gDvYUOq:-MjGUELj7MaM4YYSCTe0:b-ia6b41) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/65156fbf837c76c70bc869153b0f01d5d79a1c77/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L149)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`Iterable` should have a for-each method on it, so you shouldn't need `.asSequence()`, I wouldn't think. But also, maybe the cleanest way is:

```
for (shardedData in data.value) {
```
</blockquote></details>

got rid of the asSequence
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 184 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjGNuCm-UCDCVmJv5b0:-MjGUOfJ3DU9REkWkmfK:b-46sskz) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/65156fbf837c76c70bc869153b0f01d5d79a1c77/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L184)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I know this is old code but it looks like it'll take up around 150MiB to store `seen` because it's not sparse.

While you're editing code around here, can you add a TODO to use a smarter data structure or just swap it out for a normal MutableSet? (Observe that you would need around 100M queries before the BitSet would be worth it.)

Alternatively and maybe easier, pick ids in [0, 2^28), which would use up a much more reasonable 4MiB: `val id = Integer.remainderUnsigned(Random.nextInt(), 1 shl 28)`
</blockquote></details>

yeah - I think I talked about the latter at some point. Collisions do happen in 32 bit space. Added a TODO.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjGNVoN4ZySeO3R1GQe:-MjGWDol8UXUM7ZowDrI:bk1f1qv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/65156fbf837c76c70bc869153b0f01d5d79a1c77/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L70)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i just thought it was an easy way to misconfigure things and get a result that is hard to debug. I'd like to leave it.
</blockquote></details>

It's wrong, though. In general there will be many more buckets than queries per shard.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 149 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjGRTe0B7fL_gDvYUOq:-MjGWZPn4l6SuuhBFHEK:b-oraspb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/65156fbf837c76c70bc869153b0f01d5d79a1c77/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L149)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

got rid of the asSequence
</blockquote></details>

Stylistically a for-loop is better than `.forEach`, except in very certain circumstances. The for-loop is also  more consistent with the rest of our code.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 184 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjGNuCm-UCDCVmJv5b0:-MjGWo7Z8HsptdMKTLgO:b-ihfuvv) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/65156fbf837c76c70bc869153b0f01d5d79a1c77/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L184)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah - I think I talked about the latter at some point. Collisions do happen in 32 bit space. Added a TODO.
</blockquote></details>

It's fine if there are collisions, it'll just try again.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjGNVoN4ZySeO3R1GQe:-MjGX5C70bVamcNOBqOt:bjyeh9w) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/65156fbf837c76c70bc869153b0f01d5d79a1c77/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L70)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's wrong, though. In general there will be many more buckets than queries per shard.
</blockquote></details>

For example, you could have a database with 100B buckets and 1 shard and 1 query.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjGNVoN4ZySeO3R1GQe:-MjGYZxGAgrbUPe3NUlN:bm5y6c7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/65156fbf837c76c70bc869153b0f01d5d79a1c77/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L70)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

For example, you could have a database with 100B buckets and 1 shard and 1 query.
</blockquote></details>

+1 Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 149 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjGRTe0B7fL_gDvYUOq:-MjGYjr36SP52LG915h6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/65156fbf837c76c70bc869153b0f01d5d79a1c77/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L149)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Stylistically a for-loop is better than `.forEach`, except in very certain circumstances. The for-loop is also  more consistent with the rest of our code.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 184 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjGNuCm-UCDCVmJv5b0:-MjGZ1cU0YBpcCP76MSS:b-bi7u6l) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/65156fbf837c76c70bc869153b0f01d5d79a1c77/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L184)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's fine if there are collisions, it'll just try again.
</blockquote></details>

i'd like to think about this more. leaving as todo.

**Review by stevenwarejones — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt, line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110#-MjGNVoN4ZySeO3R1GQe:-MjGaXa_1sKzLXux-tPm:b5hjpu3) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/65156fbf837c76c70bc869153b0f01d5d79a1c77/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/CreateQueriesWorkflow.kt#L70)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

+1 Done.
</blockquote></details>

i think there are other things we could check here like numQueries < totalQueriesPerShard * numShards but I'm tending toward your position these extra checks don't really help anything.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/110)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

**Pull request merged**
