### PR TITLE
Adds Metrics to EDEP

### PR DESCRIPTION
**Pull request by jmorrrr**
Adds Apache Beam Metric to create a distribution of batch sizes and a distribution of time taken to complete JNI call and return

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/88)

### CODE REVIEW

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/88)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck and @matthewclegg)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/88)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck, @jmorrrr, and @matthewclegg)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EncryptionEventsDoFn.kt, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/88#-Mh0HTxH87vyILxutbGp:-Mh0HTxI5pJGHPYzLemQ:b-gtuhil) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8e0077a7a7f426618be15268c36023f56f6b56cc/src/main/kotlin/org/wfanet/panelmatch/client/eventpreprocessing/EncryptionEventsDoFn.kt#L38)):*
> ```Kotlin
>   private val getCryptoKey: SerializableFunction<Void?, ByteString>,
> ) : DoFn<MutableList<KV<ByteString, ByteString>>, KV<Long, ByteString>>() {
>   val jniCallTimeDistribution = Metrics.distribution(BatchingDoFn::class.java, "jni-call-time")
> ```

`private val` please

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/88)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck, @jmorrrr, @matthewclegg, and @oliver-amzn)

**Review by oliver-amzn — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/88)* status: all files reviewed, 1 unresolved discussion (waiting on @enfreck, @jmorrrr, and @matthewclegg)

**Review by efoxepstein — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/88)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Pull request merged**
