### PR TITLE
Add daemon for ExchangeStepLauncher

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18)* status: 0 of 7 files reviewed, 3 unresolved discussions (waiting on @yunyeng)

___
*[WORKSPACE, line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbCVYK5B1tGE0o8otFJ:-MbCVYK5B1tGE0o8otFK:bcj2knx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/WORKSPACE#L50)):*
> ```Starlark
>     sha256 = "6d73a34a1db5af9a89484134b2f20d78552efce21ba4a21e5a27567e6c262fc5",
>     strip_prefix = "cross-media-measurement-6c0992bc9859e0e1e2b10e4f5ee9f9f3c89d7251",
>     url = "https://github.com/world-federation-of-advertisers/cross-media-measurement/archive/6c0992bc9859e0e1e2b10e4f5ee9f9f3c89d7251.tar.gz",
> ```

Is this an older commit? I don't see a more recent commit matching that.
https://github.com/world-federation-of-advertisers/cross-media-measurement/commits/main
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbCX1M0102n9zlHP09L:-MbCX1M0102n9zlHP09M:bkpjmds) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L45)):*
> ```Kotlin
>   @CommandLine.Option(
>     names = ["--polling-interval"],
>     defaultValue = "1m",
> ```

What is a best practice here? I'm not sure we want everyone polling every minute do we? There will only be work to do like 1% of the time. Probably once per hour would be sufficient.

There actually two separate polling intervals:
1. Look for a new exchange that you haven't started working on (needs a very low poll interval ~ 1/day)
2. Look for next steps in an ongoing exchange (in this case checking every 1-5 minutes makes more sense)

What do you think?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbCXqRd38bK7YlLJCUw:-MbCXqRd38bK7YlLJCUx:bz2zes7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L62)):*
> ```Kotlin
>   @CommandLine.Option(
>     names = ["--exchange-step-attempts-service-target"],
>     description = ["Address and port of the Exchange Step Attempts service"],
> ```

what is the difference between this service and exchange steps service?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbCYSaa0mPFI_ouEibM:-MbCYSaa0mPFI_ouEibN:bwpa7a) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L58)):*
> ```Kotlin
>     ExchangeStepLauncher(grpcApiClient, ExchangeStepValidatorImpl(), BlockingJobLauncher())
> 
>   runBlocking { pollingThrottler.loopOnReady { exchangeStepLauncher.findAndRunExchangeStep() } }
> ```

please add a test that checks how many times it checked for work
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbCYOP78VQ4euGL9Uiq:-MbCYOP78VQ4euGL9Uir:b-p2j9cr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L20)):*
> ```Kotlin
> import picocli.CommandLine
> 
> class ExchangeWorkflowFlags {
> ```

please add some tests
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbC_5T72AlB0jePBx_w:-MbC_5T72AlB0jePBx_x:b-8heijm) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L26)):*
> ```Kotlin
> 
>   @CommandLine.Option(
>     names = ["--party-type"],
> ```

Since this is an enum, we should follow this convention:
https://picocli.info/#_enum_types
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbC_uobA4tUDvjIoNJi:-MbC_uobA4tUDvjIoNJj:b-7cmhkx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L53)):*
> ```Kotlin
> 
>   @CommandLine.Option(
>     names = ["--exchange-steps-service-target"],
> ```

what do you think of validating this input?
https://picocli.info/#_handling_invalid_input

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18)* status: all files reviewed, 9 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbCZP332YFVLeRnEwrW:-MbCZP340fK2-brRTT12:bt86mjt) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L58)):*
> ```Kotlin
>     ExchangeStepLauncher(grpcApiClient, ExchangeStepValidatorImpl(), BlockingJobLauncher())
> 
>   runBlocking { pollingThrottler.loopOnReady { exchangeStepLauncher.findAndRunExchangeStep() } }
> ```

We probably want to catch/log/suppress exceptions from `findAndRunExchangeStep`.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbCZnYc4EvIMg-cUBl-:-MbCZnYc4EvIMg-cUBl0:bjo388w) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L31)):*
> ```Kotlin
>     required = true
>   )
>   lateinit var partyType: String
> ```

I think enums work just fine as flags -- that's probably simpler.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbCX1M0102n9zlHP09L:-MbC_42t4Z_bhTO9L_TX:bqt4hw9) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L45)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

What is a best practice here? I'm not sure we want everyone polling every minute do we? There will only be work to do like 1% of the time. Probably once per hour would be sufficient.

There actually two separate polling intervals:
1. Look for a new exchange that you haven't started working on (needs a very low poll interval ~ 1/day)
2. Look for next steps in an ongoing exchange (in this case checking every 1-5 minutes makes more sense)

What do you think?
</blockquote></details>

I'm not really worried about a fraction of a QPS per client. Polling once a minute seems totally fine to me for now. Even polling every second would be sufficiently cheap.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbCXqRd38bK7YlLJCUw:-MbC_LrQ1gLsd4M8ckY8:bpdhfq) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L62)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what is the difference between this service and exchange steps service?
</blockquote></details>

`ExchangeSteps` is the service for the `ExchangeStep` resource and `ExchangeStepAttempts` is the service for the `ExchangeStepAttempt` resource

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18)* status: all files reviewed, 9 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbCYSaa0mPFI_ouEibM:-MbCaAGY9IHAyq4KOhNe:b-erzbwk) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L58)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

please add a test that checks how many times it checked for work
</blockquote></details>

This would just be re-testing `MinimumIntervalThrottler`, no? We have thorough coverage here: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/test/kotlin/org/wfanet/measurement/common/throttler/MinimumIntervalThrottlerTest.kt
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbCYOP78VQ4euGL9Uiq:-MbCaQLP1LbQgknY6UNj:b-yfqa30) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L20)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

please add some tests
</blockquote></details>

FWIW we've never added unit tests for flags because it's essentially re-testing picocli, a mature, well-tested library.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18)* status: all files reviewed, 9 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbCXqRd38bK7YlLJCUw:-MbCb1u29umfejIG7GNR:b-2u2cvb) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L62)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`ExchangeSteps` is the service for the `ExchangeStep` resource and `ExchangeStepAttempts` is the service for the `ExchangeStepAttempt` resource
</blockquote></details>

architecturally speaking, why would it be two different hosts?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18)* status: all files reviewed, 9 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbCXqRd38bK7YlLJCUw:-MbCbAgA7US1yIAdJJSb:bfv4f8a) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L62)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

architecturally speaking, why would it be two different hosts?
</blockquote></details>

The deployment pattern isn't really a concern of this code. For all it knows, the two services could run in different clouds in different regions by different vendors. It's completely irrelevant to this code so we shouldn't bake in any unnecessary assumptions, I don't think.

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18)* status: 4 of 7 files reviewed, 9 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[WORKSPACE, line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbCVYK5B1tGE0o8otFJ:-MbCobjD-42OoToC7cHf:bsuaqz7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/WORKSPACE#L50)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Is this an older commit? I don't see a more recent commit matching that.
https://github.com/world-federation-of-advertisers/cross-media-measurement/commits/main
</blockquote></details>

https://github.com/world-federation-of-advertisers/cross-media-measurement/commit/04da26b2fb351b857114ba44df2b992c80ad9ec3
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbCZP332YFVLeRnEwrW:-MbCjXHU5m27jro0W4Wr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L58)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

We probably want to catch/log/suppress exceptions from `findAndRunExchangeStep`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbC_5T72AlB0jePBx_w:-MbCdTV8246V98VyqRXj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L26)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Since this is an enum, we should follow this convention:
https://picocli.info/#_enum_types
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbCZnYc4EvIMg-cUBl-:-MbCdTmV1PZUmnmwO8hy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L31)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think enums work just fine as flags -- that's probably simpler.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbC_uobA4tUDvjIoNJi:-MbCogO0CefZ7q7bwIl0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L53)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what do you think of validating this input?
https://picocli.info/#_handling_invalid_input
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18)* status: all files reviewed, 8 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt, line 72 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbD0RM-4d3kzWyTBRTp:-MbD0RM-4d3kzWyTBRTq:b-sk3y3r) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/84e0ec883eacee2ac1368fdd417e58f428a04e48/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L72)):*
> ```Kotlin
> private fun validateTarget(target: String, serviceName: String) {
>   val pos = target.lastIndexOf(':')
>   require(pos >= 0) {
> ```

This doesn't really seem like a robust way of validating. Check out the link that Steven sent before -- it gives a better way.

But also, is this really necessary? If we try to build a channel and it fails, the job will crash anyway with a pretty obvious stack trace.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18)* status: all files reviewed, 7 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[WORKSPACE, line 191 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbD2GA_8Ewif1e_K107:-MbD2GA_8Ewif1e_K108:b5fl36r) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/84e0ec883eacee2ac1368fdd417e58f428a04e48/WORKSPACE#L191)):*
> ```Starlark
> http_archive(
>     name = "wfa_measurement_system",
>     sha256 = "50dcfbbd95eb7585c3e1faf66c6c1f3101d05012477f084e055348b963aeef40",
> ```

This dependency is listed 2x.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbCYSaa0mPFI_ouEibM:-MbD2V5i7oPZJ3rS4lZe:b61re0l) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L58)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This would just be re-testing `MinimumIntervalThrottler`, no? We have thorough coverage here: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/test/kotlin/org/wfanet/measurement/common/throttler/MinimumIntervalThrottlerTest.kt
</blockquote></details>

hmmm... what tests do you suggest on this file then to provide code coverage?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18)* status: 5 of 7 files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[WORKSPACE, line 191 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbD2GA_8Ewif1e_K107:-MbDAD0jBkzxQ99pLAMm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/84e0ec883eacee2ac1368fdd417e58f428a04e48/WORKSPACE#L191)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

This dependency is listed 2x.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt, line 72 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbD0RM-4d3kzWyTBRTp:-MbDAQzo8i5Zb-8WX9kk:b-nhnrgg) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/84e0ec883eacee2ac1368fdd417e58f428a04e48/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L72)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This doesn't really seem like a robust way of validating. Check out the link that Steven sent before -- it gives a better way.

But also, is this really necessary? If we try to build a channel and it fails, the job will crash anyway with a pretty obvious stack trace.
</blockquote></details>

Actually ManagedChannelBuilder already throws exception when the target is invalid.

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18)* status: 5 of 7 files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbCYSaa0mPFI_ouEibM:-MbDehhg6Pe7TiWk27wZ:b-li01vd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemon.kt#L58)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

hmmm... what tests do you suggest on this file then to provide code coverage?
</blockquote></details>

Can we cover this code's coverage in end to end test? This is just calling findAndRunExchangeStep() method every minute.

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18)* status: 5 of 7 files reviewed, 7 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbCYOP78VQ4euGL9Uiq:-MbDfCa42ZYHdPxMXp78:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L20)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

FWIW we've never added unit tests for flags because it's essentially re-testing picocli, a mature, well-tested library.
</blockquote></details>

Done.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18)* status: 5 of 7 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbC_uobA4tUDvjIoNJi:-MbDkRIwCWISu2WjZUIM:b-vnn1tc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L53)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm not seeing this. Something like this .... https://github.com/remkop/picocli/blob/master/picocli-examples/src/main/java/picocli/examples/typeconverter/InetSocketAddressConverterDemo.java

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt, line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18#-MbC_uobA4tUDvjIoNJi:-MbDvYf65WZNZrHMp2xa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/adf9a939a7e723e0eb5d5b0f9e55d0028087fbcd/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowFlags.kt#L53)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm not seeing this. Something like this .... https://github.com/remkop/picocli/blob/master/picocli-examples/src/main/java/picocli/examples/typeconverter/InetSocketAddressConverterDemo.java
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/18)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

**Pull request merged**
