### PR TITLE
Rename ApacheBeam to MapReduce

### PR DESCRIPTION
**Pull request by yunyeng**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/232)

### CODE REVIEW

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/232)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt, line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/232#-Mq9w2ZW3_upmj6pf8Af:-Mq9w2ZW3_upmj6pf8Ag:bcwj75m) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/90b899702b0c3c77fd7d78c3ad1a8097244f0ae6/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt#L55)):*
> ```Kotlin
> 
>   /** MapReduce options. */
>   protected abstract val pipelineOptions: PipelineOptions
> ```

The important part is to hide PipelineOptions behind a new interface (MapReduceRunner maybe). Do you want to do that in this PR or in a different one?

**Review by yunyeng — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/232)* status: 5 of 18 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt, line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/232#-Mq9w2ZW3_upmj6pf8Af:-MqD7kpy7J3kw0p3GGTo:b-2wrnsl) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/90b899702b0c3c77fd7d78c3ad1a8097244f0ae6/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ExchangeWorkflowDaemonFromFlags.kt#L55)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

The important part is to hide PipelineOptions behind a new interface (MapReduceRunner maybe). Do you want to do that in this PR or in a different one?
</blockquote></details>

I was thinking of sending it in another pr. But here it goes.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/232)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ApacheBeamRunner.kt, line 26 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/232#-MqD7fRN5IM03HcrE_LC:-MqD7fRN5IM03HcrE_LD:byqx35m) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8414a02079e133288b30e9b58e7cb8e41d87d059/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ApacheBeamRunner.kt#L26)):*
> ```Kotlin
>   MapReduceRunner {
> 
>   override val pipeline: Pipeline = Pipeline.create(options)
> ```

I think you'll want to create the pipeline in run() because otherwise we'll run the same pipeline over and over again, which could cause problems.
___
*[src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt, line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/232#-MqD80c8DTc-RMA47wDQ:-MqD80c8DTc-RMA47wDR:b-tsnrhj) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8414a02079e133288b30e9b58e7cb8e41d87d059/src/main/kotlin/org/wfanet/panelmatch/client/deploy/ProductionExchangeTaskMapper.kt#L38)):*
> ```Kotlin
>   override val getQueryResultsEvaluator = ::JniQueryEvaluator
>   override val queryResultsDecryptor by lazy { JniQueryResultsDecryptor() }
>   override val mapReduceRunner: MapReduceRunner = ApacheBeamRunner()
> ```

Can you make this a constructor parameter instead of directly using ApacheBeamRunner here?
___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/MapReduceRunner.kt, line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/232#-MqD8HmL3EjdL557XLZ9:-MqD8HmM5FYpXUjg5_Vo:bt1c4ow) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8414a02079e133288b30e9b58e7cb8e41d87d059/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/MapReduceRunner.kt#L25)):*
> ```Kotlin
>   val pipeline: Pipeline
> 
>   suspend fun run(): PipelineResult
> ```

Oh, I see the problem here. We want the interface to not mention Apache Beam but the things that use this need access to Apache Beam things.

Let's chat about this tomorrow.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/232)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/MapReduceRunner.kt, line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/232#-MqD8HmL3EjdL557XLZ9:-MqD9mq7EftKqPJ3dUuA:b-qoi91r) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8414a02079e133288b30e9b58e7cb8e41d87d059/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/MapReduceRunner.kt#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Oh, I see the problem here. We want the interface to not mention Apache Beam but the things that use this need access to Apache Beam things.

Let's chat about this tomorrow.
</blockquote></details>

I think we want something like this:

```
interface MapReduceRunner<T> {
  suspend fun run(runPipeline: suspend T.() -> Unit)
} 
```

and then you have something like:

```
class ApacheBeamRunner(private val options: PipelineOptions) : MapReduceRunner<Pipeline> {
  override suspend fun run(runPipeline: suspend Pipeline.() -> Unit) {
    Pipeline.create(options).runPipeline()
  } 
}
```

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/232)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/MapReduceRunner.kt, line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/232#-MqD8HmL3EjdL557XLZ9:-MqDNMU41_-JHW6IfxxY:b-t20naf) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8414a02079e133288b30e9b58e7cb8e41d87d059/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/MapReduceRunner.kt#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think we want something like this:

```
interface MapReduceRunner<T> {
  suspend fun run(runPipeline: suspend T.() -> Unit)
} 
```

and then you have something like:

```
class ApacheBeamRunner(private val options: PipelineOptions) : MapReduceRunner<Pipeline> {
  override suspend fun run(runPipeline: suspend Pipeline.() -> Unit) {
    Pipeline.create(options).runPipeline()
  } 
}
```
</blockquote></details>

Or maybe we can get away with something much simpler. I have an idea we should chat about tomorrow. Basically, ExchangeTaskMapperForJoinKeyExchange can have some abstract functions to provide ExchangeTasks for the ones that use Apache Beam. I think that should really simplify this whole PR.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/232)* status: all files reviewed, 3 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/MapReduceRunner.kt, line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/232#-MqD8HmL3EjdL557XLZ9:-MqFFJp94oznaiqG9yH_:b-kwlyiw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8414a02079e133288b30e9b58e7cb8e41d87d059/src/main/kotlin/org/wfanet/panelmatch/client/exchangetasks/MapReduceRunner.kt#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Or maybe we can get away with something much simpler. I have an idea we should chat about tomorrow. Basically, ExchangeTaskMapperForJoinKeyExchange can have some abstract functions to provide ExchangeTasks for the ones that use Apache Beam. I think that should really simplify this whole PR.
</blockquote></details>

I'm also wondering if the right thing to do is to add another layer of indirection everywhere:

```
interface CommutativeEncryptionTasks {
    suspend fun ExchangeContext.buildDecryptTask(): ExchangeTask
    suspend fun ExchangeContext.buildEncryptTask(): ExchangeTask
    suspend fun ExchangeContext.buildReEncryptTask(): ExchangeTask
    suspend fun ExchangeContext.buildGenerateCommutativeEncryptionKeyTask(): ExchangeTask
}

interface SharedStorageTasks {
  suspend fun ExchangeContext.buildCopyToSharedStorageTask()
  suspend fun ExchangeContext.buildCopyFromSharedStorageTask()
}

interface MapReduceTasks { ... }

// etc etc

class ExchangeTaskMapperForJoinKeyExchange(
  private val commutativeEncryptionTasks: CommutativeEncryptionTasks,
  private val sharedStorageTasks: SharedStorageTasks,
  private val mapReduceTasks: MapReduceTasks,
  ...
) :
  CommutativeEncryptionTasks by commutativeEncryptionTasks,
  SharedStorageTasks by sharedStorageTasks,
  MapReduceTasks by mapReduceTasks {
  ...
}

class JniCommutativeEncryptionTasks : CommutativeEncryptionTasks { ... }

class ApacheBeamTasks : MapReduceTasks { ... }
```

This feels a little more organized than the current ExchangeTaskMapperForJoinKeyExchange

**Comment by efoxepstein** [comment]
Replaced by #235

**Pull request closed without merging**
