### PR TITLE
Build out ExchangeWorkflowDaemonMain with defaults.

### PR DESCRIPTION
**Pull request by efoxepstein**
This may be directly useful for some users and serves as an illustration for how to customize the binary for others.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/203)

### CODE REVIEW

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/203)* status: 4 of 9 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/storage/PrefixedStorageClient.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/203#-Mo4qoVo6XgAbYWbbm4A:-Mo4qoVpEggHJwN5NZZ-:b-sfpx5m) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/585d3ae4c886e5dc9846ece4b011a6375ac1a687/src/main/kotlin/org/wfanet/panelmatch/common/storage/PrefixedStorageClient.kt#L22)):*
> ```Kotlin
> 
> /** Wraps [delegate] by adding [prefix] before each blob key. */
> class PrefixedStorageClient(private val delegate: StorageClient, private val prefix: String) :
> ```

whats the use case for needing a prefixedStorageClient?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/203)* status: 0 of 9 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/203#-MoA6QlY79NA6LRKQ2nV:-MoA6Qlb9J7uWN0wyAS_:b-2xkdy1) (no related file):*
@stevenwarejones I see that there are "changes requested" but I don't see any comments here...

---

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/203)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/203)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/panelmatch/common/storage/PrefixedStorageClient.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/203#-Mo4qoVo6XgAbYWbbm4A:-MoKTry40U2NVZeDcTDP:b-sz06c7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/585d3ae4c886e5dc9846ece4b011a6375ac1a687/src/main/kotlin/org/wfanet/panelmatch/common/storage/PrefixedStorageClient.kt#L22)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

whats the use case for needing a prefixedStorageClient?
</blockquote></details>

It should be pretty apparent in this PR. It's a way to scope an existing storageclient to a subdirectory.

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/203)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/203#-MoA6QlY79NA6LRKQ2nV:-MoZKnltAk7ENMAz-8UU:bn4xkjf) (no related file):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@stevenwarejones I see that there are "changes requested" but I don't see any comments here...
</blockquote></details>

What do you think about adding in an example with actual parameters that 'works'?

---
___
*[docs/deploying.md, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/203#-MoLFqaiCwPQlzTxCdey:-MoLFqaiCwPQlzTxCdez:b-ufddb0) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/90f6dc0e83361db237d0352434676d2abf45098d/docs/deploying.md#L40)):*
> ```Markdown
> MutableSecretMap for storing private keys. There are any number of ways the
> MutableSecretMap interface could be implemented. For example, rather than using
> Tink to connect to the KMS, a KMS client library could be used directed. Or
> ```

directly?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/203)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/203#-MoA6QlY79NA6LRKQ2nV:-MoZQPn0A1TSJ-9_GPdR:bpuhbjo) (no related file):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

What do you think about adding in an example with actual parameters that 'works'?
</blockquote></details>

We don't have any concrete CertificateAuthority implementations yet, so I can't easily do that. Can I do this after I implement some CAs?

---
___
*[docs/deploying.md, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/203#-MoLFqaiCwPQlzTxCdey:-MoZQKWKAp7-TjJZnkH0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/90f6dc0e83361db237d0352434676d2abf45098d/docs/deploying.md#L40)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

directly?
</blockquote></details>

Done.

**Pull request merged**
