### PR TITLE
Parse sharded files incrementally instead of all at once

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336)

### CODE REVIEW

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/ChainedInputStream.kt` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336#-N1e7i4O00SsfhHeOYy1:-N1e7i4O00SsfhHeOYy2:b6o253s) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/2afe1ae09b94d2985fd37a69f26343e3f3333353/src/main/kotlin/org/wfanet/panelmatch/common/ChainedInputStream.kt#L20)):*
> ```Kotlin
> import java.io.InputStream
> 
> open class ChainedInputStream(private val inputStreams: Iterator<InputStream>) : InputStream() {
> ```

Isn't this effectively what [SequenceInputStream](https://docs.oracle.com/javase/7/docs/api/java/io/SequenceInputStream.html) does?



_Code quote:_
```Kotlin
ChainedInputStream
```

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336)* status: 0 of 4 files reviewed, 2 unresolved discussions

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/Protos.kt` line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336#-N1k1ugY9kZffSEE1A5B:-N1k1ugY9kZffSEE1A5C:bkblxzw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/332c2615f463b54b80f868e663dcfc462a175b37/src/main/kotlin/org/wfanet/panelmatch/common/Protos.kt#L25)):*
> ```Kotlin
> fun <T : MessageLite> ByteString.parseDelimitedMessages(prototype: T): Iterable<T> = Iterable {
>   iterator {
>     newInput().use { inputStream ->
> ```

Can this function appeal the the new one below?
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/ReadShardedData.kt` line 78 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336#-N1k29o564YUnmeKitFR:-N1k29o564YUnmeKitFS:be8cm04) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/332c2615f463b54b80f868e663dcfc462a175b37/src/main/kotlin/org/wfanet/panelmatch/common/beam/ReadShardedData.kt#L78)):*
> ```Kotlin
>       var elements = 0L
> 
>       val orderedInputStreams: List<InputStream> = bytes.map { it.newInput() }.toList()
> ```

ToList will materialize the whole Flow. I think you want iterator { bytes.collect { yield(it.newInput)) }} and then to transform the iterators into an Enumeration?

**Review by robinsons — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @robinsons)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/Protos.kt` line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336#-N1k1ugY9kZffSEE1A5B:-N1kGTup0_bfmUCT7P9K:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/332c2615f463b54b80f868e663dcfc462a175b37/src/main/kotlin/org/wfanet/panelmatch/common/Protos.kt#L25)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can this function appeal the the new one below?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/beam/ReadShardedData.kt` line 78 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336#-N1k29o564YUnmeKitFR:-N1kG1IeAdHOmisz80AV:b-rcvapo) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/332c2615f463b54b80f868e663dcfc462a175b37/src/main/kotlin/org/wfanet/panelmatch/common/beam/ReadShardedData.kt#L78)):*
Updated based on offline discussion.

Summary for interested readers: You can't directly do `iterator { bytes.collect { yield(it.newInput()) } }` because of some coroutine scope crossing issues. You get this error:

> Restricted suspending functions can only invoke member or extension suspending functions on their restricted coroutine scope

Instead, resurrected the previous `ReceiveChannel` approach.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @robinsons, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336#-N1kIyrK1IAGMfsYqp6v:-N1kIyrLC1UQaaELRzH7:b-4hjcfr) (no related file):*
@robinsons has taken over this CL for me. LGTM from my perspective.

___

**Review by SanjayVas — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 3 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @robinsons, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/storage/Blobs.kt` line 37 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336#-N1kQP9o-lUH8RkNhiFV:-N1kQP9o-lUH8RkNhiFW:b-sg52ae) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e0b1e9df4928764196904bad3bf633354d104377/src/main/kotlin/org/wfanet/panelmatch/common/storage/Blobs.kt#L37)):*
> ```Kotlin
> 
> /** Returns an [InputStream] that reads the blob's bytes in [scope]. */
> suspend fun Blob.toInputStream(scope: CoroutineScope): InputStream {
> ```

Unnecessary, as this function itself doesn't suspend.



_Code quote:_
```Kotlin
suspend 
```
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/storage/Blobs.kt` line 45 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336#-N1kUPDmCVTN0DXggwvj:-N1kUPDn-9J3QrN0ki31:bgue0rd) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e0b1e9df4928764196904bad3bf633354d104377/src/main/kotlin/org/wfanet/panelmatch/common/storage/Blobs.kt#L45)):*
> ```Kotlin
>         yield(byteString.newInput())
>       } catch (_: ClosedReceiveChannelException) {
>         break
> ```

I think you can avoid this by wrapping `ChannelIterator` in a blocking `Iterator`.

```
/** Returns an [InputStream] that reads the blob's bytes in [scope]. */
fun Blob.toInputStream(scope: CoroutineScope): InputStream {
  @OptIn(FlowPreview::class) val channel: ReceiveChannel<ByteString> = read().produceIn(scope)
  val inputStreamIterator: Iterator<InputStream> =
    BlockingIterator(channel.iterator(), scope.coroutineContext)
      .asSequence()
      .map { it.newInput() }
      .iterator()
  return SequenceInputStream(Iterators.asEnumeration(inputStreamIterator))
}

/** [Iterator] that wraps [channelIterator] using [runBlocking]. */
private class BlockingIterator<T>(
  private val channelIterator: ChannelIterator<T>,
  private val context: CoroutineContext = EmptyCoroutineContext
) : Iterator<T> {
  override fun hasNext(): Boolean = runBlocking(context) { channelIterator.hasNext() }

  override fun next(): T = runBlocking(context) { channelIterator.next() }
}
```



_Code quote:_
```Kotlin
      } catch (_: ClosedReceiveChannelException) {
        break
      }
```

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336)* status: 1 of 11 files reviewed, 2 unresolved discussions (waiting on @robinsons, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/storage/Blobs.kt` line 37 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336#-N1kQP9o-lUH8RkNhiFV:-N1nsGZj9redhS02kE-E:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e0b1e9df4928764196904bad3bf633354d104377/src/main/kotlin/org/wfanet/panelmatch/common/storage/Blobs.kt#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Unnecessary, as this function itself doesn't suspend.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/panelmatch/common/storage/Blobs.kt` line 45 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336#-N1kUPDmCVTN0DXggwvj:-N1oOvPy5UQz2vVnk4-S:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/e0b1e9df4928764196904bad3bf633354d104377/src/main/kotlin/org/wfanet/panelmatch/common/storage/Blobs.kt#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think you can avoid this by wrapping `ChannelIterator` in a blocking `Iterator`.

```
/** Returns an [InputStream] that reads the blob's bytes in [scope]. */
fun Blob.toInputStream(scope: CoroutineScope): InputStream {
  @OptIn(FlowPreview::class) val channel: ReceiveChannel<ByteString> = read().produceIn(scope)
  val inputStreamIterator: Iterator<InputStream> =
    BlockingIterator(channel.iterator(), scope.coroutineContext)
      .asSequence()
      .map { it.newInput() }
      .iterator()
  return SequenceInputStream(Iterators.asEnumeration(inputStreamIterator))
}

/** [Iterator] that wraps [channelIterator] using [runBlocking]. */
private class BlockingIterator<T>(
  private val channelIterator: ChannelIterator<T>,
  private val context: CoroutineContext = EmptyCoroutineContext
) : Iterator<T> {
  override fun hasNext(): Boolean = runBlocking(context) { channelIterator.hasNext() }

  override fun next(): T = runBlocking(context) { channelIterator.next() }
}
```
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 10 of 10 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/BlockingIterator.kt` line 21 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336#-N1o_OS96MZ8ayfW-HUl:-N1o_OS96MZ8ayfW-HUm:beekzft) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8bea59d8118d20a837374abcf017e12c29eb7288/src/main/kotlin/org/wfanet/panelmatch/common/BlockingIterator.kt#L21)):*
> ```Kotlin
>       // conform to Iterator's contract by throwing NoSuchElementException when the iterator is
>       // empty.
>       if (hasNext()) channelIterator.next()
> ```

nit: use curly braces even for single statements/expressions.
___
*[`src/test/kotlin/org/wfanet/panelmatch/common/BlockingIteratorTest.kt` line 18 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336#-N1o_flK7XdLD6HZQOCz:-N1o_flK7XdLD6HZQOD-:b-e4ynp8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8bea59d8118d20a837374abcf017e12c29eb7288/src/test/kotlin/org/wfanet/panelmatch/common/BlockingIteratorTest.kt#L18)):*
> ```Kotlin
> 
>   @Test
>   fun hasNextReturnsFalseForEmptyIterator() = runBlockingTest {
> ```

nit: use backtick syntax to allow spaces in test functions.

e.g. `` `hasNext returns false for empty iterator` ``



_Code quote:_
```Kotlin
hasNextReturnsFalseForEmptyIterator
```

**Review by robinsons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336)* status: 8 of 11 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/common/BlockingIterator.kt` line 21 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336#-N1o_OS96MZ8ayfW-HUl:-N1oevo2AEMvHuZ1LQ_m:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8bea59d8118d20a837374abcf017e12c29eb7288/src/main/kotlin/org/wfanet/panelmatch/common/BlockingIterator.kt#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: use curly braces even for single statements/expressions.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/panelmatch/common/BlockingIteratorTest.kt` line 18 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336#-N1o_flK7XdLD6HZQOCz:-N1of3Nm6DeDLTVMty6b:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/8bea59d8118d20a837374abcf017e12c29eb7288/src/test/kotlin/org/wfanet/panelmatch/common/BlockingIteratorTest.kt#L18)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: use backtick syntax to allow spaces in test functions.

e.g. `` `hasNext returns false for empty iterator` ``
</blockquote></details>

Done.

**Review by SanjayVas — APPROVED** [review]
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/336)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Pull request merged**
