### PR TITLE
Add implementation for AesWithHkdf

### PR DESCRIPTION
**Pull request by enfreck**
Add implementation and test cases for AesWithHkdf for encrypting user
data.

---
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41)

### CODE REVIEW

**Review by jmorrrr — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41)* status: all files reviewed, 2 unresolved discussions (waiting on @enfreck)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeVn7zT11vSuheYNqLz:-MeVn7zU7C1bnUuF-yrC:b-f5wmws) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L29)):*
> ```objc
> #include "wfanet/panelmatch/common/crypto/hkdf.h"
> 
> namespace wfanet::panelmatch::common::crypto {
> ```

May want to change this namespace because there is a github issue open to update C++ namespaces ("The C++ namespaces should match existing code. ie wfa.panelmatch.something") if you want to be proactive - but if not just leave and whoever solves the issue can fix
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeVnRA48ClOWDzBTTt4:-MeVnRA48ClOWDzBTTt5:b-8a0zj7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc#L21)):*
> ```cpp
> namespace wfanet::panelmatch::common::crypto {
> 
> AesWithHkdf::AesWithHkdf(std::unique_ptr<Hkdf> hkdf, std::unique_ptr<Aes> aes)
> ```

I know it has been said before that comments should go in header files - but maybe short overview here ?

**Review by matthewclegg — APPROVED** [review]

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41)* status: all files reviewed, 13 unresolved discussions (waiting on @enfreck and @jmorrrr)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes.h, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWGiCj2uLLR69IhGfn:-MeWGiCj2uLLR69IhGfo:b-iqskl8) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes.h#L52)):*
> ```objc
> // AEAD_AES_SIV_CMAC_512 as defined by
> // https://datatracker.ietf.org/doc/html/rfc5297#section-6.3.
> const std::unique_ptr<Aes> GetAesSivCmac512();
> ```

Remove `const` please
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeVn7zT11vSuheYNqLz:-MeWGowa0mKA1kZv9aLm:b-4p6p6n) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L29)):*
<details><summary><i>Previously, jmorrrr wrote…</i></summary><blockquote>

May want to change this namespace because there is a github issue open to update C++ namespaces ("The C++ namespaces should match existing code. ie wfa.panelmatch.something") if you want to be proactive - but if not just leave and whoever solves the issue can fix
</blockquote></details>

Let's leave as is for now to be consistent with existing code, then we'll fix it all at once.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWHaSt4ZIBG9xmwODi:-MeWHaSt4ZIBG9xmwODj:b-ncxxfw) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L35)):*
https://google.github.io/styleguide/cppguide.html#Class_Format

Please put instance variables at the bottom of the class

> The public section should be first, followed by the protected and finally the private section.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWI72aESiAk32ZLCVZ:-MeWI72aESiAk32ZLCV_:blu7dia) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L46)):*
> ```objc
>   absl::StatusOr<std::string> Encrypt(
>       absl::string_view input,
>       const ::crypto::tink::util::SecretData key) const;
> ```

Can you change this to a const reference to a SecretData to avoid unnecessary copies?
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWIE2EBOXq-oXf98Yz:-MeWIE2EBOXq-oXf98Z-:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L52)):*
> ```objc
>   absl::StatusOr<std::string> Decrypt(
>       absl::string_view input,
>       const ::crypto::tink::util::SecretData key) const;
> ```

Ditto
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWIJaJ8HIiiJrj_kpG:-MeWIJaK2i0DstYOD3Z1:byocjkp) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc#L17)):*
> ```cpp
> #include "wfanet/panelmatch/common/crypto/aes_with_hkdf.h"
> 
> #include <utility>
> ```

#includes for SecretData, Aes, Hkdf, absl::string_view, absl::StatusOr please

also `#include <memory>`
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWHvnx7EpUuFkjnpoz:-MeWHvnx7EpUuFkjnpp-:b-idmm8h) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc#L19)):*
> ```cpp
> #include <utility>
> 
> namespace wfanet::panelmatch::common::crypto {
> ```

Please add a using-decl for SecretData
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWHzT518Ay8ZvrXttw:-MeWHzT518Ay8ZvrXttx:bt7nv6u) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc#L29)):*
> ```cpp
>       hkdf_->ComputeHkdf(key, aes_->key_size_bytes());
>   if (result.ok()) {
>     return aes_->Encrypt(input, result.value());
> ```

Simpler: `ASSIGN_OR_RETURN(SecretData result, hkdf_->ComputeHkdf(...));`
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWHoyq2y8bIkXRrBB7:-MeWHoyq2y8bIkXRrBB8:bt7nv6u) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc#L37)):*
> ```cpp
> absl::StatusOr<std::string> AesWithHkdf::Decrypt(
>     absl::string_view input, const ::crypto::tink::util::SecretData key) const {
>   absl::StatusOr<::crypto::tink::util::SecretData> result =
> ```

Simpler: `ASSIGN_OR_RETURN(SecretData result, hkdf_->ComputeHkdf(...));`
___
*[src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWIVXeD2Q0uO0Zlngo:-MeWIVXeD2Q0uO0Zlngp:bk62fby) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h#L37)):*
> ```objc
> 
> // Returns an Hkdf that uses SHA-256 as the hash function
> const std::unique_ptr<Hkdf> GetSha256Hkdf();
> ```

Remove const please
___
*[src/main/cc/wfanet/panelmatch/common/crypto/hkdf.cc, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWIXZp63DzEoMGs2TS:-MeWIXZp63DzEoMGs2TT:bn854ge) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/hkdf.cc#L49)):*
> ```cpp
> 
> const std::unique_ptr<Hkdf> GetSha256Hkdf() {
>   return std::make_unique<Sha256Hkdf>();
> ```

Please use `absl::make_unique`
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWId0Z2OJmWC7u-BEc:-MeWId0Z2OJmWC7u-BEd:b-p2mqsy) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc#L31)):*
> ```cpp
>   std::unique_ptr<Hkdf> hkdf = GetSha256Hkdf();
>   std::unique_ptr<Aes> aes = GetAesSivCmac512();
>   const AesWithHkdf& aes_hkdf = AesWithHkdf(std::move(hkdf), std::move(aes));
> ```

`AesWithHkdf aes_hkdf(std::move(hkdf), std::move(aes));`

**Review by enfreck — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41)* status: 3 of 12 files reviewed, 13 unresolved discussions (waiting on @efoxepstein and @jmorrrr)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes.h, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWGiCj2uLLR69IhGfn:-Me_UxPO35SMHa1M3J9F:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes.h#L52)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Remove `const` please
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeVn7zT11vSuheYNqLz:-Me_UyeT6Eugt7j3znLL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Let's leave as is for now to be consistent with existing code, then we'll fix it all at once.
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWHaSt4ZIBG9xmwODi:-Me_V0KcEB-BfODOZYGJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L35)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

https://google.github.io/styleguide/cppguide.html#Class_Format

Please put instance variables at the bottom of the class

> The public section should be first, followed by the protected and finally the private section.
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWI72aESiAk32ZLCVZ:-Me_V1ZW16E373k66DVa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L46)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you change this to a const reference to a SecretData to avoid unnecessary copies?
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWIE2EBOXq-oXf98Yz:-Me_V2L63ZvnDvYS1fQO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.h#L52)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWIJaJ8HIiiJrj_kpG:-Me_V3hGABBWPIDDqFvR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc#L17)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

#includes for SecretData, Aes, Hkdf, absl::string_view, absl::StatusOr please

also `#include <memory>`
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWHvnx7EpUuFkjnpoz:-Me_V5KbASejSbJvqgiM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc#L19)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please add a using-decl for SecretData
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeVnRA48ClOWDzBTTt4:-Me_V68Z4WeIxJTpIyGW:bpvxxuh) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc#L21)):*
<details><summary><i>Previously, jmorrrr wrote…</i></summary><blockquote>

I know it has been said before that comments should go in header files - but maybe short overview here ?
</blockquote></details>

I don't think it is necessary since a summarized comment would essentially be very similar to the method name.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWHzT518Ay8ZvrXttw:-Me_VTJb0R3qhptEHps0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Simpler: `ASSIGN_OR_RETURN(SecretData result, hkdf_->ComputeHkdf(...));`
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWHoyq2y8bIkXRrBB7:-Me_VTjq77UUVXkXjNmr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Simpler: `ASSIGN_OR_RETURN(SecretData result, hkdf_->ComputeHkdf(...));`
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWIVXeD2Q0uO0Zlngo:-Me_VUmD2TlbjzKuQpJc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/hkdf.h#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Remove const please
</blockquote></details>

Done.
___
*[src/main/cc/wfanet/panelmatch/common/crypto/hkdf.cc, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWIXZp63DzEoMGs2TS:-Me_VVhE561VCTtM41fo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/hkdf.cc#L49)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use `absl::make_unique`
</blockquote></details>

Done.
___
*[src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWId0Z2OJmWC7u-BEc:-Me_VXAz-FqztLSKg-KF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/test/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf_test.cc#L31)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`AesWithHkdf aes_hkdf(std::move(hkdf), std::move(aes));`
</blockquote></details>

Done.

**Review by efoxepstein — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @enfreck, and @jmorrrr)

___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWHzT518Ay8ZvrXttw:-Me_aJjlEHtDR2ur-O3b:b-o11gwx) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc#L29)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Does declaring result in the ASSIGN_OR_RETURN not work?

**Comment by enfreck** [comment]
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWHzT518Ay8ZvrXttw:-Me_i85G9d34IWvUOONk:b-n39b1o) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Does declaring result in the ASSIGN_OR_RETURN not work?
</blockquote></details>

It wasn't initially, but I think that might have been a part of a different error.  I just fixed it.

**Comment by enfreck** [comment]
___
*[src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41#-MeWHzT518Ay8ZvrXttw:-Me_iWz00yeV-hxEMEzv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/6e97647601d713ce471220fec6d51207cd76676f/src/main/cc/wfanet/panelmatch/common/crypto/aes_with_hkdf.cc#L29)):*
<details><summary><i>Previously, enfreck wrote…</i></summary><blockquote>

It wasn't initially, but I think that might have been a part of a different error.  I just fixed it.
</blockquote></details>

Done.

**Review by efoxepstein — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41)* status: all files reviewed, 2 unresolved discussions (waiting on @jmorrrr)

**Review by stevenwarejones — APPROVED** [review]
> Reviewed 3 of 11 files at r1, 8 of 9 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41)* status: all files reviewed, 2 unresolved discussions (waiting on @jmorrrr)

**Review by jmorrrr — APPROVED** [review]
> Reviewed 8 of 9 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/41)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @enfreck)

**Pull request merged**
