### PR TITLE
Update GitHub Build & Test action to compile with opt

### PR DESCRIPTION
**Pull request by efoxepstein**
This change is [Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/131)

### CODE REVIEW

**Review by SanjayVas — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/131)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/131)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[.github/workflows/build-test.yml, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/131#-MkHpaNEBuXujgIq9yhh:-MkHpaNEBuXujgIq9yhi:b9ta9nc) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5f7e3499d37178b623de370a32ebf6ef2e1c1c45/.github/workflows/build-test.yml#L38)):*
> ```YAML
>           workspace-path: .
>           build-options: |
>             --host_platform=//build/platforms:ubuntu_18_04
> ```

other places in the code refer to 20.04. https://github.com/world-federation-of-advertisers/actions/blob/1d8f3e83b6ad88add06f192d8775eadb0e5dddf1/.github/workflows/test-bazel-build-test.yml#L26

Is there a way to keep all these synced? or another question is whats the advantage to letting bazel know the host_platform here?

**Review by stevenwarejones — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/131)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[.github/workflows/build-test.yml, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/131#-MkHpt0r2r-l9CJQqflw:-MkHpt0sA__w7wBCQLUf:b-jreih5) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5f7e3499d37178b623de370a32ebf6ef2e1c1c45/.github/workflows/build-test.yml#L39)):*
> ```YAML
>           build-options: |
>             --host_platform=//build/platforms:ubuntu_18_04
>             --compilation_mode=opt
> ```

is there a reason we don't want the general action for all repos to do this?

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/131)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @stevenwarejones)

___
*[.github/workflows/build-test.yml, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/131#-MkHpt0r2r-l9CJQqflw:-MkHsuyC38QMLSXxOTTk:bn22p7l) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5f7e3499d37178b623de370a32ebf6ef2e1c1c45/.github/workflows/build-test.yml#L39)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is there a reason we don't want the general action for all repos to do this?
</blockquote></details>

Compilation takes a lot longer.

**Review by efoxepstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/131)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[.github/workflows/build-test.yml, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/131#-MkHpaNEBuXujgIq9yhh:-MkI4TIY7BMbdDoHk6ik:bhuppfr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5f7e3499d37178b623de370a32ebf6ef2e1c1c45/.github/workflows/build-test.yml#L38)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

other places in the code refer to 20.04. https://github.com/world-federation-of-advertisers/actions/blob/1d8f3e83b6ad88add06f192d8775eadb0e5dddf1/.github/workflows/test-bazel-build-test.yml#L26

Is there a way to keep all these synced? or another question is whats the advantage to letting bazel know the host_platform here?
</blockquote></details>

We need to specify the host platform to muse the right version of glibc. It should probably eventually be consistent but I don't see that as super important

**Review by stevenwarejones — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/131)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @efoxepstein)

**Comment by SanjayVas** [comment]
> _[.github/workflows/build-test.yml, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/panel-exchange-client/131#-MkHpaNEBuXujgIq9yhh:-MkI4TIY7BMbdDoHk6ik:bhuppfr) ([raw file](https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/5f7e3499d37178b623de370a32ebf6ef2e1c1c45/.github/workflows/build-test.yml#L38)):_
> 
> Previously, stevenwarejones (Steven Ware Jones) wrote…
> > other places in the code refer to 20.04. https://github.com/world-federation-of-advertisers/actions/blob/1d8f3e83b6ad88add06f192d8775eadb0e5dddf1/.github/workflows/test-bazel-build-test.yml#L26
> > Is there a way to keep all these synced? or another question is whats the advantage to letting bazel know the host_platform here?
> 
> We need to specify the host platform to muse the right version of glibc. It should probably eventually be consistent but I don't see that as super important

Just to give some extra clarification for posterity: This is telling Bazel which platform we're running on since it can't detect that by itself. As Eli mentioned, this lets Bazel know which version of glibc the system has. Certain targets such as the Mill are only compatible with certain versions of glibc (e.g. for using JNI with a base container image). Bazel will not build these targets without knowing it has a compatible glibc version. For repos where we don't have said targets, it's fine to use a newer platform (though there is indeed an argument for consistency).

We need glibc to be <=2.28 for the Mill image based on Distroless Java. Ubuntu 18.04 bionic has glibc (package libc6) 2.27, whereas Ubuntu 20.04 has glibc 2.31.

**Pull request merged**
